-- generated by newgenasym Tue Mar 01 16:21:30 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lan8710ai is
    port (    
	\col/crs_dv/mode2\: INOUT  STD_LOGIC;    
	CRS:       INOUT  STD_LOGIC;    
	\led1/regoff\: INOUT  STD_LOGIC;    
	\led2/nintsel\: INOUT  STD_LOGIC;    
	MDC:       INOUT  STD_LOGIC;    
	MDIO:      INOUT  STD_LOGIC;    
	\nint/txer/txd4\: INOUT  STD_LOGIC;    
	NRST:      INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	RBIAS:     INOUT  STD_LOGIC;    
	\rxclk/phyad1\: INOUT  STD_LOGIC;    
	\rxd0/mode0\: INOUT  STD_LOGIC;    
	\rxd1/mode1\: INOUT  STD_LOGIC;    
	\rxd2/rmiisel\: INOUT  STD_LOGIC;    
	\rxd3/phyad2\: INOUT  STD_LOGIC;    
	RXDV:      INOUT  STD_LOGIC;    
	\rxer/rxd4/phyad0\: INOUT  STD_LOGIC;    
	RXN:       INOUT  STD_LOGIC;    
	RXP:       INOUT  STD_LOGIC;    
	TXCLK:     INOUT  STD_LOGIC;    
	TXD0:      INOUT  STD_LOGIC;    
	TXD1:      INOUT  STD_LOGIC;    
	TXD2:      INOUT  STD_LOGIC;    
	TXD3:      INOUT  STD_LOGIC;    
	TXEN:      INOUT  STD_LOGIC;    
	TXN:       INOUT  STD_LOGIC;    
	TXP:       INOUT  STD_LOGIC;    
	VDD1A:     INOUT  STD_LOGIC;    
	VDD2A:     INOUT  STD_LOGIC;    
	VDDCR:     INOUT  STD_LOGIC;    
	VDDIO:     INOUT  STD_LOGIC;    
	\xtal1/clkin\: INOUT  STD_LOGIC;    
	XTAL2:     INOUT  STD_LOGIC);
end lan8710ai;
