// generated by newgenasym  Wed Mar 04 15:31:45 2009


module hmc625lp5e (acg1, acg2, acg3, acg4, acg5, acg6, ampin, ampout, attin,
        attout, clk, d0, d1, d2, d3, d4, d5, gnd1, gnd2, gnd3, gnd4, gnd5,
        gnd6, gnd7, gnd8, gnd9, le, \p/s , pup1, pup2, serin, serout, vdd);
    inout acg1;
    inout acg2;
    inout acg3;
    inout acg4;
    inout acg5;
    inout acg6;
    input ampin;
    output ampout;
    input attin;
    output attout;
    inout clk;
    inout d0;
    inout d1;
    inout d2;
    inout d3;
    inout d4;
    inout d5;
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    input gnd7;
    input gnd8;
    input gnd9;
    inout le;
    inout \p/s ;
    inout pup1;
    inout pup2;
    input serin;
    output serout;
    input vdd;


    initial
        begin
        end

endmodule
