// generated by newgenasym  Wed Mar 09 15:02:16 2011


module ksz8051 (\col/config0 , \crs/config1 , gnd, \intrp/nand_free# ,
        \led0/nwayen , \led1/speed , mdc, mdio, pad, rext, \rst# ,
        \rxc/b-cast_off , \rxd0/duplex , \rxd1/phyad2 , \rxd2/phyad1 ,
        \rxd3/phyad0 , \rxdv/config2 , \rxer/iso , rxm, rxp, txc, txd0,
        txd1, txd2, txd3, txen, txm, txp, \vdd_1.2 , \vdda_3.3 , vddio, xi,
        xo);
    inout \col/config0 ;
    inout \crs/config1 ;
    inout gnd;
    inout \intrp/nand_free# ;
    inout \led0/nwayen ;
    inout \led1/speed ;
    inout mdc;
    inout mdio;
    inout pad;
    inout rext;
    inout \rst# ;
    inout \rxc/b-cast_off ;
    inout \rxd0/duplex ;
    inout \rxd1/phyad2 ;
    inout \rxd2/phyad1 ;
    inout \rxd3/phyad0 ;
    inout \rxdv/config2 ;
    inout \rxer/iso ;
    inout rxm;
    inout rxp;
    inout txc;
    inout txd0;
    inout txd1;
    inout txd2;
    inout txd3;
    inout txen;
    inout txm;
    inout txp;
    inout \vdd_1.2 ;
    inout \vdda_3.3 ;
    inout vddio;
    inout xi;
    inout xo;


    initial
        begin
        end

endmodule
