-- generated by newgenasym Wed Mar 09 15:02:16 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ksz8051 is
    port (    
	\col/config0\: INOUT  STD_LOGIC;    
	\crs/config1\: INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\intrp/nand_free#\: INOUT  STD_LOGIC;    
	\led0/nwayen\: INOUT  STD_LOGIC;    
	\led1/speed\: INOUT  STD_LOGIC;    
	MDC:       INOUT  STD_LOGIC;    
	MDIO:      INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	REXT:      INOUT  STD_LOGIC;    
	\rst#\:    INOUT  STD_LOGIC;    
	\rxc/b-cast_off\: INOUT  STD_LOGIC;    
	\rxd0/duplex\: INOUT  STD_LOGIC;    
	\rxd1/phyad2\: INOUT  STD_LOGIC;    
	\rxd2/phyad1\: INOUT  STD_LOGIC;    
	\rxd3/phyad0\: INOUT  STD_LOGIC;    
	\rxdv/config2\: INOUT  STD_LOGIC;    
	\rxer/iso\: INOUT  STD_LOGIC;    
	RXM:       INOUT  STD_LOGIC;    
	RXP:       INOUT  STD_LOGIC;    
	TXC:       INOUT  STD_LOGIC;    
	TXD0:      INOUT  STD_LOGIC;    
	TXD1:      INOUT  STD_LOGIC;    
	TXD2:      INOUT  STD_LOGIC;    
	TXD3:      INOUT  STD_LOGIC;    
	TXEN:      INOUT  STD_LOGIC;    
	TXM:       INOUT  STD_LOGIC;    
	TXP:       INOUT  STD_LOGIC;    
	\vdd_1.2\: INOUT  STD_LOGIC;    
	\vdda_3.3\: INOUT  STD_LOGIC;    
	VDDIO:     INOUT  STD_LOGIC;    
	XI:        INOUT  STD_LOGIC;    
	XO:        INOUT  STD_LOGIC);
end ksz8051;
