// generated by newgenasym  Fri Aug 05 16:46:12 2011


module sp3491en_l (a, b, de, di, gnd, nc, \re# , ro, vcc, y, z);
    inout a;
    inout b;
    inout de;
    inout di;
    inout [2:1] gnd;
    inout [3:1] nc;
    inout \re# ;
    inout ro;
    inout vcc;
    inout y;
    inout z;


    initial
        begin
        end

endmodule
