-- generated by newgenasym Fri Aug 05 16:46:12 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SP3491EN_L is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	DE:        INOUT  STD_LOGIC;    
	DI:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	NC:        INOUT  STD_LOGIC_VECTOR (3 DOWNTO 1);    
	\re#\:     INOUT  STD_LOGIC;    
	RO:        INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	Y:         INOUT  STD_LOGIC;    
	Z:         INOUT  STD_LOGIC);
end SP3491EN_L;
