// generated by newgenasym  Thu Sep 17 15:24:45 2009


module apxs006a0x_srz (gnd, nc, \on/off , pgood, sense, seq, trim, vin, vout);
    inout [2:1] gnd;
    inout nc;
    inout \on/off ;
    inout pgood;
    inout sense;
    inout seq;
    inout trim;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
