-- generated by newgenasym Thu Sep 17 15:24:45 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity apxs006a0x_srz is
    port (    
	GND:       INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	NC:        INOUT  STD_LOGIC;    
	\on/off\:  INOUT  STD_LOGIC;    
	PGOOD:     INOUT  STD_LOGIC;    
	SENSE:     INOUT  STD_LOGIC;    
	SEQ:       INOUT  STD_LOGIC;    
	TRIM:      INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end apxs006a0x_srz;
