-- generated by newgenasym Thu Feb 12 15:23:03 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pth08t220waz is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	\inh/uvlo\: INOUT  STD_LOGIC;    
	\sense+\:  INOUT  STD_LOGIC;    
	\sense-\:  INOUT  STD_LOGIC;    
	SYNC:      INOUT  STD_LOGIC;    
	TRACK:     INOUT  STD_LOGIC;    
	TT:        INOUT  STD_LOGIC;    
	VI:        INOUT  STD_LOGIC;    
	VO:        INOUT  STD_LOGIC;    
	VOADJ:     INOUT  STD_LOGIC);
end pth08t220waz;
