// generated by newgenasym  Wed Apr 15 18:53:34 2009


module cdce72010rgctg4 (aux_sel, cp_out, gnd1, gnd2, gnd_cp, mode_sel, pll_lock,
        \power_down# , \pri_ref+ , \pri_ref- , ref_sel, \reset#/hold# ,
        \sec_ref+ , \sec_ref- , \spi_clk/cd2 , \spi_le/cd1 , spi_miso,
        \spi_mosi/cd3 , status, testouta, u0n, u0p, u1n, u1p, u2n, u2p,
        u3n, u3p, u4n, u4p, u5n, u5p, u6n, u6p, u7n, u7p, u8n, u8p,
        \u9n/auxinn , \u9p/auxinp , vbb, vcc1, vcc10, vcc11, vcc12,
        vcc13, vcc2, vcc3, vcc4, vcc5, vcc6, vcc7, vcc8, vcc9, vcc_cp,
        vcc_in1, vcc_in2, vcc_pll1, vcc_pll2, vcc_vcxo1, vcc_vcxo2,
        vcca1, vcca2, \vcxo_in+ , \vcxo_in- );
    input aux_sel;
    output cp_out;
    input gnd1;
    input gnd2;
    input gnd_cp;
    input mode_sel;
    inout pll_lock;
    input \power_down# ;
    input \pri_ref+ ;
    input \pri_ref- ;
    input ref_sel;
    input \reset#/hold# ;
    input \sec_ref+ ;
    input \sec_ref- ;
    input \spi_clk/cd2 ;
    input \spi_le/cd1 ;
    inout spi_miso;
    input \spi_mosi/cd3 ;
    output status;
    inout testouta;
    output u0n;
    output u0p;
    output u1n;
    output u1p;
    output u2n;
    output u2p;
    output u3n;
    output u3p;
    output u4n;
    output u4p;
    output u5n;
    output u5p;
    output u6n;
    output u6p;
    output u7n;
    output u7p;
    output u8n;
    output u8p;
    inout \u9n/auxinn ;
    inout \u9p/auxinp ;
    output vbb;
    input vcc1;
    input vcc10;
    input vcc11;
    input vcc12;
    input vcc13;
    input vcc2;
    input vcc3;
    input vcc4;
    input vcc5;
    input vcc6;
    input vcc7;
    input vcc8;
    input vcc9;
    input vcc_cp;
    input vcc_in1;
    input vcc_in2;
    input vcc_pll1;
    input vcc_pll2;
    input vcc_vcxo1;
    input vcc_vcxo2;
    input vcca1;
    input vcca2;
    input \vcxo_in+ ;
    input \vcxo_in- ;


    initial
        begin
        end

endmodule
