// generated by newgenasym  Fri Jul 08 18:14:51 2011


module lm393ad (\1in+ , \1in- , \1out , \2in+ , \2in- , \2out , gnd, vcc);
    inout \1in+ ;
    inout \1in- ;
    inout \1out ;
    inout \2in+ ;
    inout \2in- ;
    inout \2out ;
    inout gnd;
    inout vcc;


    initial
        begin
        end

endmodule
