// generated by newgenasym  Thu Sep 10 10:36:16 2009


module con_ci2206p1vk0_lf (\1 , \2 , \3 , \4 , \5 , \6 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;


    initial
        begin
        end

endmodule
