// generated by newgenasym  Thu Feb 12 15:14:22 2009


module lmx2531lq1910e (ce, clk, cpout, data, flout, fout, \ftest/ld , gnd_1, gnd_2,
        gnd_3, gnd_4, le, nc_1, nc_10, nc_2, nc_3, nc_4, nc_5, nc_6,
        nc_7, nc_8, nc_9, outputscin, \outputscin# , pad_gnd_1,
        pad_gnd_2, pad_nc, test, vccbuf, vccdig, vccpll, vccvco,
        vrefvco, vregbuf, vregdig, vregpll1, vregpll2, vregvco,
        vtune);
    input ce;
    input clk;
    output cpout;
    input data;
    output flout;
    output fout;
    output \ftest/ld ;
    input gnd_1;
    input gnd_2;
    input gnd_3;
    input gnd_4;
    input le;
    inout nc_1;
    inout nc_10;
    inout nc_2;
    inout nc_3;
    inout nc_4;
    inout nc_5;
    inout nc_6;
    inout nc_7;
    inout nc_8;
    inout nc_9;
    input outputscin;
    input \outputscin# ;
    input pad_gnd_1;
    input pad_gnd_2;
    inout pad_nc;
    output test;
    input vccbuf;
    input vccdig;
    input vccpll;
    input vccvco;
    input vrefvco;
    input vregbuf;
    input vregdig;
    input vregpll1;
    input vregpll2;
    input vregvco;
    input vtune;


    initial
        begin
        end

endmodule
