// generated by newgenasym  Thu Feb 12 15:26:52 2009


module sn74lvc16245adggr (a0, a1, a10, a11, a12, a13, a14, a15, a2, a3, a4, a5, a6, a7, a8,
        a9, b0, b1, b10, b11, b12, b13, b14, b15, b2, b3, b4, b5, b6, b7, b8,
        b9, gnd_1, gnd_2, gnd_3, gnd_4, gnd_5, gnd_6, gnd_7, gnd_8,
        \oe#1 , \oe#2 , \t/r#1 , \t/r#2 , vcc_1, vcc_2, vcc_3, vcc_4);
    inout a0;
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a13;
    inout a14;
    inout a15;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout b0;
    inout b1;
    inout b10;
    inout b11;
    inout b12;
    inout b13;
    inout b14;
    inout b15;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout b9;
    input gnd_1;
    input gnd_2;
    input gnd_3;
    input gnd_4;
    input gnd_5;
    input gnd_6;
    input gnd_7;
    input gnd_8;
    input \oe#1 ;
    input \oe#2 ;
    input \t/r#1 ;
    input \t/r#2 ;
    input vcc_1;
    input vcc_2;
    input vcc_3;
    input vcc_4;


    initial
        begin
        end

endmodule
