// generated by newgenasym  Mon Feb 16 17:55:50 2009


module con_sip25_4 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
