-- generated by newgenasym Mon Feb 16 17:55:50 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity con_sip25_4 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end con_sip25_4;
