// generated by newgenasym  Fri Apr 10 14:42:42 2009


module js28f512m29ewh (a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20,
        a21, a22, a23, a24, a25, a3, a4, a5, a6, a7, a8, a9, \byte# , \ce# ,
        dq0, dq1, dq10, dq11, dq12, dq13, dq14, \dq15/a-1 , dq2, dq3, dq4,
        dq5, dq6, dq7, dq8, dq9, \oe# , rfu1, rfu2, rfu3, \rst# , \ry/by# ,
        vcc, vccq, \vpp/wp# , vss1, vss2, \we# );
    input a0;
    input a1;
    input a10;
    input a11;
    input a12;
    input a13;
    input a14;
    input a15;
    input a16;
    input a17;
    input a18;
    input a19;
    input a2;
    input a20;
    input a21;
    input a22;
    input a23;
    input a24;
    input a25;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    input a9;
    input \byte# ;
    input \ce# ;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout \dq15/a-1 ;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dq8;
    inout dq9;
    input \oe# ;
    inout rfu1;
    inout rfu2;
    inout rfu3;
    input \rst# ;
    output \ry/by# ;
    input vcc;
    input vccq;
    input \vpp/wp# ;
    input vss1;
    input vss2;
    input \we# ;


    initial
        begin
        end

endmodule
