// generated by newgenasym  Fri Sep 18 14:08:02 2009


module filter4 (gnd1, gnd2, in, out);
    input gnd1;
    input gnd2;
    input in;
    output out;


    initial
        begin
        end

endmodule
