// generated by newgenasym  Thu Feb 12 15:10:46 2009


module hmc241lp3e (a, b, gnd1, gnd2, gnd3, gnd_pad, nc1, nc2, nc3, nc4, nc5, rf1,
        rf2, rf3, rf4, rfc, vdd);
    inout a;
    inout b;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd_pad;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout rf1;
    inout rf2;
    inout rf3;
    inout rf4;
    inout rfc;
    inout vdd;


    initial
        begin
        end

endmodule
