-- generated by newgenasym Thu Feb 12 15:10:46 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc241lp3e is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND_PAD:   INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NC5:       INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC;    
	RF3:       INOUT  STD_LOGIC;    
	RF4:       INOUT  STD_LOGIC;    
	RFC:       INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end hmc241lp3e;
