-- generated by newgenasym Mon Jun 07 16:45:19 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity diode_schottky is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end diode_schottky;
