// generated by newgenasym  Mon Feb 16 12:09:37 2009


module xc5vlx85_1ffg1153i (avdd_0, avss_0, cclk_0, cs_b_0, d_in_0, d_out_busy_0,
        done_0, dxn_0, dxp_0, gnd_1, gnd_10, gnd_100, gnd_101,
        gnd_102, gnd_103, gnd_104, gnd_105, gnd_106, gnd_107,
        gnd_108, gnd_109, gnd_11, gnd_110, gnd_111, gnd_112,
        gnd_113, gnd_114, gnd_115, gnd_116, gnd_117, gnd_118,
        gnd_119, gnd_12, gnd_120, gnd_121, gnd_122, gnd_123,
        gnd_124, gnd_125, gnd_126, gnd_127, gnd_128, gnd_129,
        gnd_13, gnd_130, gnd_131, gnd_132, gnd_133, gnd_134,
        gnd_135, gnd_136, gnd_137, gnd_138, gnd_139, gnd_14,
        gnd_140, gnd_141, gnd_142, gnd_143, gnd_144, gnd_145,
        gnd_146, gnd_147, gnd_148, gnd_149, gnd_15, gnd_150,
        gnd_151, gnd_152, gnd_153, gnd_154, gnd_155, gnd_156,
        gnd_157, gnd_158, gnd_159, gnd_16, gnd_160, gnd_161,
        gnd_162, gnd_163, gnd_164, gnd_165, gnd_166, gnd_167,
        gnd_168, gnd_169, gnd_17, gnd_170, gnd_171, gnd_172,
        gnd_173, gnd_174, gnd_175, gnd_176, gnd_177, gnd_178,
        gnd_179, gnd_18, gnd_180, gnd_181, gnd_182, gnd_183,
        gnd_184, gnd_185, gnd_186, gnd_187, gnd_188, gnd_189,
        gnd_19, gnd_190, gnd_191, gnd_192, gnd_193, gnd_194,
        gnd_195, gnd_196, gnd_197, gnd_2, gnd_20, gnd_21, gnd_22,
        gnd_23, gnd_24, gnd_25, gnd_26, gnd_27, gnd_28, gnd_29,
        gnd_3, gnd_30, gnd_31, gnd_32, gnd_33, gnd_34, gnd_35,
        gnd_36, gnd_37, gnd_38, gnd_39, gnd_4, gnd_40, gnd_41,
        gnd_42, gnd_43, gnd_44, gnd_45, gnd_46, gnd_47, gnd_48,
        gnd_49, gnd_5, gnd_50, gnd_51, gnd_52, gnd_53, gnd_54,
        gnd_55, gnd_56, gnd_57, gnd_58, gnd_59, gnd_6, gnd_60,
        gnd_61, gnd_62, gnd_63, gnd_64, gnd_65, gnd_66, gnd_67,
        gnd_68, gnd_69, gnd_7, gnd_70, gnd_71, gnd_72, gnd_73,
        gnd_74, gnd_75, gnd_76, gnd_77, gnd_78, gnd_79, gnd_8,
        gnd_80, gnd_81, gnd_82, gnd_83, gnd_84, gnd_85, gnd_86,
        gnd_87, gnd_88, gnd_89, gnd_9, gnd_90, gnd_91, gnd_92,
        gnd_93, gnd_94, gnd_95, gnd_96, gnd_97, gnd_98, gnd_99,
        hswapen_0, init_b_0, io_l0n_11, io_l0n_12, io_l0n_14,
        io_l0n_15, io_l0n_16, io_l0n_17, io_l0n_18, io_l0n_19,
        io_l0n_20, io_l0n_21, io_l0n_22, io_l0n_a18_1,
        io_l0n_cc_gc_3, io_l0n_cc_rs0_2, io_l0n_gc_d14_4,
        io_l0n_sm8n_13, io_l0p_11, io_l0p_12, io_l0p_14,
        io_l0p_15, io_l0p_16, io_l0p_17, io_l0p_18, io_l0p_19,
        io_l0p_20, io_l0p_21, io_l0p_22, io_l0p_a19_1,
        io_l0p_cc_gc_3, io_l0p_cc_rs1_2, io_l0p_gc_d15_4,
        io_l0p_sm8p_13, io_l10n_cc_12, io_l10n_cc_13,
        io_l10n_cc_14, io_l10n_cc_15, io_l10n_cc_16,
        io_l10n_cc_17, io_l10n_cc_18, io_l10n_cc_19,
        io_l10n_cc_20, io_l10n_cc_21, io_l10n_cc_22,
        io_l10n_cc_sm15n_11, io_l10p_cc_12, io_l10p_cc_13,
        io_l10p_cc_14, io_l10p_cc_15, io_l10p_cc_16,
        io_l10p_cc_17, io_l10p_cc_18, io_l10p_cc_19,
        io_l10p_cc_20, io_l10p_cc_21, io_l10p_cc_22,
        io_l10p_cc_sm15p_11, io_l11n_cc_12, io_l11n_cc_13,
        io_l11n_cc_14, io_l11n_cc_15, io_l11n_cc_16,
        io_l11n_cc_17, io_l11n_cc_18, io_l11n_cc_19,
        io_l11n_cc_20, io_l11n_cc_21, io_l11n_cc_22,
        io_l11n_cc_sm14n_11, io_l11p_cc_12, io_l11p_cc_13,
        io_l11p_cc_14, io_l11p_cc_15, io_l11p_cc_16,
        io_l11p_cc_17, io_l11p_cc_18, io_l11p_cc_19,
        io_l11p_cc_20, io_l11p_cc_21, io_l11p_cc_22,
        io_l11p_cc_sm14p_11, io_l12n_vrp_11, io_l12n_vrp_12,
        io_l12n_vrp_13, io_l12n_vrp_14, io_l12n_vrp_15,
        io_l12n_vrp_16, io_l12n_vrp_17, io_l12n_vrp_18,
        io_l12n_vrp_19, io_l12n_vrp_20, io_l12n_vrp_21,
        io_l12n_vrp_22, io_l12p_vrn_11, io_l12p_vrn_12,
        io_l12p_vrn_13, io_l12p_vrn_14, io_l12p_vrn_15,
        io_l12p_vrn_16, io_l12p_vrn_17, io_l12p_vrn_18,
        io_l12p_vrn_19, io_l12p_vrn_20, io_l12p_vrn_21,
        io_l12p_vrn_22, io_l13n_11, io_l13n_12, io_l13n_13,
        io_l13n_14, io_l13n_15, io_l13n_16, io_l13n_17,
        io_l13n_18, io_l13n_19, io_l13n_20, io_l13n_21,
        io_l13n_22, io_l13p_11, io_l13p_12, io_l13p_13,
        io_l13p_14, io_l13p_15, io_l13p_16, io_l13p_17,
        io_l13p_18, io_l13p_19, io_l13p_20, io_l13p_21,
        io_l13p_22, io_l14n_vref_11, io_l14n_vref_12,
        io_l14n_vref_13, io_l14n_vref_14, io_l14n_vref_15,
        io_l14n_vref_16, io_l14n_vref_17, io_l14n_vref_18,
        io_l14n_vref_19, io_l14n_vref_20, io_l14n_vref_21,
        io_l14n_vref_22, io_l14p_11, io_l14p_12, io_l14p_13,
        io_l14p_14, io_l14p_15, io_l14p_16, io_l14p_17,
        io_l14p_18, io_l14p_19, io_l14p_20, io_l14p_21,
        io_l14p_22, io_l15n_12, io_l15n_13, io_l15n_14,
        io_l15n_15, io_l15n_16, io_l15n_17, io_l15n_18,
        io_l15n_19, io_l15n_20, io_l15n_21, io_l15n_22,
        io_l15n_sm13n_11, io_l15p_12, io_l15p_13, io_l15p_14,
        io_l15p_15, io_l15p_16, io_l15p_17, io_l15p_18,
        io_l15p_19, io_l15p_20, io_l15p_21, io_l15p_22,
        io_l15p_sm13p_11, io_l16n_12, io_l16n_13, io_l16n_14,
        io_l16n_15, io_l16n_16, io_l16n_17, io_l16n_18,
        io_l16n_19, io_l16n_20, io_l16n_21, io_l16n_22,
        io_l16n_sm12n_11, io_l16p_12, io_l16p_13, io_l16p_14,
        io_l16p_15, io_l16p_16, io_l16p_17, io_l16p_18,
        io_l16p_19, io_l16p_20, io_l16p_21, io_l16p_22,
        io_l16p_sm12p_11, io_l17n_12, io_l17n_13, io_l17n_14,
        io_l17n_15, io_l17n_16, io_l17n_17, io_l17n_18,
        io_l17n_19, io_l17n_20, io_l17n_21, io_l17n_22,
        io_l17n_sm11n_11, io_l17p_12, io_l17p_13, io_l17p_14,
        io_l17p_15, io_l17p_16, io_l17p_17, io_l17p_18,
        io_l17p_19, io_l17p_20, io_l17p_21, io_l17p_22,
        io_l17p_sm11p_11, io_l18n_12, io_l18n_13, io_l18n_14,
        io_l18n_15, io_l18n_16, io_l18n_17, io_l18n_18,
        io_l18n_19, io_l18n_20, io_l18n_21, io_l18n_22,
        io_l18n_sm10n_11, io_l18p_12, io_l18p_13, io_l18p_14,
        io_l18p_15, io_l18p_16, io_l18p_17, io_l18p_18,
        io_l18p_19, io_l18p_20, io_l18p_21, io_l18p_22,
        io_l18p_sm10p_11, io_l19n_12, io_l19n_13, io_l19n_14,
        io_l19n_15, io_l19n_16, io_l19n_17, io_l19n_18,
        io_l19n_19, io_l19n_20, io_l19n_21, io_l19n_22,
        io_l19n_sm9n_11, io_l19p_12, io_l19p_13, io_l19p_14,
        io_l19p_15, io_l19p_16, io_l19p_17, io_l19p_18,
        io_l19p_19, io_l19p_20, io_l19p_21, io_l19p_22,
        io_l19p_sm9p_11, io_l1n_11, io_l1n_12, io_l1n_14,
        io_l1n_15, io_l1n_16, io_l1n_17, io_l1n_18, io_l1n_19,
        io_l1n_20, io_l1n_21, io_l1n_22, io_l1n_a16_1,
        io_l1n_cc_a24_2, io_l1n_cc_gc_3, io_l1n_gc_d12_4,
        io_l1n_sm7n_13, io_l1p_11, io_l1p_12, io_l1p_14,
        io_l1p_15, io_l1p_16, io_l1p_17, io_l1p_18, io_l1p_19,
        io_l1p_20, io_l1p_21, io_l1p_22, io_l1p_a17_1,
        io_l1p_cc_a25_2, io_l1p_cc_gc_3, io_l1p_gc_d13_4,
        io_l1p_sm7p_13, io_l2n_11, io_l2n_12, io_l2n_14,
        io_l2n_15, io_l2n_16, io_l2n_17, io_l2n_18, io_l2n_19,
        io_l2n_20, io_l2n_21, io_l2n_22, io_l2n_a14_d30_1,
        io_l2n_a22_2, io_l2n_gc_d10_4, io_l2n_gc_vrp_3,
        io_l2n_sm6n_13, io_l2p_11, io_l2p_12, io_l2p_14,
        io_l2p_15, io_l2p_16, io_l2p_17, io_l2p_18, io_l2p_19,
        io_l2p_20, io_l2p_21, io_l2p_22, io_l2p_a15_d31_1,
        io_l2p_a23_2, io_l2p_gc_d11_4, io_l2p_gc_vrn_3,
        io_l2p_sm6p_13, io_l3n_11, io_l3n_12, io_l3n_14,
        io_l3n_15, io_l3n_16, io_l3n_17, io_l3n_18, io_l3n_19,
        io_l3n_20, io_l3n_21, io_l3n_22, io_l3n_a12_d28_1,
        io_l3n_a20_2, io_l3n_gc_3, io_l3n_gc_d8_4,
        io_l3n_sm5n_13, io_l3p_11, io_l3p_12, io_l3p_14,
        io_l3p_15, io_l3p_16, io_l3p_17, io_l3p_18, io_l3p_19,
        io_l3p_20, io_l3p_21, io_l3p_22, io_l3p_a13_d29_1,
        io_l3p_a21_2, io_l3p_gc_3, io_l3p_gc_d9_4,
        io_l3p_sm5p_13, io_l4n_gc_vref_3, io_l4n_gc_vref_4,
        io_l4n_vref_11, io_l4n_vref_12, io_l4n_vref_13,
        io_l4n_vref_14, io_l4n_vref_15, io_l4n_vref_16,
        io_l4n_vref_17, io_l4n_vref_18, io_l4n_vref_19,
        io_l4n_vref_20, io_l4n_vref_21, io_l4n_vref_22,
        io_l4n_vref_a10_d26_1, io_l4n_vref_foe_b_mosi_2,
        io_l4p_11, io_l4p_12, io_l4p_13, io_l4p_14, io_l4p_15,
        io_l4p_16, io_l4p_17, io_l4p_18, io_l4p_19, io_l4p_20,
        io_l4p_21, io_l4p_22, io_l4p_a11_d27_1, io_l4p_fcs_b_2,
        io_l4p_gc_3, io_l4p_gc_4, io_l5n_11, io_l5n_12, io_l5n_14,
        io_l5n_15, io_l5n_16, io_l5n_17, io_l5n_18, io_l5n_19,
        io_l5n_20, io_l5n_21, io_l5n_22, io_l5n_a8_d24_1,
        io_l5n_cso_b_2, io_l5n_gc_3, io_l5n_gc_4, io_l5n_sm4n_13,
        io_l5p_11, io_l5p_12, io_l5p_14, io_l5p_15, io_l5p_16,
        io_l5p_17, io_l5p_18, io_l5p_19, io_l5p_20, io_l5p_21,
        io_l5p_22, io_l5p_a9_d25_1, io_l5p_fwe_b_2, io_l5p_gc_3,
        io_l5p_gc_4, io_l5p_sm4p_13, io_l6n_11, io_l6n_12,
        io_l6n_14, io_l6n_15, io_l6n_16, io_l6n_17, io_l6n_18,
        io_l6n_19, io_l6n_20, io_l6n_21, io_l6n_22,
        io_l6n_a6_d22_1, io_l6n_d6_2, io_l6n_gc_3, io_l6n_gc_4,
        io_l6n_sm3n_13, io_l6p_11, io_l6p_12, io_l6p_14,
        io_l6p_15, io_l6p_16, io_l6p_17, io_l6p_18, io_l6p_19,
        io_l6p_20, io_l6p_21, io_l6p_22, io_l6p_a7_d23_1,
        io_l6p_d7_2, io_l6p_gc_3, io_l6p_gc_4, io_l6p_sm3p_13,
        io_l7n_11, io_l7n_12, io_l7n_14, io_l7n_15, io_l7n_16,
        io_l7n_17, io_l7n_18, io_l7n_19, io_l7n_20, io_l7n_21,
        io_l7n_22, io_l7n_a4_d20_1, io_l7n_d4_2, io_l7n_gc_3,
        io_l7n_gc_vrp_4, io_l7n_sm2n_13, io_l7p_11, io_l7p_12,
        io_l7p_14, io_l7p_15, io_l7p_16, io_l7p_17, io_l7p_18,
        io_l7p_19, io_l7p_20, io_l7p_21, io_l7p_22,
        io_l7p_a5_d21_1, io_l7p_d5_2, io_l7p_gc_3,
        io_l7p_gc_vrn_4, io_l7p_sm2p_13, io_l8n_cc_11,
        io_l8n_cc_12, io_l8n_cc_14, io_l8n_cc_15, io_l8n_cc_16,
        io_l8n_cc_17, io_l8n_cc_18, io_l8n_cc_19, io_l8n_cc_20,
        io_l8n_cc_21, io_l8n_cc_22, io_l8n_cc_a2_d18_1,
        io_l8n_cc_gc_4, io_l8n_cc_sm1n_13, io_l8n_d2_fs2_2,
        io_l8n_gc_3, io_l8p_cc_11, io_l8p_cc_12, io_l8p_cc_14,
        io_l8p_cc_15, io_l8p_cc_16, io_l8p_cc_17, io_l8p_cc_18,
        io_l8p_cc_19, io_l8p_cc_20, io_l8p_cc_21, io_l8p_cc_22,
        io_l8p_cc_a3_d19_1, io_l8p_cc_gc_4, io_l8p_cc_sm1p_13,
        io_l8p_d3_2, io_l8p_gc_3, io_l9n_cc_11, io_l9n_cc_12,
        io_l9n_cc_14, io_l9n_cc_15, io_l9n_cc_16, io_l9n_cc_17,
        io_l9n_cc_18, io_l9n_cc_19, io_l9n_cc_20, io_l9n_cc_21,
        io_l9n_cc_22, io_l9n_cc_a0_d16_1, io_l9n_cc_gc_4,
        io_l9n_cc_sm0n_13, io_l9n_d0_fs0_2, io_l9n_gc_3,
        io_l9p_cc_11, io_l9p_cc_12, io_l9p_cc_14, io_l9p_cc_15,
        io_l9p_cc_16, io_l9p_cc_17, io_l9p_cc_18, io_l9p_cc_19,
        io_l9p_cc_20, io_l9p_cc_21, io_l9p_cc_22,
        io_l9p_cc_a1_d17_1, io_l9p_cc_gc_4, io_l9p_cc_sm0p_13,
        io_l9p_d1_fs1_2, io_l9p_gc_3, m0_0, m1_0, m2_0, nc_1, nc_10,
        nc_100, nc_101, nc_102, nc_103, nc_104, nc_105, nc_106,
        nc_107, nc_108, nc_109, nc_11, nc_110, nc_111, nc_112,
        nc_113, nc_114, nc_115, nc_116, nc_117, nc_118, nc_119,
        nc_12, nc_120, nc_121, nc_122, nc_123, nc_124, nc_125,
        nc_126, nc_127, nc_128, nc_129, nc_13, nc_130, nc_131,
        nc_132, nc_133, nc_134, nc_135, nc_136, nc_137, nc_138,
        nc_139, nc_14, nc_140, nc_141, nc_142, nc_143, nc_144,
        nc_145, nc_146, nc_147, nc_148, nc_149, nc_15, nc_150,
        nc_151, nc_152, nc_153, nc_154, nc_155, nc_156, nc_157,
        nc_158, nc_159, nc_16, nc_160, nc_161, nc_162, nc_163,
        nc_164, nc_165, nc_166, nc_167, nc_168, nc_169, nc_17,
        nc_170, nc_171, nc_172, nc_173, nc_174, nc_175, nc_176,
        nc_177, nc_178, nc_179, nc_18, nc_180, nc_181, nc_182,
        nc_183, nc_184, nc_185, nc_186, nc_187, nc_188, nc_189,
        nc_19, nc_190, nc_191, nc_192, nc_193, nc_194, nc_195,
        nc_196, nc_197, nc_198, nc_199, nc_2, nc_20, nc_200, nc_201,
        nc_202, nc_203, nc_204, nc_205, nc_206, nc_207, nc_208,
        nc_209, nc_21, nc_210, nc_211, nc_212, nc_213, nc_214,
        nc_215, nc_216, nc_217, nc_218, nc_219, nc_22, nc_220,
        nc_221, nc_222, nc_223, nc_224, nc_225, nc_226, nc_227,
        nc_228, nc_229, nc_23, nc_230, nc_231, nc_232, nc_233,
        nc_234, nc_235, nc_236, nc_237, nc_238, nc_239, nc_24,
        nc_240, nc_25, nc_26, nc_27, nc_28, nc_29, nc_3, nc_30, nc_31,
        nc_32, nc_33, nc_34, nc_35, nc_36, nc_37, nc_38, nc_39, nc_4,
        nc_40, nc_41, nc_42, nc_43, nc_44, nc_45, nc_46, nc_47, nc_48,
        nc_49, nc_5, nc_50, nc_51, nc_52, nc_53, nc_54, nc_55, nc_56,
        nc_57, nc_58, nc_59, nc_6, nc_60, nc_61, nc_62, nc_63, nc_64,
        nc_65, nc_66, nc_67, nc_68, nc_69, nc_7, nc_70, nc_71, nc_72,
        nc_73, nc_74, nc_75, nc_76, nc_77, nc_78, nc_79, nc_8, nc_80,
        nc_81, nc_82, nc_83, nc_84, nc_85, nc_86, nc_87, nc_88, nc_89,
        nc_9, nc_90, nc_91, nc_92, nc_93, nc_94, nc_95, nc_96, nc_97,
        nc_98, nc_99, program_b_0, rdwr_b_0, rsvd_1, rsvd_2, tck_0,
        tdi_0, tdo_0, tms_0, vbatt_0, vccaux_1, vccaux_10,
        vccaux_11, vccaux_12, vccaux_2, vccaux_3, vccaux_4,
        vccaux_5, vccaux_6, vccaux_7, vccaux_8, vccaux_9, vccint_1,
        vccint_10, vccint_11, vccint_12, vccint_13, vccint_14,
        vccint_15, vccint_16, vccint_17, vccint_18, vccint_19,
        vccint_2, vccint_20, vccint_21, vccint_22, vccint_23,
        vccint_24, vccint_25, vccint_26, vccint_27, vccint_28,
        vccint_29, vccint_3, vccint_30, vccint_31, vccint_32,
        vccint_33, vccint_34, vccint_35, vccint_36, vccint_37,
        vccint_38, vccint_39, vccint_4, vccint_40, vccint_41,
        vccint_42, vccint_43, vccint_44, vccint_45, vccint_46,
        vccint_47, vccint_48, vccint_49, vccint_5, vccint_50,
        vccint_51, vccint_52, vccint_53, vccint_6, vccint_7,
        vccint_8, vccint_9, vcco_0_1, vcco_0_2, vcco_11_1,
        vcco_11_2, vcco_11_3, vcco_12_1, vcco_12_2, vcco_12_3,
        vcco_13_1, vcco_13_2, vcco_13_3, vcco_14_1, vcco_14_2,
        vcco_14_3, vcco_15_1, vcco_15_2, vcco_15_3, vcco_16_1,
        vcco_16_2, vcco_16_3, vcco_17_1, vcco_17_2, vcco_17_3,
        vcco_18_1, vcco_18_2, vcco_18_3, vcco_19_1, vcco_19_2,
        vcco_19_3, vcco_1_1, vcco_1_2, vcco_20_1, vcco_20_2,
        vcco_20_3, vcco_21_1, vcco_21_2, vcco_21_3, vcco_22_1,
        vcco_22_2, vcco_22_3, vcco_23_1, vcco_23_2, vcco_23_3,
        vcco_24_1, vcco_24_2, vcco_24_3, vcco_25_1, vcco_25_2,
        vcco_25_3, vcco_26_1, vcco_26_2, vcco_26_3, vcco_2_1,
        vcco_2_2, vcco_3_1, vcco_3_2, vcco_4_1, vcco_4_2, vcco_5_1,
        vcco_5_2, vcco_5_3, vcco_6_1, vcco_6_2, vcco_6_3, vn_0,
        vp_0, vrefn_0, vrefp_0);
    inout avdd_0;
    inout avss_0;
    inout cclk_0;
    inout cs_b_0;
    inout d_in_0;
    inout d_out_busy_0;
    inout done_0;
    inout dxn_0;
    inout dxp_0;
    input gnd_1;
    input gnd_10;
    input gnd_100;
    input gnd_101;
    input gnd_102;
    input gnd_103;
    input gnd_104;
    input gnd_105;
    input gnd_106;
    input gnd_107;
    input gnd_108;
    input gnd_109;
    input gnd_11;
    input gnd_110;
    input gnd_111;
    input gnd_112;
    input gnd_113;
    input gnd_114;
    input gnd_115;
    input gnd_116;
    input gnd_117;
    input gnd_118;
    input gnd_119;
    input gnd_12;
    input gnd_120;
    input gnd_121;
    input gnd_122;
    input gnd_123;
    input gnd_124;
    input gnd_125;
    input gnd_126;
    input gnd_127;
    input gnd_128;
    input gnd_129;
    input gnd_13;
    input gnd_130;
    input gnd_131;
    input gnd_132;
    input gnd_133;
    input gnd_134;
    input gnd_135;
    input gnd_136;
    input gnd_137;
    input gnd_138;
    input gnd_139;
    input gnd_14;
    input gnd_140;
    input gnd_141;
    input gnd_142;
    input gnd_143;
    input gnd_144;
    input gnd_145;
    input gnd_146;
    input gnd_147;
    input gnd_148;
    input gnd_149;
    input gnd_15;
    input gnd_150;
    input gnd_151;
    input gnd_152;
    input gnd_153;
    input gnd_154;
    input gnd_155;
    input gnd_156;
    input gnd_157;
    input gnd_158;
    input gnd_159;
    input gnd_16;
    input gnd_160;
    input gnd_161;
    input gnd_162;
    input gnd_163;
    input gnd_164;
    input gnd_165;
    input gnd_166;
    input gnd_167;
    input gnd_168;
    input gnd_169;
    input gnd_17;
    input gnd_170;
    input gnd_171;
    input gnd_172;
    input gnd_173;
    input gnd_174;
    input gnd_175;
    input gnd_176;
    input gnd_177;
    input gnd_178;
    input gnd_179;
    input gnd_18;
    input gnd_180;
    input gnd_181;
    input gnd_182;
    input gnd_183;
    input gnd_184;
    input gnd_185;
    input gnd_186;
    input gnd_187;
    input gnd_188;
    input gnd_189;
    input gnd_19;
    input gnd_190;
    input gnd_191;
    input gnd_192;
    input gnd_193;
    input gnd_194;
    input gnd_195;
    input gnd_196;
    input gnd_197;
    input gnd_2;
    input gnd_20;
    input gnd_21;
    input gnd_22;
    input gnd_23;
    input gnd_24;
    input gnd_25;
    input gnd_26;
    input gnd_27;
    input gnd_28;
    input gnd_29;
    input gnd_3;
    input gnd_30;
    input gnd_31;
    input gnd_32;
    input gnd_33;
    input gnd_34;
    input gnd_35;
    input gnd_36;
    input gnd_37;
    input gnd_38;
    input gnd_39;
    input gnd_4;
    input gnd_40;
    input gnd_41;
    input gnd_42;
    input gnd_43;
    input gnd_44;
    input gnd_45;
    input gnd_46;
    input gnd_47;
    input gnd_48;
    input gnd_49;
    input gnd_5;
    input gnd_50;
    input gnd_51;
    input gnd_52;
    input gnd_53;
    input gnd_54;
    input gnd_55;
    input gnd_56;
    input gnd_57;
    input gnd_58;
    input gnd_59;
    input gnd_6;
    input gnd_60;
    input gnd_61;
    input gnd_62;
    input gnd_63;
    input gnd_64;
    input gnd_65;
    input gnd_66;
    input gnd_67;
    input gnd_68;
    input gnd_69;
    input gnd_7;
    input gnd_70;
    input gnd_71;
    input gnd_72;
    input gnd_73;
    input gnd_74;
    input gnd_75;
    input gnd_76;
    input gnd_77;
    input gnd_78;
    input gnd_79;
    input gnd_8;
    input gnd_80;
    input gnd_81;
    input gnd_82;
    input gnd_83;
    input gnd_84;
    input gnd_85;
    input gnd_86;
    input gnd_87;
    input gnd_88;
    input gnd_89;
    input gnd_9;
    input gnd_90;
    input gnd_91;
    input gnd_92;
    input gnd_93;
    input gnd_94;
    input gnd_95;
    input gnd_96;
    input gnd_97;
    input gnd_98;
    input gnd_99;
    inout hswapen_0;
    inout init_b_0;
    inout io_l0n_11;
    inout io_l0n_12;
    inout io_l0n_14;
    inout io_l0n_15;
    inout io_l0n_16;
    inout io_l0n_17;
    inout io_l0n_18;
    inout io_l0n_19;
    inout io_l0n_20;
    inout io_l0n_21;
    inout io_l0n_22;
    inout io_l0n_a18_1;
    inout io_l0n_cc_gc_3;
    inout io_l0n_cc_rs0_2;
    inout io_l0n_gc_d14_4;
    inout io_l0n_sm8n_13;
    inout io_l0p_11;
    inout io_l0p_12;
    inout io_l0p_14;
    inout io_l0p_15;
    inout io_l0p_16;
    inout io_l0p_17;
    inout io_l0p_18;
    inout io_l0p_19;
    inout io_l0p_20;
    inout io_l0p_21;
    inout io_l0p_22;
    inout io_l0p_a19_1;
    inout io_l0p_cc_gc_3;
    inout io_l0p_cc_rs1_2;
    inout io_l0p_gc_d15_4;
    inout io_l0p_sm8p_13;
    inout io_l10n_cc_12;
    inout io_l10n_cc_13;
    inout io_l10n_cc_14;
    inout io_l10n_cc_15;
    inout io_l10n_cc_16;
    inout io_l10n_cc_17;
    inout io_l10n_cc_18;
    inout io_l10n_cc_19;
    inout io_l10n_cc_20;
    inout io_l10n_cc_21;
    inout io_l10n_cc_22;
    inout io_l10n_cc_sm15n_11;
    inout io_l10p_cc_12;
    inout io_l10p_cc_13;
    inout io_l10p_cc_14;
    inout io_l10p_cc_15;
    inout io_l10p_cc_16;
    inout io_l10p_cc_17;
    inout io_l10p_cc_18;
    inout io_l10p_cc_19;
    inout io_l10p_cc_20;
    inout io_l10p_cc_21;
    inout io_l10p_cc_22;
    inout io_l10p_cc_sm15p_11;
    inout io_l11n_cc_12;
    inout io_l11n_cc_13;
    inout io_l11n_cc_14;
    inout io_l11n_cc_15;
    inout io_l11n_cc_16;
    inout io_l11n_cc_17;
    inout io_l11n_cc_18;
    inout io_l11n_cc_19;
    inout io_l11n_cc_20;
    inout io_l11n_cc_21;
    inout io_l11n_cc_22;
    inout io_l11n_cc_sm14n_11;
    inout io_l11p_cc_12;
    inout io_l11p_cc_13;
    inout io_l11p_cc_14;
    inout io_l11p_cc_15;
    inout io_l11p_cc_16;
    inout io_l11p_cc_17;
    inout io_l11p_cc_18;
    inout io_l11p_cc_19;
    inout io_l11p_cc_20;
    inout io_l11p_cc_21;
    inout io_l11p_cc_22;
    inout io_l11p_cc_sm14p_11;
    inout io_l12n_vrp_11;
    inout io_l12n_vrp_12;
    inout io_l12n_vrp_13;
    inout io_l12n_vrp_14;
    inout io_l12n_vrp_15;
    inout io_l12n_vrp_16;
    inout io_l12n_vrp_17;
    inout io_l12n_vrp_18;
    inout io_l12n_vrp_19;
    inout io_l12n_vrp_20;
    inout io_l12n_vrp_21;
    inout io_l12n_vrp_22;
    inout io_l12p_vrn_11;
    inout io_l12p_vrn_12;
    inout io_l12p_vrn_13;
    inout io_l12p_vrn_14;
    inout io_l12p_vrn_15;
    inout io_l12p_vrn_16;
    inout io_l12p_vrn_17;
    inout io_l12p_vrn_18;
    inout io_l12p_vrn_19;
    inout io_l12p_vrn_20;
    inout io_l12p_vrn_21;
    inout io_l12p_vrn_22;
    inout io_l13n_11;
    inout io_l13n_12;
    inout io_l13n_13;
    inout io_l13n_14;
    inout io_l13n_15;
    inout io_l13n_16;
    inout io_l13n_17;
    inout io_l13n_18;
    inout io_l13n_19;
    inout io_l13n_20;
    inout io_l13n_21;
    inout io_l13n_22;
    inout io_l13p_11;
    inout io_l13p_12;
    inout io_l13p_13;
    inout io_l13p_14;
    inout io_l13p_15;
    inout io_l13p_16;
    inout io_l13p_17;
    inout io_l13p_18;
    inout io_l13p_19;
    inout io_l13p_20;
    inout io_l13p_21;
    inout io_l13p_22;
    inout io_l14n_vref_11;
    inout io_l14n_vref_12;
    inout io_l14n_vref_13;
    inout io_l14n_vref_14;
    inout io_l14n_vref_15;
    inout io_l14n_vref_16;
    inout io_l14n_vref_17;
    inout io_l14n_vref_18;
    inout io_l14n_vref_19;
    inout io_l14n_vref_20;
    inout io_l14n_vref_21;
    inout io_l14n_vref_22;
    inout io_l14p_11;
    inout io_l14p_12;
    inout io_l14p_13;
    inout io_l14p_14;
    inout io_l14p_15;
    inout io_l14p_16;
    inout io_l14p_17;
    inout io_l14p_18;
    inout io_l14p_19;
    inout io_l14p_20;
    inout io_l14p_21;
    inout io_l14p_22;
    inout io_l15n_12;
    inout io_l15n_13;
    inout io_l15n_14;
    inout io_l15n_15;
    inout io_l15n_16;
    inout io_l15n_17;
    inout io_l15n_18;
    inout io_l15n_19;
    inout io_l15n_20;
    inout io_l15n_21;
    inout io_l15n_22;
    inout io_l15n_sm13n_11;
    inout io_l15p_12;
    inout io_l15p_13;
    inout io_l15p_14;
    inout io_l15p_15;
    inout io_l15p_16;
    inout io_l15p_17;
    inout io_l15p_18;
    inout io_l15p_19;
    inout io_l15p_20;
    inout io_l15p_21;
    inout io_l15p_22;
    inout io_l15p_sm13p_11;
    inout io_l16n_12;
    inout io_l16n_13;
    inout io_l16n_14;
    inout io_l16n_15;
    inout io_l16n_16;
    inout io_l16n_17;
    inout io_l16n_18;
    inout io_l16n_19;
    inout io_l16n_20;
    inout io_l16n_21;
    inout io_l16n_22;
    inout io_l16n_sm12n_11;
    inout io_l16p_12;
    inout io_l16p_13;
    inout io_l16p_14;
    inout io_l16p_15;
    inout io_l16p_16;
    inout io_l16p_17;
    inout io_l16p_18;
    inout io_l16p_19;
    inout io_l16p_20;
    inout io_l16p_21;
    inout io_l16p_22;
    inout io_l16p_sm12p_11;
    inout io_l17n_12;
    inout io_l17n_13;
    inout io_l17n_14;
    inout io_l17n_15;
    inout io_l17n_16;
    inout io_l17n_17;
    inout io_l17n_18;
    inout io_l17n_19;
    inout io_l17n_20;
    inout io_l17n_21;
    inout io_l17n_22;
    inout io_l17n_sm11n_11;
    inout io_l17p_12;
    inout io_l17p_13;
    inout io_l17p_14;
    inout io_l17p_15;
    inout io_l17p_16;
    inout io_l17p_17;
    inout io_l17p_18;
    inout io_l17p_19;
    inout io_l17p_20;
    inout io_l17p_21;
    inout io_l17p_22;
    inout io_l17p_sm11p_11;
    inout io_l18n_12;
    inout io_l18n_13;
    inout io_l18n_14;
    inout io_l18n_15;
    inout io_l18n_16;
    inout io_l18n_17;
    inout io_l18n_18;
    inout io_l18n_19;
    inout io_l18n_20;
    inout io_l18n_21;
    inout io_l18n_22;
    inout io_l18n_sm10n_11;
    inout io_l18p_12;
    inout io_l18p_13;
    inout io_l18p_14;
    inout io_l18p_15;
    inout io_l18p_16;
    inout io_l18p_17;
    inout io_l18p_18;
    inout io_l18p_19;
    inout io_l18p_20;
    inout io_l18p_21;
    inout io_l18p_22;
    inout io_l18p_sm10p_11;
    inout io_l19n_12;
    inout io_l19n_13;
    inout io_l19n_14;
    inout io_l19n_15;
    inout io_l19n_16;
    inout io_l19n_17;
    inout io_l19n_18;
    inout io_l19n_19;
    inout io_l19n_20;
    inout io_l19n_21;
    inout io_l19n_22;
    inout io_l19n_sm9n_11;
    inout io_l19p_12;
    inout io_l19p_13;
    inout io_l19p_14;
    inout io_l19p_15;
    inout io_l19p_16;
    inout io_l19p_17;
    inout io_l19p_18;
    inout io_l19p_19;
    inout io_l19p_20;
    inout io_l19p_21;
    inout io_l19p_22;
    inout io_l19p_sm9p_11;
    inout io_l1n_11;
    inout io_l1n_12;
    inout io_l1n_14;
    inout io_l1n_15;
    inout io_l1n_16;
    inout io_l1n_17;
    inout io_l1n_18;
    inout io_l1n_19;
    inout io_l1n_20;
    inout io_l1n_21;
    inout io_l1n_22;
    inout io_l1n_a16_1;
    inout io_l1n_cc_a24_2;
    inout io_l1n_cc_gc_3;
    inout io_l1n_gc_d12_4;
    inout io_l1n_sm7n_13;
    inout io_l1p_11;
    inout io_l1p_12;
    inout io_l1p_14;
    inout io_l1p_15;
    inout io_l1p_16;
    inout io_l1p_17;
    inout io_l1p_18;
    inout io_l1p_19;
    inout io_l1p_20;
    inout io_l1p_21;
    inout io_l1p_22;
    inout io_l1p_a17_1;
    inout io_l1p_cc_a25_2;
    inout io_l1p_cc_gc_3;
    inout io_l1p_gc_d13_4;
    inout io_l1p_sm7p_13;
    inout io_l2n_11;
    inout io_l2n_12;
    inout io_l2n_14;
    inout io_l2n_15;
    inout io_l2n_16;
    inout io_l2n_17;
    inout io_l2n_18;
    inout io_l2n_19;
    inout io_l2n_20;
    inout io_l2n_21;
    inout io_l2n_22;
    inout io_l2n_a14_d30_1;
    inout io_l2n_a22_2;
    inout io_l2n_gc_d10_4;
    inout io_l2n_gc_vrp_3;
    inout io_l2n_sm6n_13;
    inout io_l2p_11;
    inout io_l2p_12;
    inout io_l2p_14;
    inout io_l2p_15;
    inout io_l2p_16;
    inout io_l2p_17;
    inout io_l2p_18;
    inout io_l2p_19;
    inout io_l2p_20;
    inout io_l2p_21;
    inout io_l2p_22;
    inout io_l2p_a15_d31_1;
    inout io_l2p_a23_2;
    inout io_l2p_gc_d11_4;
    inout io_l2p_gc_vrn_3;
    inout io_l2p_sm6p_13;
    inout io_l3n_11;
    inout io_l3n_12;
    inout io_l3n_14;
    inout io_l3n_15;
    inout io_l3n_16;
    inout io_l3n_17;
    inout io_l3n_18;
    inout io_l3n_19;
    inout io_l3n_20;
    inout io_l3n_21;
    inout io_l3n_22;
    inout io_l3n_a12_d28_1;
    inout io_l3n_a20_2;
    inout io_l3n_gc_3;
    inout io_l3n_gc_d8_4;
    inout io_l3n_sm5n_13;
    inout io_l3p_11;
    inout io_l3p_12;
    inout io_l3p_14;
    inout io_l3p_15;
    inout io_l3p_16;
    inout io_l3p_17;
    inout io_l3p_18;
    inout io_l3p_19;
    inout io_l3p_20;
    inout io_l3p_21;
    inout io_l3p_22;
    inout io_l3p_a13_d29_1;
    inout io_l3p_a21_2;
    inout io_l3p_gc_3;
    inout io_l3p_gc_d9_4;
    inout io_l3p_sm5p_13;
    inout io_l4n_gc_vref_3;
    inout io_l4n_gc_vref_4;
    inout io_l4n_vref_11;
    inout io_l4n_vref_12;
    inout io_l4n_vref_13;
    inout io_l4n_vref_14;
    inout io_l4n_vref_15;
    inout io_l4n_vref_16;
    inout io_l4n_vref_17;
    inout io_l4n_vref_18;
    inout io_l4n_vref_19;
    inout io_l4n_vref_20;
    inout io_l4n_vref_21;
    inout io_l4n_vref_22;
    inout io_l4n_vref_a10_d26_1;
    inout io_l4n_vref_foe_b_mosi_2;
    inout io_l4p_11;
    inout io_l4p_12;
    inout io_l4p_13;
    inout io_l4p_14;
    inout io_l4p_15;
    inout io_l4p_16;
    inout io_l4p_17;
    inout io_l4p_18;
    inout io_l4p_19;
    inout io_l4p_20;
    inout io_l4p_21;
    inout io_l4p_22;
    inout io_l4p_a11_d27_1;
    inout io_l4p_fcs_b_2;
    inout io_l4p_gc_3;
    inout io_l4p_gc_4;
    inout io_l5n_11;
    inout io_l5n_12;
    inout io_l5n_14;
    inout io_l5n_15;
    inout io_l5n_16;
    inout io_l5n_17;
    inout io_l5n_18;
    inout io_l5n_19;
    inout io_l5n_20;
    inout io_l5n_21;
    inout io_l5n_22;
    inout io_l5n_a8_d24_1;
    inout io_l5n_cso_b_2;
    inout io_l5n_gc_3;
    inout io_l5n_gc_4;
    inout io_l5n_sm4n_13;
    inout io_l5p_11;
    inout io_l5p_12;
    inout io_l5p_14;
    inout io_l5p_15;
    inout io_l5p_16;
    inout io_l5p_17;
    inout io_l5p_18;
    inout io_l5p_19;
    inout io_l5p_20;
    inout io_l5p_21;
    inout io_l5p_22;
    inout io_l5p_a9_d25_1;
    inout io_l5p_fwe_b_2;
    inout io_l5p_gc_3;
    inout io_l5p_gc_4;
    inout io_l5p_sm4p_13;
    inout io_l6n_11;
    inout io_l6n_12;
    inout io_l6n_14;
    inout io_l6n_15;
    inout io_l6n_16;
    inout io_l6n_17;
    inout io_l6n_18;
    inout io_l6n_19;
    inout io_l6n_20;
    inout io_l6n_21;
    inout io_l6n_22;
    inout io_l6n_a6_d22_1;
    inout io_l6n_d6_2;
    inout io_l6n_gc_3;
    inout io_l6n_gc_4;
    inout io_l6n_sm3n_13;
    inout io_l6p_11;
    inout io_l6p_12;
    inout io_l6p_14;
    inout io_l6p_15;
    inout io_l6p_16;
    inout io_l6p_17;
    inout io_l6p_18;
    inout io_l6p_19;
    inout io_l6p_20;
    inout io_l6p_21;
    inout io_l6p_22;
    inout io_l6p_a7_d23_1;
    inout io_l6p_d7_2;
    inout io_l6p_gc_3;
    inout io_l6p_gc_4;
    inout io_l6p_sm3p_13;
    inout io_l7n_11;
    inout io_l7n_12;
    inout io_l7n_14;
    inout io_l7n_15;
    inout io_l7n_16;
    inout io_l7n_17;
    inout io_l7n_18;
    inout io_l7n_19;
    inout io_l7n_20;
    inout io_l7n_21;
    inout io_l7n_22;
    inout io_l7n_a4_d20_1;
    inout io_l7n_d4_2;
    inout io_l7n_gc_3;
    inout io_l7n_gc_vrp_4;
    inout io_l7n_sm2n_13;
    inout io_l7p_11;
    inout io_l7p_12;
    inout io_l7p_14;
    inout io_l7p_15;
    inout io_l7p_16;
    inout io_l7p_17;
    inout io_l7p_18;
    inout io_l7p_19;
    inout io_l7p_20;
    inout io_l7p_21;
    inout io_l7p_22;
    inout io_l7p_a5_d21_1;
    inout io_l7p_d5_2;
    inout io_l7p_gc_3;
    inout io_l7p_gc_vrn_4;
    inout io_l7p_sm2p_13;
    inout io_l8n_cc_11;
    inout io_l8n_cc_12;
    inout io_l8n_cc_14;
    inout io_l8n_cc_15;
    inout io_l8n_cc_16;
    inout io_l8n_cc_17;
    inout io_l8n_cc_18;
    inout io_l8n_cc_19;
    inout io_l8n_cc_20;
    inout io_l8n_cc_21;
    inout io_l8n_cc_22;
    inout io_l8n_cc_a2_d18_1;
    inout io_l8n_cc_gc_4;
    inout io_l8n_cc_sm1n_13;
    inout io_l8n_d2_fs2_2;
    inout io_l8n_gc_3;
    inout io_l8p_cc_11;
    inout io_l8p_cc_12;
    inout io_l8p_cc_14;
    inout io_l8p_cc_15;
    inout io_l8p_cc_16;
    inout io_l8p_cc_17;
    inout io_l8p_cc_18;
    inout io_l8p_cc_19;
    inout io_l8p_cc_20;
    inout io_l8p_cc_21;
    inout io_l8p_cc_22;
    inout io_l8p_cc_a3_d19_1;
    inout io_l8p_cc_gc_4;
    inout io_l8p_cc_sm1p_13;
    inout io_l8p_d3_2;
    inout io_l8p_gc_3;
    inout io_l9n_cc_11;
    inout io_l9n_cc_12;
    inout io_l9n_cc_14;
    inout io_l9n_cc_15;
    inout io_l9n_cc_16;
    inout io_l9n_cc_17;
    inout io_l9n_cc_18;
    inout io_l9n_cc_19;
    inout io_l9n_cc_20;
    inout io_l9n_cc_21;
    inout io_l9n_cc_22;
    inout io_l9n_cc_a0_d16_1;
    inout io_l9n_cc_gc_4;
    inout io_l9n_cc_sm0n_13;
    inout io_l9n_d0_fs0_2;
    inout io_l9n_gc_3;
    inout io_l9p_cc_11;
    inout io_l9p_cc_12;
    inout io_l9p_cc_14;
    inout io_l9p_cc_15;
    inout io_l9p_cc_16;
    inout io_l9p_cc_17;
    inout io_l9p_cc_18;
    inout io_l9p_cc_19;
    inout io_l9p_cc_20;
    inout io_l9p_cc_21;
    inout io_l9p_cc_22;
    inout io_l9p_cc_a1_d17_1;
    inout io_l9p_cc_gc_4;
    inout io_l9p_cc_sm0p_13;
    inout io_l9p_d1_fs1_2;
    inout io_l9p_gc_3;
    inout m0_0;
    inout m1_0;
    inout m2_0;
    inout nc_1;
    inout nc_10;
    inout nc_100;
    inout nc_101;
    inout nc_102;
    inout nc_103;
    inout nc_104;
    inout nc_105;
    inout nc_106;
    inout nc_107;
    inout nc_108;
    inout nc_109;
    inout nc_11;
    inout nc_110;
    inout nc_111;
    inout nc_112;
    inout nc_113;
    inout nc_114;
    inout nc_115;
    inout nc_116;
    inout nc_117;
    inout nc_118;
    inout nc_119;
    inout nc_12;
    inout nc_120;
    inout nc_121;
    inout nc_122;
    inout nc_123;
    inout nc_124;
    inout nc_125;
    inout nc_126;
    inout nc_127;
    inout nc_128;
    inout nc_129;
    inout nc_13;
    inout nc_130;
    inout nc_131;
    inout nc_132;
    inout nc_133;
    inout nc_134;
    inout nc_135;
    inout nc_136;
    inout nc_137;
    inout nc_138;
    inout nc_139;
    inout nc_14;
    inout nc_140;
    inout nc_141;
    inout nc_142;
    inout nc_143;
    inout nc_144;
    inout nc_145;
    inout nc_146;
    inout nc_147;
    inout nc_148;
    inout nc_149;
    inout nc_15;
    inout nc_150;
    inout nc_151;
    inout nc_152;
    inout nc_153;
    inout nc_154;
    inout nc_155;
    inout nc_156;
    inout nc_157;
    inout nc_158;
    inout nc_159;
    inout nc_16;
    inout nc_160;
    inout nc_161;
    inout nc_162;
    inout nc_163;
    inout nc_164;
    inout nc_165;
    inout nc_166;
    inout nc_167;
    inout nc_168;
    inout nc_169;
    inout nc_17;
    inout nc_170;
    inout nc_171;
    inout nc_172;
    inout nc_173;
    inout nc_174;
    inout nc_175;
    inout nc_176;
    inout nc_177;
    inout nc_178;
    inout nc_179;
    inout nc_18;
    inout nc_180;
    inout nc_181;
    inout nc_182;
    inout nc_183;
    inout nc_184;
    inout nc_185;
    inout nc_186;
    inout nc_187;
    inout nc_188;
    inout nc_189;
    inout nc_19;
    inout nc_190;
    inout nc_191;
    inout nc_192;
    inout nc_193;
    inout nc_194;
    inout nc_195;
    inout nc_196;
    inout nc_197;
    inout nc_198;
    inout nc_199;
    inout nc_2;
    inout nc_20;
    inout nc_200;
    inout nc_201;
    inout nc_202;
    inout nc_203;
    inout nc_204;
    inout nc_205;
    inout nc_206;
    inout nc_207;
    inout nc_208;
    inout nc_209;
    inout nc_21;
    inout nc_210;
    inout nc_211;
    inout nc_212;
    inout nc_213;
    inout nc_214;
    inout nc_215;
    inout nc_216;
    inout nc_217;
    inout nc_218;
    inout nc_219;
    inout nc_22;
    inout nc_220;
    inout nc_221;
    inout nc_222;
    inout nc_223;
    inout nc_224;
    inout nc_225;
    inout nc_226;
    inout nc_227;
    inout nc_228;
    inout nc_229;
    inout nc_23;
    inout nc_230;
    inout nc_231;
    inout nc_232;
    inout nc_233;
    inout nc_234;
    inout nc_235;
    inout nc_236;
    inout nc_237;
    inout nc_238;
    inout nc_239;
    inout nc_24;
    inout nc_240;
    inout nc_25;
    inout nc_26;
    inout nc_27;
    inout nc_28;
    inout nc_29;
    inout nc_3;
    inout nc_30;
    inout nc_31;
    inout nc_32;
    inout nc_33;
    inout nc_34;
    inout nc_35;
    inout nc_36;
    inout nc_37;
    inout nc_38;
    inout nc_39;
    inout nc_4;
    inout nc_40;
    inout nc_41;
    inout nc_42;
    inout nc_43;
    inout nc_44;
    inout nc_45;
    inout nc_46;
    inout nc_47;
    inout nc_48;
    inout nc_49;
    inout nc_5;
    inout nc_50;
    inout nc_51;
    inout nc_52;
    inout nc_53;
    inout nc_54;
    inout nc_55;
    inout nc_56;
    inout nc_57;
    inout nc_58;
    inout nc_59;
    inout nc_6;
    inout nc_60;
    inout nc_61;
    inout nc_62;
    inout nc_63;
    inout nc_64;
    inout nc_65;
    inout nc_66;
    inout nc_67;
    inout nc_68;
    inout nc_69;
    inout nc_7;
    inout nc_70;
    inout nc_71;
    inout nc_72;
    inout nc_73;
    inout nc_74;
    inout nc_75;
    inout nc_76;
    inout nc_77;
    inout nc_78;
    inout nc_79;
    inout nc_8;
    inout nc_80;
    inout nc_81;
    inout nc_82;
    inout nc_83;
    inout nc_84;
    inout nc_85;
    inout nc_86;
    inout nc_87;
    inout nc_88;
    inout nc_89;
    inout nc_9;
    inout nc_90;
    inout nc_91;
    inout nc_92;
    inout nc_93;
    inout nc_94;
    inout nc_95;
    inout nc_96;
    inout nc_97;
    inout nc_98;
    inout nc_99;
    inout program_b_0;
    inout rdwr_b_0;
    inout rsvd_1;
    inout rsvd_2;
    inout tck_0;
    inout tdi_0;
    inout tdo_0;
    inout tms_0;
    inout vbatt_0;
    input vccaux_1;
    input vccaux_10;
    input vccaux_11;
    input vccaux_12;
    input vccaux_2;
    input vccaux_3;
    input vccaux_4;
    input vccaux_5;
    input vccaux_6;
    input vccaux_7;
    input vccaux_8;
    input vccaux_9;
    input vccint_1;
    input vccint_10;
    input vccint_11;
    input vccint_12;
    input vccint_13;
    input vccint_14;
    input vccint_15;
    input vccint_16;
    input vccint_17;
    input vccint_18;
    input vccint_19;
    input vccint_2;
    input vccint_20;
    input vccint_21;
    input vccint_22;
    input vccint_23;
    input vccint_24;
    input vccint_25;
    input vccint_26;
    input vccint_27;
    input vccint_28;
    input vccint_29;
    input vccint_3;
    input vccint_30;
    input vccint_31;
    input vccint_32;
    input vccint_33;
    input vccint_34;
    input vccint_35;
    input vccint_36;
    input vccint_37;
    input vccint_38;
    input vccint_39;
    input vccint_4;
    input vccint_40;
    input vccint_41;
    input vccint_42;
    input vccint_43;
    input vccint_44;
    input vccint_45;
    input vccint_46;
    input vccint_47;
    input vccint_48;
    input vccint_49;
    input vccint_5;
    input vccint_50;
    input vccint_51;
    input vccint_52;
    input vccint_53;
    input vccint_6;
    input vccint_7;
    input vccint_8;
    input vccint_9;
    input vcco_0_1;
    input vcco_0_2;
    input vcco_11_1;
    input vcco_11_2;
    input vcco_11_3;
    input vcco_12_1;
    input vcco_12_2;
    input vcco_12_3;
    input vcco_13_1;
    input vcco_13_2;
    input vcco_13_3;
    input vcco_14_1;
    input vcco_14_2;
    input vcco_14_3;
    input vcco_15_1;
    input vcco_15_2;
    input vcco_15_3;
    input vcco_16_1;
    input vcco_16_2;
    input vcco_16_3;
    input vcco_17_1;
    input vcco_17_2;
    input vcco_17_3;
    input vcco_18_1;
    input vcco_18_2;
    input vcco_18_3;
    input vcco_19_1;
    input vcco_19_2;
    input vcco_19_3;
    input vcco_1_1;
    input vcco_1_2;
    input vcco_20_1;
    input vcco_20_2;
    input vcco_20_3;
    input vcco_21_1;
    input vcco_21_2;
    input vcco_21_3;
    input vcco_22_1;
    input vcco_22_2;
    input vcco_22_3;
    input vcco_23_1;
    input vcco_23_2;
    input vcco_23_3;
    input vcco_24_1;
    input vcco_24_2;
    input vcco_24_3;
    input vcco_25_1;
    input vcco_25_2;
    input vcco_25_3;
    input vcco_26_1;
    input vcco_26_2;
    input vcco_26_3;
    input vcco_2_1;
    input vcco_2_2;
    input vcco_3_1;
    input vcco_3_2;
    input vcco_4_1;
    input vcco_4_2;
    input vcco_5_1;
    input vcco_5_2;
    input vcco_5_3;
    input vcco_6_1;
    input vcco_6_2;
    input vcco_6_3;
    inout vn_0;
    inout vp_0;
    inout vrefn_0;
    inout vrefp_0;


    initial
        begin
        end

endmodule
