-- generated by newgenasym Tue Apr 21 11:03:30 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \1smb5927bt3g\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end \1smb5927bt3g\;
