-- generated by newgenasym Mon Jun 29 16:23:20 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lt5554 is
    port (    
	DEC1:      INOUT  STD_LOGIC;    
	DEC2:      INOUT  STD_LOGIC;    
	ENB:       INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND10:     INOUT  STD_LOGIC;    
	GND11:     INOUT  STD_LOGIC;    
	GND12:     INOUT  STD_LOGIC;    
	GND13:     INOUT  STD_LOGIC;    
	GND14:     INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	GND5:      INOUT  STD_LOGIC;    
	GND6:      INOUT  STD_LOGIC;    
	GND7:      INOUT  STD_LOGIC;    
	GND8:      INOUT  STD_LOGIC;    
	GND9:      INOUT  STD_LOGIC;    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	MODE:      INOUT  STD_LOGIC;    
	\out+\:    INOUT  STD_LOGIC;    
	\out-\:    INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	PG0:       INOUT  STD_LOGIC;    
	PG1:       INOUT  STD_LOGIC;    
	PG2:       INOUT  STD_LOGIC;    
	PG3:       INOUT  STD_LOGIC;    
	PG4:       INOUT  STD_LOGIC;    
	PG5:       INOUT  STD_LOGIC;    
	PG6:       INOUT  STD_LOGIC;    
	STROBE:    INOUT  STD_LOGIC;    
	VCC1:      INOUT  STD_LOGIC;    
	VCC2:      INOUT  STD_LOGIC);
end lt5554;
