// generated by newgenasym  Mon May 23 15:46:40 2011


module spx29300t_5 (gnd1, gnd2, vin, vout);
    input gnd1;
    input gnd2;
    input vin;
    output vout;


    initial
        begin
        end

endmodule
