// generated by newgenasym  Thu Oct 21 14:06:34 2010


module sxb_4089z (gnd1, gnd2, rf_in, rf_out);
    inout gnd1;
    inout gnd2;
    inout rf_in;
    inout rf_out;


    initial
        begin
        end

endmodule
