-- generated by newgenasym Thu Oct 21 14:06:34 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SXB_4089Z is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	RF_IN:     INOUT  STD_LOGIC;    
	RF_OUT:    INOUT  STD_LOGIC);
end SXB_4089Z;
