// generated by newgenasym  Tue Mar 01 18:29:44 2011


module isp1301bs (\adr/psw , agnd, c1, c2, cgnd, \dat/vp , dm, dp, id, \int#n ,
        \oe#n/int#n , pad, rcv, \reset#n , scl, sda, \se0/vm , speed,
        suspend, vbat, vbus, vdd_lgc, vm, vp, vreg3v3);
    inout \adr/psw ;
    inout agnd;
    inout c1;
    inout c2;
    inout cgnd;
    inout \dat/vp ;
    inout dm;
    inout dp;
    inout id;
    inout \int#n ;
    inout \oe#n/int#n ;
    inout pad;
    inout rcv;
    inout \reset#n ;
    inout scl;
    inout sda;
    inout \se0/vm ;
    inout speed;
    inout suspend;
    inout vbat;
    inout vbus;
    inout vdd_lgc;
    inout vm;
    inout vp;
    inout vreg3v3;


    initial
        begin
        end

endmodule
