-- generated by newgenasym Thu Jul 07 18:01:51 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dt_26_g06n_32p768k is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end dt_26_g06n_32p768k;
