-- generated by newgenasym Fri Feb 13 18:12:23 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad7918bruz is
    port (    
	AGND1:     IN     STD_LOGIC;    
	AGND2:     IN     STD_LOGIC;    
	AGND3:     IN     STD_LOGIC;    
	AGND4:     IN     STD_LOGIC;    
	AVDD1:     IN     STD_LOGIC;    
	AVDD2:     IN     STD_LOGIC;    
	CS:        INOUT  STD_LOGIC;    
	DIN:       IN     STD_LOGIC;    
	DOUT:      OUT    STD_LOGIC;    
	NQ3:       INOUT  STD_LOGIC;    
	SCLK:      INOUT  STD_LOGIC;    
	VDRIVE:    INOUT  STD_LOGIC;    
	VIN0:      INOUT  STD_LOGIC;    
	VIN1:      INOUT  STD_LOGIC;    
	VIN2:      INOUT  STD_LOGIC;    
	VIN3:      INOUT  STD_LOGIC;    
	VIN4:      INOUT  STD_LOGIC;    
	VIN5:      INOUT  STD_LOGIC;    
	VIN6:      INOUT  STD_LOGIC;    
	VIN7:      INOUT  STD_LOGIC);
end ad7918bruz;
