// generated by newgenasym  Fri Feb 13 09:46:39 2009


module \74lvc244apw  (\1a0 , \1a1 , \1a2 , \1a3 , \1oe# , \1y0 , \1y1 , \1y2 , \1y3 , \2a0 , \2a1 , \2a2 , \2a3 ,
        \2oe# , \2y0 , \2y1 , \2y2 , \2y3 , gnd, vcc);
    input \1a0 ;
    input \1a1 ;
    input \1a2 ;
    input \1a3 ;
    input \1oe# ;
    output \1y0 ;
    output \1y1 ;
    output \1y2 ;
    output \1y3 ;
    input \2a0 ;
    input \2a1 ;
    input \2a2 ;
    input \2a3 ;
    input \2oe# ;
    output \2y0 ;
    output \2y1 ;
    output \2y2 ;
    output \2y3 ;
    input gnd;
    input vcc;


    initial
        begin
        end

endmodule
