-- generated by newgenasym Fri Feb 13 09:46:39 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lvc244apw\ is
    port (    
	\1a0\:     IN     STD_LOGIC;    
	\1a1\:     IN     STD_LOGIC;    
	\1a2\:     IN     STD_LOGIC;    
	\1a3\:     IN     STD_LOGIC;    
	\1oe#\:    IN     STD_LOGIC;    
	\1y0\:     OUT    STD_LOGIC;    
	\1y1\:     OUT    STD_LOGIC;    
	\1y2\:     OUT    STD_LOGIC;    
	\1y3\:     OUT    STD_LOGIC;    
	\2a0\:     IN     STD_LOGIC;    
	\2a1\:     IN     STD_LOGIC;    
	\2a2\:     IN     STD_LOGIC;    
	\2a3\:     IN     STD_LOGIC;    
	\2oe#\:    IN     STD_LOGIC;    
	\2y0\:     OUT    STD_LOGIC;    
	\2y1\:     OUT    STD_LOGIC;    
	\2y2\:     OUT    STD_LOGIC;    
	\2y3\:     OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end \74lvc244apw\;
