-- generated by newgenasym Wed Feb 11 13:27:46 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity capacitor is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end capacitor;
