-- generated by newgenasym Mon Apr 27 15:48:15 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm75adp is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	OS:        OUT    STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end lm75adp;
