-- generated by newgenasym Wed Sep 21 14:21:24 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity DIODE_BAV70 is
    port (    
	ANODE:     INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	CATHODE:   INOUT  STD_LOGIC);
end DIODE_BAV70;
