// generated by newgenasym  Mon Apr 18 14:54:23 2011


module vc75_uagtc (gnd, out, \tri-s/nc , vc, vcc);
    inout gnd;
    inout out;
    inout [2:1] \tri-s/nc ;
    inout vc;
    inout vcc;


    initial
        begin
        end

endmodule
