// generated by newgenasym  Fri Sep 30 15:10:44 2011


module reset_dtsa_62n_v (\1 , \2 , gnd1, gnd2);
    inout \1 ;
    inout \2 ;
    inout gnd1;
    inout gnd2;


    initial
        begin
        end

endmodule
