// generated by newgenasym  Tue Mar 15 16:23:51 2011


module prj_005 (gnd, \l_led+ , \l_led- , \n/c , r_ct, \r_led+ , \r_led- , \rd+ , \rd- ,
        t_ct, \td+ , \td- );
    inout [3:1] gnd;
    inout \l_led+ ;
    inout \l_led- ;
    inout \n/c ;
    inout r_ct;
    inout \r_led+ ;
    inout \r_led- ;
    inout \rd+ ;
    inout \rd- ;
    inout t_ct;
    inout \td+ ;
    inout \td- ;


    initial
        begin
        end

endmodule
