// generated by newgenasym  Thu May 19 11:39:13 2011


module xo75p (\e/d , gnd, \n/c , out, \out# , vcc);
    inout \e/d ;
    inout gnd;
    inout \n/c ;
    inout out;
    inout \out# ;
    inout vcc;


    initial
        begin
        end

endmodule
