-- generated by newgenasym Thu Mar 29 13:51:52 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ts5a3166dckr is
    port (    
	COM:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	NO:        INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC);
end ts5a3166dckr;
