-- generated by newgenasym Tue Aug 18 10:41:17 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dnf100_2x7a is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	\out+\:    INOUT  STD_LOGIC;    
	\out-\:    INOUT  STD_LOGIC);
end dnf100_2x7a;
