// generated by newgenasym  Thu Jun 03 10:27:55 2010


module ad8342acpz (comm1, comm2, comm3, comm4, comm5, exrb, ifom, ifop, locm,
        loin, pad, pwdn, rfcm, rfin, vpdc, vplo, vpmx);
    inout comm1;
    inout comm2;
    inout comm3;
    inout comm4;
    inout comm5;
    inout exrb;
    inout ifom;
    inout ifop;
    inout locm;
    inout loin;
    inout pad;
    inout pwdn;
    inout rfcm;
    inout rfin;
    inout vpdc;
    inout vplo;
    inout vpmx;


    initial
        begin
        end

endmodule
