-- generated by newgenasym Wed Feb 11 09:33:20 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc306_g06q is
    port (    
	N:         INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	P:         INOUT  STD_LOGIC);
end mc306_g06q;
