-- generated by newgenasym Fri Apr 22 16:30:11 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity RJ45_LED is
    port (    
	GND:       INOUT  STD_LOGIC_VECTOR (3 DOWNTO 1);    
	\led1+\:   INOUT  STD_LOGIC;    
	\led1-\:   INOUT  STD_LOGIC;    
	\led2+\:   INOUT  STD_LOGIC;    
	\led2-\:   INOUT  STD_LOGIC;    
	\n/c\:     INOUT  STD_LOGIC;    
	RCT:       INOUT  STD_LOGIC;    
	\rd+\:     INOUT  STD_LOGIC;    
	\rd-\:     INOUT  STD_LOGIC;    
	TCT:       INOUT  STD_LOGIC;    
	\td+\:     INOUT  STD_LOGIC;    
	\td-\:     INOUT  STD_LOGIC);
end RJ45_LED;
