-- generated by newgenasym Tue Jul 12 14:20:49 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CON_BNC is
    port (    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC);
end CON_BNC;
