// generated by newgenasym  Thu Oct 21 11:38:07 2010


module hmc483ms8ge (gnd1, gnd2, gnd3, \if , lo, \n/c , pad, rf, vdd);
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout \if ;
    inout lo;
    inout \n/c ;
    inout pad;
    inout rf;
    inout vdd;


    initial
        begin
        end

endmodule
