-- generated by newgenasym Thu Oct 21 11:38:07 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc483ms8ge is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	\if\:      INOUT  STD_LOGIC;    
	LO:        INOUT  STD_LOGIC;    
	\n/c\:     INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	RF:        INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end hmc483ms8ge;
