-- generated by newgenasym Fri Aug 05 16:16:10 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PA_SOT89 is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	RF_IN:     INOUT  STD_LOGIC;    
	RF_OUT:    INOUT  STD_LOGIC);
end PA_SOT89;
