// generated by newgenasym  Thu Apr 09 17:15:33 2009


module tlk3132zen (agnd1, agnd10, agnd11, agnd12, agnd2, agnd3, agnd4, agnd5,
        agnd6, agnd7, agnd8, agnd9, amux0, amux1, avdd1, avdd2, avdd3,
        avdd4, avdd5, avdd6, avdd7, avdd8, avdd9, code, cp_out, dgnd1,
        dgnd10, dgnd11, dgnd12, dgnd13, dgnd14, dgnd15, dgnd16,
        dgnd17, dgnd18, dgnd19, dgnd2, dgnd20, dgnd21, dgnd22,
        dgnd23, dgnd24, dgnd25, dgnd26, dgnd27, dgnd28, dgnd29,
        dgnd3, dgnd30, dgnd31, dgnd32, dgnd33, dgnd4, dgnd5, dgnd6,
        dgnd7, dgnd8, dgnd9, dvdd1, dvdd10, dvdd11, dvdd2, dvdd3,
        dvdd4, dvdd5, dvdd6, dvdd7, dvdd8, dvdd9, enable, gpi1, gpo0,
        gpo1, gpo2, gpo3, gpo4, mdc, mdio, ploop, prbs_en, prtad0,
        prtad1, prtad2, prtad3, prtad4, rdn0, rdn1, rdp0, rdp1,
        refclk, refclkn, refclkp, res1, res3, res4, \rst# , rxc0, rxc1,
        rxc4, rxc5, rxclk0, rxclk1, rxd0, rxd1, rxd10, rxd11, rxd12,
        rxd13, rxd14, rxd15, rxd2, rxd3, rxd4, rxd5, rxd6, rxd7, rxd8,
        rxd9, sloop, speed0, speed1, tck, tdi, tdn0, tdn1, tdo, tdp0,
        tdp1, testen, tms, \trst# , tst_out, txc0, txc1, txc4, txc5,
        txclk0, txclk1, txd0, txd1, txd10, txd11, txd12, txd13, txd14,
        txd15, txd2, txd3, txd4, txd5, txd6, txd7, txd8, txd9,
        vco_tl_tst, vdd_cml, vdd_pll, vdda_cp, vdda_vco, vddd1,
        vddd2, vddd3, vddd4, vddm, vddo1, vddo2, vddo3, vddo4, vddq1,
        vddq10, vddq11, vddq12, vddq2, vddq3, vddq4, vddq5, vddq6,
        vddq7, vddq8, vddq9, vddr1, vddr2, vddt1, vddt2, vddt3, vddt4,
        vddt5, vpp0, vpp1, vref1, vref2, vss_cml, vss_pll, vssa_cp,
        vssa_vco, vtune);
    input agnd1;
    input agnd10;
    input agnd11;
    input agnd12;
    input agnd2;
    input agnd3;
    input agnd4;
    input agnd5;
    input agnd6;
    input agnd7;
    input agnd8;
    input agnd9;
    output amux0;
    output amux1;
    input avdd1;
    input avdd2;
    input avdd3;
    input avdd4;
    input avdd5;
    input avdd6;
    input avdd7;
    input avdd8;
    input avdd9;
    input code;
    output cp_out;
    input dgnd1;
    input dgnd10;
    input dgnd11;
    input dgnd12;
    input dgnd13;
    input dgnd14;
    input dgnd15;
    input dgnd16;
    input dgnd17;
    input dgnd18;
    input dgnd19;
    input dgnd2;
    input dgnd20;
    input dgnd21;
    input dgnd22;
    input dgnd23;
    input dgnd24;
    input dgnd25;
    input dgnd26;
    input dgnd27;
    input dgnd28;
    input dgnd29;
    input dgnd3;
    input dgnd30;
    input dgnd31;
    input dgnd32;
    input dgnd33;
    input dgnd4;
    input dgnd5;
    input dgnd6;
    input dgnd7;
    input dgnd8;
    input dgnd9;
    input dvdd1;
    input dvdd10;
    input dvdd11;
    input dvdd2;
    input dvdd3;
    input dvdd4;
    input dvdd5;
    input dvdd6;
    input dvdd7;
    input dvdd8;
    input dvdd9;
    input enable;
    input gpi1;
    output gpo0;
    output gpo1;
    output gpo2;
    output gpo3;
    output gpo4;
    input mdc;
    inout mdio;
    input ploop;
    input prbs_en;
    input prtad0;
    input prtad1;
    input prtad2;
    input prtad3;
    input prtad4;
    input rdn0;
    input rdn1;
    input rdp0;
    input rdp1;
    input refclk;
    inout refclkn;
    inout refclkp;
    inout res1;
    inout res3;
    inout res4;
    input \rst# ;
    output rxc0;
    output rxc1;
    output rxc4;
    output rxc5;
    output rxclk0;
    output rxclk1;
    output rxd0;
    output rxd1;
    output rxd10;
    output rxd11;
    output rxd12;
    output rxd13;
    output rxd14;
    output rxd15;
    output rxd2;
    output rxd3;
    output rxd4;
    output rxd5;
    output rxd6;
    output rxd7;
    output rxd8;
    output rxd9;
    input sloop;
    input speed0;
    input speed1;
    input tck;
    input tdi;
    output tdn0;
    output tdn1;
    output tdo;
    output tdp0;
    output tdp1;
    input testen;
    input tms;
    input \trst# ;
    inout tst_out;
    input txc0;
    input txc1;
    input txc4;
    input txc5;
    input txclk0;
    input txclk1;
    input txd0;
    input txd1;
    input txd10;
    input txd11;
    input txd12;
    input txd13;
    input txd14;
    input txd15;
    input txd2;
    input txd3;
    input txd4;
    input txd5;
    input txd6;
    input txd7;
    input txd8;
    input txd9;
    input vco_tl_tst;
    input vdd_cml;
    input vdd_pll;
    input vdda_cp;
    input vdda_vco;
    input vddd1;
    input vddd2;
    input vddd3;
    input vddd4;
    input vddm;
    input vddo1;
    input vddo2;
    input vddo3;
    input vddo4;
    input vddq1;
    input vddq10;
    input vddq11;
    input vddq12;
    input vddq2;
    input vddq3;
    input vddq4;
    input vddq5;
    input vddq6;
    input vddq7;
    input vddq8;
    input vddq9;
    input vddr1;
    input vddr2;
    input vddt1;
    input vddt2;
    input vddt3;
    input vddt4;
    input vddt5;
    input vpp0;
    input vpp1;
    input vref1;
    input vref2;
    input vss_cml;
    input vss_pll;
    input vssa_cp;
    input vssa_vco;
    input vtune;


    initial
        begin
        end

endmodule
