-- generated by newgenasym Thu Sep 03 09:35:32 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ts_1102s is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC);
end ts_1102s;
