-- generated by newgenasym Thu Apr 30 15:11:58 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ath030a0x3_srhz is
    port (    
	GND1:      IN     STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	\on/off\:  INOUT  STD_LOGIC;    
	SENSE:     INOUT  STD_LOGIC;    
	SEQ:       INOUT  STD_LOGIC;    
	SHARE:     IN     STD_LOGIC;    
	TRIM:      INOUT  STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      IN     STD_LOGIC);
end ath030a0x3_srhz;
