-- generated by newgenasym Wed Jun 09 14:48:23 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc273ms10ge is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC;    
	V1:        INOUT  STD_LOGIC;    
	V2:        INOUT  STD_LOGIC;    
	V3:        INOUT  STD_LOGIC;    
	V4:        INOUT  STD_LOGIC;    
	V5:        INOUT  STD_LOGIC);
end hmc273ms10ge;
