// generated by newgenasym  Thu Feb 12 15:00:03 2009


module dac5682zirgct (avdd_0, avdd_1, avdd_2, avdd_3, avdd_4, biasj, clkin,
        clkinc, clkvdd, d0n, d0p, d10n, d10p, d11n, d11p, d12n, d12p,
        d13n, d13p, d14n, d14p, d15n, d15p, d1n, d1p, d2n, d2p, d3n, d3p,
        d4n, d4p, d5n, d5p, d6n, d6p, d7n, d7p, d8n, d8p, d9n, d9p, dclkn,
        dclkp, dvdd_0, dvdd_1, dvdd_2, dvdd_3, extio, extlo, gnd,
        iouta1, iouta2, ioutb1, ioutb2, iovdd, lpf, pwrpad, resetb,
        sclk, sdenb, sdio, sdo, syncn, syncp, vfuse);
    input avdd_0;
    input avdd_1;
    input avdd_2;
    input avdd_3;
    input avdd_4;
    inout biasj;
    inout clkin;
    inout clkinc;
    input clkvdd;
    inout d0n;
    inout d0p;
    inout d10n;
    inout d10p;
    inout d11n;
    inout d11p;
    inout d12n;
    inout d12p;
    inout d13n;
    inout d13p;
    inout d14n;
    inout d14p;
    inout d15n;
    inout d15p;
    inout d1n;
    inout d1p;
    inout d2n;
    inout d2p;
    inout d3n;
    inout d3p;
    inout d4n;
    inout d4p;
    inout d5n;
    inout d5p;
    inout d6n;
    inout d6p;
    inout d7n;
    inout d7p;
    inout d8n;
    inout d8p;
    inout d9n;
    inout d9p;
    inout dclkn;
    inout dclkp;
    input dvdd_0;
    input dvdd_1;
    input dvdd_2;
    input dvdd_3;
    inout extio;
    inout extlo;
    input gnd;
    inout iouta1;
    inout iouta2;
    inout ioutb1;
    inout ioutb2;
    input iovdd;
    inout lpf;
    input pwrpad;
    inout resetb;
    inout sclk;
    inout sdenb;
    inout sdio;
    inout sdo;
    inout syncn;
    inout syncp;
    inout vfuse;


    initial
        begin
        end

endmodule
