-- generated by newgenasym Thu Aug 13 15:53:39 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity FILTER is
    port (    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	GND4:      IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end FILTER;
