// generated by newgenasym  Wed Jun 29 11:34:34 2011


module con_ci2214p1vk0_lf (\1 , \10 , \11 , \12 , \13 , \14 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    inout \1 ;
    inout \10 ;
    inout \11 ;
    inout \12 ;
    inout \13 ;
    inout \14 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;


    initial
        begin
        end

endmodule
