// generated by newgenasym  Fri Jul 08 17:28:19 2011


module esda6v1w5 (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
