// generated by newgenasym  Thu Feb 25 19:33:17 2010


module nand_flash_tsop (ale, \ce# , cle, io0, io1, io2, io3, io4, io5, io6, io7, nc1, nc10,
        nc11, nc12, nc13, nc14, nc15, nc16, nc17, nc18, nc19, nc2, nc20,
        nc21, nc22, nc23, nc24, nc25, nc26, nc27, nc28, nc29, nc3, nc4,
        nc5, nc6, nc7, nc8, nc9, \r/b# , \re# , vdd1, vdd2, vss1, vss2, \we# ,
        \wp# );
    inout ale;
    inout \ce# ;
    inout cle;
    inout io0;
    inout io1;
    inout io2;
    inout io3;
    inout io4;
    inout io5;
    inout io6;
    inout io7;
    inout nc1;
    inout nc10;
    inout nc11;
    inout nc12;
    inout nc13;
    inout nc14;
    inout nc15;
    inout nc16;
    inout nc17;
    inout nc18;
    inout nc19;
    inout nc2;
    inout nc20;
    inout nc21;
    inout nc22;
    inout nc23;
    inout nc24;
    inout nc25;
    inout nc26;
    inout nc27;
    inout nc28;
    inout nc29;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout nc7;
    inout nc8;
    inout nc9;
    inout \r/b# ;
    inout \re# ;
    inout vdd1;
    inout vdd2;
    inout vss1;
    inout vss2;
    inout \we# ;
    inout \wp# ;


    initial
        begin
        end

endmodule
