// generated by newgenasym  Thu Jan 21 16:40:59 2010


module xc6vlx195t_1ffg1156i (avdd_0, avss_0, cclk_0, csi_b_0, din_0, done_0,
        dout_busy_0, dxn_0, dxp_0, gnd1, gnd10, gnd100, gnd101,
        gnd102, gnd103, gnd104, gnd105, gnd106, gnd107, gnd108,
        gnd109, gnd11, gnd110, gnd111, gnd112, gnd113, gnd114,
        gnd115, gnd116, gnd117, gnd118, gnd119, gnd12, gnd120,
        gnd121, gnd122, gnd123, gnd124, gnd125, gnd126, gnd127,
        gnd128, gnd129, gnd13, gnd130, gnd131, gnd132, gnd133,
        gnd134, gnd135, gnd136, gnd137, gnd138, gnd139, gnd14,
        gnd140, gnd141, gnd142, gnd143, gnd144, gnd145, gnd146,
        gnd147, gnd148, gnd149, gnd15, gnd150, gnd151, gnd152,
        gnd153, gnd154, gnd155, gnd156, gnd157, gnd158, gnd159,
        gnd16, gnd160, gnd161, gnd162, gnd163, gnd164, gnd165,
        gnd166, gnd167, gnd168, gnd169, gnd17, gnd170, gnd171,
        gnd172, gnd173, gnd174, gnd175, gnd176, gnd177, gnd178,
        gnd179, gnd18, gnd180, gnd181, gnd182, gnd183, gnd184,
        gnd185, gnd186, gnd187, gnd188, gnd189, gnd19, gnd190,
        gnd191, gnd192, gnd193, gnd194, gnd195, gnd196, gnd197,
        gnd198, gnd199, gnd2, gnd20, gnd200, gnd201, gnd202, gnd203,
        gnd204, gnd205, gnd206, gnd207, gnd208, gnd209, gnd21,
        gnd210, gnd211, gnd212, gnd213, gnd214, gnd215, gnd216,
        gnd217, gnd218, gnd219, gnd22, gnd220, gnd221, gnd222,
        gnd223, gnd224, gnd225, gnd226, gnd227, gnd228, gnd229,
        gnd23, gnd230, gnd231, gnd232, gnd233, gnd234, gnd235,
        gnd236, gnd237, gnd238, gnd239, gnd24, gnd240, gnd241,
        gnd242, gnd243, gnd244, gnd245, gnd246, gnd247, gnd248,
        gnd249, gnd25, gnd250, gnd251, gnd252, gnd253, gnd26, gnd27,
        gnd28, gnd29, gnd3, gnd30, gnd31, gnd32, gnd33, gnd34, gnd35,
        gnd36, gnd37, gnd38, gnd39, gnd4, gnd40, gnd41, gnd42, gnd43,
        gnd44, gnd45, gnd46, gnd47, gnd48, gnd49, gnd5, gnd50, gnd51,
        gnd52, gnd53, gnd54, gnd55, gnd56, gnd57, gnd58, gnd59, gnd6,
        gnd60, gnd61, gnd62, gnd63, gnd64, gnd65, gnd66, gnd67, gnd68,
        gnd69, gnd7, gnd70, gnd71, gnd72, gnd73, gnd74, gnd75, gnd76,
        gnd77, gnd78, gnd79, gnd8, gnd80, gnd81, gnd82, gnd83, gnd84,
        gnd85, gnd86, gnd87, gnd88, gnd89, gnd9, gnd90, gnd91, gnd92,
        gnd93, gnd94, gnd95, gnd96, gnd97, gnd98, gnd99, hswapen_0,
        init_b_0, io_l0n_12, io_l0n_13, io_l0n_14, io_l0n_15,
        io_l0n_16, io_l0n_22, io_l0n_23, io_l0n_25, io_l0n_26,
        io_l0n_32, io_l0n_33, io_l0n_35, io_l0n_36, io_l0n_gc_24,
        io_l0n_gc_34, io_l0p_12, io_l0p_13, io_l0p_14, io_l0p_15,
        io_l0p_16, io_l0p_22, io_l0p_23, io_l0p_25, io_l0p_26,
        io_l0p_32, io_l0p_33, io_l0p_35, io_l0p_36, io_l0p_gc_24,
        io_l0p_gc_34, io_l10n_mrcc_12, io_l10n_mrcc_13,
        io_l10n_mrcc_14, io_l10n_mrcc_15, io_l10n_mrcc_16,
        io_l10n_mrcc_22, io_l10n_mrcc_23, io_l10n_mrcc_24,
        io_l10n_mrcc_25, io_l10n_mrcc_26, io_l10n_mrcc_32,
        io_l10n_mrcc_33, io_l10n_mrcc_34, io_l10n_mrcc_35,
        io_l10n_mrcc_36, io_l10p_mrcc_12, io_l10p_mrcc_13,
        io_l10p_mrcc_14, io_l10p_mrcc_15, io_l10p_mrcc_16,
        io_l10p_mrcc_22, io_l10p_mrcc_23, io_l10p_mrcc_24,
        io_l10p_mrcc_25, io_l10p_mrcc_26, io_l10p_mrcc_32,
        io_l10p_mrcc_33, io_l10p_mrcc_34, io_l10p_mrcc_35,
        io_l10p_mrcc_36, io_l11n_srcc_12, io_l11n_srcc_13,
        io_l11n_srcc_14, io_l11n_srcc_15, io_l11n_srcc_16,
        io_l11n_srcc_22, io_l11n_srcc_23, io_l11n_srcc_24,
        io_l11n_srcc_25, io_l11n_srcc_26, io_l11n_srcc_32,
        io_l11n_srcc_33, io_l11n_srcc_34, io_l11n_srcc_35,
        io_l11n_srcc_36, io_l11p_srcc_12, io_l11p_srcc_13,
        io_l11p_srcc_14, io_l11p_srcc_15, io_l11p_srcc_16,
        io_l11p_srcc_22, io_l11p_srcc_23, io_l11p_srcc_24,
        io_l11p_srcc_25, io_l11p_srcc_26, io_l11p_srcc_32,
        io_l11p_srcc_33, io_l11p_srcc_34, io_l11p_srcc_35,
        io_l11p_srcc_36, io_l12n_25, io_l12n_a02_d18_34,
        io_l12n_d2_fs2_24, io_l12n_sm13n_15, io_l12n_sm5n_35,
        io_l12n_vrp_12, io_l12n_vrp_13, io_l12n_vrp_14,
        io_l12n_vrp_16, io_l12n_vrp_22, io_l12n_vrp_23,
        io_l12n_vrp_26, io_l12n_vrp_32, io_l12n_vrp_33,
        io_l12n_vrp_36, io_l12p_25, io_l12p_a03_d19_34,
        io_l12p_d3_24, io_l12p_sm13p_15, io_l12p_sm5p_35,
        io_l12p_vrn_12, io_l12p_vrn_13, io_l12p_vrn_14,
        io_l12p_vrn_16, io_l12p_vrn_22, io_l12p_vrn_23,
        io_l12p_vrn_26, io_l12p_vrn_32, io_l12p_vrn_33,
        io_l12p_vrn_36, io_l13n_12, io_l13n_13, io_l13n_14,
        io_l13n_16, io_l13n_22, io_l13n_23, io_l13n_25,
        io_l13n_26, io_l13n_32, io_l13n_33, io_l13n_36,
        io_l13n_a00_d16_34, io_l13n_d0_fs0_24, io_l13n_sm14n_15,
        io_l13n_sm6n_35, io_l13p_12, io_l13p_13, io_l13p_14,
        io_l13p_16, io_l13p_22, io_l13p_23, io_l13p_25,
        io_l13p_26, io_l13p_32, io_l13p_33, io_l13p_36,
        io_l13p_a01_d17_34, io_l13p_d1_fs1_24, io_l13p_sm14p_15,
        io_l13p_sm6p_35, io_l14n_vref_12, io_l14n_vref_13,
        io_l14n_vref_14, io_l14n_vref_15, io_l14n_vref_16,
        io_l14n_vref_22, io_l14n_vref_23, io_l14n_vref_25,
        io_l14n_vref_26, io_l14n_vref_32, io_l14n_vref_33,
        io_l14n_vref_35, io_l14n_vref_36, io_l14n_vref_a24_34,
        io_l14n_vref_foe_b_mosi_24, io_l14p_12, io_l14p_13,
        io_l14p_14, io_l14p_15, io_l14p_16, io_l14p_22,
        io_l14p_23, io_l14p_25, io_l14p_26, io_l14p_32,
        io_l14p_33, io_l14p_35, io_l14p_36, io_l14p_a25_34,
        io_l14p_fcs_b_24, io_l15n_12, io_l15n_13, io_l15n_14,
        io_l15n_16, io_l15n_22, io_l15n_23, io_l15n_25,
        io_l15n_26, io_l15n_32, io_l15n_33, io_l15n_36,
        io_l15n_a22_34, io_l15n_rs1_24, io_l15n_sm15n_15,
        io_l15n_sm7n_35, io_l15p_12, io_l15p_13, io_l15p_14,
        io_l15p_16, io_l15p_22, io_l15p_23, io_l15p_25,
        io_l15p_26, io_l15p_32, io_l15p_33, io_l15p_36,
        io_l15p_a23_34, io_l15p_fwe_b_24, io_l15p_sm15p_15,
        io_l15p_sm7p_35, io_l16n_12, io_l16n_13, io_l16n_14,
        io_l16n_16, io_l16n_22, io_l16n_23, io_l16n_26,
        io_l16n_32, io_l16n_33, io_l16n_36, io_l16n_a20_34,
        io_l16n_cso_b_24, io_l16n_vrp_15, io_l16n_vrp_25,
        io_l16n_vrp_35, io_l16p_12, io_l16p_13, io_l16p_14,
        io_l16p_16, io_l16p_22, io_l16p_23, io_l16p_26,
        io_l16p_32, io_l16p_33, io_l16p_36, io_l16p_a21_34,
        io_l16p_rs0_24, io_l16p_vrn_15, io_l16p_vrn_25,
        io_l16p_vrn_35, io_l17n_12, io_l17n_13, io_l17n_14,
        io_l17n_15, io_l17n_16, io_l17n_22, io_l17n_23,
        io_l17n_25, io_l17n_26, io_l17n_32, io_l17n_33,
        io_l17n_35, io_l17n_36, io_l17n_a18_34, io_l17n_vrp_24,
        io_l17p_12, io_l17p_13, io_l17p_14, io_l17p_15,
        io_l17p_16, io_l17p_22, io_l17p_23, io_l17p_25,
        io_l17p_26, io_l17p_32, io_l17p_33, io_l17p_35,
        io_l17p_36, io_l17p_a19_34, io_l17p_vrn_24, io_l18n_12,
        io_l18n_13, io_l18n_14, io_l18n_15, io_l18n_16,
        io_l18n_22, io_l18n_23, io_l18n_24, io_l18n_26,
        io_l18n_32, io_l18n_33, io_l18n_36, io_l18n_a16_34,
        io_l18n_gc_25, io_l18n_gc_35, io_l18p_12, io_l18p_13,
        io_l18p_14, io_l18p_15, io_l18p_16, io_l18p_22,
        io_l18p_23, io_l18p_24, io_l18p_26, io_l18p_32,
        io_l18p_33, io_l18p_36, io_l18p_a17_34, io_l18p_gc_25,
        io_l18p_gc_35, io_l19n_12, io_l19n_13, io_l19n_14,
        io_l19n_15, io_l19n_16, io_l19n_22, io_l19n_23,
        io_l19n_24, io_l19n_26, io_l19n_32, io_l19n_33,
        io_l19n_36, io_l19n_gc_25, io_l19n_gc_35, io_l19n_vrp_34,
        io_l19p_12, io_l19p_13, io_l19p_14, io_l19p_15,
        io_l19p_16, io_l19p_22, io_l19p_23, io_l19p_24,
        io_l19p_26, io_l19p_32, io_l19p_33, io_l19p_36,
        io_l19p_gc_25, io_l19p_gc_35, io_l19p_vrn_34, io_l1n_12,
        io_l1n_13, io_l1n_14, io_l1n_15, io_l1n_16, io_l1n_22,
        io_l1n_23, io_l1n_25, io_l1n_26, io_l1n_32, io_l1n_33,
        io_l1n_35, io_l1n_36, io_l1n_gc_24, io_l1n_gc_34,
        io_l1p_12, io_l1p_13, io_l1p_14, io_l1p_15, io_l1p_16,
        io_l1p_22, io_l1p_23, io_l1p_25, io_l1p_26, io_l1p_32,
        io_l1p_33, io_l1p_35, io_l1p_36, io_l1p_gc_24,
        io_l1p_gc_34, io_l2n_12, io_l2n_13, io_l2n_14, io_l2n_16,
        io_l2n_22, io_l2n_23, io_l2n_25, io_l2n_26, io_l2n_32,
        io_l2n_33, io_l2n_36, io_l2n_a14_d30_34, io_l2n_d14_24,
        io_l2n_sm0n_35, io_l2n_sm8n_15, io_l2p_12, io_l2p_13,
        io_l2p_14, io_l2p_16, io_l2p_22, io_l2p_23, io_l2p_25,
        io_l2p_26, io_l2p_32, io_l2p_33, io_l2p_36,
        io_l2p_a15_d31_34, io_l2p_d15_24, io_l2p_sm0p_35,
        io_l2p_sm8p_15, io_l3n_12, io_l3n_13, io_l3n_14,
        io_l3n_16, io_l3n_22, io_l3n_23, io_l3n_25, io_l3n_26,
        io_l3n_32, io_l3n_33, io_l3n_36, io_l3n_a12_d28_34,
        io_l3n_d12_24, io_l3n_sm1n_35, io_l3n_sm9n_15, io_l3p_12,
        io_l3p_13, io_l3p_14, io_l3p_16, io_l3p_22, io_l3p_23,
        io_l3p_25, io_l3p_26, io_l3p_32, io_l3p_33, io_l3p_36,
        io_l3p_a13_d29_34, io_l3p_d13_24, io_l3p_sm1p_35,
        io_l3p_sm9p_15, io_l4n_vref_12, io_l4n_vref_13,
        io_l4n_vref_14, io_l4n_vref_15, io_l4n_vref_16,
        io_l4n_vref_22, io_l4n_vref_23, io_l4n_vref_25,
        io_l4n_vref_26, io_l4n_vref_32, io_l4n_vref_33,
        io_l4n_vref_35, io_l4n_vref_36, io_l4n_vref_a10_d26_34,
        io_l4n_vref_d10_24, io_l4p_12, io_l4p_13, io_l4p_14,
        io_l4p_15, io_l4p_16, io_l4p_22, io_l4p_23, io_l4p_25,
        io_l4p_26, io_l4p_32, io_l4p_33, io_l4p_35, io_l4p_36,
        io_l4p_a11_d27_34, io_l4p_d11_24, io_l5n_12, io_l5n_13,
        io_l5n_14, io_l5n_16, io_l5n_22, io_l5n_23, io_l5n_25,
        io_l5n_26, io_l5n_32, io_l5n_33, io_l5n_36,
        io_l5n_a08_d24_34, io_l5n_d8_24, io_l5n_sm10n_15,
        io_l5n_sm2n_35, io_l5p_12, io_l5p_13, io_l5p_14,
        io_l5p_16, io_l5p_22, io_l5p_23, io_l5p_25, io_l5p_26,
        io_l5p_32, io_l5p_33, io_l5p_36, io_l5p_a09_d25_34,
        io_l5p_d9_24, io_l5p_sm10p_15, io_l5p_sm2p_35, io_l6n_12,
        io_l6n_13, io_l6n_14, io_l6n_16, io_l6n_22, io_l6n_23,
        io_l6n_25, io_l6n_26, io_l6n_32, io_l6n_33, io_l6n_36,
        io_l6n_a06_d22_34, io_l6n_d6_24, io_l6n_sm11n_15,
        io_l6n_sm3n_35, io_l6p_12, io_l6p_13, io_l6p_14,
        io_l6p_16, io_l6p_22, io_l6p_23, io_l6p_25, io_l6p_26,
        io_l6p_32, io_l6p_33, io_l6p_36, io_l6p_a07_d23_34,
        io_l6p_d7_24, io_l6p_sm11p_15, io_l6p_sm3p_35, io_l7n_12,
        io_l7n_13, io_l7n_14, io_l7n_16, io_l7n_22, io_l7n_23,
        io_l7n_25, io_l7n_26, io_l7n_32, io_l7n_33, io_l7n_36,
        io_l7n_a04_d20_34, io_l7n_d4_24, io_l7n_sm12n_15,
        io_l7n_sm4n_35, io_l7p_12, io_l7p_13, io_l7p_14,
        io_l7p_16, io_l7p_22, io_l7p_23, io_l7p_25, io_l7p_26,
        io_l7p_32, io_l7p_33, io_l7p_36, io_l7p_a05_d21_34,
        io_l7p_d5_24, io_l7p_sm12p_15, io_l7p_sm4p_35,
        io_l8n_srcc_12, io_l8n_srcc_13, io_l8n_srcc_14,
        io_l8n_srcc_15, io_l8n_srcc_16, io_l8n_srcc_22,
        io_l8n_srcc_23, io_l8n_srcc_24, io_l8n_srcc_25,
        io_l8n_srcc_26, io_l8n_srcc_32, io_l8n_srcc_33,
        io_l8n_srcc_34, io_l8n_srcc_35, io_l8n_srcc_36,
        io_l8p_srcc_12, io_l8p_srcc_13, io_l8p_srcc_14,
        io_l8p_srcc_15, io_l8p_srcc_16, io_l8p_srcc_22,
        io_l8p_srcc_23, io_l8p_srcc_24, io_l8p_srcc_25,
        io_l8p_srcc_26, io_l8p_srcc_32, io_l8p_srcc_33,
        io_l8p_srcc_34, io_l8p_srcc_35, io_l8p_srcc_36,
        io_l9n_mrcc_12, io_l9n_mrcc_13, io_l9n_mrcc_14,
        io_l9n_mrcc_15, io_l9n_mrcc_16, io_l9n_mrcc_22,
        io_l9n_mrcc_23, io_l9n_mrcc_24, io_l9n_mrcc_25,
        io_l9n_mrcc_26, io_l9n_mrcc_32, io_l9n_mrcc_33,
        io_l9n_mrcc_34, io_l9n_mrcc_35, io_l9n_mrcc_36,
        io_l9p_mrcc_12, io_l9p_mrcc_13, io_l9p_mrcc_14,
        io_l9p_mrcc_15, io_l9p_mrcc_16, io_l9p_mrcc_22,
        io_l9p_mrcc_23, io_l9p_mrcc_24, io_l9p_mrcc_25,
        io_l9p_mrcc_26, io_l9p_mrcc_32, io_l9p_mrcc_33,
        io_l9p_mrcc_34, io_l9p_mrcc_35, io_l9p_mrcc_36, m0_0,
        m1_0, m2_0, mgtavcc_n_1, mgtavcc_n_2, mgtavcc_n_3,
        mgtavcc_n_4, mgtavcc_n_5, mgtavcc_n_6, mgtavcc_s_1,
        mgtavcc_s_10, mgtavcc_s_2, mgtavcc_s_3, mgtavcc_s_4,
        mgtavcc_s_5, mgtavcc_s_6, mgtavcc_s_7, mgtavcc_s_8,
        mgtavcc_s_9, mgtavtt_n_1, mgtavtt_n_2, mgtavtt_n_3,
        mgtavtt_n_4, mgtavtt_n_5, mgtavtt_n_6, mgtavtt_s_1,
        mgtavtt_s_10, mgtavtt_s_2, mgtavtt_s_3, mgtavtt_s_4,
        mgtavtt_s_5, mgtavtt_s_6, mgtavtt_s_7, mgtavtt_s_8,
        mgtavtt_s_9, mgtavttrcal_115, mgtrefclk0n_112,
        mgtrefclk0n_113, mgtrefclk0n_114, mgtrefclk0n_115,
        mgtrefclk0n_116, mgtrefclk0p_112, mgtrefclk0p_113,
        mgtrefclk0p_114, mgtrefclk0p_115, mgtrefclk0p_116,
        mgtrefclk1n_112, mgtrefclk1n_113, mgtrefclk1n_114,
        mgtrefclk1n_115, mgtrefclk1n_116, mgtrefclk1p_112,
        mgtrefclk1p_113, mgtrefclk1p_114, mgtrefclk1p_115,
        mgtrefclk1p_116, mgtrref_115, mgtrxn0_112, mgtrxn0_113,
        mgtrxn0_114, mgtrxn0_115, mgtrxn0_116, mgtrxn1_112,
        mgtrxn1_113, mgtrxn1_114, mgtrxn1_115, mgtrxn1_116,
        mgtrxn2_112, mgtrxn2_113, mgtrxn2_114, mgtrxn2_115,
        mgtrxn2_116, mgtrxn3_112, mgtrxn3_113, mgtrxn3_114,
        mgtrxn3_115, mgtrxn3_116, mgtrxp0_112, mgtrxp0_113,
        mgtrxp0_114, mgtrxp0_115, mgtrxp0_116, mgtrxp1_112,
        mgtrxp1_113, mgtrxp1_114, mgtrxp1_115, mgtrxp1_116,
        mgtrxp2_112, mgtrxp2_113, mgtrxp2_114, mgtrxp2_115,
        mgtrxp2_116, mgtrxp3_112, mgtrxp3_113, mgtrxp3_114,
        mgtrxp3_115, mgtrxp3_116, mgttxn0_112, mgttxn0_113,
        mgttxn0_114, mgttxn0_115, mgttxn0_116, mgttxn1_112,
        mgttxn1_113, mgttxn1_114, mgttxn1_115, mgttxn1_116,
        mgttxn2_112, mgttxn2_113, mgttxn2_114, mgttxn2_115,
        mgttxn2_116, mgttxn3_112, mgttxn3_113, mgttxn3_114,
        mgttxn3_115, mgttxn3_116, mgttxp0_112, mgttxp0_113,
        mgttxp0_114, mgttxp0_115, mgttxp0_116, mgttxp1_112,
        mgttxp1_113, mgttxp1_114, mgttxp1_115, mgttxp1_116,
        mgttxp2_112, mgttxp2_113, mgttxp2_114, mgttxp2_115,
        mgttxp2_116, mgttxp3_112, mgttxp3_113, mgttxp3_114,
        mgttxp3_115, mgttxp3_116, program_b_0, rdwr_b_0, tck_0,
        tdi_0, tdo_0, tms_0, vbatt_0, vccaux_1, vccaux_10,
        vccaux_11, vccaux_12, vccaux_13, vccaux_2, vccaux_3,
        vccaux_4, vccaux_5, vccaux_6, vccaux_7, vccaux_8, vccaux_9,
        vccint_1, vccint_10, vccint_11, vccint_12, vccint_13,
        vccint_14, vccint_15, vccint_16, vccint_17, vccint_18,
        vccint_19, vccint_2, vccint_20, vccint_21, vccint_22,
        vccint_23, vccint_24, vccint_25, vccint_26, vccint_27,
        vccint_28, vccint_29, vccint_3, vccint_30, vccint_31,
        vccint_32, vccint_33, vccint_34, vccint_35, vccint_36,
        vccint_37, vccint_38, vccint_39, vccint_4, vccint_40,
        vccint_41, vccint_42, vccint_43, vccint_44, vccint_45,
        vccint_46, vccint_47, vccint_48, vccint_49, vccint_5,
        vccint_50, vccint_51, vccint_52, vccint_53, vccint_54,
        vccint_55, vccint_6, vccint_7, vccint_8, vccint_9,
        vcco_0_1, vcco_0_2, vcco_12_1, vcco_12_2, vcco_12_3,
        vcco_12_4, vcco_13_1, vcco_13_2, vcco_13_3, vcco_13_4,
        vcco_13_5, vcco_14_1, vcco_14_2, vcco_14_3, vcco_14_4,
        vcco_15_1, vcco_15_2, vcco_15_3, vcco_15_4, vcco_15_5,
        vcco_16_1, vcco_16_2, vcco_16_3, vcco_16_4, vcco_16_5,
        vcco_16_6, vcco_22_1, vcco_22_2, vcco_22_3, vcco_22_4,
        vcco_22_5, vcco_23_1, vcco_23_2, vcco_23_3, vcco_23_4,
        vcco_24_1, vcco_24_2, vcco_24_3, vcco_24_4, vcco_24_5,
        vcco_24_6, vcco_25_1, vcco_25_2, vcco_25_3, vcco_25_4,
        vcco_26_1, vcco_26_2, vcco_26_3, vcco_26_4, vcco_26_5,
        vcco_32_1, vcco_32_2, vcco_32_3, vcco_32_4, vcco_32_5,
        vcco_33_1, vcco_33_2, vcco_33_3, vcco_33_4, vcco_33_5,
        vcco_34_1, vcco_34_2, vcco_34_3, vcco_34_4, vcco_34_5,
        vcco_34_6, vcco_35_1, vcco_35_2, vcco_35_3, vcco_35_4,
        vcco_35_5, vcco_36_1, vcco_36_2, vcco_36_3, vcco_36_4,
        vfs_0, vn_0, vp_0, vrefn_0, vrefp_0);
    inout avdd_0;
    inout avss_0;
    inout cclk_0;
    inout csi_b_0;
    inout din_0;
    inout done_0;
    inout dout_busy_0;
    inout dxn_0;
    inout dxp_0;
    input gnd1;
    input gnd10;
    input gnd100;
    input gnd101;
    input gnd102;
    input gnd103;
    input gnd104;
    input gnd105;
    input gnd106;
    input gnd107;
    input gnd108;
    input gnd109;
    input gnd11;
    input gnd110;
    input gnd111;
    input gnd112;
    input gnd113;
    input gnd114;
    input gnd115;
    input gnd116;
    input gnd117;
    input gnd118;
    input gnd119;
    input gnd12;
    input gnd120;
    input gnd121;
    input gnd122;
    input gnd123;
    input gnd124;
    input gnd125;
    input gnd126;
    input gnd127;
    input gnd128;
    input gnd129;
    input gnd13;
    input gnd130;
    input gnd131;
    input gnd132;
    input gnd133;
    input gnd134;
    input gnd135;
    input gnd136;
    input gnd137;
    input gnd138;
    input gnd139;
    input gnd14;
    input gnd140;
    input gnd141;
    input gnd142;
    input gnd143;
    input gnd144;
    input gnd145;
    input gnd146;
    input gnd147;
    input gnd148;
    input gnd149;
    input gnd15;
    input gnd150;
    input gnd151;
    input gnd152;
    input gnd153;
    input gnd154;
    input gnd155;
    input gnd156;
    input gnd157;
    input gnd158;
    input gnd159;
    input gnd16;
    input gnd160;
    input gnd161;
    input gnd162;
    input gnd163;
    input gnd164;
    input gnd165;
    input gnd166;
    input gnd167;
    input gnd168;
    input gnd169;
    input gnd17;
    input gnd170;
    input gnd171;
    input gnd172;
    input gnd173;
    input gnd174;
    input gnd175;
    input gnd176;
    input gnd177;
    input gnd178;
    input gnd179;
    input gnd18;
    input gnd180;
    input gnd181;
    input gnd182;
    input gnd183;
    input gnd184;
    input gnd185;
    input gnd186;
    input gnd187;
    input gnd188;
    input gnd189;
    input gnd19;
    input gnd190;
    input gnd191;
    input gnd192;
    input gnd193;
    input gnd194;
    input gnd195;
    input gnd196;
    input gnd197;
    input gnd198;
    input gnd199;
    input gnd2;
    input gnd20;
    input gnd200;
    input gnd201;
    input gnd202;
    input gnd203;
    input gnd204;
    input gnd205;
    input gnd206;
    input gnd207;
    input gnd208;
    input gnd209;
    input gnd21;
    input gnd210;
    input gnd211;
    input gnd212;
    input gnd213;
    input gnd214;
    input gnd215;
    input gnd216;
    input gnd217;
    input gnd218;
    input gnd219;
    input gnd22;
    input gnd220;
    input gnd221;
    input gnd222;
    input gnd223;
    input gnd224;
    input gnd225;
    input gnd226;
    input gnd227;
    input gnd228;
    input gnd229;
    input gnd23;
    input gnd230;
    input gnd231;
    input gnd232;
    input gnd233;
    input gnd234;
    input gnd235;
    input gnd236;
    input gnd237;
    input gnd238;
    input gnd239;
    input gnd24;
    input gnd240;
    input gnd241;
    input gnd242;
    input gnd243;
    input gnd244;
    input gnd245;
    input gnd246;
    input gnd247;
    input gnd248;
    input gnd249;
    input gnd25;
    input gnd250;
    input gnd251;
    input gnd252;
    input gnd253;
    input gnd26;
    input gnd27;
    input gnd28;
    input gnd29;
    input gnd3;
    input gnd30;
    input gnd31;
    input gnd32;
    input gnd33;
    input gnd34;
    input gnd35;
    input gnd36;
    input gnd37;
    input gnd38;
    input gnd39;
    input gnd4;
    input gnd40;
    input gnd41;
    input gnd42;
    input gnd43;
    input gnd44;
    input gnd45;
    input gnd46;
    input gnd47;
    input gnd48;
    input gnd49;
    input gnd5;
    input gnd50;
    input gnd51;
    input gnd52;
    input gnd53;
    input gnd54;
    input gnd55;
    input gnd56;
    input gnd57;
    input gnd58;
    input gnd59;
    input gnd6;
    input gnd60;
    input gnd61;
    input gnd62;
    input gnd63;
    input gnd64;
    input gnd65;
    input gnd66;
    input gnd67;
    input gnd68;
    input gnd69;
    input gnd7;
    input gnd70;
    input gnd71;
    input gnd72;
    input gnd73;
    input gnd74;
    input gnd75;
    input gnd76;
    input gnd77;
    input gnd78;
    input gnd79;
    input gnd8;
    input gnd80;
    input gnd81;
    input gnd82;
    input gnd83;
    input gnd84;
    input gnd85;
    input gnd86;
    input gnd87;
    input gnd88;
    input gnd89;
    input gnd9;
    input gnd90;
    input gnd91;
    input gnd92;
    input gnd93;
    input gnd94;
    input gnd95;
    input gnd96;
    input gnd97;
    input gnd98;
    input gnd99;
    inout hswapen_0;
    inout init_b_0;
    inout io_l0n_12;
    inout io_l0n_13;
    inout io_l0n_14;
    inout io_l0n_15;
    inout io_l0n_16;
    inout io_l0n_22;
    inout io_l0n_23;
    inout io_l0n_25;
    inout io_l0n_26;
    inout io_l0n_32;
    inout io_l0n_33;
    inout io_l0n_35;
    inout io_l0n_36;
    inout io_l0n_gc_24;
    inout io_l0n_gc_34;
    inout io_l0p_12;
    inout io_l0p_13;
    inout io_l0p_14;
    inout io_l0p_15;
    inout io_l0p_16;
    inout io_l0p_22;
    inout io_l0p_23;
    inout io_l0p_25;
    inout io_l0p_26;
    inout io_l0p_32;
    inout io_l0p_33;
    inout io_l0p_35;
    inout io_l0p_36;
    inout io_l0p_gc_24;
    inout io_l0p_gc_34;
    inout io_l10n_mrcc_12;
    inout io_l10n_mrcc_13;
    inout io_l10n_mrcc_14;
    inout io_l10n_mrcc_15;
    inout io_l10n_mrcc_16;
    inout io_l10n_mrcc_22;
    inout io_l10n_mrcc_23;
    inout io_l10n_mrcc_24;
    inout io_l10n_mrcc_25;
    inout io_l10n_mrcc_26;
    inout io_l10n_mrcc_32;
    inout io_l10n_mrcc_33;
    inout io_l10n_mrcc_34;
    inout io_l10n_mrcc_35;
    inout io_l10n_mrcc_36;
    inout io_l10p_mrcc_12;
    inout io_l10p_mrcc_13;
    inout io_l10p_mrcc_14;
    inout io_l10p_mrcc_15;
    inout io_l10p_mrcc_16;
    inout io_l10p_mrcc_22;
    inout io_l10p_mrcc_23;
    inout io_l10p_mrcc_24;
    inout io_l10p_mrcc_25;
    inout io_l10p_mrcc_26;
    inout io_l10p_mrcc_32;
    inout io_l10p_mrcc_33;
    inout io_l10p_mrcc_34;
    inout io_l10p_mrcc_35;
    inout io_l10p_mrcc_36;
    inout io_l11n_srcc_12;
    inout io_l11n_srcc_13;
    inout io_l11n_srcc_14;
    inout io_l11n_srcc_15;
    inout io_l11n_srcc_16;
    inout io_l11n_srcc_22;
    inout io_l11n_srcc_23;
    inout io_l11n_srcc_24;
    inout io_l11n_srcc_25;
    inout io_l11n_srcc_26;
    inout io_l11n_srcc_32;
    inout io_l11n_srcc_33;
    inout io_l11n_srcc_34;
    inout io_l11n_srcc_35;
    inout io_l11n_srcc_36;
    inout io_l11p_srcc_12;
    inout io_l11p_srcc_13;
    inout io_l11p_srcc_14;
    inout io_l11p_srcc_15;
    inout io_l11p_srcc_16;
    inout io_l11p_srcc_22;
    inout io_l11p_srcc_23;
    inout io_l11p_srcc_24;
    inout io_l11p_srcc_25;
    inout io_l11p_srcc_26;
    inout io_l11p_srcc_32;
    inout io_l11p_srcc_33;
    inout io_l11p_srcc_34;
    inout io_l11p_srcc_35;
    inout io_l11p_srcc_36;
    inout io_l12n_25;
    inout io_l12n_a02_d18_34;
    inout io_l12n_d2_fs2_24;
    inout io_l12n_sm13n_15;
    inout io_l12n_sm5n_35;
    inout io_l12n_vrp_12;
    inout io_l12n_vrp_13;
    inout io_l12n_vrp_14;
    inout io_l12n_vrp_16;
    inout io_l12n_vrp_22;
    inout io_l12n_vrp_23;
    inout io_l12n_vrp_26;
    inout io_l12n_vrp_32;
    inout io_l12n_vrp_33;
    inout io_l12n_vrp_36;
    inout io_l12p_25;
    inout io_l12p_a03_d19_34;
    inout io_l12p_d3_24;
    inout io_l12p_sm13p_15;
    inout io_l12p_sm5p_35;
    inout io_l12p_vrn_12;
    inout io_l12p_vrn_13;
    inout io_l12p_vrn_14;
    inout io_l12p_vrn_16;
    inout io_l12p_vrn_22;
    inout io_l12p_vrn_23;
    inout io_l12p_vrn_26;
    inout io_l12p_vrn_32;
    inout io_l12p_vrn_33;
    inout io_l12p_vrn_36;
    inout io_l13n_12;
    inout io_l13n_13;
    inout io_l13n_14;
    inout io_l13n_16;
    inout io_l13n_22;
    inout io_l13n_23;
    inout io_l13n_25;
    inout io_l13n_26;
    inout io_l13n_32;
    inout io_l13n_33;
    inout io_l13n_36;
    inout io_l13n_a00_d16_34;
    inout io_l13n_d0_fs0_24;
    inout io_l13n_sm14n_15;
    inout io_l13n_sm6n_35;
    inout io_l13p_12;
    inout io_l13p_13;
    inout io_l13p_14;
    inout io_l13p_16;
    inout io_l13p_22;
    inout io_l13p_23;
    inout io_l13p_25;
    inout io_l13p_26;
    inout io_l13p_32;
    inout io_l13p_33;
    inout io_l13p_36;
    inout io_l13p_a01_d17_34;
    inout io_l13p_d1_fs1_24;
    inout io_l13p_sm14p_15;
    inout io_l13p_sm6p_35;
    inout io_l14n_vref_12;
    inout io_l14n_vref_13;
    inout io_l14n_vref_14;
    inout io_l14n_vref_15;
    inout io_l14n_vref_16;
    inout io_l14n_vref_22;
    inout io_l14n_vref_23;
    inout io_l14n_vref_25;
    inout io_l14n_vref_26;
    inout io_l14n_vref_32;
    inout io_l14n_vref_33;
    inout io_l14n_vref_35;
    inout io_l14n_vref_36;
    inout io_l14n_vref_a24_34;
    inout io_l14n_vref_foe_b_mosi_24;
    inout io_l14p_12;
    inout io_l14p_13;
    inout io_l14p_14;
    inout io_l14p_15;
    inout io_l14p_16;
    inout io_l14p_22;
    inout io_l14p_23;
    inout io_l14p_25;
    inout io_l14p_26;
    inout io_l14p_32;
    inout io_l14p_33;
    inout io_l14p_35;
    inout io_l14p_36;
    inout io_l14p_a25_34;
    inout io_l14p_fcs_b_24;
    inout io_l15n_12;
    inout io_l15n_13;
    inout io_l15n_14;
    inout io_l15n_16;
    inout io_l15n_22;
    inout io_l15n_23;
    inout io_l15n_25;
    inout io_l15n_26;
    inout io_l15n_32;
    inout io_l15n_33;
    inout io_l15n_36;
    inout io_l15n_a22_34;
    inout io_l15n_rs1_24;
    inout io_l15n_sm15n_15;
    inout io_l15n_sm7n_35;
    inout io_l15p_12;
    inout io_l15p_13;
    inout io_l15p_14;
    inout io_l15p_16;
    inout io_l15p_22;
    inout io_l15p_23;
    inout io_l15p_25;
    inout io_l15p_26;
    inout io_l15p_32;
    inout io_l15p_33;
    inout io_l15p_36;
    inout io_l15p_a23_34;
    inout io_l15p_fwe_b_24;
    inout io_l15p_sm15p_15;
    inout io_l15p_sm7p_35;
    inout io_l16n_12;
    inout io_l16n_13;
    inout io_l16n_14;
    inout io_l16n_16;
    inout io_l16n_22;
    inout io_l16n_23;
    inout io_l16n_26;
    inout io_l16n_32;
    inout io_l16n_33;
    inout io_l16n_36;
    inout io_l16n_a20_34;
    inout io_l16n_cso_b_24;
    inout io_l16n_vrp_15;
    inout io_l16n_vrp_25;
    inout io_l16n_vrp_35;
    inout io_l16p_12;
    inout io_l16p_13;
    inout io_l16p_14;
    inout io_l16p_16;
    inout io_l16p_22;
    inout io_l16p_23;
    inout io_l16p_26;
    inout io_l16p_32;
    inout io_l16p_33;
    inout io_l16p_36;
    inout io_l16p_a21_34;
    inout io_l16p_rs0_24;
    inout io_l16p_vrn_15;
    inout io_l16p_vrn_25;
    inout io_l16p_vrn_35;
    inout io_l17n_12;
    inout io_l17n_13;
    inout io_l17n_14;
    inout io_l17n_15;
    inout io_l17n_16;
    inout io_l17n_22;
    inout io_l17n_23;
    inout io_l17n_25;
    inout io_l17n_26;
    inout io_l17n_32;
    inout io_l17n_33;
    inout io_l17n_35;
    inout io_l17n_36;
    inout io_l17n_a18_34;
    inout io_l17n_vrp_24;
    inout io_l17p_12;
    inout io_l17p_13;
    inout io_l17p_14;
    inout io_l17p_15;
    inout io_l17p_16;
    inout io_l17p_22;
    inout io_l17p_23;
    inout io_l17p_25;
    inout io_l17p_26;
    inout io_l17p_32;
    inout io_l17p_33;
    inout io_l17p_35;
    inout io_l17p_36;
    inout io_l17p_a19_34;
    inout io_l17p_vrn_24;
    inout io_l18n_12;
    inout io_l18n_13;
    inout io_l18n_14;
    inout io_l18n_15;
    inout io_l18n_16;
    inout io_l18n_22;
    inout io_l18n_23;
    inout io_l18n_24;
    inout io_l18n_26;
    inout io_l18n_32;
    inout io_l18n_33;
    inout io_l18n_36;
    inout io_l18n_a16_34;
    inout io_l18n_gc_25;
    inout io_l18n_gc_35;
    inout io_l18p_12;
    inout io_l18p_13;
    inout io_l18p_14;
    inout io_l18p_15;
    inout io_l18p_16;
    inout io_l18p_22;
    inout io_l18p_23;
    inout io_l18p_24;
    inout io_l18p_26;
    inout io_l18p_32;
    inout io_l18p_33;
    inout io_l18p_36;
    inout io_l18p_a17_34;
    inout io_l18p_gc_25;
    inout io_l18p_gc_35;
    inout io_l19n_12;
    inout io_l19n_13;
    inout io_l19n_14;
    inout io_l19n_15;
    inout io_l19n_16;
    inout io_l19n_22;
    inout io_l19n_23;
    inout io_l19n_24;
    inout io_l19n_26;
    inout io_l19n_32;
    inout io_l19n_33;
    inout io_l19n_36;
    inout io_l19n_gc_25;
    inout io_l19n_gc_35;
    inout io_l19n_vrp_34;
    inout io_l19p_12;
    inout io_l19p_13;
    inout io_l19p_14;
    inout io_l19p_15;
    inout io_l19p_16;
    inout io_l19p_22;
    inout io_l19p_23;
    inout io_l19p_24;
    inout io_l19p_26;
    inout io_l19p_32;
    inout io_l19p_33;
    inout io_l19p_36;
    inout io_l19p_gc_25;
    inout io_l19p_gc_35;
    inout io_l19p_vrn_34;
    inout io_l1n_12;
    inout io_l1n_13;
    inout io_l1n_14;
    inout io_l1n_15;
    inout io_l1n_16;
    inout io_l1n_22;
    inout io_l1n_23;
    inout io_l1n_25;
    inout io_l1n_26;
    inout io_l1n_32;
    inout io_l1n_33;
    inout io_l1n_35;
    inout io_l1n_36;
    inout io_l1n_gc_24;
    inout io_l1n_gc_34;
    inout io_l1p_12;
    inout io_l1p_13;
    inout io_l1p_14;
    inout io_l1p_15;
    inout io_l1p_16;
    inout io_l1p_22;
    inout io_l1p_23;
    inout io_l1p_25;
    inout io_l1p_26;
    inout io_l1p_32;
    inout io_l1p_33;
    inout io_l1p_35;
    inout io_l1p_36;
    inout io_l1p_gc_24;
    inout io_l1p_gc_34;
    inout io_l2n_12;
    inout io_l2n_13;
    inout io_l2n_14;
    inout io_l2n_16;
    inout io_l2n_22;
    inout io_l2n_23;
    inout io_l2n_25;
    inout io_l2n_26;
    inout io_l2n_32;
    inout io_l2n_33;
    inout io_l2n_36;
    inout io_l2n_a14_d30_34;
    inout io_l2n_d14_24;
    inout io_l2n_sm0n_35;
    inout io_l2n_sm8n_15;
    inout io_l2p_12;
    inout io_l2p_13;
    inout io_l2p_14;
    inout io_l2p_16;
    inout io_l2p_22;
    inout io_l2p_23;
    inout io_l2p_25;
    inout io_l2p_26;
    inout io_l2p_32;
    inout io_l2p_33;
    inout io_l2p_36;
    inout io_l2p_a15_d31_34;
    inout io_l2p_d15_24;
    inout io_l2p_sm0p_35;
    inout io_l2p_sm8p_15;
    inout io_l3n_12;
    inout io_l3n_13;
    inout io_l3n_14;
    inout io_l3n_16;
    inout io_l3n_22;
    inout io_l3n_23;
    inout io_l3n_25;
    inout io_l3n_26;
    inout io_l3n_32;
    inout io_l3n_33;
    inout io_l3n_36;
    inout io_l3n_a12_d28_34;
    inout io_l3n_d12_24;
    inout io_l3n_sm1n_35;
    inout io_l3n_sm9n_15;
    inout io_l3p_12;
    inout io_l3p_13;
    inout io_l3p_14;
    inout io_l3p_16;
    inout io_l3p_22;
    inout io_l3p_23;
    inout io_l3p_25;
    inout io_l3p_26;
    inout io_l3p_32;
    inout io_l3p_33;
    inout io_l3p_36;
    inout io_l3p_a13_d29_34;
    inout io_l3p_d13_24;
    inout io_l3p_sm1p_35;
    inout io_l3p_sm9p_15;
    inout io_l4n_vref_12;
    inout io_l4n_vref_13;
    inout io_l4n_vref_14;
    inout io_l4n_vref_15;
    inout io_l4n_vref_16;
    inout io_l4n_vref_22;
    inout io_l4n_vref_23;
    inout io_l4n_vref_25;
    inout io_l4n_vref_26;
    inout io_l4n_vref_32;
    inout io_l4n_vref_33;
    inout io_l4n_vref_35;
    inout io_l4n_vref_36;
    inout io_l4n_vref_a10_d26_34;
    inout io_l4n_vref_d10_24;
    inout io_l4p_12;
    inout io_l4p_13;
    inout io_l4p_14;
    inout io_l4p_15;
    inout io_l4p_16;
    inout io_l4p_22;
    inout io_l4p_23;
    inout io_l4p_25;
    inout io_l4p_26;
    inout io_l4p_32;
    inout io_l4p_33;
    inout io_l4p_35;
    inout io_l4p_36;
    inout io_l4p_a11_d27_34;
    inout io_l4p_d11_24;
    inout io_l5n_12;
    inout io_l5n_13;
    inout io_l5n_14;
    inout io_l5n_16;
    inout io_l5n_22;
    inout io_l5n_23;
    inout io_l5n_25;
    inout io_l5n_26;
    inout io_l5n_32;
    inout io_l5n_33;
    inout io_l5n_36;
    inout io_l5n_a08_d24_34;
    inout io_l5n_d8_24;
    inout io_l5n_sm10n_15;
    inout io_l5n_sm2n_35;
    inout io_l5p_12;
    inout io_l5p_13;
    inout io_l5p_14;
    inout io_l5p_16;
    inout io_l5p_22;
    inout io_l5p_23;
    inout io_l5p_25;
    inout io_l5p_26;
    inout io_l5p_32;
    inout io_l5p_33;
    inout io_l5p_36;
    inout io_l5p_a09_d25_34;
    inout io_l5p_d9_24;
    inout io_l5p_sm10p_15;
    inout io_l5p_sm2p_35;
    inout io_l6n_12;
    inout io_l6n_13;
    inout io_l6n_14;
    inout io_l6n_16;
    inout io_l6n_22;
    inout io_l6n_23;
    inout io_l6n_25;
    inout io_l6n_26;
    inout io_l6n_32;
    inout io_l6n_33;
    inout io_l6n_36;
    inout io_l6n_a06_d22_34;
    inout io_l6n_d6_24;
    inout io_l6n_sm11n_15;
    inout io_l6n_sm3n_35;
    inout io_l6p_12;
    inout io_l6p_13;
    inout io_l6p_14;
    inout io_l6p_16;
    inout io_l6p_22;
    inout io_l6p_23;
    inout io_l6p_25;
    inout io_l6p_26;
    inout io_l6p_32;
    inout io_l6p_33;
    inout io_l6p_36;
    inout io_l6p_a07_d23_34;
    inout io_l6p_d7_24;
    inout io_l6p_sm11p_15;
    inout io_l6p_sm3p_35;
    inout io_l7n_12;
    inout io_l7n_13;
    inout io_l7n_14;
    inout io_l7n_16;
    inout io_l7n_22;
    inout io_l7n_23;
    inout io_l7n_25;
    inout io_l7n_26;
    inout io_l7n_32;
    inout io_l7n_33;
    inout io_l7n_36;
    inout io_l7n_a04_d20_34;
    inout io_l7n_d4_24;
    inout io_l7n_sm12n_15;
    inout io_l7n_sm4n_35;
    inout io_l7p_12;
    inout io_l7p_13;
    inout io_l7p_14;
    inout io_l7p_16;
    inout io_l7p_22;
    inout io_l7p_23;
    inout io_l7p_25;
    inout io_l7p_26;
    inout io_l7p_32;
    inout io_l7p_33;
    inout io_l7p_36;
    inout io_l7p_a05_d21_34;
    inout io_l7p_d5_24;
    inout io_l7p_sm12p_15;
    inout io_l7p_sm4p_35;
    inout io_l8n_srcc_12;
    inout io_l8n_srcc_13;
    inout io_l8n_srcc_14;
    inout io_l8n_srcc_15;
    inout io_l8n_srcc_16;
    inout io_l8n_srcc_22;
    inout io_l8n_srcc_23;
    inout io_l8n_srcc_24;
    inout io_l8n_srcc_25;
    inout io_l8n_srcc_26;
    inout io_l8n_srcc_32;
    inout io_l8n_srcc_33;
    inout io_l8n_srcc_34;
    inout io_l8n_srcc_35;
    inout io_l8n_srcc_36;
    inout io_l8p_srcc_12;
    inout io_l8p_srcc_13;
    inout io_l8p_srcc_14;
    inout io_l8p_srcc_15;
    inout io_l8p_srcc_16;
    inout io_l8p_srcc_22;
    inout io_l8p_srcc_23;
    inout io_l8p_srcc_24;
    inout io_l8p_srcc_25;
    inout io_l8p_srcc_26;
    inout io_l8p_srcc_32;
    inout io_l8p_srcc_33;
    inout io_l8p_srcc_34;
    inout io_l8p_srcc_35;
    inout io_l8p_srcc_36;
    inout io_l9n_mrcc_12;
    inout io_l9n_mrcc_13;
    inout io_l9n_mrcc_14;
    inout io_l9n_mrcc_15;
    inout io_l9n_mrcc_16;
    inout io_l9n_mrcc_22;
    inout io_l9n_mrcc_23;
    inout io_l9n_mrcc_24;
    inout io_l9n_mrcc_25;
    inout io_l9n_mrcc_26;
    inout io_l9n_mrcc_32;
    inout io_l9n_mrcc_33;
    inout io_l9n_mrcc_34;
    inout io_l9n_mrcc_35;
    inout io_l9n_mrcc_36;
    inout io_l9p_mrcc_12;
    inout io_l9p_mrcc_13;
    inout io_l9p_mrcc_14;
    inout io_l9p_mrcc_15;
    inout io_l9p_mrcc_16;
    inout io_l9p_mrcc_22;
    inout io_l9p_mrcc_23;
    inout io_l9p_mrcc_24;
    inout io_l9p_mrcc_25;
    inout io_l9p_mrcc_26;
    inout io_l9p_mrcc_32;
    inout io_l9p_mrcc_33;
    inout io_l9p_mrcc_34;
    inout io_l9p_mrcc_35;
    inout io_l9p_mrcc_36;
    inout m0_0;
    inout m1_0;
    inout m2_0;
    inout mgtavcc_n_1;
    inout mgtavcc_n_2;
    inout mgtavcc_n_3;
    inout mgtavcc_n_4;
    inout mgtavcc_n_5;
    inout mgtavcc_n_6;
    inout mgtavcc_s_1;
    inout mgtavcc_s_10;
    inout mgtavcc_s_2;
    inout mgtavcc_s_3;
    inout mgtavcc_s_4;
    inout mgtavcc_s_5;
    inout mgtavcc_s_6;
    inout mgtavcc_s_7;
    inout mgtavcc_s_8;
    inout mgtavcc_s_9;
    inout mgtavtt_n_1;
    inout mgtavtt_n_2;
    inout mgtavtt_n_3;
    inout mgtavtt_n_4;
    inout mgtavtt_n_5;
    inout mgtavtt_n_6;
    inout mgtavtt_s_1;
    inout mgtavtt_s_10;
    inout mgtavtt_s_2;
    inout mgtavtt_s_3;
    inout mgtavtt_s_4;
    inout mgtavtt_s_5;
    inout mgtavtt_s_6;
    inout mgtavtt_s_7;
    inout mgtavtt_s_8;
    inout mgtavtt_s_9;
    inout mgtavttrcal_115;
    inout mgtrefclk0n_112;
    inout mgtrefclk0n_113;
    inout mgtrefclk0n_114;
    inout mgtrefclk0n_115;
    inout mgtrefclk0n_116;
    inout mgtrefclk0p_112;
    inout mgtrefclk0p_113;
    inout mgtrefclk0p_114;
    inout mgtrefclk0p_115;
    inout mgtrefclk0p_116;
    inout mgtrefclk1n_112;
    inout mgtrefclk1n_113;
    inout mgtrefclk1n_114;
    inout mgtrefclk1n_115;
    inout mgtrefclk1n_116;
    inout mgtrefclk1p_112;
    inout mgtrefclk1p_113;
    inout mgtrefclk1p_114;
    inout mgtrefclk1p_115;
    inout mgtrefclk1p_116;
    inout mgtrref_115;
    inout mgtrxn0_112;
    inout mgtrxn0_113;
    inout mgtrxn0_114;
    inout mgtrxn0_115;
    inout mgtrxn0_116;
    inout mgtrxn1_112;
    inout mgtrxn1_113;
    inout mgtrxn1_114;
    inout mgtrxn1_115;
    inout mgtrxn1_116;
    inout mgtrxn2_112;
    inout mgtrxn2_113;
    inout mgtrxn2_114;
    inout mgtrxn2_115;
    inout mgtrxn2_116;
    inout mgtrxn3_112;
    inout mgtrxn3_113;
    inout mgtrxn3_114;
    inout mgtrxn3_115;
    inout mgtrxn3_116;
    inout mgtrxp0_112;
    inout mgtrxp0_113;
    inout mgtrxp0_114;
    inout mgtrxp0_115;
    inout mgtrxp0_116;
    inout mgtrxp1_112;
    inout mgtrxp1_113;
    inout mgtrxp1_114;
    inout mgtrxp1_115;
    inout mgtrxp1_116;
    inout mgtrxp2_112;
    inout mgtrxp2_113;
    inout mgtrxp2_114;
    inout mgtrxp2_115;
    inout mgtrxp2_116;
    inout mgtrxp3_112;
    inout mgtrxp3_113;
    inout mgtrxp3_114;
    inout mgtrxp3_115;
    inout mgtrxp3_116;
    inout mgttxn0_112;
    inout mgttxn0_113;
    inout mgttxn0_114;
    inout mgttxn0_115;
    inout mgttxn0_116;
    inout mgttxn1_112;
    inout mgttxn1_113;
    inout mgttxn1_114;
    inout mgttxn1_115;
    inout mgttxn1_116;
    inout mgttxn2_112;
    inout mgttxn2_113;
    inout mgttxn2_114;
    inout mgttxn2_115;
    inout mgttxn2_116;
    inout mgttxn3_112;
    inout mgttxn3_113;
    inout mgttxn3_114;
    inout mgttxn3_115;
    inout mgttxn3_116;
    inout mgttxp0_112;
    inout mgttxp0_113;
    inout mgttxp0_114;
    inout mgttxp0_115;
    inout mgttxp0_116;
    inout mgttxp1_112;
    inout mgttxp1_113;
    inout mgttxp1_114;
    inout mgttxp1_115;
    inout mgttxp1_116;
    inout mgttxp2_112;
    inout mgttxp2_113;
    inout mgttxp2_114;
    inout mgttxp2_115;
    inout mgttxp2_116;
    inout mgttxp3_112;
    inout mgttxp3_113;
    inout mgttxp3_114;
    inout mgttxp3_115;
    inout mgttxp3_116;
    inout program_b_0;
    inout rdwr_b_0;
    inout tck_0;
    inout tdi_0;
    inout tdo_0;
    inout tms_0;
    inout vbatt_0;
    input vccaux_1;
    input vccaux_10;
    input vccaux_11;
    input vccaux_12;
    input vccaux_13;
    input vccaux_2;
    input vccaux_3;
    input vccaux_4;
    input vccaux_5;
    input vccaux_6;
    input vccaux_7;
    input vccaux_8;
    input vccaux_9;
    input vccint_1;
    input vccint_10;
    input vccint_11;
    input vccint_12;
    input vccint_13;
    input vccint_14;
    input vccint_15;
    input vccint_16;
    input vccint_17;
    input vccint_18;
    input vccint_19;
    input vccint_2;
    input vccint_20;
    input vccint_21;
    input vccint_22;
    input vccint_23;
    input vccint_24;
    input vccint_25;
    input vccint_26;
    input vccint_27;
    input vccint_28;
    input vccint_29;
    input vccint_3;
    input vccint_30;
    input vccint_31;
    input vccint_32;
    input vccint_33;
    input vccint_34;
    input vccint_35;
    input vccint_36;
    input vccint_37;
    input vccint_38;
    input vccint_39;
    input vccint_4;
    input vccint_40;
    input vccint_41;
    input vccint_42;
    input vccint_43;
    input vccint_44;
    input vccint_45;
    input vccint_46;
    input vccint_47;
    input vccint_48;
    input vccint_49;
    input vccint_5;
    input vccint_50;
    input vccint_51;
    input vccint_52;
    input vccint_53;
    input vccint_54;
    input vccint_55;
    input vccint_6;
    input vccint_7;
    input vccint_8;
    input vccint_9;
    input vcco_0_1;
    input vcco_0_2;
    input vcco_12_1;
    input vcco_12_2;
    input vcco_12_3;
    input vcco_12_4;
    input vcco_13_1;
    input vcco_13_2;
    input vcco_13_3;
    input vcco_13_4;
    input vcco_13_5;
    input vcco_14_1;
    input vcco_14_2;
    input vcco_14_3;
    input vcco_14_4;
    input vcco_15_1;
    input vcco_15_2;
    input vcco_15_3;
    input vcco_15_4;
    input vcco_15_5;
    input vcco_16_1;
    input vcco_16_2;
    input vcco_16_3;
    input vcco_16_4;
    input vcco_16_5;
    input vcco_16_6;
    input vcco_22_1;
    input vcco_22_2;
    input vcco_22_3;
    input vcco_22_4;
    input vcco_22_5;
    input vcco_23_1;
    input vcco_23_2;
    input vcco_23_3;
    input vcco_23_4;
    input vcco_24_1;
    input vcco_24_2;
    input vcco_24_3;
    input vcco_24_4;
    input vcco_24_5;
    input vcco_24_6;
    input vcco_25_1;
    input vcco_25_2;
    input vcco_25_3;
    input vcco_25_4;
    input vcco_26_1;
    input vcco_26_2;
    input vcco_26_3;
    input vcco_26_4;
    input vcco_26_5;
    input vcco_32_1;
    input vcco_32_2;
    input vcco_32_3;
    input vcco_32_4;
    input vcco_32_5;
    input vcco_33_1;
    input vcco_33_2;
    input vcco_33_3;
    input vcco_33_4;
    input vcco_33_5;
    input vcco_34_1;
    input vcco_34_2;
    input vcco_34_3;
    input vcco_34_4;
    input vcco_34_5;
    input vcco_34_6;
    input vcco_35_1;
    input vcco_35_2;
    input vcco_35_3;
    input vcco_35_4;
    input vcco_35_5;
    input vcco_36_1;
    input vcco_36_2;
    input vcco_36_3;
    input vcco_36_4;
    inout vfs_0;
    inout vn_0;
    inout vp_0;
    inout vrefn_0;
    inout vrefp_0;


    initial
        begin
        end

endmodule
