// generated by newgenasym  Thu Feb 19 11:30:55 2009


module \1746540_4  (a0, a1, a10, a11, a12, a13, a2, a3, a4, a5, a6, a7, a8, a9, ba0,
        ba1, \cas# , ck0, \ck0# , ck1, \ck1# , cke0, cke1, dm0, dm1, dm2, dm3,
        dm4, dm5, dm6, dm7, dq0, dq1, dq10, dq11, dq12, dq13, dq14, dq15,
        dq16, dq17, dq18, dq19, dq2, dq20, dq21, dq22, dq23, dq24, dq25,
        dq26, dq27, dq28, dq29, dq3, dq30, dq31, dq32, dq33, dq34, dq35,
        dq36, dq37, dq38, dq39, dq4, dq40, dq41, dq42, dq43, dq44, dq45,
        dq46, dq47, dq48, dq49, dq5, dq50, dq51, dq52, dq53, dq54, dq55,
        dq56, dq57, dq58, dq59, dq6, dq60, dq61, dq62, dq63, dq7, dq8,
        dq9, dqs0, \dqs0# , dqs1, \dqs1# , dqs2, \dqs2# , dqs3, \dqs3# , dqs4,
        \dqs4# , dqs5, \dqs5# , dqs6, \dqs6# , dqs7, \dqs7# , nc_1, nc_2, nc_3,
        nc_4, \nc_5/ba2 , nc_6, nc_7, nc_8, odt0, odt1, pad1, pad2, \ras# ,
        \s0# , \s1# , sa0, sa1, scl, sda, vdd_1, vdd_10, vdd_11, vdd_12,
        vdd_2, vdd_3, vdd_4, vdd_5, vdd_6, vdd_7, vdd_8, vdd_9,
        vddspd, vref, vss_1, vss_10, vss_11, vss_12, vss_13, vss_14,
        vss_15, vss_16, vss_17, vss_18, vss_19, vss_2, vss_20,
        vss_21, vss_22, vss_23, vss_24, vss_25, vss_26, vss_27,
        vss_28, vss_29, vss_3, vss_30, vss_31, vss_32, vss_33,
        vss_34, vss_35, vss_36, vss_37, vss_38, vss_39, vss_4,
        vss_40, vss_41, vss_42, vss_43, vss_44, vss_45, vss_46,
        vss_47, vss_48, vss_49, vss_5, vss_50, vss_51, vss_52,
        vss_53, vss_54, vss_55, vss_56, vss_57, vss_6, vss_7, vss_8,
        vss_9, \we# );
    inout a0;
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a13;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout ba0;
    inout ba1;
    inout \cas# ;
    inout ck0;
    inout \ck0# ;
    inout ck1;
    inout \ck1# ;
    inout cke0;
    inout cke1;
    inout dm0;
    inout dm1;
    inout dm2;
    inout dm3;
    inout dm4;
    inout dm5;
    inout dm6;
    inout dm7;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout dq15;
    inout dq16;
    inout dq17;
    inout dq18;
    inout dq19;
    inout dq2;
    inout dq20;
    inout dq21;
    inout dq22;
    inout dq23;
    inout dq24;
    inout dq25;
    inout dq26;
    inout dq27;
    inout dq28;
    inout dq29;
    inout dq3;
    inout dq30;
    inout dq31;
    inout dq32;
    inout dq33;
    inout dq34;
    inout dq35;
    inout dq36;
    inout dq37;
    inout dq38;
    inout dq39;
    inout dq4;
    inout dq40;
    inout dq41;
    inout dq42;
    inout dq43;
    inout dq44;
    inout dq45;
    inout dq46;
    inout dq47;
    inout dq48;
    inout dq49;
    inout dq5;
    inout dq50;
    inout dq51;
    inout dq52;
    inout dq53;
    inout dq54;
    inout dq55;
    inout dq56;
    inout dq57;
    inout dq58;
    inout dq59;
    inout dq6;
    inout dq60;
    inout dq61;
    inout dq62;
    inout dq63;
    inout dq7;
    inout dq8;
    inout dq9;
    inout dqs0;
    inout \dqs0# ;
    inout dqs1;
    inout \dqs1# ;
    inout dqs2;
    inout \dqs2# ;
    inout dqs3;
    inout \dqs3# ;
    inout dqs4;
    inout \dqs4# ;
    inout dqs5;
    inout \dqs5# ;
    inout dqs6;
    inout \dqs6# ;
    inout dqs7;
    inout \dqs7# ;
    inout nc_1;
    inout nc_2;
    inout nc_3;
    inout nc_4;
    inout \nc_5/ba2 ;
    inout nc_6;
    inout nc_7;
    inout nc_8;
    inout odt0;
    inout odt1;
    inout pad1;
    inout pad2;
    inout \ras# ;
    inout \s0# ;
    inout \s1# ;
    inout sa0;
    inout sa1;
    inout scl;
    inout sda;
    inout vdd_1;
    inout vdd_10;
    inout vdd_11;
    inout vdd_12;
    inout vdd_2;
    inout vdd_3;
    inout vdd_4;
    inout vdd_5;
    inout vdd_6;
    inout vdd_7;
    inout vdd_8;
    inout vdd_9;
    inout vddspd;
    inout vref;
    inout vss_1;
    inout vss_10;
    inout vss_11;
    inout vss_12;
    inout vss_13;
    inout vss_14;
    inout vss_15;
    inout vss_16;
    inout vss_17;
    inout vss_18;
    inout vss_19;
    inout vss_2;
    inout vss_20;
    inout vss_21;
    inout vss_22;
    inout vss_23;
    inout vss_24;
    inout vss_25;
    inout vss_26;
    inout vss_27;
    inout vss_28;
    inout vss_29;
    inout vss_3;
    inout vss_30;
    inout vss_31;
    inout vss_32;
    inout vss_33;
    inout vss_34;
    inout vss_35;
    inout vss_36;
    inout vss_37;
    inout vss_38;
    inout vss_39;
    inout vss_4;
    inout vss_40;
    inout vss_41;
    inout vss_42;
    inout vss_43;
    inout vss_44;
    inout vss_45;
    inout vss_46;
    inout vss_47;
    inout vss_48;
    inout vss_49;
    inout vss_5;
    inout vss_50;
    inout vss_51;
    inout vss_52;
    inout vss_53;
    inout vss_54;
    inout vss_55;
    inout vss_56;
    inout vss_57;
    inout vss_6;
    inout vss_7;
    inout vss_8;
    inout vss_9;
    inout \we# ;


    initial
        begin
        end

endmodule
