-- generated by newgenasym Mon Aug 22 17:38:25 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity atf_54143_blkg is
    port (    
	D:         INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	S1:        INOUT  STD_LOGIC;    
	S2:        INOUT  STD_LOGIC);
end atf_54143_blkg;
