// generated by newgenasym  Fri Apr 15 16:51:13 2011


module sbb_2089 (gnd1, gnd2, rf_in, \rf_out/bias );
    inout gnd1;
    inout gnd2;
    inout rf_in;
    inout \rf_out/bias ;


    initial
        begin
        end

endmodule
