-- generated by newgenasym Fri Apr 15 16:51:13 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SBB_2089 is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	RF_IN:     INOUT  STD_LOGIC;    
	\rf_out/bias\: INOUT  STD_LOGIC);
end SBB_2089;
