// generated by newgenasym  Wed Jul 14 09:56:21 2010


module bp4p (gnd1, gnd2, gnd3, port1, port2, port3, port4, sum_port);
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout port1;
    inout port2;
    inout port3;
    inout port4;
    inout sum_port;


    initial
        begin
        end

endmodule
