-- generated by newgenasym Sat Feb 14 14:13:15 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ox3627b is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	VC:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end ox3627b;
