-- generated by newgenasym Mon Jul 11 09:31:44 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds26lv32atmnopb is
    port (    
	EN:        INOUT  STD_LOGIC;    
	\en#\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\ri 1+\:   INOUT  STD_LOGIC;    
	\ri 1-\:   INOUT  STD_LOGIC;    
	\ri 2+\:   INOUT  STD_LOGIC;    
	\ri 2-\:   INOUT  STD_LOGIC;    
	\ri 3+\:   INOUT  STD_LOGIC;    
	\ri 3-\:   INOUT  STD_LOGIC;    
	\ri 4+\:   INOUT  STD_LOGIC;    
	\ri 4-\:   INOUT  STD_LOGIC;    
	\ro 1\:    INOUT  STD_LOGIC;    
	\ro 2\:    INOUT  STD_LOGIC;    
	\ro 3\:    INOUT  STD_LOGIC;    
	\ro 4\:    INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end ds26lv32atmnopb;
