// generated by newgenasym  Thu Feb 02 16:12:49 2012


module con_z_pack_6469169_1 (a1, a10, a2, a3, a4, a5, a6, a7, a8, a9, b1, b10, b2, b3, b4, b5, b6,
        b7, b8, b9, c1, c10, c2, c3, c4, c5, c6, c7, c8, c9, d1, d10, d2, d3,
        d4, d5, d6, d7, d8, d9, gnd);
    inout a1;
    inout a10;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout b1;
    inout b10;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout b9;
    inout c1;
    inout c10;
    inout c2;
    inout c3;
    inout c4;
    inout c5;
    inout c6;
    inout c7;
    inout c8;
    inout c9;
    inout d1;
    inout d10;
    inout d2;
    inout d3;
    inout d4;
    inout d5;
    inout d6;
    inout d7;
    inout d8;
    inout d9;
    inout [20:1] gnd;


    initial
        begin
        end

endmodule
