-- generated by newgenasym Mon Jul 11 19:46:06 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity e112_s_d1_av2_g_e is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1));
end e112_s_d1_av2_g_e;
