-- generated by newgenasym Fri Feb 13 19:10:00 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adt1_1wt is
    port (    
	NOTUSED:   INOUT  STD_LOGIC;    
	PRI:       INOUT  STD_LOGIC;    
	PRI_DOT:   INOUT  STD_LOGIC;    
	SEC:       INOUT  STD_LOGIC;    
	SEC_CT:    INOUT  STD_LOGIC;    
	SEC_DOT:   INOUT  STD_LOGIC);
end adt1_1wt;
