-- generated by newgenasym Fri Sep 30 16:44:05 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity USB_A_F_A90 is
    port (    
	DM:        INOUT  STD_LOGIC;    
	DP:        INOUT  STD_LOGIC;    
	GND01:     INOUT  STD_LOGIC;    
	GND02:     INOUT  STD_LOGIC;    
	GND03:     INOUT  STD_LOGIC;    
	GND04:     INOUT  STD_LOGIC;    
	GND05:     INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end USB_A_F_A90;
