// generated by newgenasym  Wed Apr 29 14:10:07 2009


module sn74ahc1g04drlr (a, gnd, nc, vcc, y);
    inout a;
    inout gnd;
    inout nc;
    inout vcc;
    inout y;


    initial
        begin
        end

endmodule
