-- generated by newgenasym Wed Apr 29 14:10:07 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74ahc1g04drlr is
    port (    
	A:         INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	Y:         INOUT  STD_LOGIC);
end sn74ahc1g04drlr;
