// generated by newgenasym  Thu Apr 16 17:44:48 2009


module ptvc75640_122r88m (\e/d , gnd, \rf-1 , \rf-2 , vc, vs);
    inout \e/d ;
    inout gnd;
    inout \rf-1 ;
    inout \rf-2 ;
    inout vc;
    inout vs;


    initial
        begin
        end

endmodule
