-- generated by newgenasym Thu Apr 16 17:44:48 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ptvc75640_122r88m is
    port (    
	\e/d\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\rf-1\:    INOUT  STD_LOGIC;    
	\rf-2\:    INOUT  STD_LOGIC;    
	VC:        INOUT  STD_LOGIC;    
	VS:        INOUT  STD_LOGIC);
end ptvc75640_122r88m;
