-- generated by newgenasym Mon Apr 27 10:55:11 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ina193aidbvrg4 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\vin+\:    INOUT  STD_LOGIC;    
	\vin-\:    INOUT  STD_LOGIC);
end ina193aidbvrg4;
