-- generated by newgenasym Fri Aug 05 16:17:34 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PESD_BIPOLAR is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end PESD_BIPOLAR;
