-- generated by newgenasym Tue Mar 13 14:24:40 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc1g04dbvr is
    port (    
	A:         INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\n/c\:     INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	Y:         INOUT  STD_LOGIC);
end sn74lvc1g04dbvr;
