-- generated by newgenasym Fri Apr 17 10:36:57 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ics8535agi_21lft is
    port (    
	CLK0:      IN     STD_LOGIC;    
	CLK1:      IN     STD_LOGIC;    
	CLK_EN:    IN     STD_LOGIC;    
	CLK_SEL:   IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	NQ0:       OUT    STD_LOGIC;    
	NQ1:       OUT    STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	VCC1:      IN     STD_LOGIC;    
	VCC2:      IN     STD_LOGIC;    
	VCC3:      IN     STD_LOGIC;    
	VEE1:      IN     STD_LOGIC;    
	VEE2:      IN     STD_LOGIC);
end ics8535agi_21lft;
