-- generated by newgenasym Mon Sep 26 18:10:09 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity wf42022ws06w0x is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end wf42022ws06w0x;
