-- generated by newgenasym Tue Jul 12 15:33:32 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity N_POWER_MOSFET is
    port (    
	D:         INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC);
end N_POWER_MOSFET;
