-- generated by newgenasym Fri Dec 25 10:07:26 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adl5355xcpz is
    port (    
	COMM1:     INOUT  STD_LOGIC;    
	COMM2:     INOUT  STD_LOGIC;    
	IFGM:      INOUT  STD_LOGIC;    
	IFON:      INOUT  STD_LOGIC;    
	IFOP:      INOUT  STD_LOGIC;    
	LEXT:      INOUT  STD_LOGIC;    
	LGM3:      INOUT  STD_LOGIC;    
	LOI1:      INOUT  STD_LOGIC;    
	LOI2:      INOUT  STD_LOGIC;    
	LOSW:      INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	PWDN:      INOUT  STD_LOGIC;    
	RFCT:      INOUT  STD_LOGIC;    
	RFIN:      INOUT  STD_LOGIC;    
	VGS0:      INOUT  STD_LOGIC;    
	VGS1:      INOUT  STD_LOGIC;    
	VLO2:      INOUT  STD_LOGIC;    
	VLO3:      INOUT  STD_LOGIC;    
	VPIF:      INOUT  STD_LOGIC;    
	VPSW:      INOUT  STD_LOGIC);
end adl5355xcpz;
