// generated by newgenasym  Tue Jul 12 18:55:23 2011


module tlv5631ipwr (agnd, avdd, dgnd, din, dout, dvdd, fs, \ldac# , mode, outa, outb,
        outc, outd, oute, outf, outg, outh, \pre# , ref, sclk);
    inout agnd;
    inout avdd;
    inout dgnd;
    inout din;
    inout dout;
    inout dvdd;
    inout fs;
    inout \ldac# ;
    inout mode;
    inout outa;
    inout outb;
    inout outc;
    inout outd;
    inout oute;
    inout outf;
    inout outg;
    inout outh;
    inout \pre# ;
    inout ref;
    inout sclk;


    initial
        begin
        end

endmodule
