-- generated by newgenasym Fri Apr 17 16:00:36 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ics85310ayi_01lft is
    port (    
	CLK0:      IN     STD_LOGIC;    
	CLK1:      IN     STD_LOGIC;    
	CLK_SEL:   IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	NCLK0:     IN     STD_LOGIC;    
	NCLK1:     IN     STD_LOGIC;    
	NQ0:       OUT    STD_LOGIC;    
	NQ1:       OUT    STD_LOGIC;    
	NQ2:       OUT    STD_LOGIC;    
	NQ3:       OUT    STD_LOGIC;    
	NQ4:       OUT    STD_LOGIC;    
	NQ5:       OUT    STD_LOGIC;    
	NQ6:       OUT    STD_LOGIC;    
	NQ7:       OUT    STD_LOGIC;    
	NQ8:       OUT    STD_LOGIC;    
	NQ9:       OUT    STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	Q4:        OUT    STD_LOGIC;    
	Q5:        OUT    STD_LOGIC;    
	Q6:        OUT    STD_LOGIC;    
	Q7:        OUT    STD_LOGIC;    
	Q8:        OUT    STD_LOGIC;    
	Q9:        OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VCCO1:     IN     STD_LOGIC;    
	VCCO2:     IN     STD_LOGIC;    
	VCCO3:     IN     STD_LOGIC;    
	VCCO4:     IN     STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end ics85310ayi_01lft;
