// generated by newgenasym  Fri May 28 10:19:35 2010


module hmc627lp5e (acg1, acg2, acg3, acg4, acg5, acg6, ampin, ampout, clk, d0, d1,
        d2, d3, d4, d5, dat1, dat2, gnd1, gnd2, gnd3, gnd4, gnd5, gnd6,
        gnd7, le, \n/c , \p/s , pad, pup1, pup2, serin, serout, vdd);
    inout acg1;
    inout acg2;
    inout acg3;
    inout acg4;
    inout acg5;
    inout acg6;
    input ampin;
    output ampout;
    inout clk;
    inout d0;
    inout d1;
    inout d2;
    inout d3;
    inout d4;
    inout d5;
    output dat1;
    input dat2;
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    input gnd7;
    inout le;
    input \n/c ;
    inout \p/s ;
    input pad;
    inout pup1;
    inout pup2;
    input serin;
    output serout;
    input vdd;


    initial
        begin
        end

endmodule
