// generated by newgenasym  Tue Jul 19 10:01:53 2011


module at25df321a_sh_b (\cs# , gnd, \hold# , sck, \si/sio , \so/soi , vcc, \wp# );
    inout \cs# ;
    inout gnd;
    inout \hold# ;
    inout sck;
    inout \si/sio ;
    inout \so/soi ;
    inout vcc;
    inout \wp# ;


    initial
        begin
        end

endmodule
