-- generated by newgenasym Wed Apr 22 17:26:09 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity con_dip165_6 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end con_dip165_6;
