-- generated by newgenasym Thu Apr 21 10:57:16 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity DIODE_LED_RGY is
    port (    
	\1+\:      INOUT  STD_LOGIC;    
	\2-\:      INOUT  STD_LOGIC;    
	\3-\:      INOUT  STD_LOGIC);
end DIODE_LED_RGY;
