-- generated by newgenasym Thu Oct 21 14:39:35 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mp2602dq_lf is
    port (    
	\acok#\:   INOUT  STD_LOGIC;    
	BATT:      INOUT  STD_LOGIC;    
	\chg#\:    INOUT  STD_LOGIC;    
	\en#\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	IBF:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	ISET:      INOUT  STD_LOGIC;    
	NTC:       INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	SS:        INOUT  STD_LOGIC);
end mp2602dq_lf;
