-- generated by newgenasym Thu Sep 29 10:14:06 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity con_2135_208msncunt1 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end con_2135_208msncunt1;
