-- generated by newgenasym Mon Feb 16 17:36:53 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dc_208 is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end dc_208;
