// generated by newgenasym  Fri Aug 14 10:54:23 2009


module xc3sd3400a_4fg676i (done, gnd, io_2, io_l01n_0, io_l01n_1_ldc2, io_l01n_2_m0,
        io_l01n_3, io_l01p_0, io_l01p_1_hdc, io_l01p_2_m1,
        io_l01p_3, io_l02n_0, io_l02n_1_ldc0, io_l02n_2_cso_b,
        io_l02n_3, io_l02p_0_vref_0, io_l02p_1_ldc1,
        io_l02p_2_m2, io_l02p_3, io_l03n_1_a1, io_l03n_3,
        io_l03p_1_a0, io_l03p_3, io_l04n_1, io_l04p_1, io_l05n_0,
        io_l05n_1, io_l05n_2, io_l05n_3, io_l05p_0, io_l05p_1,
        io_l05p_2, io_l05p_3, io_l06n_0, io_l06n_1, io_l06n_2,
        io_l06n_3, io_l06p_0, io_l06p_1, io_l06p_2, io_l06p_3,
        io_l07n_0, io_l07n_1_vref_1, io_l07n_2, io_l07n_3,
        io_l07p_0, io_l07p_1, io_l07p_2, io_l07p_3, io_l08n_0,
        io_l08n_1, io_l08n_2, io_l08p_0, io_l08p_1, io_l08p_2,
        io_l09n_0, io_l09n_1, io_l09n_2, io_l09n_3, io_l09p_0,
        io_l09p_1, io_l09p_2, io_l09p_3, io_l10n_0, io_l10n_1,
        io_l10n_2, io_l10n_3, io_l10p_0, io_l10p_1, io_l10p_2,
        io_l10p_3, io_l11n_0, io_l11n_1, io_l11n_2, io_l11n_3,
        io_l11p_0, io_l11p_1, io_l11p_2, io_l11p_3, io_l12n_0,
        io_l12n_1, io_l12n_2, io_l12p_0, io_l12p_1, io_l12p_2,
        io_l13n_0, io_l13n_1, io_l13n_2, io_l13n_3, io_l13p_0,
        io_l13p_1, io_l13p_2, io_l13p_3, io_l14n_0, io_l14n_1,
        io_l14n_2, io_l14n_3, io_l14p_0_vref_0, io_l14p_1,
        io_l14p_2, io_l14p_3, io_l15n_0, io_l15n_1, io_l15n_2,
        io_l15n_3, io_l15p_0, io_l15p_1, io_l15p_2, io_l15p_3,
        io_l16n_0, io_l16n_2, io_l16p_0, io_l16p_2, io_l17n_0,
        io_l17n_1, io_l17n_2_vs2, io_l17n_3, io_l17p_0, io_l17p_1,
        io_l17p_2_rdwr_b, io_l17p_3, io_l18n_0, io_l18n_1,
        io_l18n_2, io_l18n_3, io_l18p_0, io_l18p_1, io_l18p_2,
        io_l18p_3, io_l19n_0, io_l19n_1, io_l19n_2_vs0, io_l19n_3,
        io_l19p_0, io_l19p_1, io_l19p_2_vs1, io_l19p_3,
        io_l20n_0_vref_0, io_l20n_2, io_l20p_0, io_l20p_2,
        io_l21n_0, io_l21n_1, io_l21n_2, io_l21n_3, io_l21p_0,
        io_l21p_1, io_l21p_2, io_l21p_3, io_l22n_0, io_l22n_1,
        io_l22n_2_d6, io_l22n_3, io_l22p_0, io_l22p_1,
        io_l22p_2_d7, io_l22p_3, io_l23n_0, io_l23n_1_vref_1,
        io_l23n_2, io_l23n_3, io_l23p_0, io_l23p_1, io_l23p_2,
        io_l23p_3, io_l24n_0, io_l24n_2_d4, io_l24p_0,
        io_l24p_2_d5, io_l25n_0_gclk5, io_l25n_1_a3,
        io_l25n_2_gclk13, io_l25n_3, io_l25p_0_gclk4,
        io_l25p_1_a2, io_l25p_2_gclk12, io_l25p_3,
        io_l26n_0_gclk7, io_l26n_1_a5, io_l26n_2_gclk15,
        io_l26n_3, io_l26p_0_gclk6, io_l26p_1_a4,
        io_l26p_2_gclk14, io_l26p_3, io_l27n_0_gclk9,
        io_l27n_1_a7, io_l27n_2_gclk1, io_l27n_3,
        io_l27p_0_gclk8, io_l27p_1_a6, io_l27p_2_gclk0,
        io_l27p_3, io_l28n_0_gclk11, io_l28n_2_gclk3, io_l28n_3,
        io_l28p_0_gclk10, io_l28p_2_gclk2, io_l28p_3, io_l29n_0,
        io_l29n_1_a9, io_l29n_2, io_l29n_3_vref_3, io_l29p_0,
        io_l29p_1_a8, io_l29p_2, io_l29p_3, io_l30n_0,
        io_l30n_1_rhclk1, io_l30n_2_mosi_csi_b, io_l30n_3,
        io_l30p_0, io_l30p_1_rhclk0, io_l30p_2, io_l30p_3,
        io_l31n_0, io_l31n_1_trdy1_rhclk3, io_l31n_2, io_l31n_3,
        io_l31p_0, io_l31p_1_rhclk2, io_l31p_2, io_l31p_3,
        io_l32n_0_vref_0, io_l32n_2_dout, io_l32n_3_lhclk1,
        io_l32p_0, io_l32p_2_awake, io_l32p_3_lhclk0, io_l33n_0,
        io_l33n_1_rhclk5, io_l33n_2, io_l33n_3_irdy2_lhclk3,
        io_l33p_0, io_l33p_1_rhclk4, io_l33p_2, io_l33p_3_lhclk2,
        io_l34n_0, io_l34n_1_rhclk7, io_l34n_2_d3,
        io_l34n_3_lhclk5, io_l34p_0, io_l34p_1_irdy1_rhclk6,
        io_l34p_2_init_b, io_l34p_3_lhclk4, io_l35n_0,
        io_l35n_1_a11, io_l35n_2, io_l35n_3_lhclk7, io_l35p_0,
        io_l35p_1_a10, io_l35p_2, io_l35p_3_trdy2_lhclk6,
        io_l36n_0, io_l36n_2_d1, io_l36n_3, io_l36p_0,
        io_l36p_2_d2, io_l36p_3_vref_3, io_l37n_0, io_l37n_1,
        io_l37n_2, io_l37n_3, io_l37p_0, io_l37p_1, io_l37p_2,
        io_l37p_3, io_l38n_0, io_l38n_1_a13, io_l38n_2, io_l38n_3,
        io_l38p_0, io_l38p_1_a12, io_l38p_2, io_l38p_3, io_l39n_0,
        io_l39n_1_a15, io_l39n_2, io_l39n_3, io_l39p_0,
        io_l39p_1_a14, io_l39p_2, io_l39p_3, io_l40n_0, io_l40n_2,
        io_l40n_3, io_l40p_0, io_l40p_2, io_l40p_3, io_l41n_0,
        io_l41n_1, io_l41n_2, io_l41n_3, io_l41p_0, io_l41p_1,
        io_l41p_2, io_l41p_3, io_l42n_0, io_l42n_1_a17, io_l42n_2,
        io_l42n_3, io_l42p_0, io_l42p_1_a16, io_l42p_2, io_l42p_3,
        io_l43n_0, io_l43n_1_a19, io_l43n_2, io_l43n_3, io_l43p_0,
        io_l43p_1_a18, io_l43p_2, io_l43p_3_vref_3, io_l44n_0,
        io_l44n_2, io_l44n_3, io_l44p_0, io_l44p_2, io_l44p_3,
        io_l45n_0, io_l45n_1, io_l45n_2, io_l45n_3, io_l45p_0,
        io_l45p_1, io_l45p_2, io_l45p_3, io_l46n_0, io_l46n_1,
        io_l46n_2, io_l46p_0, io_l46p_1, io_l46p_2, io_l47n_0,
        io_l47n_1, io_l47n_2, io_l47n_3, io_l47p_0, io_l47p_1,
        io_l47p_2, io_l47p_3, io_l48n_0, io_l48n_2, io_l48n_3,
        io_l48p_0, io_l48p_2, io_l48p_3, io_l49n_1, io_l49n_3,
        io_l49p_1, io_l49p_3, io_l50n_1, io_l50p_1, io_l51n_0,
        io_l51n_1, io_l51n_2, io_l51n_3, io_l51p_0, io_l51p_1,
        io_l51p_2, io_l51p_3, io_l52n_0_pudc_b, io_l52n_2_cclk,
        io_l52n_3, io_l52p_0_vref_0, io_l52p_2_d0_din_miso,
        io_l52p_3, io_l53n_1, io_l53n_3, io_l53p_1, io_l53p_3,
        io_l54n_1, io_l54p_1, io_l55n_1, io_l55n_3, io_l55p_1,
        io_l55p_3, io_l56n_1, io_l56n_3, io_l56p_1, io_l56p_3,
        io_l57n_1, io_l57n_3, io_l57p_1, io_l57p_3, io_l58n_1,
        io_l58p_1_vref_1, io_l59n_1, io_l59n_3, io_l59p_1,
        io_l59p_3, io_l60n_1, io_l60n_3, io_l60p_1, io_l60p_3,
        io_l61n_1, io_l61n_3, io_l61p_1, io_l61p_3, io_l62n_1_a21,
        io_l62p_1_a20, io_l63n_1_a23, io_l63n_3, io_l63p_1_a22,
        io_l63p_3, io_l64n_1_a25, io_l64n_3, io_l64p_1_a24,
        io_l64p_3, io_l65n_3, io_l65p_3, ip_0, ip_0_vref_0, ip_1,
        ip_1_vref_1, ip_2, ip_2_vref_2, ip_3, ip_3_vref_3,
        ip_l20n_3_vref_3, ip_l20p_3, ip_l24n_3, ip_l24p_3,
        ip_l28n_1, ip_l28p_1_vref_1, ip_l32n_1, ip_l32p_1,
        ip_l36n_1, ip_l36p_1_vref_1, ip_l40n_1, ip_l40p_1,
        ip_l46n_3, ip_l46p_3, ip_l50n_3_vref_3, ip_l50p_3,
        ip_l66n_3_vref_3, ip_l66p_3, prog_b, suspend, tck, tdi, tdo,
        tms, vccaux, vccint, vcco_0, vcco_1, vcco_2, vcco_3);
    inout done;
    input [100:1] gnd;
    inout io_2;
    inout io_l01n_0;
    inout io_l01n_1_ldc2;
    inout io_l01n_2_m0;
    inout io_l01n_3;
    inout io_l01p_0;
    inout io_l01p_1_hdc;
    inout io_l01p_2_m1;
    inout io_l01p_3;
    inout io_l02n_0;
    inout io_l02n_1_ldc0;
    inout io_l02n_2_cso_b;
    inout io_l02n_3;
    inout io_l02p_0_vref_0;
    inout io_l02p_1_ldc1;
    inout io_l02p_2_m2;
    inout io_l02p_3;
    inout io_l03n_1_a1;
    inout io_l03n_3;
    inout io_l03p_1_a0;
    inout io_l03p_3;
    inout io_l04n_1;
    inout io_l04p_1;
    inout io_l05n_0;
    inout io_l05n_1;
    inout io_l05n_2;
    inout io_l05n_3;
    inout io_l05p_0;
    inout io_l05p_1;
    inout io_l05p_2;
    inout io_l05p_3;
    inout io_l06n_0;
    inout io_l06n_1;
    inout io_l06n_2;
    inout io_l06n_3;
    inout io_l06p_0;
    inout io_l06p_1;
    inout io_l06p_2;
    inout io_l06p_3;
    inout io_l07n_0;
    inout io_l07n_1_vref_1;
    inout io_l07n_2;
    inout io_l07n_3;
    inout io_l07p_0;
    inout io_l07p_1;
    inout io_l07p_2;
    inout io_l07p_3;
    inout io_l08n_0;
    inout io_l08n_1;
    inout io_l08n_2;
    inout io_l08p_0;
    inout io_l08p_1;
    inout io_l08p_2;
    inout io_l09n_0;
    inout io_l09n_1;
    inout io_l09n_2;
    inout io_l09n_3;
    inout io_l09p_0;
    inout io_l09p_1;
    inout io_l09p_2;
    inout io_l09p_3;
    inout io_l10n_0;
    inout io_l10n_1;
    inout io_l10n_2;
    inout io_l10n_3;
    inout io_l10p_0;
    inout io_l10p_1;
    inout io_l10p_2;
    inout io_l10p_3;
    inout io_l11n_0;
    inout io_l11n_1;
    inout io_l11n_2;
    inout io_l11n_3;
    inout io_l11p_0;
    inout io_l11p_1;
    inout io_l11p_2;
    inout io_l11p_3;
    inout io_l12n_0;
    inout io_l12n_1;
    inout io_l12n_2;
    inout io_l12p_0;
    inout io_l12p_1;
    inout io_l12p_2;
    inout io_l13n_0;
    inout io_l13n_1;
    inout io_l13n_2;
    inout io_l13n_3;
    inout io_l13p_0;
    inout io_l13p_1;
    inout io_l13p_2;
    inout io_l13p_3;
    inout io_l14n_0;
    inout io_l14n_1;
    inout io_l14n_2;
    inout io_l14n_3;
    inout io_l14p_0_vref_0;
    inout io_l14p_1;
    inout io_l14p_2;
    inout io_l14p_3;
    inout io_l15n_0;
    inout io_l15n_1;
    inout io_l15n_2;
    inout io_l15n_3;
    inout io_l15p_0;
    inout io_l15p_1;
    inout io_l15p_2;
    inout io_l15p_3;
    inout io_l16n_0;
    inout io_l16n_2;
    inout io_l16p_0;
    inout io_l16p_2;
    inout io_l17n_0;
    inout io_l17n_1;
    inout io_l17n_2_vs2;
    inout io_l17n_3;
    inout io_l17p_0;
    inout io_l17p_1;
    inout io_l17p_2_rdwr_b;
    inout io_l17p_3;
    inout io_l18n_0;
    inout io_l18n_1;
    inout io_l18n_2;
    inout io_l18n_3;
    inout io_l18p_0;
    inout io_l18p_1;
    inout io_l18p_2;
    inout io_l18p_3;
    inout io_l19n_0;
    inout io_l19n_1;
    inout io_l19n_2_vs0;
    inout io_l19n_3;
    inout io_l19p_0;
    inout io_l19p_1;
    inout io_l19p_2_vs1;
    inout io_l19p_3;
    inout io_l20n_0_vref_0;
    inout io_l20n_2;
    inout io_l20p_0;
    inout io_l20p_2;
    inout io_l21n_0;
    inout io_l21n_1;
    inout io_l21n_2;
    inout io_l21n_3;
    inout io_l21p_0;
    inout io_l21p_1;
    inout io_l21p_2;
    inout io_l21p_3;
    inout io_l22n_0;
    inout io_l22n_1;
    inout io_l22n_2_d6;
    inout io_l22n_3;
    inout io_l22p_0;
    inout io_l22p_1;
    inout io_l22p_2_d7;
    inout io_l22p_3;
    inout io_l23n_0;
    inout io_l23n_1_vref_1;
    inout io_l23n_2;
    inout io_l23n_3;
    inout io_l23p_0;
    inout io_l23p_1;
    inout io_l23p_2;
    inout io_l23p_3;
    inout io_l24n_0;
    inout io_l24n_2_d4;
    inout io_l24p_0;
    inout io_l24p_2_d5;
    inout io_l25n_0_gclk5;
    inout io_l25n_1_a3;
    inout io_l25n_2_gclk13;
    inout io_l25n_3;
    inout io_l25p_0_gclk4;
    inout io_l25p_1_a2;
    inout io_l25p_2_gclk12;
    inout io_l25p_3;
    inout io_l26n_0_gclk7;
    inout io_l26n_1_a5;
    inout io_l26n_2_gclk15;
    inout io_l26n_3;
    inout io_l26p_0_gclk6;
    inout io_l26p_1_a4;
    inout io_l26p_2_gclk14;
    inout io_l26p_3;
    inout io_l27n_0_gclk9;
    inout io_l27n_1_a7;
    inout io_l27n_2_gclk1;
    inout io_l27n_3;
    inout io_l27p_0_gclk8;
    inout io_l27p_1_a6;
    inout io_l27p_2_gclk0;
    inout io_l27p_3;
    inout io_l28n_0_gclk11;
    inout io_l28n_2_gclk3;
    inout io_l28n_3;
    inout io_l28p_0_gclk10;
    inout io_l28p_2_gclk2;
    inout io_l28p_3;
    inout io_l29n_0;
    inout io_l29n_1_a9;
    inout io_l29n_2;
    inout io_l29n_3_vref_3;
    inout io_l29p_0;
    inout io_l29p_1_a8;
    inout io_l29p_2;
    inout io_l29p_3;
    inout io_l30n_0;
    inout io_l30n_1_rhclk1;
    inout io_l30n_2_mosi_csi_b;
    inout io_l30n_3;
    inout io_l30p_0;
    inout io_l30p_1_rhclk0;
    inout io_l30p_2;
    inout io_l30p_3;
    inout io_l31n_0;
    inout io_l31n_1_trdy1_rhclk3;
    inout io_l31n_2;
    inout io_l31n_3;
    inout io_l31p_0;
    inout io_l31p_1_rhclk2;
    inout io_l31p_2;
    inout io_l31p_3;
    inout io_l32n_0_vref_0;
    inout io_l32n_2_dout;
    inout io_l32n_3_lhclk1;
    inout io_l32p_0;
    inout io_l32p_2_awake;
    inout io_l32p_3_lhclk0;
    inout io_l33n_0;
    inout io_l33n_1_rhclk5;
    inout io_l33n_2;
    inout io_l33n_3_irdy2_lhclk3;
    inout io_l33p_0;
    inout io_l33p_1_rhclk4;
    inout io_l33p_2;
    inout io_l33p_3_lhclk2;
    inout io_l34n_0;
    inout io_l34n_1_rhclk7;
    inout io_l34n_2_d3;
    inout io_l34n_3_lhclk5;
    inout io_l34p_0;
    inout io_l34p_1_irdy1_rhclk6;
    inout io_l34p_2_init_b;
    inout io_l34p_3_lhclk4;
    inout io_l35n_0;
    inout io_l35n_1_a11;
    inout io_l35n_2;
    inout io_l35n_3_lhclk7;
    inout io_l35p_0;
    inout io_l35p_1_a10;
    inout io_l35p_2;
    inout io_l35p_3_trdy2_lhclk6;
    inout io_l36n_0;
    inout io_l36n_2_d1;
    inout io_l36n_3;
    inout io_l36p_0;
    inout io_l36p_2_d2;
    inout io_l36p_3_vref_3;
    inout io_l37n_0;
    inout io_l37n_1;
    inout io_l37n_2;
    inout io_l37n_3;
    inout io_l37p_0;
    inout io_l37p_1;
    inout io_l37p_2;
    inout io_l37p_3;
    inout io_l38n_0;
    inout io_l38n_1_a13;
    inout io_l38n_2;
    inout io_l38n_3;
    inout io_l38p_0;
    inout io_l38p_1_a12;
    inout io_l38p_2;
    inout io_l38p_3;
    inout io_l39n_0;
    inout io_l39n_1_a15;
    inout io_l39n_2;
    inout io_l39n_3;
    inout io_l39p_0;
    inout io_l39p_1_a14;
    inout io_l39p_2;
    inout io_l39p_3;
    inout io_l40n_0;
    inout io_l40n_2;
    inout io_l40n_3;
    inout io_l40p_0;
    inout io_l40p_2;
    inout io_l40p_3;
    inout io_l41n_0;
    inout io_l41n_1;
    inout io_l41n_2;
    inout io_l41n_3;
    inout io_l41p_0;
    inout io_l41p_1;
    inout io_l41p_2;
    inout io_l41p_3;
    inout io_l42n_0;
    inout io_l42n_1_a17;
    inout io_l42n_2;
    inout io_l42n_3;
    inout io_l42p_0;
    inout io_l42p_1_a16;
    inout io_l42p_2;
    inout io_l42p_3;
    inout io_l43n_0;
    inout io_l43n_1_a19;
    inout io_l43n_2;
    inout io_l43n_3;
    inout io_l43p_0;
    inout io_l43p_1_a18;
    inout io_l43p_2;
    inout io_l43p_3_vref_3;
    inout io_l44n_0;
    inout io_l44n_2;
    inout io_l44n_3;
    inout io_l44p_0;
    inout io_l44p_2;
    inout io_l44p_3;
    inout io_l45n_0;
    inout io_l45n_1;
    inout io_l45n_2;
    inout io_l45n_3;
    inout io_l45p_0;
    inout io_l45p_1;
    inout io_l45p_2;
    inout io_l45p_3;
    inout io_l46n_0;
    inout io_l46n_1;
    inout io_l46n_2;
    inout io_l46p_0;
    inout io_l46p_1;
    inout io_l46p_2;
    inout io_l47n_0;
    inout io_l47n_1;
    inout io_l47n_2;
    inout io_l47n_3;
    inout io_l47p_0;
    inout io_l47p_1;
    inout io_l47p_2;
    inout io_l47p_3;
    inout io_l48n_0;
    inout io_l48n_2;
    inout io_l48n_3;
    inout io_l48p_0;
    inout io_l48p_2;
    inout io_l48p_3;
    inout io_l49n_1;
    inout io_l49n_3;
    inout io_l49p_1;
    inout io_l49p_3;
    inout io_l50n_1;
    inout io_l50p_1;
    inout io_l51n_0;
    inout io_l51n_1;
    inout io_l51n_2;
    inout io_l51n_3;
    inout io_l51p_0;
    inout io_l51p_1;
    inout io_l51p_2;
    inout io_l51p_3;
    inout io_l52n_0_pudc_b;
    inout io_l52n_2_cclk;
    inout io_l52n_3;
    inout io_l52p_0_vref_0;
    inout io_l52p_2_d0_din_miso;
    inout io_l52p_3;
    inout io_l53n_1;
    inout io_l53n_3;
    inout io_l53p_1;
    inout io_l53p_3;
    inout io_l54n_1;
    inout io_l54p_1;
    inout io_l55n_1;
    inout io_l55n_3;
    inout io_l55p_1;
    inout io_l55p_3;
    inout io_l56n_1;
    inout io_l56n_3;
    inout io_l56p_1;
    inout io_l56p_3;
    inout io_l57n_1;
    inout io_l57n_3;
    inout io_l57p_1;
    inout io_l57p_3;
    inout io_l58n_1;
    inout io_l58p_1_vref_1;
    inout io_l59n_1;
    inout io_l59n_3;
    inout io_l59p_1;
    inout io_l59p_3;
    inout io_l60n_1;
    inout io_l60n_3;
    inout io_l60p_1;
    inout io_l60p_3;
    inout io_l61n_1;
    inout io_l61n_3;
    inout io_l61p_1;
    inout io_l61p_3;
    inout io_l62n_1_a21;
    inout io_l62p_1_a20;
    inout io_l63n_1_a23;
    inout io_l63n_3;
    inout io_l63p_1_a22;
    inout io_l63p_3;
    inout io_l64n_1_a25;
    inout io_l64n_3;
    inout io_l64p_1_a24;
    inout io_l64p_3;
    inout io_l65n_3;
    inout io_l65p_3;
    input [11:1] ip_0;
    input [4:1] ip_0_vref_0;
    input [2:1] ip_1;
    input [5:1] ip_1_vref_1;
    input [6:1] ip_2;
    input [9:1] ip_2_vref_2;
    input [2:1] ip_3;
    input [3:1] ip_3_vref_3;
    inout ip_l20n_3_vref_3;
    inout ip_l20p_3;
    inout ip_l24n_3;
    input ip_l24p_3;
    input ip_l28n_1;
    input ip_l28p_1_vref_1;
    input ip_l32n_1;
    input ip_l32p_1;
    input ip_l36n_1;
    input ip_l36p_1_vref_1;
    input ip_l40n_1;
    input ip_l40p_1;
    input ip_l46n_3;
    inout ip_l46p_3;
    input ip_l50n_3_vref_3;
    input ip_l50p_3;
    input ip_l66n_3_vref_3;
    input ip_l66p_3;
    inout prog_b;
    inout suspend;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    input [24:1] vccaux;
    input [36:1] vccint;
    input [10:1] vcco_0;
    input [10:1] vcco_1;
    input [10:1] vcco_2;
    input [10:1] vcco_3;


    initial
        begin
        end

endmodule
