// generated by newgenasym  Fri May 15 14:58:07 2009


module lp5900sdx (gnd1, gnd2, nc1, nc2, ven, vin, vout);
    input gnd1;
    input gnd2;
    inout nc1;
    inout nc2;
    input ven;
    input vin;
    output vout;


    initial
        begin
        end

endmodule
