-- generated by newgenasym Fri May 15 14:58:07 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lp5900sdx is
    port (    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	VEN:       IN     STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC);
end lp5900sdx;
