// generated by newgenasym  Thu Apr 23 11:47:44 2009


module xo75_nagtc (gnd, \nc/tris , out, vcc);
    input gnd;
    inout \nc/tris ;
    output out;
    input vcc;


    initial
        begin
        end

endmodule
