-- generated by newgenasym Thu Apr 23 11:47:44 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xo75_nagtc is
    port (    
	GND:       IN     STD_LOGIC;    
	\nc/tris\: INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end xo75_nagtc;
