// generated by newgenasym  Wed Feb 24 10:22:40 2010


module tps40055 (boost, bp10, bp5, comp, hdrv, ilim, kff, ldrv, pad, pgnd, rt,
        sgnd, \ss/sd , sw, sync, vfb, vin);
    output boost;
    output bp10;
    output bp5;
    output comp;
    output hdrv;
    input ilim;
    input kff;
    output ldrv;
    input pad;
    input pgnd;
    input rt;
    input sgnd;
    input \ss/sd ;
    input sw;
    input sync;
    input vfb;
    input vin;


    initial
        begin
        end

endmodule
