// generated by newgenasym  Thu Sep 10 10:37:00 2009


module con_ci2210p1vk0_lf (\1 , \10 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    inout \1 ;
    inout \10 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;


    initial
        begin
        end

endmodule
