-- generated by newgenasym Fri Feb 10 17:22:28 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds_02_v is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end ds_02_v;
