-- generated by newgenasym Fri Feb 13 14:33:15 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity diode_led is
    port (    
	ANODE:     INOUT  STD_LOGIC;    
	CATHODE:   INOUT  STD_LOGIC);
end diode_led;
