-- generated by newgenasym Tue Jul 13 10:41:13 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity DIODE_LED_D is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end DIODE_LED_D;
