// generated by newgenasym  Tue Jul 12 17:20:47 2011


module mcp79410_isn (mfp, scl, sda, vbat, vcc, vss, x1, x2);
    inout mfp;
    inout scl;
    inout sda;
    inout vbat;
    inout vcc;
    inout vss;
    inout x1;
    inout x2;


    initial
        begin
        end

endmodule
