-- generated by newgenasym Thu Oct 28 10:38:44 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity EHHD075A0A41_HZ is
    port (    
	\on/off\:  INOUT  STD_LOGIC;    
	\sense+\:  INOUT  STD_LOGIC;    
	\sense-\:  INOUT  STD_LOGIC;    
	TRIM:      INOUT  STD_LOGIC;    
	\vi+\:     INOUT  STD_LOGIC;    
	\vi-\:     INOUT  STD_LOGIC;    
	\vo+\:     INOUT  STD_LOGIC;    
	\vo-\:     INOUT  STD_LOGIC);
end EHHD075A0A41_HZ;
