// generated by newgenasym  Mon Jun 27 11:23:24 2011


module qmga_0020 (gnd1, gnd2, rf_in, rf_out);
    inout gnd1;
    inout gnd2;
    inout rf_in;
    inout rf_out;


    initial
        begin
        end

endmodule
