// generated by newgenasym  Thu Oct 21 11:21:36 2010


module hmc472lp4e (acg1, acg2, acg3, acg4, acg5, acg6, acg7, nc1, nc2, nc3, nc4,
        nc5, nc6, nc7, nc8, pad, rf1, rf2, v1, v2, v3, v4, v5, v6, vdd);
    inout acg1;
    inout acg2;
    inout acg3;
    inout acg4;
    inout acg5;
    inout acg6;
    inout acg7;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout nc7;
    inout nc8;
    inout pad;
    inout rf1;
    inout rf2;
    inout v1;
    inout v2;
    inout v3;
    inout v4;
    inout v5;
    inout v6;
    inout vdd;


    initial
        begin
        end

endmodule
