-- generated by newgenasym Thu Aug 20 17:03:54 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity con_51740 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\10\:      INOUT  STD_LOGIC;    
	\11\:      INOUT  STD_LOGIC;    
	\12\:      INOUT  STD_LOGIC;    
	\13\:      INOUT  STD_LOGIC;    
	\14\:      INOUT  STD_LOGIC;    
	\15\:      INOUT  STD_LOGIC;    
	\16\:      INOUT  STD_LOGIC;    
	\17\:      INOUT  STD_LOGIC;    
	\18\:      INOUT  STD_LOGIC;    
	\19\:      INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\20\:      INOUT  STD_LOGIC;    
	\21\:      INOUT  STD_LOGIC;    
	\22\:      INOUT  STD_LOGIC;    
	\23\:      INOUT  STD_LOGIC;    
	\24\:      INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	\9\:       INOUT  STD_LOGIC;    
	P1_1:      INOUT  STD_LOGIC;    
	P1_2:      INOUT  STD_LOGIC;    
	P1_3:      INOUT  STD_LOGIC;    
	P1_4:      INOUT  STD_LOGIC;    
	P1_5:      INOUT  STD_LOGIC;    
	P1_6:      INOUT  STD_LOGIC;    
	P1_7:      INOUT  STD_LOGIC;    
	P1_8:      INOUT  STD_LOGIC;    
	P2_1:      INOUT  STD_LOGIC;    
	P2_2:      INOUT  STD_LOGIC;    
	P2_3:      INOUT  STD_LOGIC;    
	P2_4:      INOUT  STD_LOGIC;    
	P2_5:      INOUT  STD_LOGIC;    
	P2_6:      INOUT  STD_LOGIC;    
	P2_7:      INOUT  STD_LOGIC;    
	P2_8:      INOUT  STD_LOGIC);
end con_51740;
