// generated by newgenasym  Thu Feb 12 15:27:37 2009


module sp3223eea (\c1+ , \c1- , \c2+ , \c2- , \en# , gnd, \online# , r1in, r1out, r2in,
        r2out, \shutdw# , \status# , t1in, t1out, t2in, t2out, \v+ , \v- , vcc);
    inout \c1+ ;
    inout \c1- ;
    inout \c2+ ;
    inout \c2- ;
    inout \en# ;
    input gnd;
    inout \online# ;
    input r1in;
    output r1out;
    input r2in;
    output r2out;
    inout \shutdw# ;
    inout \status# ;
    input t1in;
    output t1out;
    input t2in;
    output t2out;
    inout \v+ ;
    inout \v- ;
    input vcc;


    initial
        begin
        end

endmodule
