-- generated by newgenasym Thu Feb 12 15:27:37 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sp3223eea is
    port (    
	\c1+\:     INOUT  STD_LOGIC;    
	\c1-\:     INOUT  STD_LOGIC;    
	\c2+\:     INOUT  STD_LOGIC;    
	\c2-\:     INOUT  STD_LOGIC;    
	\en#\:     INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\online#\: INOUT  STD_LOGIC;    
	R1IN:      IN     STD_LOGIC;    
	R1OUT:     OUT    STD_LOGIC;    
	R2IN:      IN     STD_LOGIC;    
	R2OUT:     OUT    STD_LOGIC;    
	\shutdw#\: INOUT  STD_LOGIC;    
	\status#\: INOUT  STD_LOGIC;    
	T1IN:      IN     STD_LOGIC;    
	T1OUT:     OUT    STD_LOGIC;    
	T2IN:      IN     STD_LOGIC;    
	T2OUT:     OUT    STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end sp3223eea;
