-- generated by newgenasym Tue May 19 11:21:44 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mic29302wu is
    port (    
	ADJUST:    INOUT  STD_LOGIC;    
	ENABLE:    INOUT  STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	INPUT:     IN     STD_LOGIC;    
	OUTPUT:    OUT    STD_LOGIC);
end mic29302wu;
