// generated by newgenasym  Thu Feb 12 15:38:58 2009


module trf370333irge (gnd_0, gnd_1, gnd_2, gnd_3, gnd_4, gnd_5, gnd_6, gnd_7,
        gnd_8, gnd_9, in, ip, lon, lop, nc1, nc2, nc3, nc4, nc5, pp, qn,
        qp, rfout, vcc1, vcc2);
    input gnd_0;
    input gnd_1;
    input gnd_2;
    input gnd_3;
    input gnd_4;
    input gnd_5;
    input gnd_6;
    input gnd_7;
    input gnd_8;
    input gnd_9;
    input in;
    input ip;
    input lon;
    input lop;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    input pp;
    input qn;
    input qp;
    output rfout;
    input vcc1;
    input vcc2;


    initial
        begin
        end

endmodule
