-- generated by newgenasym Thu Feb 12 15:38:58 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity trf370333irge is
    port (    
	GND_0:     IN     STD_LOGIC;    
	GND_1:     IN     STD_LOGIC;    
	GND_2:     IN     STD_LOGIC;    
	GND_3:     IN     STD_LOGIC;    
	GND_4:     IN     STD_LOGIC;    
	GND_5:     IN     STD_LOGIC;    
	GND_6:     IN     STD_LOGIC;    
	GND_7:     IN     STD_LOGIC;    
	GND_8:     IN     STD_LOGIC;    
	GND_9:     IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	IP:        IN     STD_LOGIC;    
	LON:       IN     STD_LOGIC;    
	LOP:       IN     STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NC5:       INOUT  STD_LOGIC;    
	PP:        IN     STD_LOGIC;    
	QN:        IN     STD_LOGIC;    
	QP:        IN     STD_LOGIC;    
	RFOUT:     OUT    STD_LOGIC;    
	VCC1:      IN     STD_LOGIC;    
	VCC2:      IN     STD_LOGIC);
end trf370333irge;
