-- generated by newgenasym Thu Jul 15 11:17:22 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity con_9002_c06c10pu is
    port (    
	C1:        INOUT  STD_LOGIC;    
	C2:        INOUT  STD_LOGIC;    
	C3:        INOUT  STD_LOGIC;    
	C5:        INOUT  STD_LOGIC;    
	C6:        INOUT  STD_LOGIC;    
	C7:        INOUT  STD_LOGIC);
end con_9002_c06c10pu;
