-- generated by newgenasym Mon May 23 14:20:27 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity P_POWER_MOSFET_1G2S3D is
    port (    
	D:         INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC);
end P_POWER_MOSFET_1G2S3D;
