// generated by newgenasym  Tue Jul 12 19:54:40 2011


module con_5747832_6 (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 , gnd);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;
    inout [2:1] gnd;


    initial
        begin
        end

endmodule
