-- generated by newgenasym Mon May 18 19:20:02 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CX2047LNL is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end CX2047LNL;
