-- generated by newgenasym Fri Sep 11 10:04:15 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc687lp4 is
    port (    
	G_BIAS:    INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	IFN:       INOUT  STD_LOGIC;    
	IFP:       INOUT  STD_LOGIC;    
	LO:        INOUT  STD_LOGIC;    
	LO_BIAS:   INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC10:      INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NC5:       INOUT  STD_LOGIC;    
	NC6:       INOUT  STD_LOGIC;    
	NC7:       INOUT  STD_LOGIC;    
	NC8:       INOUT  STD_LOGIC;    
	NC9:       INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	RF:        INOUT  STD_LOGIC;    
	TAP:       INOUT  STD_LOGIC;    
	VCC1:      INOUT  STD_LOGIC;    
	VCC2:      INOUT  STD_LOGIC;    
	VCC3:      INOUT  STD_LOGIC);
end hmc687lp4;
