-- generated by newgenasym Tue Aug 16 16:28:12 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pesd_smda12c_8 is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	IO1:       INOUT  STD_LOGIC;    
	IO2:       INOUT  STD_LOGIC;    
	IO3:       INOUT  STD_LOGIC;    
	IO4:       INOUT  STD_LOGIC;    
	IO5:       INOUT  STD_LOGIC;    
	IO6:       INOUT  STD_LOGIC;    
	IO7:       INOUT  STD_LOGIC;    
	IO8:       INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC);
end pesd_smda12c_8;
