-- generated by newgenasym Mon Jul 12 16:05:04 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity con_dmp3_3w3p_193 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end con_dmp3_3w3p_193;
