-- generated by newgenasym Fri Apr 24 14:31:56 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8353acpz is
    port (    
	\com1-1\:  INOUT  STD_LOGIC;    
	\com1-2\:  INOUT  STD_LOGIC;    
	\com2-1\:  INOUT  STD_LOGIC;    
	\com2-2\:  INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	RFIN:      IN     STD_LOGIC;    
	RFOUT:     OUT    STD_LOGIC;    
	VPOS:      IN     STD_LOGIC);
end ad8353acpz;
