-- generated by newgenasym Tue Jul 12 16:51:18 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tl082bcd is
    port (    
	\1in+\:    INOUT  STD_LOGIC;    
	\1in-\:    INOUT  STD_LOGIC;    
	\1out\:    INOUT  STD_LOGIC;    
	\2in+\:    INOUT  STD_LOGIC;    
	\2in-\:    INOUT  STD_LOGIC;    
	\2out\:    INOUT  STD_LOGIC;    
	\vcc+\:    INOUT  STD_LOGIC;    
	\vcc-\:    INOUT  STD_LOGIC);
end tl082bcd;
