// generated by newgenasym  Wed Sep 15 14:07:24 2010


module ics8535bgi_01lft (clk0, clk1, clk_en, clk_sel, nc1, nc2, nc3, nc4, nq0, nq1, nq2,
        nq3, q0, q1, q2, q3, vcc1, vcc2, vcc3, vee1);
    input clk0;
    input clk1;
    input clk_en;
    input clk_sel;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    output nq0;
    output nq1;
    output nq2;
    output nq3;
    output q0;
    output q1;
    output q2;
    output q3;
    input vcc1;
    input vcc2;
    input vcc3;
    input vee1;


    initial
        begin
        end

endmodule
