-- generated by newgenasym Wed Sep 15 14:07:24 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ics8535bgi_01lft is
    port (    
	CLK0:      IN     STD_LOGIC;    
	CLK1:      IN     STD_LOGIC;    
	CLK_EN:    IN     STD_LOGIC;    
	CLK_SEL:   IN     STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NQ0:       OUT    STD_LOGIC;    
	NQ1:       OUT    STD_LOGIC;    
	NQ2:       OUT    STD_LOGIC;    
	NQ3:       OUT    STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	VCC1:      IN     STD_LOGIC;    
	VCC2:      IN     STD_LOGIC;    
	VCC3:      IN     STD_LOGIC;    
	VEE1:      IN     STD_LOGIC);
end ics8535bgi_01lft;
