-- generated by newgenasym Thu Feb 19 14:28:05 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ts3193us10 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end ts3193us10;
