-- generated by newgenasym Fri Sep 04 17:32:02 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sma is
    port (    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC);
end sma;
