-- generated by newgenasym Mon Apr 23 10:45:41 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity saw_3x3 is
    port (    
	G1:        INOUT  STD_LOGIC;    
	G2:        INOUT  STD_LOGIC;    
	G3:        INOUT  STD_LOGIC;    
	G4:        INOUT  STD_LOGIC;    
	I:         INOUT  STD_LOGIC;    
	O:         INOUT  STD_LOGIC);
end saw_3x3;
