// generated by newgenasym  Thu Aug 13 17:57:26 2009


module xc4vsx35_10ffg668i (avdd_sm, avss_sm, cclk_0, cs_b_0, d_in_0, done_0,
        dout_busy_0, gnd, hswapen_0, init_0, io_l10n_10, io_l10n_5,
        io_l10n_6, io_l10n_7, io_l10n_8, io_l10n_9, io_l10p_10,
        io_l10p_5, io_l10p_6, io_l10p_7, io_l10p_8, io_l10p_9,
        io_l11n_10, io_l11n_5, io_l11n_6, io_l11n_7, io_l11n_8,
        io_l11n_9, io_l11p_10, io_l11p_5, io_l11p_6, io_l11p_7,
        io_l11p_8, io_l11p_9, io_l12n_vref_10, io_l12n_vref_5,
        io_l12n_vref_6, io_l12n_vref_7, io_l12n_vref_8,
        io_l12n_vref_9, io_l12p_10, io_l12p_5, io_l12p_6,
        io_l12p_7, io_l12p_8, io_l12p_9, io_l13n_10, io_l13n_5,
        io_l13n_6, io_l13n_7, io_l13n_8, io_l13n_9, io_l13p_10,
        io_l13p_5, io_l13p_6, io_l13p_7, io_l13p_8, io_l13p_9,
        io_l14n_10, io_l14n_5, io_l14n_6, io_l14n_7, io_l14n_8,
        io_l14n_9, io_l14p_10, io_l14p_5, io_l14p_6, io_l14p_7,
        io_l14p_8, io_l14p_9, io_l15n_10, io_l15n_5, io_l15n_6,
        io_l15n_7, io_l15n_8, io_l15n_9, io_l15p_10, io_l15p_5,
        io_l15p_6, io_l15p_7, io_l15p_8, io_l15p_9, io_l16n_10,
        io_l16n_5, io_l16n_6, io_l16n_7, io_l16n_8, io_l16n_9,
        io_l16p_10, io_l16p_5, io_l16p_6, io_l16p_7, io_l16p_8,
        io_l16p_9, io_l17n_10, io_l17n_5, io_l17n_6, io_l17n_7,
        io_l17n_8, io_l17n_9, io_l17p_10, io_l17p_5, io_l17p_6,
        io_l17p_7, io_l17p_8, io_l17p_9, io_l18n_10, io_l18n_5,
        io_l18n_6, io_l18n_7, io_l18n_8, io_l18n_9, io_l18p_10,
        io_l18p_5, io_l18p_6, io_l18p_7, io_l18p_8, io_l18p_9,
        io_l19n_10, io_l19n_5, io_l19n_6, io_l19n_7, io_l19n_8,
        io_l19n_9, io_l19p_10, io_l19p_5, io_l19p_6, io_l19p_7,
        io_l19p_8, io_l19p_9, io_l1n_10, io_l1n_5, io_l1n_6,
        io_l1n_7, io_l1n_8, io_l1n_9, io_l1n_d14_cc_lc_2,
        io_l1n_d30_lc_1, io_l1n_gc_cc_lc_3, io_l1n_gc_lc_4,
        io_l1p_10, io_l1p_5, io_l1p_6, io_l1p_7, io_l1p_8,
        io_l1p_9, io_l1p_d15_cc_lc_2, io_l1p_d31_lc_1,
        io_l1p_gc_cc_lc_3, io_l1p_gc_lc_4, io_l20n_vref_10,
        io_l20n_vref_5, io_l20n_vref_6, io_l20n_vref_7,
        io_l20n_vref_8, io_l20n_vref_9, io_l20p_10, io_l20p_5,
        io_l20p_6, io_l20p_7, io_l20p_8, io_l20p_9, io_l21n_10,
        io_l21n_5, io_l21n_6, io_l21n_7, io_l21n_8, io_l21n_9,
        io_l21p_10, io_l21p_5, io_l21p_6, io_l21p_7, io_l21p_8,
        io_l21p_9, io_l22n_10, io_l22n_5, io_l22n_6, io_l22n_7,
        io_l22n_8, io_l22n_9, io_l22p_10, io_l22p_5, io_l22p_6,
        io_l22p_7, io_l22p_8, io_l22p_9, io_l23n_vrp_10,
        io_l23n_vrp_5, io_l23n_vrp_6, io_l23n_vrp_7,
        io_l23n_vrp_8, io_l23n_vrp_9, io_l23p_vrn_10,
        io_l23p_vrn_5, io_l23p_vrn_6, io_l23p_vrn_7,
        io_l23p_vrn_8, io_l23p_vrn_9, io_l24n_cc_lc_10,
        io_l24n_cc_lc_5, io_l24n_cc_lc_6, io_l24n_cc_lc_7,
        io_l24n_cc_lc_8, io_l24n_cc_lc_9, io_l24p_cc_lc_10,
        io_l24p_cc_lc_5, io_l24p_cc_lc_6, io_l24p_cc_lc_7,
        io_l24p_cc_lc_8, io_l24p_cc_lc_9, io_l25n_cc_lc_10,
        io_l25n_cc_lc_5, io_l25n_cc_lc_6, io_l25n_cc_lc_8,
        io_l25n_cc_lc_9, io_l25n_cc_sm7_lc_7, io_l25p_cc_lc_10,
        io_l25p_cc_lc_5, io_l25p_cc_lc_6, io_l25p_cc_lc_8,
        io_l25p_cc_lc_9, io_l25p_cc_sm7_lc_7, io_l26n_10,
        io_l26n_5, io_l26n_6, io_l26n_8, io_l26n_9, io_l26n_sm6_7,
        io_l26p_10, io_l26p_5, io_l26p_6, io_l26p_8, io_l26p_9,
        io_l26p_sm6_7, io_l27n_10, io_l27n_5, io_l27n_6,
        io_l27n_8, io_l27n_9, io_l27n_sm5_7, io_l27p_10,
        io_l27p_5, io_l27p_6, io_l27p_8, io_l27p_9, io_l27p_sm5_7,
        io_l28n_vref_10, io_l28n_vref_5, io_l28n_vref_6,
        io_l28n_vref_7, io_l28n_vref_8, io_l28n_vref_9,
        io_l28p_10, io_l28p_5, io_l28p_6, io_l28p_7, io_l28p_8,
        io_l28p_9, io_l29n_10, io_l29n_5, io_l29n_6, io_l29n_8,
        io_l29n_9, io_l29n_sm4_7, io_l29p_10, io_l29p_5,
        io_l29p_6, io_l29p_8, io_l29p_9, io_l29p_sm4_7, io_l2n_10,
        io_l2n_5, io_l2n_6, io_l2n_7, io_l2n_8, io_l2n_9,
        io_l2n_d12_lc_2, io_l2n_d28_lc_1, io_l2n_gc_lc_4,
        io_l2n_gc_vrp_lc_3, io_l2p_10, io_l2p_5, io_l2p_6,
        io_l2p_7, io_l2p_8, io_l2p_9, io_l2p_d13_lc_2,
        io_l2p_d29_lc_1, io_l2p_gc_lc_4, io_l2p_gc_vrn_lc_3,
        io_l30n_10, io_l30n_5, io_l30n_6, io_l30n_8, io_l30n_9,
        io_l30n_sm3_7, io_l30p_10, io_l30p_5, io_l30p_6,
        io_l30p_8, io_l30p_9, io_l30p_sm3_7, io_l31n_10,
        io_l31n_5, io_l31n_6, io_l31n_8, io_l31n_9, io_l31n_sm2_7,
        io_l31p_10, io_l31p_5, io_l31p_6, io_l31p_8, io_l31p_9,
        io_l31p_sm2_7, io_l32n_10, io_l32n_5, io_l32n_6,
        io_l32n_8, io_l32n_9, io_l32n_sm1_7, io_l32p_10,
        io_l32p_5, io_l32p_6, io_l32p_8, io_l32p_9, io_l32p_sm1_7,
        io_l3n_10, io_l3n_5, io_l3n_6, io_l3n_7, io_l3n_8,
        io_l3n_9, io_l3n_d10_lc_2, io_l3n_d26_lc_1,
        io_l3n_gc_lc_3, io_l3n_gc_lc_4, io_l3p_10, io_l3p_5,
        io_l3p_6, io_l3p_7, io_l3p_8, io_l3p_9, io_l3p_d11_lc_2,
        io_l3p_d27_lc_1, io_l3p_gc_lc_3, io_l3p_gc_lc_4,
        io_l4n_d24_vref_lc_1, io_l4n_d8_vref_lc_2,
        io_l4n_gc_vref_lc_3, io_l4n_gc_vref_lc_4,
        io_l4n_vref_10, io_l4n_vref_5, io_l4n_vref_6,
        io_l4n_vref_7, io_l4n_vref_8, io_l4n_vref_9, io_l4p_10,
        io_l4p_5, io_l4p_6, io_l4p_7, io_l4p_8, io_l4p_9,
        io_l4p_d25_lc_1, io_l4p_d9_lc_2, io_l4p_gc_lc_3,
        io_l4p_gc_lc_4, io_l5n_10, io_l5n_5, io_l5n_6, io_l5n_7,
        io_l5n_8, io_l5n_9, io_l5n_d22_lc_1, io_l5n_d6_lc_2,
        io_l5n_gc_lc_3, io_l5n_gc_lc_4, io_l5p_10, io_l5p_5,
        io_l5p_6, io_l5p_7, io_l5p_8, io_l5p_9, io_l5p_d23_lc_1,
        io_l5p_d7_lc_2, io_l5p_gc_lc_3, io_l5p_gc_lc_4,
        io_l6n_10, io_l6n_5, io_l6n_6, io_l6n_7, io_l6n_8,
        io_l6n_9, io_l6n_d20_lc_1, io_l6n_d4_lc_2,
        io_l6n_gc_lc_3, io_l6n_gc_lc_4, io_l6p_10, io_l6p_5,
        io_l6p_6, io_l6p_7, io_l6p_8, io_l6p_9, io_l6p_d21_lc_1,
        io_l6p_d5_lc_2, io_l6p_gc_lc_3, io_l6p_gc_lc_4,
        io_l7n_10, io_l7n_5, io_l7n_6, io_l7n_7, io_l7n_8,
        io_l7n_9, io_l7n_d18_lc_1, io_l7n_d2_lc_2,
        io_l7n_gc_lc_3, io_l7n_gc_vrp_lc_4, io_l7p_10, io_l7p_5,
        io_l7p_6, io_l7p_7, io_l7p_8, io_l7p_9, io_l7p_d19_lc_1,
        io_l7p_d3_lc_2, io_l7p_gc_lc_3, io_l7p_gc_vrn_lc_4,
        io_l8n_cc_lc_10, io_l8n_cc_lc_5, io_l8n_cc_lc_6,
        io_l8n_cc_lc_7, io_l8n_cc_lc_8, io_l8n_cc_lc_9,
        io_l8n_d0_lc_2, io_l8n_d16_cc_lc_1, io_l8n_gc_cc_lc_4,
        io_l8n_gc_lc_3, io_l8p_cc_lc_10, io_l8p_cc_lc_5,
        io_l8p_cc_lc_6, io_l8p_cc_lc_7, io_l8p_cc_lc_8,
        io_l8p_cc_lc_9, io_l8p_d17_cc_lc_1, io_l8p_d1_lc_2,
        io_l8p_gc_cc_lc_4, io_l8p_gc_lc_3, io_l9n_cc_lc_10,
        io_l9n_cc_lc_5, io_l9n_cc_lc_6, io_l9n_cc_lc_7,
        io_l9n_cc_lc_8, io_l9n_cc_lc_9, io_l9p_cc_lc_10,
        io_l9p_cc_lc_5, io_l9p_cc_lc_6, io_l9p_cc_lc_7,
        io_l9p_cc_lc_8, io_l9p_cc_lc_9, m0_0, m1_0, m2_0,
        program_b_0, pwrdwn_b_0, rdwr_b_0, tck_0, tdi_0, tdn_0,
        tdo_0, tdp_0, tms_0, vbatt_0, vccaux, vccint, vcco_0, vcco_1,
        vcco_10, vcco_2, vcco_3, vcco_4, vcco_5, vcco_6, vcco_7,
        vcco_8, vcco_9, vn_sm, vp_sm, vrefn_sm, vrefp_sm);
    inout avdd_sm;
    inout avss_sm;
    inout cclk_0;
    inout cs_b_0;
    inout d_in_0;
    inout done_0;
    inout dout_busy_0;
    input [90:1] gnd;
    inout hswapen_0;
    inout init_0;
    inout io_l10n_10;
    inout io_l10n_5;
    inout io_l10n_6;
    inout io_l10n_7;
    inout io_l10n_8;
    inout io_l10n_9;
    inout io_l10p_10;
    inout io_l10p_5;
    inout io_l10p_6;
    inout io_l10p_7;
    inout io_l10p_8;
    inout io_l10p_9;
    inout io_l11n_10;
    inout io_l11n_5;
    inout io_l11n_6;
    inout io_l11n_7;
    inout io_l11n_8;
    inout io_l11n_9;
    inout io_l11p_10;
    inout io_l11p_5;
    inout io_l11p_6;
    inout io_l11p_7;
    inout io_l11p_8;
    inout io_l11p_9;
    inout io_l12n_vref_10;
    inout io_l12n_vref_5;
    inout io_l12n_vref_6;
    inout io_l12n_vref_7;
    inout io_l12n_vref_8;
    inout io_l12n_vref_9;
    inout io_l12p_10;
    inout io_l12p_5;
    inout io_l12p_6;
    inout io_l12p_7;
    inout io_l12p_8;
    inout io_l12p_9;
    inout io_l13n_10;
    inout io_l13n_5;
    inout io_l13n_6;
    inout io_l13n_7;
    inout io_l13n_8;
    inout io_l13n_9;
    inout io_l13p_10;
    inout io_l13p_5;
    inout io_l13p_6;
    inout io_l13p_7;
    inout io_l13p_8;
    inout io_l13p_9;
    inout io_l14n_10;
    inout io_l14n_5;
    inout io_l14n_6;
    inout io_l14n_7;
    inout io_l14n_8;
    inout io_l14n_9;
    inout io_l14p_10;
    inout io_l14p_5;
    inout io_l14p_6;
    inout io_l14p_7;
    inout io_l14p_8;
    inout io_l14p_9;
    inout io_l15n_10;
    inout io_l15n_5;
    inout io_l15n_6;
    inout io_l15n_7;
    inout io_l15n_8;
    inout io_l15n_9;
    inout io_l15p_10;
    inout io_l15p_5;
    inout io_l15p_6;
    inout io_l15p_7;
    inout io_l15p_8;
    inout io_l15p_9;
    inout io_l16n_10;
    inout io_l16n_5;
    inout io_l16n_6;
    inout io_l16n_7;
    inout io_l16n_8;
    inout io_l16n_9;
    inout io_l16p_10;
    inout io_l16p_5;
    inout io_l16p_6;
    inout io_l16p_7;
    inout io_l16p_8;
    inout io_l16p_9;
    inout io_l17n_10;
    inout io_l17n_5;
    inout io_l17n_6;
    inout io_l17n_7;
    inout io_l17n_8;
    inout io_l17n_9;
    inout io_l17p_10;
    inout io_l17p_5;
    inout io_l17p_6;
    inout io_l17p_7;
    inout io_l17p_8;
    inout io_l17p_9;
    inout io_l18n_10;
    inout io_l18n_5;
    inout io_l18n_6;
    inout io_l18n_7;
    inout io_l18n_8;
    inout io_l18n_9;
    inout io_l18p_10;
    inout io_l18p_5;
    inout io_l18p_6;
    inout io_l18p_7;
    inout io_l18p_8;
    inout io_l18p_9;
    inout io_l19n_10;
    inout io_l19n_5;
    inout io_l19n_6;
    inout io_l19n_7;
    inout io_l19n_8;
    inout io_l19n_9;
    inout io_l19p_10;
    inout io_l19p_5;
    inout io_l19p_6;
    inout io_l19p_7;
    inout io_l19p_8;
    inout io_l19p_9;
    inout io_l1n_10;
    inout io_l1n_5;
    inout io_l1n_6;
    inout io_l1n_7;
    inout io_l1n_8;
    inout io_l1n_9;
    inout io_l1n_d14_cc_lc_2;
    inout io_l1n_d30_lc_1;
    inout io_l1n_gc_cc_lc_3;
    inout io_l1n_gc_lc_4;
    inout io_l1p_10;
    inout io_l1p_5;
    inout io_l1p_6;
    inout io_l1p_7;
    inout io_l1p_8;
    inout io_l1p_9;
    inout io_l1p_d15_cc_lc_2;
    inout io_l1p_d31_lc_1;
    inout io_l1p_gc_cc_lc_3;
    inout io_l1p_gc_lc_4;
    inout io_l20n_vref_10;
    inout io_l20n_vref_5;
    inout io_l20n_vref_6;
    inout io_l20n_vref_7;
    inout io_l20n_vref_8;
    inout io_l20n_vref_9;
    inout io_l20p_10;
    inout io_l20p_5;
    inout io_l20p_6;
    inout io_l20p_7;
    inout io_l20p_8;
    inout io_l20p_9;
    inout io_l21n_10;
    inout io_l21n_5;
    inout io_l21n_6;
    inout io_l21n_7;
    inout io_l21n_8;
    inout io_l21n_9;
    inout io_l21p_10;
    inout io_l21p_5;
    inout io_l21p_6;
    inout io_l21p_7;
    inout io_l21p_8;
    inout io_l21p_9;
    inout io_l22n_10;
    inout io_l22n_5;
    inout io_l22n_6;
    inout io_l22n_7;
    inout io_l22n_8;
    inout io_l22n_9;
    inout io_l22p_10;
    inout io_l22p_5;
    inout io_l22p_6;
    inout io_l22p_7;
    inout io_l22p_8;
    inout io_l22p_9;
    inout io_l23n_vrp_10;
    inout io_l23n_vrp_5;
    inout io_l23n_vrp_6;
    inout io_l23n_vrp_7;
    inout io_l23n_vrp_8;
    inout io_l23n_vrp_9;
    inout io_l23p_vrn_10;
    inout io_l23p_vrn_5;
    inout io_l23p_vrn_6;
    inout io_l23p_vrn_7;
    inout io_l23p_vrn_8;
    inout io_l23p_vrn_9;
    inout io_l24n_cc_lc_10;
    inout io_l24n_cc_lc_5;
    inout io_l24n_cc_lc_6;
    inout io_l24n_cc_lc_7;
    inout io_l24n_cc_lc_8;
    inout io_l24n_cc_lc_9;
    inout io_l24p_cc_lc_10;
    inout io_l24p_cc_lc_5;
    inout io_l24p_cc_lc_6;
    inout io_l24p_cc_lc_7;
    inout io_l24p_cc_lc_8;
    inout io_l24p_cc_lc_9;
    inout io_l25n_cc_lc_10;
    inout io_l25n_cc_lc_5;
    inout io_l25n_cc_lc_6;
    inout io_l25n_cc_lc_8;
    inout io_l25n_cc_lc_9;
    inout io_l25n_cc_sm7_lc_7;
    inout io_l25p_cc_lc_10;
    inout io_l25p_cc_lc_5;
    inout io_l25p_cc_lc_6;
    inout io_l25p_cc_lc_8;
    inout io_l25p_cc_lc_9;
    inout io_l25p_cc_sm7_lc_7;
    inout io_l26n_10;
    inout io_l26n_5;
    inout io_l26n_6;
    inout io_l26n_8;
    inout io_l26n_9;
    inout io_l26n_sm6_7;
    inout io_l26p_10;
    inout io_l26p_5;
    inout io_l26p_6;
    inout io_l26p_8;
    inout io_l26p_9;
    inout io_l26p_sm6_7;
    inout io_l27n_10;
    inout io_l27n_5;
    inout io_l27n_6;
    inout io_l27n_8;
    inout io_l27n_9;
    inout io_l27n_sm5_7;
    inout io_l27p_10;
    inout io_l27p_5;
    inout io_l27p_6;
    inout io_l27p_8;
    inout io_l27p_9;
    inout io_l27p_sm5_7;
    inout io_l28n_vref_10;
    inout io_l28n_vref_5;
    inout io_l28n_vref_6;
    inout io_l28n_vref_7;
    inout io_l28n_vref_8;
    inout io_l28n_vref_9;
    inout io_l28p_10;
    inout io_l28p_5;
    inout io_l28p_6;
    inout io_l28p_7;
    inout io_l28p_8;
    inout io_l28p_9;
    inout io_l29n_10;
    inout io_l29n_5;
    inout io_l29n_6;
    inout io_l29n_8;
    inout io_l29n_9;
    inout io_l29n_sm4_7;
    inout io_l29p_10;
    inout io_l29p_5;
    inout io_l29p_6;
    inout io_l29p_8;
    inout io_l29p_9;
    inout io_l29p_sm4_7;
    inout io_l2n_10;
    inout io_l2n_5;
    inout io_l2n_6;
    inout io_l2n_7;
    inout io_l2n_8;
    inout io_l2n_9;
    inout io_l2n_d12_lc_2;
    inout io_l2n_d28_lc_1;
    inout io_l2n_gc_lc_4;
    inout io_l2n_gc_vrp_lc_3;
    inout io_l2p_10;
    inout io_l2p_5;
    inout io_l2p_6;
    inout io_l2p_7;
    inout io_l2p_8;
    inout io_l2p_9;
    inout io_l2p_d13_lc_2;
    inout io_l2p_d29_lc_1;
    inout io_l2p_gc_lc_4;
    inout io_l2p_gc_vrn_lc_3;
    inout io_l30n_10;
    inout io_l30n_5;
    inout io_l30n_6;
    inout io_l30n_8;
    inout io_l30n_9;
    inout io_l30n_sm3_7;
    inout io_l30p_10;
    inout io_l30p_5;
    inout io_l30p_6;
    inout io_l30p_8;
    inout io_l30p_9;
    inout io_l30p_sm3_7;
    inout io_l31n_10;
    inout io_l31n_5;
    inout io_l31n_6;
    inout io_l31n_8;
    inout io_l31n_9;
    inout io_l31n_sm2_7;
    inout io_l31p_10;
    inout io_l31p_5;
    inout io_l31p_6;
    inout io_l31p_8;
    inout io_l31p_9;
    inout io_l31p_sm2_7;
    inout io_l32n_10;
    inout io_l32n_5;
    inout io_l32n_6;
    inout io_l32n_8;
    inout io_l32n_9;
    inout io_l32n_sm1_7;
    inout io_l32p_10;
    inout io_l32p_5;
    inout io_l32p_6;
    inout io_l32p_8;
    inout io_l32p_9;
    inout io_l32p_sm1_7;
    inout io_l3n_10;
    inout io_l3n_5;
    inout io_l3n_6;
    inout io_l3n_7;
    inout io_l3n_8;
    inout io_l3n_9;
    inout io_l3n_d10_lc_2;
    inout io_l3n_d26_lc_1;
    inout io_l3n_gc_lc_3;
    inout io_l3n_gc_lc_4;
    inout io_l3p_10;
    inout io_l3p_5;
    inout io_l3p_6;
    inout io_l3p_7;
    inout io_l3p_8;
    inout io_l3p_9;
    inout io_l3p_d11_lc_2;
    inout io_l3p_d27_lc_1;
    inout io_l3p_gc_lc_3;
    inout io_l3p_gc_lc_4;
    inout io_l4n_d24_vref_lc_1;
    inout io_l4n_d8_vref_lc_2;
    inout io_l4n_gc_vref_lc_3;
    inout io_l4n_gc_vref_lc_4;
    inout io_l4n_vref_10;
    inout io_l4n_vref_5;
    inout io_l4n_vref_6;
    inout io_l4n_vref_7;
    inout io_l4n_vref_8;
    inout io_l4n_vref_9;
    inout io_l4p_10;
    inout io_l4p_5;
    inout io_l4p_6;
    inout io_l4p_7;
    inout io_l4p_8;
    inout io_l4p_9;
    inout io_l4p_d25_lc_1;
    inout io_l4p_d9_lc_2;
    inout io_l4p_gc_lc_3;
    inout io_l4p_gc_lc_4;
    inout io_l5n_10;
    inout io_l5n_5;
    inout io_l5n_6;
    inout io_l5n_7;
    inout io_l5n_8;
    inout io_l5n_9;
    inout io_l5n_d22_lc_1;
    inout io_l5n_d6_lc_2;
    inout io_l5n_gc_lc_3;
    inout io_l5n_gc_lc_4;
    inout io_l5p_10;
    inout io_l5p_5;
    inout io_l5p_6;
    inout io_l5p_7;
    inout io_l5p_8;
    inout io_l5p_9;
    inout io_l5p_d23_lc_1;
    inout io_l5p_d7_lc_2;
    inout io_l5p_gc_lc_3;
    inout io_l5p_gc_lc_4;
    inout io_l6n_10;
    inout io_l6n_5;
    inout io_l6n_6;
    inout io_l6n_7;
    inout io_l6n_8;
    inout io_l6n_9;
    inout io_l6n_d20_lc_1;
    inout io_l6n_d4_lc_2;
    inout io_l6n_gc_lc_3;
    inout io_l6n_gc_lc_4;
    inout io_l6p_10;
    inout io_l6p_5;
    inout io_l6p_6;
    inout io_l6p_7;
    inout io_l6p_8;
    inout io_l6p_9;
    inout io_l6p_d21_lc_1;
    inout io_l6p_d5_lc_2;
    inout io_l6p_gc_lc_3;
    inout io_l6p_gc_lc_4;
    inout io_l7n_10;
    inout io_l7n_5;
    inout io_l7n_6;
    inout io_l7n_7;
    inout io_l7n_8;
    inout io_l7n_9;
    inout io_l7n_d18_lc_1;
    inout io_l7n_d2_lc_2;
    inout io_l7n_gc_lc_3;
    inout io_l7n_gc_vrp_lc_4;
    inout io_l7p_10;
    inout io_l7p_5;
    inout io_l7p_6;
    inout io_l7p_7;
    inout io_l7p_8;
    inout io_l7p_9;
    inout io_l7p_d19_lc_1;
    inout io_l7p_d3_lc_2;
    inout io_l7p_gc_lc_3;
    inout io_l7p_gc_vrn_lc_4;
    inout io_l8n_cc_lc_10;
    inout io_l8n_cc_lc_5;
    inout io_l8n_cc_lc_6;
    inout io_l8n_cc_lc_7;
    inout io_l8n_cc_lc_8;
    inout io_l8n_cc_lc_9;
    inout io_l8n_d0_lc_2;
    inout io_l8n_d16_cc_lc_1;
    inout io_l8n_gc_cc_lc_4;
    inout io_l8n_gc_lc_3;
    inout io_l8p_cc_lc_10;
    inout io_l8p_cc_lc_5;
    inout io_l8p_cc_lc_6;
    inout io_l8p_cc_lc_7;
    inout io_l8p_cc_lc_8;
    inout io_l8p_cc_lc_9;
    inout io_l8p_d17_cc_lc_1;
    inout io_l8p_d1_lc_2;
    inout io_l8p_gc_cc_lc_4;
    inout io_l8p_gc_lc_3;
    inout io_l9n_cc_lc_10;
    inout io_l9n_cc_lc_5;
    inout io_l9n_cc_lc_6;
    inout io_l9n_cc_lc_7;
    inout io_l9n_cc_lc_8;
    inout io_l9n_cc_lc_9;
    inout io_l9p_cc_lc_10;
    inout io_l9p_cc_lc_5;
    inout io_l9p_cc_lc_6;
    inout io_l9p_cc_lc_7;
    inout io_l9p_cc_lc_8;
    inout io_l9p_cc_lc_9;
    inout m0_0;
    inout m1_0;
    inout m2_0;
    inout program_b_0;
    inout pwrdwn_b_0;
    inout rdwr_b_0;
    inout tck_0;
    inout tdi_0;
    inout tdn_0;
    inout tdo_0;
    inout tdp_0;
    inout tms_0;
    inout vbatt_0;
    input [14:1] vccaux;
    input [32:1] vccint;
    input [2:1] vcco_0;
    input [2:1] vcco_1;
    input [8:1] vcco_10;
    input [2:1] vcco_2;
    input [2:1] vcco_3;
    input [2:1] vcco_4;
    input [8:1] vcco_5;
    input [8:1] vcco_6;
    input [8:1] vcco_7;
    input [8:1] vcco_8;
    input [8:1] vcco_9;
    inout vn_sm;
    inout vp_sm;
    inout vrefn_sm;
    inout vrefp_sm;


    initial
        begin
        end

endmodule
