// generated by newgenasym  Tue Dec 15 18:07:23 2009


module lt3080eq (in, nc, out, set, tout, vcon);
    inout in;
    inout nc;
    inout out;
    inout set;
    inout tout;
    inout vcon;


    initial
        begin
        end

endmodule
