-- generated by newgenasym Fri Jun 24 11:38:20 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity etc1_1_13tr is
    port (    
	\n/c\:     INOUT  STD_LOGIC;    
	PRI:       INOUT  STD_LOGIC;    
	PRI_DOT:   INOUT  STD_LOGIC;    
	SEC:       INOUT  STD_LOGIC;    
	SEC_DOT:   INOUT  STD_LOGIC);
end etc1_1_13tr;
