// generated by newgenasym  Tue Jul 19 14:10:01 2011


module sn74hct00pw (\1a , \1b , \1y , \2a , \2b , \2y , \3a , \3b , \3y , \4a , \4b , \4y , gnd, vcc);
    inout \1a ;
    inout \1b ;
    inout \1y ;
    inout \2a ;
    inout \2b ;
    inout \2y ;
    inout \3a ;
    inout \3b ;
    inout \3y ;
    inout \4a ;
    inout \4b ;
    inout \4y ;
    inout gnd;
    inout vcc;


    initial
        begin
        end

endmodule
