-- generated by newgenasym Mon Apr 23 11:15:24 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max6627mta is
    port (    
	CSN:       INOUT  STD_LOGIC;    
	DXN:       INOUT  STD_LOGIC;    
	DXP:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	SCK:       INOUT  STD_LOGIC;    
	SDO:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end max6627mta;
