// generated by newgenasym  Thu Feb 12 15:37:52 2009


module tps54610pwp (agnd, boot, comp, pgnd_0, pgnd_1, pgnd_2, pgnd_3, pgnd_4,
        ph1, ph2, ph3, ph4, ph5, ph6, ph7, ph8, ph9, pwrgd, pwrpad, rt,
        \ss/ena , sync, vbias, vin1, vin2, vin3, vin4, vin5, vsense);
    input agnd;
    output boot;
    output comp;
    input pgnd_0;
    input pgnd_1;
    input pgnd_2;
    input pgnd_3;
    input pgnd_4;
    output ph1;
    output ph2;
    output ph3;
    output ph4;
    output ph5;
    output ph6;
    output ph7;
    output ph8;
    output ph9;
    output pwrgd;
    input pwrpad;
    input rt;
    inout \ss/ena ;
    input sync;
    output vbias;
    input vin1;
    input vin2;
    input vin3;
    input vin4;
    input vin5;
    input vsense;


    initial
        begin
        end

endmodule
