// generated by newgenasym  Mon Apr 20 17:45:34 2009


module lm2901vdr2g (gnd, \input1+ , \input1- , \input2+ , \input2- , \input3+ , \input3- ,
        \input4+ , \input4- , output1, output2, output3, output4, vcc);
    input gnd;
    input \input1+ ;
    input \input1- ;
    input \input2+ ;
    input \input2- ;
    input \input3+ ;
    input \input3- ;
    input \input4+ ;
    input \input4- ;
    output output1;
    output output2;
    output output3;
    output output4;
    input vcc;


    initial
        begin
        end

endmodule
