-- generated by newgenasym Mon Apr 20 17:45:34 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm2901vdr2g is
    port (    
	GND:       IN     STD_LOGIC;    
	\input1+\: IN     STD_LOGIC;    
	\input1-\: IN     STD_LOGIC;    
	\input2+\: IN     STD_LOGIC;    
	\input2-\: IN     STD_LOGIC;    
	\input3+\: IN     STD_LOGIC;    
	\input3-\: IN     STD_LOGIC;    
	\input4+\: IN     STD_LOGIC;    
	\input4-\: IN     STD_LOGIC;    
	OUTPUT1:   OUT    STD_LOGIC;    
	OUTPUT2:   OUT    STD_LOGIC;    
	OUTPUT3:   OUT    STD_LOGIC;    
	OUTPUT4:   OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end lm2901vdr2g;
