// generated by newgenasym  Wed Sep 09 18:53:02 2009


module ics853s011bmilf (pclk, \pclk# , q0, \q0# , q1, \q1# , vcc, vee);
    inout pclk;
    inout \pclk# ;
    inout q0;
    inout \q0# ;
    inout q1;
    inout \q1# ;
    inout vcc;
    inout vee;


    initial
        begin
        end

endmodule
