-- generated by newgenasym Wed Sep 09 18:53:02 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ics853s011bmilf is
    port (    
	PCLK:      INOUT  STD_LOGIC;    
	\pclk#\:   INOUT  STD_LOGIC;    
	Q0:        INOUT  STD_LOGIC;    
	\q0#\:     INOUT  STD_LOGIC;    
	Q1:        INOUT  STD_LOGIC;    
	\q1#\:     INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	VEE:       INOUT  STD_LOGIC);
end ics853s011bmilf;
