// generated by newgenasym  Mon Apr 23 10:44:45 2012


module pd1722j5050d2hf (g, i, m1, m2, o1, o2);
    inout g;
    inout i;
    inout m1;
    inout m2;
    inout o1;
    inout o2;


    initial
        begin
        end

endmodule
