// generated by newgenasym  Fri Mar 02 09:10:51 2012


module tps54618rte (agnd, boot, comp, en, gnd, pad, ph, pwrgd, \rt/clk , \ss/tr , vin,
        vsense);
    inout agnd;
    inout boot;
    inout comp;
    inout en;
    inout [2:1] gnd;
    inout pad;
    inout [3:1] ph;
    inout pwrgd;
    inout \rt/clk ;
    inout \ss/tr ;
    inout [3:1] vin;
    inout vsense;


    initial
        begin
        end

endmodule
