-- generated by newgenasym Fri Mar 30 16:34:15 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dmmt3904w is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end dmmt3904w;
