// generated by newgenasym  Tue Jul 27 20:06:02 2010


module ams1117 (\gnd/adj , pad, vin, vout);
    inout \gnd/adj ;
    inout pad;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
