-- generated by newgenasym Mon Aug 08 15:51:31 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CON_M_DV200_14 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\10\:      INOUT  STD_LOGIC;    
	\11\:      INOUT  STD_LOGIC;    
	\12\:      INOUT  STD_LOGIC;    
	\13\:      INOUT  STD_LOGIC;    
	\14\:      INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	\9\:       INOUT  STD_LOGIC);
end CON_M_DV200_14;
