-- generated by newgenasym Wed Nov 08 16:41:39 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TESTPOINT_DIFF is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end TESTPOINT_DIFF;
