// generated by newgenasym  Fri Jun 24 10:37:52 2011


module adl5380acpz (adj, enbl, gnd1, gnd2, gnd3, gnd4, ihi, ilo, loin, loip, \n/c ,
        pad, qhi, qlo, rfin, rfip, vcc1, vcc2, vcc3);
    inout adj;
    inout enbl;
    inout [2:1] gnd1;
    inout [2:1] gnd2;
    inout [4:1] gnd3;
    inout [2:1] gnd4;
    inout ihi;
    inout ilo;
    inout loin;
    inout loip;
    inout \n/c ;
    inout pad;
    inout qhi;
    inout qlo;
    inout rfin;
    inout rfip;
    inout vcc1;
    inout vcc2;
    inout vcc3;


    initial
        begin
        end

endmodule
