-- generated by newgenasym Fri Jun 24 10:37:52 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adl5380acpz is
    port (    
	ADJ:       INOUT  STD_LOGIC;    
	ENBL:      INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	GND2:      INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	GND3:      INOUT  STD_LOGIC_VECTOR (4 DOWNTO 1);    
	GND4:      INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	IHI:       INOUT  STD_LOGIC;    
	ILO:       INOUT  STD_LOGIC;    
	LOIN:      INOUT  STD_LOGIC;    
	LOIP:      INOUT  STD_LOGIC;    
	\n/c\:     INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	QHI:       INOUT  STD_LOGIC;    
	QLO:       INOUT  STD_LOGIC;    
	RFIN:      INOUT  STD_LOGIC;    
	RFIP:      INOUT  STD_LOGIC;    
	VCC1:      INOUT  STD_LOGIC;    
	VCC2:      INOUT  STD_LOGIC;    
	VCC3:      INOUT  STD_LOGIC);
end adl5380acpz;
