// generated by newgenasym  Mon Apr 09 15:13:49 2012


module xc7k325t_1fbg900i (cclk_0, cfgbvs_0, done_0, dxn_0, dxp_0, gnd, gndadc_0,
        init_b_0, io_0_12, io_0_13, io_0_14, io_0_15, io_0_16,
        io_0_17, io_0_18, io_0_vrn_32, io_0_vrn_33, io_0_vrn_34,
        io_25_12, io_25_13, io_25_14, io_25_15, io_25_16, io_25_17,
        io_25_18, io_25_vrp_32, io_25_vrp_33, io_25_vrp_34,
        io_l10n_t1_12, io_l10n_t1_13, io_l10n_t1_16,
        io_l10n_t1_17, io_l10n_t1_18, io_l10n_t1_32,
        io_l10n_t1_33, io_l10n_t1_34, io_l10n_t1_ad4n_15,
        io_l10n_t1_d15_14, io_l10p_t1_12, io_l10p_t1_13,
        io_l10p_t1_16, io_l10p_t1_17, io_l10p_t1_18,
        io_l10p_t1_32, io_l10p_t1_33, io_l10p_t1_34,
        io_l10p_t1_ad4p_15, io_l10p_t1_d14_14,
        io_l11n_t1_srcc_12, io_l11n_t1_srcc_13,
        io_l11n_t1_srcc_14, io_l11n_t1_srcc_16,
        io_l11n_t1_srcc_17, io_l11n_t1_srcc_18,
        io_l11n_t1_srcc_32, io_l11n_t1_srcc_33,
        io_l11n_t1_srcc_34, io_l11n_t1_srcc_ad12n_15,
        io_l11p_t1_srcc_12, io_l11p_t1_srcc_13,
        io_l11p_t1_srcc_14, io_l11p_t1_srcc_16,
        io_l11p_t1_srcc_17, io_l11p_t1_srcc_18,
        io_l11p_t1_srcc_32, io_l11p_t1_srcc_33,
        io_l11p_t1_srcc_34, io_l11p_t1_srcc_ad12p_15,
        io_l12n_t1_mrcc_12, io_l12n_t1_mrcc_13,
        io_l12n_t1_mrcc_14, io_l12n_t1_mrcc_16,
        io_l12n_t1_mrcc_17, io_l12n_t1_mrcc_18,
        io_l12n_t1_mrcc_32, io_l12n_t1_mrcc_33,
        io_l12n_t1_mrcc_34, io_l12n_t1_mrcc_ad5n_15,
        io_l12p_t1_mrcc_12, io_l12p_t1_mrcc_13,
        io_l12p_t1_mrcc_14, io_l12p_t1_mrcc_16,
        io_l12p_t1_mrcc_17, io_l12p_t1_mrcc_18,
        io_l12p_t1_mrcc_32, io_l12p_t1_mrcc_33,
        io_l12p_t1_mrcc_34, io_l12p_t1_mrcc_ad5p_15,
        io_l13n_t2_mrcc_12, io_l13n_t2_mrcc_13,
        io_l13n_t2_mrcc_14, io_l13n_t2_mrcc_15,
        io_l13n_t2_mrcc_16, io_l13n_t2_mrcc_17,
        io_l13n_t2_mrcc_18, io_l13n_t2_mrcc_32,
        io_l13n_t2_mrcc_33, io_l13n_t2_mrcc_34,
        io_l13p_t2_mrcc_12, io_l13p_t2_mrcc_13,
        io_l13p_t2_mrcc_14, io_l13p_t2_mrcc_15,
        io_l13p_t2_mrcc_16, io_l13p_t2_mrcc_17,
        io_l13p_t2_mrcc_18, io_l13p_t2_mrcc_32,
        io_l13p_t2_mrcc_33, io_l13p_t2_mrcc_34,
        io_l14n_t2_srcc_12, io_l14n_t2_srcc_13,
        io_l14n_t2_srcc_14, io_l14n_t2_srcc_15,
        io_l14n_t2_srcc_16, io_l14n_t2_srcc_17,
        io_l14n_t2_srcc_18, io_l14n_t2_srcc_32,
        io_l14n_t2_srcc_33, io_l14n_t2_srcc_34,
        io_l14p_t2_srcc_12, io_l14p_t2_srcc_13,
        io_l14p_t2_srcc_14, io_l14p_t2_srcc_15,
        io_l14p_t2_srcc_16, io_l14p_t2_srcc_17,
        io_l14p_t2_srcc_18, io_l14p_t2_srcc_32,
        io_l14p_t2_srcc_33, io_l14p_t2_srcc_34,
        io_l15n_t2_dqs_12, io_l15n_t2_dqs_13, io_l15n_t2_dqs_16,
        io_l15n_t2_dqs_17, io_l15n_t2_dqs_18, io_l15n_t2_dqs_32,
        io_l15n_t2_dqs_33, io_l15n_t2_dqs_34,
        io_l15n_t2_dqs_adv_b_15, io_l15n_t2_dqs_dout_cso_b_14,
        io_l15p_t2_dqs_12, io_l15p_t2_dqs_13, io_l15p_t2_dqs_15,
        io_l15p_t2_dqs_16, io_l15p_t2_dqs_17, io_l15p_t2_dqs_18,
        io_l15p_t2_dqs_32, io_l15p_t2_dqs_33, io_l15p_t2_dqs_34,
        io_l15p_t2_dqs_rdwr_b_14, io_l16n_t2_12, io_l16n_t2_13,
        io_l16n_t2_16, io_l16n_t2_17, io_l16n_t2_18,
        io_l16n_t2_32, io_l16n_t2_33, io_l16n_t2_34,
        io_l16n_t2_a15_d31_14, io_l16n_t2_a27_15, io_l16p_t2_12,
        io_l16p_t2_13, io_l16p_t2_16, io_l16p_t2_17,
        io_l16p_t2_18, io_l16p_t2_32, io_l16p_t2_33,
        io_l16p_t2_34, io_l16p_t2_a28_15, io_l16p_t2_csi_b_14,
        io_l17n_t2_12, io_l17n_t2_13, io_l17n_t2_16,
        io_l17n_t2_17, io_l17n_t2_18, io_l17n_t2_32,
        io_l17n_t2_33, io_l17n_t2_34, io_l17n_t2_a13_d29_14,
        io_l17n_t2_a25_15, io_l17p_t2_12, io_l17p_t2_13,
        io_l17p_t2_16, io_l17p_t2_17, io_l17p_t2_18,
        io_l17p_t2_32, io_l17p_t2_33, io_l17p_t2_34,
        io_l17p_t2_a14_d30_14, io_l17p_t2_a26_15, io_l18n_t2_12,
        io_l18n_t2_13, io_l18n_t2_16, io_l18n_t2_17,
        io_l18n_t2_18, io_l18n_t2_32, io_l18n_t2_33,
        io_l18n_t2_34, io_l18n_t2_a11_d27_14, io_l18n_t2_a23_15,
        io_l18p_t2_12, io_l18p_t2_13, io_l18p_t2_16,
        io_l18p_t2_17, io_l18p_t2_18, io_l18p_t2_32,
        io_l18p_t2_33, io_l18p_t2_34, io_l18p_t2_a12_d28_14,
        io_l18p_t2_a24_15, io_l19n_t3_a09_d25_vref_14,
        io_l19n_t3_a21_vref_15, io_l19n_t3_vref_12,
        io_l19n_t3_vref_13, io_l19n_t3_vref_16,
        io_l19n_t3_vref_17, io_l19n_t3_vref_18,
        io_l19n_t3_vref_32, io_l19n_t3_vref_33,
        io_l19n_t3_vref_34, io_l19p_t3_12, io_l19p_t3_13,
        io_l19p_t3_16, io_l19p_t3_17, io_l19p_t3_18,
        io_l19p_t3_32, io_l19p_t3_33, io_l19p_t3_34,
        io_l19p_t3_a10_d26_14, io_l19p_t3_a22_15, io_l1n_t0_12,
        io_l1n_t0_13, io_l1n_t0_16, io_l1n_t0_17, io_l1n_t0_18,
        io_l1n_t0_32, io_l1n_t0_33, io_l1n_t0_34,
        io_l1n_t0_ad0n_15, io_l1n_t0_d01_din_14, io_l1p_t0_12,
        io_l1p_t0_13, io_l1p_t0_16, io_l1p_t0_17, io_l1p_t0_18,
        io_l1p_t0_32, io_l1p_t0_33, io_l1p_t0_34,
        io_l1p_t0_ad0p_15, io_l1p_t0_d00_mosi_14, io_l20n_t3_12,
        io_l20n_t3_13, io_l20n_t3_16, io_l20n_t3_17,
        io_l20n_t3_18, io_l20n_t3_32, io_l20n_t3_33,
        io_l20n_t3_34, io_l20n_t3_a07_d23_14, io_l20n_t3_a19_15,
        io_l20p_t3_12, io_l20p_t3_13, io_l20p_t3_16,
        io_l20p_t3_17, io_l20p_t3_18, io_l20p_t3_32,
        io_l20p_t3_33, io_l20p_t3_34, io_l20p_t3_a08_d24_14,
        io_l20p_t3_a20_15, io_l21n_t3_dqs_12, io_l21n_t3_dqs_13,
        io_l21n_t3_dqs_16, io_l21n_t3_dqs_17, io_l21n_t3_dqs_18,
        io_l21n_t3_dqs_32, io_l21n_t3_dqs_33, io_l21n_t3_dqs_34,
        io_l21n_t3_dqs_a06_d22_14, io_l21n_t3_dqs_a18_15,
        io_l21p_t3_dqs_12, io_l21p_t3_dqs_13, io_l21p_t3_dqs_14,
        io_l21p_t3_dqs_15, io_l21p_t3_dqs_16, io_l21p_t3_dqs_17,
        io_l21p_t3_dqs_18, io_l21p_t3_dqs_32, io_l21p_t3_dqs_33,
        io_l21p_t3_dqs_34, io_l22n_t3_12, io_l22n_t3_13,
        io_l22n_t3_16, io_l22n_t3_17, io_l22n_t3_18,
        io_l22n_t3_32, io_l22n_t3_33, io_l22n_t3_34,
        io_l22n_t3_a04_d20_14, io_l22n_t3_a16_15, io_l22p_t3_12,
        io_l22p_t3_13, io_l22p_t3_16, io_l22p_t3_17,
        io_l22p_t3_18, io_l22p_t3_32, io_l22p_t3_33,
        io_l22p_t3_34, io_l22p_t3_a05_d21_14, io_l22p_t3_a17_15,
        io_l23n_t3_12, io_l23n_t3_13, io_l23n_t3_16,
        io_l23n_t3_17, io_l23n_t3_18, io_l23n_t3_32,
        io_l23n_t3_33, io_l23n_t3_34, io_l23n_t3_a02_d18_14,
        io_l23n_t3_fwe_b_15, io_l23p_t3_12, io_l23p_t3_13,
        io_l23p_t3_16, io_l23p_t3_17, io_l23p_t3_18,
        io_l23p_t3_32, io_l23p_t3_33, io_l23p_t3_34,
        io_l23p_t3_a03_d19_14, io_l23p_t3_foe_b_15,
        io_l24n_t3_12, io_l24n_t3_13, io_l24n_t3_16,
        io_l24n_t3_17, io_l24n_t3_18, io_l24n_t3_32,
        io_l24n_t3_33, io_l24n_t3_34, io_l24n_t3_a00_d16_14,
        io_l24n_t3_rs0_15, io_l24p_t3_12, io_l24p_t3_13,
        io_l24p_t3_16, io_l24p_t3_17, io_l24p_t3_18,
        io_l24p_t3_32, io_l24p_t3_33, io_l24p_t3_34,
        io_l24p_t3_a01_d17_14, io_l24p_t3_rs1_15, io_l2n_t0_12,
        io_l2n_t0_13, io_l2n_t0_16, io_l2n_t0_17, io_l2n_t0_18,
        io_l2n_t0_32, io_l2n_t0_33, io_l2n_t0_34,
        io_l2n_t0_ad8n_15, io_l2n_t0_d03_14, io_l2p_t0_12,
        io_l2p_t0_13, io_l2p_t0_16, io_l2p_t0_17, io_l2p_t0_18,
        io_l2p_t0_32, io_l2p_t0_33, io_l2p_t0_34,
        io_l2p_t0_ad8p_15, io_l2p_t0_d02_14, io_l3n_t0_dqs_12,
        io_l3n_t0_dqs_13, io_l3n_t0_dqs_16, io_l3n_t0_dqs_17,
        io_l3n_t0_dqs_18, io_l3n_t0_dqs_32, io_l3n_t0_dqs_33,
        io_l3n_t0_dqs_34, io_l3n_t0_dqs_ad1n_15,
        io_l3n_t0_dqs_emcclk_14, io_l3p_t0_dqs_12,
        io_l3p_t0_dqs_13, io_l3p_t0_dqs_16, io_l3p_t0_dqs_17,
        io_l3p_t0_dqs_18, io_l3p_t0_dqs_32, io_l3p_t0_dqs_33,
        io_l3p_t0_dqs_34, io_l3p_t0_dqs_ad1p_15,
        io_l3p_t0_dqs_pudc_b_14, io_l4n_t0_12, io_l4n_t0_13,
        io_l4n_t0_16, io_l4n_t0_17, io_l4n_t0_18, io_l4n_t0_32,
        io_l4n_t0_33, io_l4n_t0_34, io_l4n_t0_ad9n_15,
        io_l4n_t0_d05_14, io_l4p_t0_12, io_l4p_t0_13,
        io_l4p_t0_16, io_l4p_t0_17, io_l4p_t0_18, io_l4p_t0_32,
        io_l4p_t0_33, io_l4p_t0_34, io_l4p_t0_ad9p_15,
        io_l4p_t0_d04_14, io_l5n_t0_12, io_l5n_t0_13,
        io_l5n_t0_16, io_l5n_t0_17, io_l5n_t0_18, io_l5n_t0_32,
        io_l5n_t0_33, io_l5n_t0_34, io_l5n_t0_ad2n_15,
        io_l5n_t0_d07_14, io_l5p_t0_12, io_l5p_t0_13,
        io_l5p_t0_16, io_l5p_t0_17, io_l5p_t0_18, io_l5p_t0_32,
        io_l5p_t0_33, io_l5p_t0_34, io_l5p_t0_ad2p_15,
        io_l5p_t0_d06_14, io_l6n_t0_d08_vref_14,
        io_l6n_t0_vref_12, io_l6n_t0_vref_13, io_l6n_t0_vref_15,
        io_l6n_t0_vref_16, io_l6n_t0_vref_17, io_l6n_t0_vref_18,
        io_l6n_t0_vref_32, io_l6n_t0_vref_33, io_l6n_t0_vref_34,
        io_l6p_t0_12, io_l6p_t0_13, io_l6p_t0_15, io_l6p_t0_16,
        io_l6p_t0_17, io_l6p_t0_18, io_l6p_t0_32, io_l6p_t0_33,
        io_l6p_t0_34, io_l6p_t0_fcs_b_14, io_l7n_t1_12,
        io_l7n_t1_13, io_l7n_t1_16, io_l7n_t1_17, io_l7n_t1_18,
        io_l7n_t1_32, io_l7n_t1_33, io_l7n_t1_34,
        io_l7n_t1_ad10n_15, io_l7n_t1_d10_14, io_l7p_t1_12,
        io_l7p_t1_13, io_l7p_t1_16, io_l7p_t1_17, io_l7p_t1_18,
        io_l7p_t1_32, io_l7p_t1_33, io_l7p_t1_34,
        io_l7p_t1_ad10p_15, io_l7p_t1_d09_14, io_l8n_t1_12,
        io_l8n_t1_13, io_l8n_t1_16, io_l8n_t1_17, io_l8n_t1_18,
        io_l8n_t1_32, io_l8n_t1_33, io_l8n_t1_34,
        io_l8n_t1_ad3n_15, io_l8n_t1_d12_14, io_l8p_t1_12,
        io_l8p_t1_13, io_l8p_t1_16, io_l8p_t1_17, io_l8p_t1_18,
        io_l8p_t1_32, io_l8p_t1_33, io_l8p_t1_34,
        io_l8p_t1_ad3p_15, io_l8p_t1_d11_14, io_l9n_t1_dqs_12,
        io_l9n_t1_dqs_13, io_l9n_t1_dqs_16, io_l9n_t1_dqs_17,
        io_l9n_t1_dqs_18, io_l9n_t1_dqs_32, io_l9n_t1_dqs_33,
        io_l9n_t1_dqs_34, io_l9n_t1_dqs_ad11n_15,
        io_l9n_t1_dqs_d13_14, io_l9p_t1_dqs_12,
        io_l9p_t1_dqs_13, io_l9p_t1_dqs_14, io_l9p_t1_dqs_16,
        io_l9p_t1_dqs_17, io_l9p_t1_dqs_18, io_l9p_t1_dqs_32,
        io_l9p_t1_dqs_33, io_l9p_t1_dqs_34,
        io_l9p_t1_dqs_ad11p_15, m0_0, m1_0, m2_0, mgtavcc, mgtavtt,
        mgtavttrcal_115, mgtrefclk0n_115, mgtrefclk0n_116,
        mgtrefclk0n_117, mgtrefclk0n_118, mgtrefclk0p_115,
        mgtrefclk0p_116, mgtrefclk0p_117, mgtrefclk0p_118,
        mgtrefclk1n_115, mgtrefclk1n_116, mgtrefclk1n_117,
        mgtrefclk1n_118, mgtrefclk1p_115, mgtrefclk1p_116,
        mgtrefclk1p_117, mgtrefclk1p_118, mgtrref_115, mgtvccaux,
        mgtxrxn0_115, mgtxrxn0_116, mgtxrxn0_117, mgtxrxn0_118,
        mgtxrxn1_115, mgtxrxn1_116, mgtxrxn1_117, mgtxrxn1_118,
        mgtxrxn2_115, mgtxrxn2_116, mgtxrxn2_117, mgtxrxn2_118,
        mgtxrxn3_115, mgtxrxn3_116, mgtxrxn3_117, mgtxrxn3_118,
        mgtxrxp0_115, mgtxrxp0_116, mgtxrxp0_117, mgtxrxp0_118,
        mgtxrxp1_115, mgtxrxp1_116, mgtxrxp1_117, mgtxrxp1_118,
        mgtxrxp2_115, mgtxrxp2_116, mgtxrxp2_117, mgtxrxp2_118,
        mgtxrxp3_115, mgtxrxp3_116, mgtxrxp3_117, mgtxrxp3_118,
        mgtxtxn0_115, mgtxtxn0_116, mgtxtxn0_117, mgtxtxn0_118,
        mgtxtxn1_115, mgtxtxn1_116, mgtxtxn1_117, mgtxtxn1_118,
        mgtxtxn2_115, mgtxtxn2_116, mgtxtxn2_117, mgtxtxn2_118,
        mgtxtxn3_115, mgtxtxn3_116, mgtxtxn3_117, mgtxtxn3_118,
        mgtxtxp0_115, mgtxtxp0_116, mgtxtxp0_117, mgtxtxp0_118,
        mgtxtxp1_115, mgtxtxp1_116, mgtxtxp1_117, mgtxtxp1_118,
        mgtxtxp2_115, mgtxtxp2_116, mgtxtxp2_117, mgtxtxp2_118,
        mgtxtxp3_115, mgtxtxp3_116, mgtxtxp3_117, mgtxtxp3_118,
        program_b_0, tck_0, tdi_0, tdo_0, tms_0, vccadc_0, vccaux,
        vccaux_io_g0, vccbatt_0, vccbram, vccint, vcco_0, vcco_12,
        vcco_13, vcco_14, vcco_15, vcco_16, vcco_17, vcco_18,
        vcco_32, vcco_33, vcco_34, vn_0, vp_0, vrefn_0, vrefp_0);
    inout cclk_0;
    inout cfgbvs_0;
    inout done_0;
    inout dxn_0;
    inout dxp_0;
    inout [173:1] gnd;
    inout gndadc_0;
    inout init_b_0;
    inout io_0_12;
    inout io_0_13;
    inout io_0_14;
    inout io_0_15;
    inout io_0_16;
    inout io_0_17;
    inout io_0_18;
    inout io_0_vrn_32;
    inout io_0_vrn_33;
    inout io_0_vrn_34;
    inout io_25_12;
    inout io_25_13;
    inout io_25_14;
    inout io_25_15;
    inout io_25_16;
    inout io_25_17;
    inout io_25_18;
    inout io_25_vrp_32;
    inout io_25_vrp_33;
    inout io_25_vrp_34;
    inout io_l10n_t1_12;
    inout io_l10n_t1_13;
    inout io_l10n_t1_16;
    inout io_l10n_t1_17;
    inout io_l10n_t1_18;
    inout io_l10n_t1_32;
    inout io_l10n_t1_33;
    inout io_l10n_t1_34;
    inout io_l10n_t1_ad4n_15;
    inout io_l10n_t1_d15_14;
    inout io_l10p_t1_12;
    inout io_l10p_t1_13;
    inout io_l10p_t1_16;
    inout io_l10p_t1_17;
    inout io_l10p_t1_18;
    inout io_l10p_t1_32;
    inout io_l10p_t1_33;
    inout io_l10p_t1_34;
    inout io_l10p_t1_ad4p_15;
    inout io_l10p_t1_d14_14;
    inout io_l11n_t1_srcc_12;
    inout io_l11n_t1_srcc_13;
    inout io_l11n_t1_srcc_14;
    inout io_l11n_t1_srcc_16;
    inout io_l11n_t1_srcc_17;
    inout io_l11n_t1_srcc_18;
    inout io_l11n_t1_srcc_32;
    inout io_l11n_t1_srcc_33;
    inout io_l11n_t1_srcc_34;
    inout io_l11n_t1_srcc_ad12n_15;
    inout io_l11p_t1_srcc_12;
    inout io_l11p_t1_srcc_13;
    inout io_l11p_t1_srcc_14;
    inout io_l11p_t1_srcc_16;
    inout io_l11p_t1_srcc_17;
    inout io_l11p_t1_srcc_18;
    inout io_l11p_t1_srcc_32;
    inout io_l11p_t1_srcc_33;
    inout io_l11p_t1_srcc_34;
    inout io_l11p_t1_srcc_ad12p_15;
    inout io_l12n_t1_mrcc_12;
    inout io_l12n_t1_mrcc_13;
    inout io_l12n_t1_mrcc_14;
    inout io_l12n_t1_mrcc_16;
    inout io_l12n_t1_mrcc_17;
    inout io_l12n_t1_mrcc_18;
    inout io_l12n_t1_mrcc_32;
    inout io_l12n_t1_mrcc_33;
    inout io_l12n_t1_mrcc_34;
    inout io_l12n_t1_mrcc_ad5n_15;
    inout io_l12p_t1_mrcc_12;
    inout io_l12p_t1_mrcc_13;
    inout io_l12p_t1_mrcc_14;
    inout io_l12p_t1_mrcc_16;
    inout io_l12p_t1_mrcc_17;
    inout io_l12p_t1_mrcc_18;
    inout io_l12p_t1_mrcc_32;
    inout io_l12p_t1_mrcc_33;
    inout io_l12p_t1_mrcc_34;
    inout io_l12p_t1_mrcc_ad5p_15;
    inout io_l13n_t2_mrcc_12;
    inout io_l13n_t2_mrcc_13;
    inout io_l13n_t2_mrcc_14;
    inout io_l13n_t2_mrcc_15;
    inout io_l13n_t2_mrcc_16;
    inout io_l13n_t2_mrcc_17;
    inout io_l13n_t2_mrcc_18;
    inout io_l13n_t2_mrcc_32;
    inout io_l13n_t2_mrcc_33;
    inout io_l13n_t2_mrcc_34;
    inout io_l13p_t2_mrcc_12;
    inout io_l13p_t2_mrcc_13;
    inout io_l13p_t2_mrcc_14;
    inout io_l13p_t2_mrcc_15;
    inout io_l13p_t2_mrcc_16;
    inout io_l13p_t2_mrcc_17;
    inout io_l13p_t2_mrcc_18;
    inout io_l13p_t2_mrcc_32;
    inout io_l13p_t2_mrcc_33;
    inout io_l13p_t2_mrcc_34;
    inout io_l14n_t2_srcc_12;
    inout io_l14n_t2_srcc_13;
    inout io_l14n_t2_srcc_14;
    inout io_l14n_t2_srcc_15;
    inout io_l14n_t2_srcc_16;
    inout io_l14n_t2_srcc_17;
    inout io_l14n_t2_srcc_18;
    inout io_l14n_t2_srcc_32;
    inout io_l14n_t2_srcc_33;
    inout io_l14n_t2_srcc_34;
    inout io_l14p_t2_srcc_12;
    inout io_l14p_t2_srcc_13;
    inout io_l14p_t2_srcc_14;
    inout io_l14p_t2_srcc_15;
    inout io_l14p_t2_srcc_16;
    inout io_l14p_t2_srcc_17;
    inout io_l14p_t2_srcc_18;
    inout io_l14p_t2_srcc_32;
    inout io_l14p_t2_srcc_33;
    inout io_l14p_t2_srcc_34;
    inout io_l15n_t2_dqs_12;
    inout io_l15n_t2_dqs_13;
    inout io_l15n_t2_dqs_16;
    inout io_l15n_t2_dqs_17;
    inout io_l15n_t2_dqs_18;
    inout io_l15n_t2_dqs_32;
    inout io_l15n_t2_dqs_33;
    inout io_l15n_t2_dqs_34;
    inout io_l15n_t2_dqs_adv_b_15;
    inout io_l15n_t2_dqs_dout_cso_b_14;
    inout io_l15p_t2_dqs_12;
    inout io_l15p_t2_dqs_13;
    inout io_l15p_t2_dqs_15;
    inout io_l15p_t2_dqs_16;
    inout io_l15p_t2_dqs_17;
    inout io_l15p_t2_dqs_18;
    inout io_l15p_t2_dqs_32;
    inout io_l15p_t2_dqs_33;
    inout io_l15p_t2_dqs_34;
    inout io_l15p_t2_dqs_rdwr_b_14;
    inout io_l16n_t2_12;
    inout io_l16n_t2_13;
    inout io_l16n_t2_16;
    inout io_l16n_t2_17;
    inout io_l16n_t2_18;
    inout io_l16n_t2_32;
    inout io_l16n_t2_33;
    inout io_l16n_t2_34;
    inout io_l16n_t2_a15_d31_14;
    inout io_l16n_t2_a27_15;
    inout io_l16p_t2_12;
    inout io_l16p_t2_13;
    inout io_l16p_t2_16;
    inout io_l16p_t2_17;
    inout io_l16p_t2_18;
    inout io_l16p_t2_32;
    inout io_l16p_t2_33;
    inout io_l16p_t2_34;
    inout io_l16p_t2_a28_15;
    inout io_l16p_t2_csi_b_14;
    inout io_l17n_t2_12;
    inout io_l17n_t2_13;
    inout io_l17n_t2_16;
    inout io_l17n_t2_17;
    inout io_l17n_t2_18;
    inout io_l17n_t2_32;
    inout io_l17n_t2_33;
    inout io_l17n_t2_34;
    inout io_l17n_t2_a13_d29_14;
    inout io_l17n_t2_a25_15;
    inout io_l17p_t2_12;
    inout io_l17p_t2_13;
    inout io_l17p_t2_16;
    inout io_l17p_t2_17;
    inout io_l17p_t2_18;
    inout io_l17p_t2_32;
    inout io_l17p_t2_33;
    inout io_l17p_t2_34;
    inout io_l17p_t2_a14_d30_14;
    inout io_l17p_t2_a26_15;
    inout io_l18n_t2_12;
    inout io_l18n_t2_13;
    inout io_l18n_t2_16;
    inout io_l18n_t2_17;
    inout io_l18n_t2_18;
    inout io_l18n_t2_32;
    inout io_l18n_t2_33;
    inout io_l18n_t2_34;
    inout io_l18n_t2_a11_d27_14;
    inout io_l18n_t2_a23_15;
    inout io_l18p_t2_12;
    inout io_l18p_t2_13;
    inout io_l18p_t2_16;
    inout io_l18p_t2_17;
    inout io_l18p_t2_18;
    inout io_l18p_t2_32;
    inout io_l18p_t2_33;
    inout io_l18p_t2_34;
    inout io_l18p_t2_a12_d28_14;
    inout io_l18p_t2_a24_15;
    inout io_l19n_t3_a09_d25_vref_14;
    inout io_l19n_t3_a21_vref_15;
    inout io_l19n_t3_vref_12;
    inout io_l19n_t3_vref_13;
    inout io_l19n_t3_vref_16;
    inout io_l19n_t3_vref_17;
    inout io_l19n_t3_vref_18;
    inout io_l19n_t3_vref_32;
    inout io_l19n_t3_vref_33;
    inout io_l19n_t3_vref_34;
    inout io_l19p_t3_12;
    inout io_l19p_t3_13;
    inout io_l19p_t3_16;
    inout io_l19p_t3_17;
    inout io_l19p_t3_18;
    inout io_l19p_t3_32;
    inout io_l19p_t3_33;
    inout io_l19p_t3_34;
    inout io_l19p_t3_a10_d26_14;
    inout io_l19p_t3_a22_15;
    inout io_l1n_t0_12;
    inout io_l1n_t0_13;
    inout io_l1n_t0_16;
    inout io_l1n_t0_17;
    inout io_l1n_t0_18;
    inout io_l1n_t0_32;
    inout io_l1n_t0_33;
    inout io_l1n_t0_34;
    inout io_l1n_t0_ad0n_15;
    inout io_l1n_t0_d01_din_14;
    inout io_l1p_t0_12;
    inout io_l1p_t0_13;
    inout io_l1p_t0_16;
    inout io_l1p_t0_17;
    inout io_l1p_t0_18;
    inout io_l1p_t0_32;
    inout io_l1p_t0_33;
    inout io_l1p_t0_34;
    inout io_l1p_t0_ad0p_15;
    inout io_l1p_t0_d00_mosi_14;
    inout io_l20n_t3_12;
    inout io_l20n_t3_13;
    inout io_l20n_t3_16;
    inout io_l20n_t3_17;
    inout io_l20n_t3_18;
    inout io_l20n_t3_32;
    inout io_l20n_t3_33;
    inout io_l20n_t3_34;
    inout io_l20n_t3_a07_d23_14;
    inout io_l20n_t3_a19_15;
    inout io_l20p_t3_12;
    inout io_l20p_t3_13;
    inout io_l20p_t3_16;
    inout io_l20p_t3_17;
    inout io_l20p_t3_18;
    inout io_l20p_t3_32;
    inout io_l20p_t3_33;
    inout io_l20p_t3_34;
    inout io_l20p_t3_a08_d24_14;
    inout io_l20p_t3_a20_15;
    inout io_l21n_t3_dqs_12;
    inout io_l21n_t3_dqs_13;
    inout io_l21n_t3_dqs_16;
    inout io_l21n_t3_dqs_17;
    inout io_l21n_t3_dqs_18;
    inout io_l21n_t3_dqs_32;
    inout io_l21n_t3_dqs_33;
    inout io_l21n_t3_dqs_34;
    inout io_l21n_t3_dqs_a06_d22_14;
    inout io_l21n_t3_dqs_a18_15;
    inout io_l21p_t3_dqs_12;
    inout io_l21p_t3_dqs_13;
    inout io_l21p_t3_dqs_14;
    inout io_l21p_t3_dqs_15;
    inout io_l21p_t3_dqs_16;
    inout io_l21p_t3_dqs_17;
    inout io_l21p_t3_dqs_18;
    inout io_l21p_t3_dqs_32;
    inout io_l21p_t3_dqs_33;
    inout io_l21p_t3_dqs_34;
    inout io_l22n_t3_12;
    inout io_l22n_t3_13;
    inout io_l22n_t3_16;
    inout io_l22n_t3_17;
    inout io_l22n_t3_18;
    inout io_l22n_t3_32;
    inout io_l22n_t3_33;
    inout io_l22n_t3_34;
    inout io_l22n_t3_a04_d20_14;
    inout io_l22n_t3_a16_15;
    inout io_l22p_t3_12;
    inout io_l22p_t3_13;
    inout io_l22p_t3_16;
    inout io_l22p_t3_17;
    inout io_l22p_t3_18;
    inout io_l22p_t3_32;
    inout io_l22p_t3_33;
    inout io_l22p_t3_34;
    inout io_l22p_t3_a05_d21_14;
    inout io_l22p_t3_a17_15;
    inout io_l23n_t3_12;
    inout io_l23n_t3_13;
    inout io_l23n_t3_16;
    inout io_l23n_t3_17;
    inout io_l23n_t3_18;
    inout io_l23n_t3_32;
    inout io_l23n_t3_33;
    inout io_l23n_t3_34;
    inout io_l23n_t3_a02_d18_14;
    inout io_l23n_t3_fwe_b_15;
    inout io_l23p_t3_12;
    inout io_l23p_t3_13;
    inout io_l23p_t3_16;
    inout io_l23p_t3_17;
    inout io_l23p_t3_18;
    inout io_l23p_t3_32;
    inout io_l23p_t3_33;
    inout io_l23p_t3_34;
    inout io_l23p_t3_a03_d19_14;
    inout io_l23p_t3_foe_b_15;
    inout io_l24n_t3_12;
    inout io_l24n_t3_13;
    inout io_l24n_t3_16;
    inout io_l24n_t3_17;
    inout io_l24n_t3_18;
    inout io_l24n_t3_32;
    inout io_l24n_t3_33;
    inout io_l24n_t3_34;
    inout io_l24n_t3_a00_d16_14;
    inout io_l24n_t3_rs0_15;
    inout io_l24p_t3_12;
    inout io_l24p_t3_13;
    inout io_l24p_t3_16;
    inout io_l24p_t3_17;
    inout io_l24p_t3_18;
    inout io_l24p_t3_32;
    inout io_l24p_t3_33;
    inout io_l24p_t3_34;
    inout io_l24p_t3_a01_d17_14;
    inout io_l24p_t3_rs1_15;
    inout io_l2n_t0_12;
    inout io_l2n_t0_13;
    inout io_l2n_t0_16;
    inout io_l2n_t0_17;
    inout io_l2n_t0_18;
    inout io_l2n_t0_32;
    inout io_l2n_t0_33;
    inout io_l2n_t0_34;
    inout io_l2n_t0_ad8n_15;
    inout io_l2n_t0_d03_14;
    inout io_l2p_t0_12;
    inout io_l2p_t0_13;
    inout io_l2p_t0_16;
    inout io_l2p_t0_17;
    inout io_l2p_t0_18;
    inout io_l2p_t0_32;
    inout io_l2p_t0_33;
    inout io_l2p_t0_34;
    inout io_l2p_t0_ad8p_15;
    inout io_l2p_t0_d02_14;
    inout io_l3n_t0_dqs_12;
    inout io_l3n_t0_dqs_13;
    inout io_l3n_t0_dqs_16;
    inout io_l3n_t0_dqs_17;
    inout io_l3n_t0_dqs_18;
    inout io_l3n_t0_dqs_32;
    inout io_l3n_t0_dqs_33;
    inout io_l3n_t0_dqs_34;
    inout io_l3n_t0_dqs_ad1n_15;
    inout io_l3n_t0_dqs_emcclk_14;
    inout io_l3p_t0_dqs_12;
    inout io_l3p_t0_dqs_13;
    inout io_l3p_t0_dqs_16;
    inout io_l3p_t0_dqs_17;
    inout io_l3p_t0_dqs_18;
    inout io_l3p_t0_dqs_32;
    inout io_l3p_t0_dqs_33;
    inout io_l3p_t0_dqs_34;
    inout io_l3p_t0_dqs_ad1p_15;
    inout io_l3p_t0_dqs_pudc_b_14;
    inout io_l4n_t0_12;
    inout io_l4n_t0_13;
    inout io_l4n_t0_16;
    inout io_l4n_t0_17;
    inout io_l4n_t0_18;
    inout io_l4n_t0_32;
    inout io_l4n_t0_33;
    inout io_l4n_t0_34;
    inout io_l4n_t0_ad9n_15;
    inout io_l4n_t0_d05_14;
    inout io_l4p_t0_12;
    inout io_l4p_t0_13;
    inout io_l4p_t0_16;
    inout io_l4p_t0_17;
    inout io_l4p_t0_18;
    inout io_l4p_t0_32;
    inout io_l4p_t0_33;
    inout io_l4p_t0_34;
    inout io_l4p_t0_ad9p_15;
    inout io_l4p_t0_d04_14;
    inout io_l5n_t0_12;
    inout io_l5n_t0_13;
    inout io_l5n_t0_16;
    inout io_l5n_t0_17;
    inout io_l5n_t0_18;
    inout io_l5n_t0_32;
    inout io_l5n_t0_33;
    inout io_l5n_t0_34;
    inout io_l5n_t0_ad2n_15;
    inout io_l5n_t0_d07_14;
    inout io_l5p_t0_12;
    inout io_l5p_t0_13;
    inout io_l5p_t0_16;
    inout io_l5p_t0_17;
    inout io_l5p_t0_18;
    inout io_l5p_t0_32;
    inout io_l5p_t0_33;
    inout io_l5p_t0_34;
    inout io_l5p_t0_ad2p_15;
    inout io_l5p_t0_d06_14;
    inout io_l6n_t0_d08_vref_14;
    inout io_l6n_t0_vref_12;
    inout io_l6n_t0_vref_13;
    inout io_l6n_t0_vref_15;
    inout io_l6n_t0_vref_16;
    inout io_l6n_t0_vref_17;
    inout io_l6n_t0_vref_18;
    inout io_l6n_t0_vref_32;
    inout io_l6n_t0_vref_33;
    inout io_l6n_t0_vref_34;
    inout io_l6p_t0_12;
    inout io_l6p_t0_13;
    inout io_l6p_t0_15;
    inout io_l6p_t0_16;
    inout io_l6p_t0_17;
    inout io_l6p_t0_18;
    inout io_l6p_t0_32;
    inout io_l6p_t0_33;
    inout io_l6p_t0_34;
    inout io_l6p_t0_fcs_b_14;
    inout io_l7n_t1_12;
    inout io_l7n_t1_13;
    inout io_l7n_t1_16;
    inout io_l7n_t1_17;
    inout io_l7n_t1_18;
    inout io_l7n_t1_32;
    inout io_l7n_t1_33;
    inout io_l7n_t1_34;
    inout io_l7n_t1_ad10n_15;
    inout io_l7n_t1_d10_14;
    inout io_l7p_t1_12;
    inout io_l7p_t1_13;
    inout io_l7p_t1_16;
    inout io_l7p_t1_17;
    inout io_l7p_t1_18;
    inout io_l7p_t1_32;
    inout io_l7p_t1_33;
    inout io_l7p_t1_34;
    inout io_l7p_t1_ad10p_15;
    inout io_l7p_t1_d09_14;
    inout io_l8n_t1_12;
    inout io_l8n_t1_13;
    inout io_l8n_t1_16;
    inout io_l8n_t1_17;
    inout io_l8n_t1_18;
    inout io_l8n_t1_32;
    inout io_l8n_t1_33;
    inout io_l8n_t1_34;
    inout io_l8n_t1_ad3n_15;
    inout io_l8n_t1_d12_14;
    inout io_l8p_t1_12;
    inout io_l8p_t1_13;
    inout io_l8p_t1_16;
    inout io_l8p_t1_17;
    inout io_l8p_t1_18;
    inout io_l8p_t1_32;
    inout io_l8p_t1_33;
    inout io_l8p_t1_34;
    inout io_l8p_t1_ad3p_15;
    inout io_l8p_t1_d11_14;
    inout io_l9n_t1_dqs_12;
    inout io_l9n_t1_dqs_13;
    inout io_l9n_t1_dqs_16;
    inout io_l9n_t1_dqs_17;
    inout io_l9n_t1_dqs_18;
    inout io_l9n_t1_dqs_32;
    inout io_l9n_t1_dqs_33;
    inout io_l9n_t1_dqs_34;
    inout io_l9n_t1_dqs_ad11n_15;
    inout io_l9n_t1_dqs_d13_14;
    inout io_l9p_t1_dqs_12;
    inout io_l9p_t1_dqs_13;
    inout io_l9p_t1_dqs_14;
    inout io_l9p_t1_dqs_16;
    inout io_l9p_t1_dqs_17;
    inout io_l9p_t1_dqs_18;
    inout io_l9p_t1_dqs_32;
    inout io_l9p_t1_dqs_33;
    inout io_l9p_t1_dqs_34;
    inout io_l9p_t1_dqs_ad11p_15;
    inout m0_0;
    inout m1_0;
    inout m2_0;
    inout [7:1] mgtavcc;
    inout [18:1] mgtavtt;
    inout mgtavttrcal_115;
    inout mgtrefclk0n_115;
    inout mgtrefclk0n_116;
    inout mgtrefclk0n_117;
    inout mgtrefclk0n_118;
    inout mgtrefclk0p_115;
    inout mgtrefclk0p_116;
    inout mgtrefclk0p_117;
    inout mgtrefclk0p_118;
    inout mgtrefclk1n_115;
    inout mgtrefclk1n_116;
    inout mgtrefclk1n_117;
    inout mgtrefclk1n_118;
    inout mgtrefclk1p_115;
    inout mgtrefclk1p_116;
    inout mgtrefclk1p_117;
    inout mgtrefclk1p_118;
    inout mgtrref_115;
    inout [2:1] mgtvccaux;
    inout mgtxrxn0_115;
    inout mgtxrxn0_116;
    inout mgtxrxn0_117;
    inout mgtxrxn0_118;
    inout mgtxrxn1_115;
    inout mgtxrxn1_116;
    inout mgtxrxn1_117;
    inout mgtxrxn1_118;
    inout mgtxrxn2_115;
    inout mgtxrxn2_116;
    inout mgtxrxn2_117;
    inout mgtxrxn2_118;
    inout mgtxrxn3_115;
    inout mgtxrxn3_116;
    inout mgtxrxn3_117;
    inout mgtxrxn3_118;
    inout mgtxrxp0_115;
    inout mgtxrxp0_116;
    inout mgtxrxp0_117;
    inout mgtxrxp0_118;
    inout mgtxrxp1_115;
    inout mgtxrxp1_116;
    inout mgtxrxp1_117;
    inout mgtxrxp1_118;
    inout mgtxrxp2_115;
    inout mgtxrxp2_116;
    inout mgtxrxp2_117;
    inout mgtxrxp2_118;
    inout mgtxrxp3_115;
    inout mgtxrxp3_116;
    inout mgtxrxp3_117;
    inout mgtxrxp3_118;
    inout mgtxtxn0_115;
    inout mgtxtxn0_116;
    inout mgtxtxn0_117;
    inout mgtxtxn0_118;
    inout mgtxtxn1_115;
    inout mgtxtxn1_116;
    inout mgtxtxn1_117;
    inout mgtxtxn1_118;
    inout mgtxtxn2_115;
    inout mgtxtxn2_116;
    inout mgtxtxn2_117;
    inout mgtxtxn2_118;
    inout mgtxtxn3_115;
    inout mgtxtxn3_116;
    inout mgtxtxn3_117;
    inout mgtxtxn3_118;
    inout mgtxtxp0_115;
    inout mgtxtxp0_116;
    inout mgtxtxp0_117;
    inout mgtxtxp0_118;
    inout mgtxtxp1_115;
    inout mgtxtxp1_116;
    inout mgtxtxp1_117;
    inout mgtxtxp1_118;
    inout mgtxtxp2_115;
    inout mgtxtxp2_116;
    inout mgtxtxp2_117;
    inout mgtxtxp2_118;
    inout mgtxtxp3_115;
    inout mgtxtxp3_116;
    inout mgtxtxp3_117;
    inout mgtxtxp3_118;
    inout program_b_0;
    inout tck_0;
    inout tdi_0;
    inout tdo_0;
    inout tms_0;
    inout vccadc_0;
    inout [5:1] vccaux;
    inout [3:1] vccaux_io_g0;
    inout vccbatt_0;
    inout [4:1] vccbram;
    inout [20:1] vccint;
    inout [2:1] vcco_0;
    inout [6:1] vcco_12;
    inout [6:1] vcco_13;
    inout [6:1] vcco_14;
    inout [6:1] vcco_15;
    inout [7:1] vcco_16;
    inout [7:1] vcco_17;
    inout [6:1] vcco_18;
    inout [6:1] vcco_32;
    inout [6:1] vcco_33;
    inout [7:1] vcco_34;
    inout vn_0;
    inout vp_0;
    inout vrefn_0;
    inout vrefp_0;


    initial
        begin
        end

endmodule
