-- generated by newgenasym Thu Apr 21 11:57:59 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pj_20 is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end pj_20;
