// generated by newgenasym  Fri Aug 21 11:19:41 2009


module \74lv573pw  (d0, d1, d2, d3, d4, d5, d6, d7, gnd, le, oen, q0, q1, q2, q3, q4, q5,
        q6, q7, vcc);
    input d0;
    output d1;
    input d2;
    output d3;
    input d4;
    output d5;
    input d6;
    output d7;
    input gnd;
    input le;
    input oen;
    input q0;
    output q1;
    input q2;
    output q3;
    input q4;
    output q5;
    input q6;
    output q7;
    input vcc;


    initial
        begin
        end

endmodule
