-- generated by newgenasym Fri Aug 21 11:19:41 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lv573pw\ is
    port (    
	D0:        IN     STD_LOGIC;    
	D1:        OUT    STD_LOGIC;    
	D2:        IN     STD_LOGIC;    
	D3:        OUT    STD_LOGIC;    
	D4:        IN     STD_LOGIC;    
	D5:        OUT    STD_LOGIC;    
	D6:        IN     STD_LOGIC;    
	D7:        OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	LE:        IN     STD_LOGIC;    
	OEN:       IN     STD_LOGIC;    
	Q0:        IN     STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        IN     STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	Q4:        IN     STD_LOGIC;    
	Q5:        OUT    STD_LOGIC;    
	Q6:        IN     STD_LOGIC;    
	Q7:        OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end \74lv573pw\;
