// generated by newgenasym  Mon Apr 27 15:11:26 2009


module xc5vsx50t_1ffg1136i (avdd_0, avss_0, cclk_0, cs_b_0, d_in_0, d_out_busy_0,
        done_0, dxn_0, dxp_0, float, gnd1, gnd10, gnd100, gnd101,
        gnd102, gnd103, gnd104, gnd105, gnd106, gnd107, gnd108,
        gnd109, gnd11, gnd110, gnd111, gnd112, gnd113, gnd114,
        gnd115, gnd116, gnd117, gnd118, gnd119, gnd12, gnd120,
        gnd121, gnd122, gnd123, gnd124, gnd125, gnd126, gnd127,
        gnd128, gnd129, gnd13, gnd130, gnd131, gnd132, gnd133,
        gnd134, gnd135, gnd136, gnd137, gnd138, gnd139, gnd14,
        gnd140, gnd141, gnd142, gnd143, gnd144, gnd145, gnd146,
        gnd147, gnd148, gnd149, gnd15, gnd150, gnd151, gnd152,
        gnd153, gnd154, gnd155, gnd156, gnd157, gnd158, gnd159,
        gnd16, gnd160, gnd161, gnd162, gnd163, gnd164, gnd165,
        gnd166, gnd167, gnd168, gnd169, gnd17, gnd170, gnd171,
        gnd172, gnd173, gnd174, gnd175, gnd176, gnd177, gnd178,
        gnd179, gnd18, gnd180, gnd181, gnd182, gnd183, gnd184,
        gnd185, gnd186, gnd187, gnd188, gnd189, gnd19, gnd190,
        gnd191, gnd192, gnd193, gnd194, gnd195, gnd196, gnd197,
        gnd198, gnd199, gnd2, gnd20, gnd200, gnd201, gnd202, gnd203,
        gnd204, gnd205, gnd206, gnd207, gnd208, gnd209, gnd21,
        gnd210, gnd211, gnd212, gnd213, gnd214, gnd215, gnd216,
        gnd217, gnd218, gnd219, gnd22, gnd23, gnd24, gnd25, gnd26,
        gnd27, gnd28, gnd29, gnd3, gnd30, gnd31, gnd32, gnd33, gnd34,
        gnd35, gnd36, gnd37, gnd38, gnd39, gnd4, gnd40, gnd41, gnd42,
        gnd43, gnd44, gnd45, gnd46, gnd47, gnd48, gnd49, gnd5, gnd50,
        gnd51, gnd52, gnd53, gnd54, gnd55, gnd56, gnd57, gnd58, gnd59,
        gnd6, gnd60, gnd61, gnd62, gnd63, gnd64, gnd65, gnd66, gnd67,
        gnd68, gnd69, gnd7, gnd70, gnd71, gnd72, gnd73, gnd74, gnd75,
        gnd76, gnd77, gnd78, gnd79, gnd8, gnd80, gnd81, gnd82, gnd83,
        gnd84, gnd85, gnd86, gnd87, gnd88, gnd89, gnd9, gnd90, gnd91,
        gnd92, gnd93, gnd94, gnd95, gnd96, gnd97, gnd98, gnd99,
        hswapen_0, init_b_0, io_l0n_11, io_l0n_12, io_l0n_15,
        io_l0n_17, io_l0n_18, io_l0n_19, io_l0n_20, io_l0n_21,
        io_l0n_22, io_l0n_a18_1, io_l0n_cc_gc_3, io_l0n_cc_rs0_2,
        io_l0n_gc_d14_4, io_l0n_sm8n_13, io_l0p_11, io_l0p_12,
        io_l0p_15, io_l0p_17, io_l0p_18, io_l0p_19, io_l0p_20,
        io_l0p_21, io_l0p_22, io_l0p_a19_1, io_l0p_cc_gc_3,
        io_l0p_cc_rs1_2, io_l0p_gc_d15_4, io_l0p_sm8p_13,
        io_l10n_cc_12, io_l10n_cc_13, io_l10n_cc_15,
        io_l10n_cc_17, io_l10n_cc_18, io_l10n_cc_19,
        io_l10n_cc_20, io_l10n_cc_21, io_l10n_cc_22,
        io_l10n_cc_sm15n_11, io_l10p_cc_12, io_l10p_cc_13,
        io_l10p_cc_15, io_l10p_cc_17, io_l10p_cc_18,
        io_l10p_cc_19, io_l10p_cc_20, io_l10p_cc_21,
        io_l10p_cc_22, io_l10p_cc_sm15p_11, io_l11n_cc_12,
        io_l11n_cc_13, io_l11n_cc_15, io_l11n_cc_17,
        io_l11n_cc_18, io_l11n_cc_19, io_l11n_cc_20,
        io_l11n_cc_21, io_l11n_cc_22, io_l11n_cc_sm14n_11,
        io_l11p_cc_12, io_l11p_cc_13, io_l11p_cc_15,
        io_l11p_cc_17, io_l11p_cc_18, io_l11p_cc_19,
        io_l11p_cc_20, io_l11p_cc_21, io_l11p_cc_22,
        io_l11p_cc_sm14p_11, io_l12n_vrp_11, io_l12n_vrp_12,
        io_l12n_vrp_13, io_l12n_vrp_15, io_l12n_vrp_17,
        io_l12n_vrp_18, io_l12n_vrp_19, io_l12n_vrp_20,
        io_l12n_vrp_21, io_l12n_vrp_22, io_l12p_vrn_11,
        io_l12p_vrn_12, io_l12p_vrn_13, io_l12p_vrn_15,
        io_l12p_vrn_17, io_l12p_vrn_18, io_l12p_vrn_19,
        io_l12p_vrn_20, io_l12p_vrn_21, io_l12p_vrn_22,
        io_l13n_11, io_l13n_12, io_l13n_13, io_l13n_15,
        io_l13n_17, io_l13n_18, io_l13n_19, io_l13n_20,
        io_l13n_21, io_l13n_22, io_l13p_11, io_l13p_12,
        io_l13p_13, io_l13p_15, io_l13p_17, io_l13p_18,
        io_l13p_19, io_l13p_20, io_l13p_21, io_l13p_22,
        io_l14n_vref_11, io_l14n_vref_12, io_l14n_vref_13,
        io_l14n_vref_15, io_l14n_vref_17, io_l14n_vref_18,
        io_l14n_vref_19, io_l14n_vref_20, io_l14n_vref_21,
        io_l14n_vref_22, io_l14p_11, io_l14p_12, io_l14p_13,
        io_l14p_15, io_l14p_17, io_l14p_18, io_l14p_19,
        io_l14p_20, io_l14p_21, io_l14p_22, io_l15n_12,
        io_l15n_13, io_l15n_15, io_l15n_17, io_l15n_18,
        io_l15n_19, io_l15n_20, io_l15n_21, io_l15n_22,
        io_l15n_sm13n_11, io_l15p_12, io_l15p_13, io_l15p_15,
        io_l15p_17, io_l15p_18, io_l15p_19, io_l15p_20,
        io_l15p_21, io_l15p_22, io_l15p_sm13p_11, io_l16n_12,
        io_l16n_13, io_l16n_15, io_l16n_17, io_l16n_18,
        io_l16n_19, io_l16n_20, io_l16n_21, io_l16n_22,
        io_l16n_sm12n_11, io_l16p_12, io_l16p_13, io_l16p_15,
        io_l16p_17, io_l16p_18, io_l16p_19, io_l16p_20,
        io_l16p_21, io_l16p_22, io_l16p_sm12p_11, io_l17n_12,
        io_l17n_13, io_l17n_15, io_l17n_17, io_l17n_18,
        io_l17n_19, io_l17n_20, io_l17n_21, io_l17n_22,
        io_l17n_sm11n_11, io_l17p_12, io_l17p_13, io_l17p_15,
        io_l17p_17, io_l17p_18, io_l17p_19, io_l17p_20,
        io_l17p_21, io_l17p_22, io_l17p_sm11p_11, io_l18n_12,
        io_l18n_13, io_l18n_15, io_l18n_17, io_l18n_18,
        io_l18n_19, io_l18n_20, io_l18n_21, io_l18n_22,
        io_l18n_sm10n_11, io_l18p_12, io_l18p_13, io_l18p_15,
        io_l18p_17, io_l18p_18, io_l18p_19, io_l18p_20,
        io_l18p_21, io_l18p_22, io_l18p_sm10p_11, io_l19n_12,
        io_l19n_13, io_l19n_15, io_l19n_17, io_l19n_18,
        io_l19n_19, io_l19n_20, io_l19n_21, io_l19n_22,
        io_l19n_sm9n_11, io_l19p_12, io_l19p_13, io_l19p_15,
        io_l19p_17, io_l19p_18, io_l19p_19, io_l19p_20,
        io_l19p_21, io_l19p_22, io_l19p_sm9p_11, io_l1n_11,
        io_l1n_12, io_l1n_15, io_l1n_17, io_l1n_18, io_l1n_19,
        io_l1n_20, io_l1n_21, io_l1n_22, io_l1n_a16_1,
        io_l1n_cc_a24_2, io_l1n_cc_gc_3, io_l1n_gc_d12_4,
        io_l1n_sm7n_13, io_l1p_11, io_l1p_12, io_l1p_15,
        io_l1p_17, io_l1p_18, io_l1p_19, io_l1p_20, io_l1p_21,
        io_l1p_22, io_l1p_a17_1, io_l1p_cc_a25_2, io_l1p_cc_gc_3,
        io_l1p_gc_d13_4, io_l1p_sm7p_13, io_l2n_11, io_l2n_12,
        io_l2n_15, io_l2n_17, io_l2n_18, io_l2n_19, io_l2n_20,
        io_l2n_21, io_l2n_22, io_l2n_a14_d30_1, io_l2n_a22_2,
        io_l2n_gc_d10_4, io_l2n_gc_vrp_3, io_l2n_sm6n_13,
        io_l2p_11, io_l2p_12, io_l2p_15, io_l2p_17, io_l2p_18,
        io_l2p_19, io_l2p_20, io_l2p_21, io_l2p_22,
        io_l2p_a15_d31_1, io_l2p_a23_2, io_l2p_gc_d11_4,
        io_l2p_gc_vrn_3, io_l2p_sm6p_13, io_l3n_11, io_l3n_12,
        io_l3n_15, io_l3n_17, io_l3n_18, io_l3n_19, io_l3n_20,
        io_l3n_21, io_l3n_22, io_l3n_a12_d28_1, io_l3n_a20_2,
        io_l3n_gc_3, io_l3n_gc_d8_4, io_l3n_sm5n_13, io_l3p_11,
        io_l3p_12, io_l3p_15, io_l3p_17, io_l3p_18, io_l3p_19,
        io_l3p_20, io_l3p_21, io_l3p_22, io_l3p_a13_d29_1,
        io_l3p_a21_2, io_l3p_gc_3, io_l3p_gc_d9_4,
        io_l3p_sm5p_13, io_l4n_gc_vref_3, io_l4n_gc_vref_4,
        io_l4n_vref_11, io_l4n_vref_12, io_l4n_vref_13,
        io_l4n_vref_15, io_l4n_vref_17, io_l4n_vref_18,
        io_l4n_vref_19, io_l4n_vref_20, io_l4n_vref_21,
        io_l4n_vref_22, io_l4n_vref_a10_d26_1,
        io_l4n_vref_foe_b_mosi_2, io_l4p_11, io_l4p_12,
        io_l4p_13, io_l4p_15, io_l4p_17, io_l4p_18, io_l4p_19,
        io_l4p_20, io_l4p_21, io_l4p_22, io_l4p_a11_d27_1,
        io_l4p_fcs_b_2, io_l4p_gc_3, io_l4p_gc_4, io_l5n_11,
        io_l5n_12, io_l5n_15, io_l5n_17, io_l5n_18, io_l5n_19,
        io_l5n_20, io_l5n_21, io_l5n_22, io_l5n_a8_d24_1,
        io_l5n_cso_b_2, io_l5n_gc_3, io_l5n_gc_4, io_l5n_sm4n_13,
        io_l5p_11, io_l5p_12, io_l5p_15, io_l5p_17, io_l5p_18,
        io_l5p_19, io_l5p_20, io_l5p_21, io_l5p_22,
        io_l5p_a9_d25_1, io_l5p_fwe_b_2, io_l5p_gc_3,
        io_l5p_gc_4, io_l5p_sm4p_13, io_l6n_11, io_l6n_12,
        io_l6n_15, io_l6n_17, io_l6n_18, io_l6n_19, io_l6n_20,
        io_l6n_21, io_l6n_22, io_l6n_a6_d22_1, io_l6n_d6_2,
        io_l6n_gc_3, io_l6n_gc_4, io_l6n_sm3n_13, io_l6p_11,
        io_l6p_12, io_l6p_15, io_l6p_17, io_l6p_18, io_l6p_19,
        io_l6p_20, io_l6p_21, io_l6p_22, io_l6p_a7_d23_1,
        io_l6p_d7_2, io_l6p_gc_3, io_l6p_gc_4, io_l6p_sm3p_13,
        io_l7n_11, io_l7n_12, io_l7n_15, io_l7n_17, io_l7n_18,
        io_l7n_19, io_l7n_20, io_l7n_21, io_l7n_22,
        io_l7n_a4_d20_1, io_l7n_d4_2, io_l7n_gc_3,
        io_l7n_gc_vrp_4, io_l7n_sm2n_13, io_l7p_11, io_l7p_12,
        io_l7p_15, io_l7p_17, io_l7p_18, io_l7p_19, io_l7p_20,
        io_l7p_21, io_l7p_22, io_l7p_a5_d21_1, io_l7p_d5_2,
        io_l7p_gc_3, io_l7p_gc_vrn_4, io_l7p_sm2p_13,
        io_l8n_cc_11, io_l8n_cc_12, io_l8n_cc_15, io_l8n_cc_17,
        io_l8n_cc_18, io_l8n_cc_19, io_l8n_cc_20, io_l8n_cc_21,
        io_l8n_cc_22, io_l8n_cc_a2_d18_1, io_l8n_cc_gc_4,
        io_l8n_cc_sm1n_13, io_l8n_d2_fs2_2, io_l8n_gc_3,
        io_l8p_cc_11, io_l8p_cc_12, io_l8p_cc_15, io_l8p_cc_17,
        io_l8p_cc_18, io_l8p_cc_19, io_l8p_cc_20, io_l8p_cc_21,
        io_l8p_cc_22, io_l8p_cc_a3_d19_1, io_l8p_cc_gc_4,
        io_l8p_cc_sm1p_13, io_l8p_d3_2, io_l8p_gc_3,
        io_l9n_cc_11, io_l9n_cc_12, io_l9n_cc_15, io_l9n_cc_17,
        io_l9n_cc_18, io_l9n_cc_19, io_l9n_cc_20, io_l9n_cc_21,
        io_l9n_cc_22, io_l9n_cc_a0_d16_1, io_l9n_cc_gc_4,
        io_l9n_cc_sm0n_13, io_l9n_d0_fs0_2, io_l9n_gc_3,
        io_l9p_cc_11, io_l9p_cc_12, io_l9p_cc_15, io_l9p_cc_17,
        io_l9p_cc_18, io_l9p_cc_19, io_l9p_cc_20, io_l9p_cc_21,
        io_l9p_cc_22, io_l9p_cc_a1_d17_1, io_l9p_cc_gc_4,
        io_l9p_cc_sm0p_13, io_l9p_d1_fs1_2, io_l9p_gc_3, m0_0,
        m1_0, m2_0, mgtavcc_112_1, mgtavcc_112_2, mgtavcc_114_1,
        mgtavcc_114_2, mgtavcc_116_1, mgtavcc_116_2,
        mgtavcc_118_1, mgtavcc_118_2, mgtavcc_120_1,
        mgtavcc_120_2, mgtavcc_122_1, mgtavcc_122_2,
        mgtavccpll_112, mgtavccpll_114, mgtavccpll_116,
        mgtavccpll_118, mgtavccpll_120, mgtavccpll_122,
        mgtavttrx_112, mgtavttrx_114, mgtavttrx_116,
        mgtavttrx_118, mgtavttrx_120, mgtavttrx_122, mgtavttrxc,
        mgtavtttx_112_1, mgtavtttx_112_2, mgtavtttx_114_1,
        mgtavtttx_114_2, mgtavtttx_116_1, mgtavtttx_116_2,
        mgtavtttx_118_1, mgtavtttx_118_2, mgtavtttx_120_1,
        mgtavtttx_120_2, mgtavtttx_122_1, mgtavtttx_122_2,
        mgtrefclkn_112, mgtrefclkn_114, mgtrefclkn_116,
        mgtrefclkn_118, mgtrefclkn_120, mgtrefclkn_122,
        mgtrefclkp_112, mgtrefclkp_114, mgtrefclkp_116,
        mgtrefclkp_118, mgtrefclkp_120, mgtrefclkp_122,
        mgtrref_112, mgtrxn0_112, mgtrxn0_114, mgtrxn0_116,
        mgtrxn0_118, mgtrxn0_120, mgtrxn0_122, mgtrxn1_112,
        mgtrxn1_114, mgtrxn1_116, mgtrxn1_118, mgtrxn1_120,
        mgtrxn1_122, mgtrxp0_112, mgtrxp0_114, mgtrxp0_116,
        mgtrxp0_118, mgtrxp0_120, mgtrxp0_122, mgtrxp1_112,
        mgtrxp1_114, mgtrxp1_116, mgtrxp1_118, mgtrxp1_120,
        mgtrxp1_122, mgttxn0_112, mgttxn0_114, mgttxn0_116,
        mgttxn0_118, mgttxn0_120, mgttxn0_122, mgttxn1_112,
        mgttxn1_114, mgttxn1_116, mgttxn1_118, mgttxn1_120,
        mgttxn1_122, mgttxp0_112, mgttxp0_114, mgttxp0_116,
        mgttxp0_118, mgttxp0_120, mgttxp0_122, mgttxp1_112,
        mgttxp1_114, mgttxp1_116, mgttxp1_118, mgttxp1_120,
        mgttxp1_122, nc1, nc10, nc100, nc101, nc102, nc103, nc104,
        nc105, nc106, nc107, nc108, nc109, nc11, nc110, nc111, nc112,
        nc113, nc114, nc115, nc116, nc117, nc118, nc119, nc12, nc120,
        nc121, nc122, nc123, nc124, nc125, nc126, nc127, nc128, nc129,
        nc13, nc130, nc131, nc132, nc133, nc134, nc135, nc136, nc137,
        nc138, nc139, nc14, nc140, nc141, nc142, nc143, nc144, nc145,
        nc146, nc147, nc148, nc149, nc15, nc150, nc151, nc152, nc153,
        nc154, nc155, nc156, nc157, nc158, nc159, nc16, nc160, nc161,
        nc162, nc163, nc164, nc165, nc166, nc167, nc168, nc169, nc17,
        nc170, nc171, nc172, nc173, nc174, nc175, nc176, nc177, nc178,
        nc179, nc18, nc180, nc181, nc182, nc183, nc184, nc185, nc186,
        nc187, nc188, nc189, nc19, nc190, nc191, nc192, nc193, nc2,
        nc20, nc21, nc22, nc23, nc24, nc25, nc26, nc27, nc28, nc29, nc3,
        nc30, nc31, nc32, nc33, nc34, nc35, nc36, nc37, nc38, nc39, nc4,
        nc40, nc41, nc42, nc43, nc44, nc45, nc46, nc47, nc48, nc49, nc5,
        nc50, nc51, nc52, nc53, nc54, nc55, nc56, nc57, nc58, nc59, nc6,
        nc60, nc61, nc62, nc63, nc64, nc65, nc66, nc67, nc68, nc69, nc7,
        nc70, nc71, nc72, nc73, nc74, nc75, nc76, nc77, nc78, nc79, nc8,
        nc80, nc81, nc82, nc83, nc84, nc85, nc86, nc87, nc88, nc89, nc9,
        nc90, nc91, nc92, nc93, nc94, nc95, nc96, nc97, nc98, nc99,
        program_b_0, rdwr_b_0, rsvd1, rsvd2, tck_0, tdi_0, tdo_0,
        tms_0, vbatt_0, vccaux1, vccaux10, vccaux11, vccaux12,
        vccaux2, vccaux3, vccaux4, vccaux5, vccaux6, vccaux7,
        vccaux8, vccaux9, vccint1, vccint10, vccint11, vccint12,
        vccint13, vccint14, vccint15, vccint16, vccint17, vccint18,
        vccint19, vccint2, vccint20, vccint21, vccint22, vccint23,
        vccint24, vccint25, vccint26, vccint27, vccint28, vccint29,
        vccint3, vccint30, vccint31, vccint32, vccint33, vccint34,
        vccint35, vccint36, vccint37, vccint38, vccint39, vccint4,
        vccint40, vccint41, vccint42, vccint43, vccint44, vccint45,
        vccint46, vccint47, vccint48, vccint49, vccint5, vccint50,
        vccint51, vccint52, vccint53, vccint54, vccint6, vccint7,
        vccint8, vccint9, vcco_0_1, vcco_0_2, vcco_11_1, vcco_11_2,
        vcco_11_3, vcco_12_1, vcco_12_2, vcco_12_3, vcco_13_1,
        vcco_13_2, vcco_13_3, vcco_15_1, vcco_15_2, vcco_15_3,
        vcco_17_1, vcco_17_2, vcco_17_3, vcco_18_1, vcco_18_2,
        vcco_18_3, vcco_19_1, vcco_19_2, vcco_19_3, vcco_1_1,
        vcco_1_2, vcco_20_1, vcco_20_2, vcco_20_3, vcco_21_1,
        vcco_21_2, vcco_21_3, vcco_22_1, vcco_22_2, vcco_22_3,
        vcco_23_1, vcco_23_2, vcco_23_3, vcco_25_1, vcco_25_2,
        vcco_25_3, vcco_2_1, vcco_2_2, vcco_3_1, vcco_3_2,
        vcco_4_1, vcco_4_2, vcco_5_1, vcco_5_2, vcco_5_3, vcco_6_1,
        vcco_6_2, vcco_6_3, vn_0, vp_0, vrefn_0, vrefp_0);
    inout avdd_0;
    inout avss_0;
    inout cclk_0;
    inout cs_b_0;
    inout d_in_0;
    inout d_out_busy_0;
    inout done_0;
    inout dxn_0;
    inout dxp_0;
    inout float;
    input gnd1;
    input gnd10;
    input gnd100;
    input gnd101;
    input gnd102;
    input gnd103;
    input gnd104;
    input gnd105;
    input gnd106;
    input gnd107;
    input gnd108;
    input gnd109;
    input gnd11;
    input gnd110;
    input gnd111;
    input gnd112;
    input gnd113;
    input gnd114;
    input gnd115;
    input gnd116;
    input gnd117;
    input gnd118;
    input gnd119;
    input gnd12;
    input gnd120;
    input gnd121;
    input gnd122;
    input gnd123;
    input gnd124;
    input gnd125;
    input gnd126;
    input gnd127;
    input gnd128;
    input gnd129;
    input gnd13;
    input gnd130;
    input gnd131;
    input gnd132;
    input gnd133;
    input gnd134;
    input gnd135;
    input gnd136;
    input gnd137;
    input gnd138;
    input gnd139;
    input gnd14;
    input gnd140;
    input gnd141;
    input gnd142;
    input gnd143;
    input gnd144;
    input gnd145;
    input gnd146;
    input gnd147;
    input gnd148;
    input gnd149;
    input gnd15;
    input gnd150;
    input gnd151;
    input gnd152;
    input gnd153;
    input gnd154;
    input gnd155;
    input gnd156;
    input gnd157;
    input gnd158;
    input gnd159;
    input gnd16;
    input gnd160;
    input gnd161;
    input gnd162;
    input gnd163;
    input gnd164;
    input gnd165;
    input gnd166;
    input gnd167;
    input gnd168;
    input gnd169;
    input gnd17;
    input gnd170;
    input gnd171;
    input gnd172;
    input gnd173;
    input gnd174;
    input gnd175;
    input gnd176;
    input gnd177;
    input gnd178;
    input gnd179;
    input gnd18;
    input gnd180;
    input gnd181;
    input gnd182;
    input gnd183;
    input gnd184;
    input gnd185;
    input gnd186;
    input gnd187;
    input gnd188;
    input gnd189;
    input gnd19;
    input gnd190;
    input gnd191;
    input gnd192;
    input gnd193;
    input gnd194;
    input gnd195;
    input gnd196;
    input gnd197;
    input gnd198;
    input gnd199;
    input gnd2;
    input gnd20;
    input gnd200;
    input gnd201;
    input gnd202;
    input gnd203;
    input gnd204;
    input gnd205;
    input gnd206;
    input gnd207;
    input gnd208;
    input gnd209;
    input gnd21;
    input gnd210;
    input gnd211;
    input gnd212;
    input gnd213;
    input gnd214;
    input gnd215;
    input gnd216;
    input gnd217;
    input gnd218;
    input gnd219;
    input gnd22;
    input gnd23;
    input gnd24;
    input gnd25;
    input gnd26;
    input gnd27;
    input gnd28;
    input gnd29;
    input gnd3;
    input gnd30;
    input gnd31;
    input gnd32;
    input gnd33;
    input gnd34;
    input gnd35;
    input gnd36;
    input gnd37;
    input gnd38;
    input gnd39;
    input gnd4;
    input gnd40;
    input gnd41;
    input gnd42;
    input gnd43;
    input gnd44;
    input gnd45;
    input gnd46;
    input gnd47;
    input gnd48;
    input gnd49;
    input gnd5;
    input gnd50;
    input gnd51;
    input gnd52;
    input gnd53;
    input gnd54;
    input gnd55;
    input gnd56;
    input gnd57;
    input gnd58;
    input gnd59;
    input gnd6;
    input gnd60;
    input gnd61;
    input gnd62;
    input gnd63;
    input gnd64;
    input gnd65;
    input gnd66;
    input gnd67;
    input gnd68;
    input gnd69;
    input gnd7;
    input gnd70;
    input gnd71;
    input gnd72;
    input gnd73;
    input gnd74;
    input gnd75;
    input gnd76;
    input gnd77;
    input gnd78;
    input gnd79;
    input gnd8;
    input gnd80;
    input gnd81;
    input gnd82;
    input gnd83;
    input gnd84;
    input gnd85;
    input gnd86;
    input gnd87;
    input gnd88;
    input gnd89;
    input gnd9;
    input gnd90;
    input gnd91;
    input gnd92;
    input gnd93;
    input gnd94;
    input gnd95;
    input gnd96;
    input gnd97;
    input gnd98;
    input gnd99;
    inout hswapen_0;
    inout init_b_0;
    inout io_l0n_11;
    inout io_l0n_12;
    inout io_l0n_15;
    inout io_l0n_17;
    inout io_l0n_18;
    inout io_l0n_19;
    inout io_l0n_20;
    inout io_l0n_21;
    inout io_l0n_22;
    inout io_l0n_a18_1;
    inout io_l0n_cc_gc_3;
    inout io_l0n_cc_rs0_2;
    inout io_l0n_gc_d14_4;
    inout io_l0n_sm8n_13;
    inout io_l0p_11;
    inout io_l0p_12;
    inout io_l0p_15;
    inout io_l0p_17;
    inout io_l0p_18;
    inout io_l0p_19;
    inout io_l0p_20;
    inout io_l0p_21;
    inout io_l0p_22;
    inout io_l0p_a19_1;
    inout io_l0p_cc_gc_3;
    inout io_l0p_cc_rs1_2;
    inout io_l0p_gc_d15_4;
    inout io_l0p_sm8p_13;
    inout io_l10n_cc_12;
    inout io_l10n_cc_13;
    inout io_l10n_cc_15;
    inout io_l10n_cc_17;
    inout io_l10n_cc_18;
    inout io_l10n_cc_19;
    inout io_l10n_cc_20;
    inout io_l10n_cc_21;
    inout io_l10n_cc_22;
    inout io_l10n_cc_sm15n_11;
    inout io_l10p_cc_12;
    inout io_l10p_cc_13;
    inout io_l10p_cc_15;
    inout io_l10p_cc_17;
    inout io_l10p_cc_18;
    inout io_l10p_cc_19;
    inout io_l10p_cc_20;
    inout io_l10p_cc_21;
    inout io_l10p_cc_22;
    inout io_l10p_cc_sm15p_11;
    inout io_l11n_cc_12;
    inout io_l11n_cc_13;
    inout io_l11n_cc_15;
    inout io_l11n_cc_17;
    inout io_l11n_cc_18;
    inout io_l11n_cc_19;
    inout io_l11n_cc_20;
    inout io_l11n_cc_21;
    inout io_l11n_cc_22;
    inout io_l11n_cc_sm14n_11;
    inout io_l11p_cc_12;
    inout io_l11p_cc_13;
    inout io_l11p_cc_15;
    inout io_l11p_cc_17;
    inout io_l11p_cc_18;
    inout io_l11p_cc_19;
    inout io_l11p_cc_20;
    inout io_l11p_cc_21;
    inout io_l11p_cc_22;
    inout io_l11p_cc_sm14p_11;
    inout io_l12n_vrp_11;
    inout io_l12n_vrp_12;
    inout io_l12n_vrp_13;
    inout io_l12n_vrp_15;
    inout io_l12n_vrp_17;
    inout io_l12n_vrp_18;
    inout io_l12n_vrp_19;
    inout io_l12n_vrp_20;
    inout io_l12n_vrp_21;
    inout io_l12n_vrp_22;
    inout io_l12p_vrn_11;
    inout io_l12p_vrn_12;
    inout io_l12p_vrn_13;
    inout io_l12p_vrn_15;
    inout io_l12p_vrn_17;
    inout io_l12p_vrn_18;
    inout io_l12p_vrn_19;
    inout io_l12p_vrn_20;
    inout io_l12p_vrn_21;
    inout io_l12p_vrn_22;
    inout io_l13n_11;
    inout io_l13n_12;
    inout io_l13n_13;
    inout io_l13n_15;
    inout io_l13n_17;
    inout io_l13n_18;
    inout io_l13n_19;
    inout io_l13n_20;
    inout io_l13n_21;
    inout io_l13n_22;
    inout io_l13p_11;
    inout io_l13p_12;
    inout io_l13p_13;
    inout io_l13p_15;
    inout io_l13p_17;
    inout io_l13p_18;
    inout io_l13p_19;
    inout io_l13p_20;
    inout io_l13p_21;
    inout io_l13p_22;
    inout io_l14n_vref_11;
    inout io_l14n_vref_12;
    inout io_l14n_vref_13;
    inout io_l14n_vref_15;
    inout io_l14n_vref_17;
    inout io_l14n_vref_18;
    inout io_l14n_vref_19;
    inout io_l14n_vref_20;
    inout io_l14n_vref_21;
    inout io_l14n_vref_22;
    inout io_l14p_11;
    inout io_l14p_12;
    inout io_l14p_13;
    inout io_l14p_15;
    inout io_l14p_17;
    inout io_l14p_18;
    inout io_l14p_19;
    inout io_l14p_20;
    inout io_l14p_21;
    inout io_l14p_22;
    inout io_l15n_12;
    inout io_l15n_13;
    inout io_l15n_15;
    inout io_l15n_17;
    inout io_l15n_18;
    inout io_l15n_19;
    inout io_l15n_20;
    inout io_l15n_21;
    inout io_l15n_22;
    inout io_l15n_sm13n_11;
    inout io_l15p_12;
    inout io_l15p_13;
    inout io_l15p_15;
    inout io_l15p_17;
    inout io_l15p_18;
    inout io_l15p_19;
    inout io_l15p_20;
    inout io_l15p_21;
    inout io_l15p_22;
    inout io_l15p_sm13p_11;
    inout io_l16n_12;
    inout io_l16n_13;
    inout io_l16n_15;
    inout io_l16n_17;
    inout io_l16n_18;
    inout io_l16n_19;
    inout io_l16n_20;
    inout io_l16n_21;
    inout io_l16n_22;
    inout io_l16n_sm12n_11;
    inout io_l16p_12;
    inout io_l16p_13;
    inout io_l16p_15;
    inout io_l16p_17;
    inout io_l16p_18;
    inout io_l16p_19;
    inout io_l16p_20;
    inout io_l16p_21;
    inout io_l16p_22;
    inout io_l16p_sm12p_11;
    inout io_l17n_12;
    inout io_l17n_13;
    inout io_l17n_15;
    inout io_l17n_17;
    inout io_l17n_18;
    inout io_l17n_19;
    inout io_l17n_20;
    inout io_l17n_21;
    inout io_l17n_22;
    inout io_l17n_sm11n_11;
    inout io_l17p_12;
    inout io_l17p_13;
    inout io_l17p_15;
    inout io_l17p_17;
    inout io_l17p_18;
    inout io_l17p_19;
    inout io_l17p_20;
    inout io_l17p_21;
    inout io_l17p_22;
    inout io_l17p_sm11p_11;
    inout io_l18n_12;
    inout io_l18n_13;
    inout io_l18n_15;
    inout io_l18n_17;
    inout io_l18n_18;
    inout io_l18n_19;
    inout io_l18n_20;
    inout io_l18n_21;
    inout io_l18n_22;
    inout io_l18n_sm10n_11;
    inout io_l18p_12;
    inout io_l18p_13;
    inout io_l18p_15;
    inout io_l18p_17;
    inout io_l18p_18;
    inout io_l18p_19;
    inout io_l18p_20;
    inout io_l18p_21;
    inout io_l18p_22;
    inout io_l18p_sm10p_11;
    inout io_l19n_12;
    inout io_l19n_13;
    inout io_l19n_15;
    inout io_l19n_17;
    inout io_l19n_18;
    inout io_l19n_19;
    inout io_l19n_20;
    inout io_l19n_21;
    inout io_l19n_22;
    inout io_l19n_sm9n_11;
    inout io_l19p_12;
    inout io_l19p_13;
    inout io_l19p_15;
    inout io_l19p_17;
    inout io_l19p_18;
    inout io_l19p_19;
    inout io_l19p_20;
    inout io_l19p_21;
    inout io_l19p_22;
    inout io_l19p_sm9p_11;
    inout io_l1n_11;
    inout io_l1n_12;
    inout io_l1n_15;
    inout io_l1n_17;
    inout io_l1n_18;
    inout io_l1n_19;
    inout io_l1n_20;
    inout io_l1n_21;
    inout io_l1n_22;
    inout io_l1n_a16_1;
    inout io_l1n_cc_a24_2;
    inout io_l1n_cc_gc_3;
    inout io_l1n_gc_d12_4;
    inout io_l1n_sm7n_13;
    inout io_l1p_11;
    inout io_l1p_12;
    inout io_l1p_15;
    inout io_l1p_17;
    inout io_l1p_18;
    inout io_l1p_19;
    inout io_l1p_20;
    inout io_l1p_21;
    inout io_l1p_22;
    inout io_l1p_a17_1;
    inout io_l1p_cc_a25_2;
    inout io_l1p_cc_gc_3;
    inout io_l1p_gc_d13_4;
    inout io_l1p_sm7p_13;
    inout io_l2n_11;
    inout io_l2n_12;
    inout io_l2n_15;
    inout io_l2n_17;
    inout io_l2n_18;
    inout io_l2n_19;
    inout io_l2n_20;
    inout io_l2n_21;
    inout io_l2n_22;
    inout io_l2n_a14_d30_1;
    inout io_l2n_a22_2;
    inout io_l2n_gc_d10_4;
    inout io_l2n_gc_vrp_3;
    inout io_l2n_sm6n_13;
    inout io_l2p_11;
    inout io_l2p_12;
    inout io_l2p_15;
    inout io_l2p_17;
    inout io_l2p_18;
    inout io_l2p_19;
    inout io_l2p_20;
    inout io_l2p_21;
    inout io_l2p_22;
    inout io_l2p_a15_d31_1;
    inout io_l2p_a23_2;
    inout io_l2p_gc_d11_4;
    inout io_l2p_gc_vrn_3;
    inout io_l2p_sm6p_13;
    inout io_l3n_11;
    inout io_l3n_12;
    inout io_l3n_15;
    inout io_l3n_17;
    inout io_l3n_18;
    inout io_l3n_19;
    inout io_l3n_20;
    inout io_l3n_21;
    inout io_l3n_22;
    inout io_l3n_a12_d28_1;
    inout io_l3n_a20_2;
    inout io_l3n_gc_3;
    inout io_l3n_gc_d8_4;
    inout io_l3n_sm5n_13;
    inout io_l3p_11;
    inout io_l3p_12;
    inout io_l3p_15;
    inout io_l3p_17;
    inout io_l3p_18;
    inout io_l3p_19;
    inout io_l3p_20;
    inout io_l3p_21;
    inout io_l3p_22;
    inout io_l3p_a13_d29_1;
    inout io_l3p_a21_2;
    inout io_l3p_gc_3;
    inout io_l3p_gc_d9_4;
    inout io_l3p_sm5p_13;
    inout io_l4n_gc_vref_3;
    inout io_l4n_gc_vref_4;
    inout io_l4n_vref_11;
    inout io_l4n_vref_12;
    inout io_l4n_vref_13;
    inout io_l4n_vref_15;
    inout io_l4n_vref_17;
    inout io_l4n_vref_18;
    inout io_l4n_vref_19;
    inout io_l4n_vref_20;
    inout io_l4n_vref_21;
    inout io_l4n_vref_22;
    inout io_l4n_vref_a10_d26_1;
    inout io_l4n_vref_foe_b_mosi_2;
    inout io_l4p_11;
    inout io_l4p_12;
    inout io_l4p_13;
    inout io_l4p_15;
    inout io_l4p_17;
    inout io_l4p_18;
    inout io_l4p_19;
    inout io_l4p_20;
    inout io_l4p_21;
    inout io_l4p_22;
    inout io_l4p_a11_d27_1;
    inout io_l4p_fcs_b_2;
    inout io_l4p_gc_3;
    inout io_l4p_gc_4;
    inout io_l5n_11;
    inout io_l5n_12;
    inout io_l5n_15;
    inout io_l5n_17;
    inout io_l5n_18;
    inout io_l5n_19;
    inout io_l5n_20;
    inout io_l5n_21;
    inout io_l5n_22;
    inout io_l5n_a8_d24_1;
    inout io_l5n_cso_b_2;
    inout io_l5n_gc_3;
    inout io_l5n_gc_4;
    inout io_l5n_sm4n_13;
    inout io_l5p_11;
    inout io_l5p_12;
    inout io_l5p_15;
    inout io_l5p_17;
    inout io_l5p_18;
    inout io_l5p_19;
    inout io_l5p_20;
    inout io_l5p_21;
    inout io_l5p_22;
    inout io_l5p_a9_d25_1;
    inout io_l5p_fwe_b_2;
    inout io_l5p_gc_3;
    inout io_l5p_gc_4;
    inout io_l5p_sm4p_13;
    inout io_l6n_11;
    inout io_l6n_12;
    inout io_l6n_15;
    inout io_l6n_17;
    inout io_l6n_18;
    inout io_l6n_19;
    inout io_l6n_20;
    inout io_l6n_21;
    inout io_l6n_22;
    inout io_l6n_a6_d22_1;
    inout io_l6n_d6_2;
    inout io_l6n_gc_3;
    inout io_l6n_gc_4;
    inout io_l6n_sm3n_13;
    inout io_l6p_11;
    inout io_l6p_12;
    inout io_l6p_15;
    inout io_l6p_17;
    inout io_l6p_18;
    inout io_l6p_19;
    inout io_l6p_20;
    inout io_l6p_21;
    inout io_l6p_22;
    inout io_l6p_a7_d23_1;
    inout io_l6p_d7_2;
    inout io_l6p_gc_3;
    inout io_l6p_gc_4;
    inout io_l6p_sm3p_13;
    inout io_l7n_11;
    inout io_l7n_12;
    inout io_l7n_15;
    inout io_l7n_17;
    inout io_l7n_18;
    inout io_l7n_19;
    inout io_l7n_20;
    inout io_l7n_21;
    inout io_l7n_22;
    inout io_l7n_a4_d20_1;
    inout io_l7n_d4_2;
    inout io_l7n_gc_3;
    inout io_l7n_gc_vrp_4;
    inout io_l7n_sm2n_13;
    inout io_l7p_11;
    inout io_l7p_12;
    inout io_l7p_15;
    inout io_l7p_17;
    inout io_l7p_18;
    inout io_l7p_19;
    inout io_l7p_20;
    inout io_l7p_21;
    inout io_l7p_22;
    inout io_l7p_a5_d21_1;
    inout io_l7p_d5_2;
    inout io_l7p_gc_3;
    inout io_l7p_gc_vrn_4;
    inout io_l7p_sm2p_13;
    inout io_l8n_cc_11;
    inout io_l8n_cc_12;
    inout io_l8n_cc_15;
    inout io_l8n_cc_17;
    inout io_l8n_cc_18;
    inout io_l8n_cc_19;
    inout io_l8n_cc_20;
    inout io_l8n_cc_21;
    inout io_l8n_cc_22;
    inout io_l8n_cc_a2_d18_1;
    inout io_l8n_cc_gc_4;
    inout io_l8n_cc_sm1n_13;
    inout io_l8n_d2_fs2_2;
    inout io_l8n_gc_3;
    inout io_l8p_cc_11;
    inout io_l8p_cc_12;
    inout io_l8p_cc_15;
    inout io_l8p_cc_17;
    inout io_l8p_cc_18;
    inout io_l8p_cc_19;
    inout io_l8p_cc_20;
    inout io_l8p_cc_21;
    inout io_l8p_cc_22;
    inout io_l8p_cc_a3_d19_1;
    inout io_l8p_cc_gc_4;
    inout io_l8p_cc_sm1p_13;
    inout io_l8p_d3_2;
    inout io_l8p_gc_3;
    inout io_l9n_cc_11;
    inout io_l9n_cc_12;
    inout io_l9n_cc_15;
    inout io_l9n_cc_17;
    inout io_l9n_cc_18;
    inout io_l9n_cc_19;
    inout io_l9n_cc_20;
    inout io_l9n_cc_21;
    inout io_l9n_cc_22;
    inout io_l9n_cc_a0_d16_1;
    inout io_l9n_cc_gc_4;
    inout io_l9n_cc_sm0n_13;
    inout io_l9n_d0_fs0_2;
    inout io_l9n_gc_3;
    inout io_l9p_cc_11;
    inout io_l9p_cc_12;
    inout io_l9p_cc_15;
    inout io_l9p_cc_17;
    inout io_l9p_cc_18;
    inout io_l9p_cc_19;
    inout io_l9p_cc_20;
    inout io_l9p_cc_21;
    inout io_l9p_cc_22;
    inout io_l9p_cc_a1_d17_1;
    inout io_l9p_cc_gc_4;
    inout io_l9p_cc_sm0p_13;
    inout io_l9p_d1_fs1_2;
    inout io_l9p_gc_3;
    inout m0_0;
    inout m1_0;
    inout m2_0;
    inout mgtavcc_112_1;
    inout mgtavcc_112_2;
    inout mgtavcc_114_1;
    inout mgtavcc_114_2;
    inout mgtavcc_116_1;
    inout mgtavcc_116_2;
    inout mgtavcc_118_1;
    inout mgtavcc_118_2;
    inout mgtavcc_120_1;
    inout mgtavcc_120_2;
    inout mgtavcc_122_1;
    inout mgtavcc_122_2;
    inout mgtavccpll_112;
    inout mgtavccpll_114;
    inout mgtavccpll_116;
    inout mgtavccpll_118;
    inout mgtavccpll_120;
    inout mgtavccpll_122;
    inout mgtavttrx_112;
    inout mgtavttrx_114;
    inout mgtavttrx_116;
    inout mgtavttrx_118;
    inout mgtavttrx_120;
    inout mgtavttrx_122;
    inout mgtavttrxc;
    inout mgtavtttx_112_1;
    inout mgtavtttx_112_2;
    inout mgtavtttx_114_1;
    inout mgtavtttx_114_2;
    inout mgtavtttx_116_1;
    inout mgtavtttx_116_2;
    inout mgtavtttx_118_1;
    inout mgtavtttx_118_2;
    inout mgtavtttx_120_1;
    inout mgtavtttx_120_2;
    inout mgtavtttx_122_1;
    inout mgtavtttx_122_2;
    inout mgtrefclkn_112;
    inout mgtrefclkn_114;
    inout mgtrefclkn_116;
    inout mgtrefclkn_118;
    inout mgtrefclkn_120;
    inout mgtrefclkn_122;
    inout mgtrefclkp_112;
    inout mgtrefclkp_114;
    inout mgtrefclkp_116;
    inout mgtrefclkp_118;
    inout mgtrefclkp_120;
    inout mgtrefclkp_122;
    inout mgtrref_112;
    inout mgtrxn0_112;
    inout mgtrxn0_114;
    inout mgtrxn0_116;
    inout mgtrxn0_118;
    inout mgtrxn0_120;
    inout mgtrxn0_122;
    inout mgtrxn1_112;
    inout mgtrxn1_114;
    inout mgtrxn1_116;
    inout mgtrxn1_118;
    inout mgtrxn1_120;
    inout mgtrxn1_122;
    inout mgtrxp0_112;
    inout mgtrxp0_114;
    inout mgtrxp0_116;
    inout mgtrxp0_118;
    inout mgtrxp0_120;
    inout mgtrxp0_122;
    inout mgtrxp1_112;
    inout mgtrxp1_114;
    inout mgtrxp1_116;
    inout mgtrxp1_118;
    inout mgtrxp1_120;
    inout mgtrxp1_122;
    inout mgttxn0_112;
    inout mgttxn0_114;
    inout mgttxn0_116;
    inout mgttxn0_118;
    inout mgttxn0_120;
    inout mgttxn0_122;
    inout mgttxn1_112;
    inout mgttxn1_114;
    inout mgttxn1_116;
    inout mgttxn1_118;
    inout mgttxn1_120;
    inout mgttxn1_122;
    inout mgttxp0_112;
    inout mgttxp0_114;
    inout mgttxp0_116;
    inout mgttxp0_118;
    inout mgttxp0_120;
    inout mgttxp0_122;
    inout mgttxp1_112;
    inout mgttxp1_114;
    inout mgttxp1_116;
    inout mgttxp1_118;
    inout mgttxp1_120;
    inout mgttxp1_122;
    inout nc1;
    inout nc10;
    inout nc100;
    inout nc101;
    inout nc102;
    inout nc103;
    inout nc104;
    inout nc105;
    inout nc106;
    inout nc107;
    inout nc108;
    inout nc109;
    inout nc11;
    inout nc110;
    inout nc111;
    inout nc112;
    inout nc113;
    inout nc114;
    inout nc115;
    inout nc116;
    inout nc117;
    inout nc118;
    inout nc119;
    inout nc12;
    inout nc120;
    inout nc121;
    inout nc122;
    inout nc123;
    inout nc124;
    inout nc125;
    inout nc126;
    inout nc127;
    inout nc128;
    inout nc129;
    inout nc13;
    inout nc130;
    inout nc131;
    inout nc132;
    inout nc133;
    inout nc134;
    inout nc135;
    inout nc136;
    inout nc137;
    inout nc138;
    inout nc139;
    inout nc14;
    inout nc140;
    inout nc141;
    inout nc142;
    inout nc143;
    inout nc144;
    inout nc145;
    inout nc146;
    inout nc147;
    inout nc148;
    inout nc149;
    inout nc15;
    inout nc150;
    inout nc151;
    inout nc152;
    inout nc153;
    inout nc154;
    inout nc155;
    inout nc156;
    inout nc157;
    inout nc158;
    inout nc159;
    inout nc16;
    inout nc160;
    inout nc161;
    inout nc162;
    inout nc163;
    inout nc164;
    inout nc165;
    inout nc166;
    inout nc167;
    inout nc168;
    inout nc169;
    inout nc17;
    inout nc170;
    inout nc171;
    inout nc172;
    inout nc173;
    inout nc174;
    inout nc175;
    inout nc176;
    inout nc177;
    inout nc178;
    inout nc179;
    inout nc18;
    inout nc180;
    inout nc181;
    inout nc182;
    inout nc183;
    inout nc184;
    inout nc185;
    inout nc186;
    inout nc187;
    inout nc188;
    inout nc189;
    inout nc19;
    inout nc190;
    inout nc191;
    inout nc192;
    inout nc193;
    inout nc2;
    inout nc20;
    inout nc21;
    inout nc22;
    inout nc23;
    inout nc24;
    inout nc25;
    inout nc26;
    inout nc27;
    inout nc28;
    inout nc29;
    inout nc3;
    inout nc30;
    inout nc31;
    inout nc32;
    inout nc33;
    inout nc34;
    inout nc35;
    inout nc36;
    inout nc37;
    inout nc38;
    inout nc39;
    inout nc4;
    inout nc40;
    inout nc41;
    inout nc42;
    inout nc43;
    inout nc44;
    inout nc45;
    inout nc46;
    inout nc47;
    inout nc48;
    inout nc49;
    inout nc5;
    inout nc50;
    inout nc51;
    inout nc52;
    inout nc53;
    inout nc54;
    inout nc55;
    inout nc56;
    inout nc57;
    inout nc58;
    inout nc59;
    inout nc6;
    inout nc60;
    inout nc61;
    inout nc62;
    inout nc63;
    inout nc64;
    inout nc65;
    inout nc66;
    inout nc67;
    inout nc68;
    inout nc69;
    inout nc7;
    inout nc70;
    inout nc71;
    inout nc72;
    inout nc73;
    inout nc74;
    inout nc75;
    inout nc76;
    inout nc77;
    inout nc78;
    inout nc79;
    inout nc8;
    inout nc80;
    inout nc81;
    inout nc82;
    inout nc83;
    inout nc84;
    inout nc85;
    inout nc86;
    inout nc87;
    inout nc88;
    inout nc89;
    inout nc9;
    inout nc90;
    inout nc91;
    inout nc92;
    inout nc93;
    inout nc94;
    inout nc95;
    inout nc96;
    inout nc97;
    inout nc98;
    inout nc99;
    inout program_b_0;
    inout rdwr_b_0;
    inout rsvd1;
    inout rsvd2;
    inout tck_0;
    inout tdi_0;
    inout tdo_0;
    inout tms_0;
    inout vbatt_0;
    input vccaux1;
    input vccaux10;
    input vccaux11;
    input vccaux12;
    input vccaux2;
    input vccaux3;
    input vccaux4;
    input vccaux5;
    input vccaux6;
    input vccaux7;
    input vccaux8;
    input vccaux9;
    input vccint1;
    input vccint10;
    input vccint11;
    input vccint12;
    input vccint13;
    input vccint14;
    input vccint15;
    input vccint16;
    input vccint17;
    input vccint18;
    input vccint19;
    input vccint2;
    input vccint20;
    input vccint21;
    input vccint22;
    input vccint23;
    input vccint24;
    input vccint25;
    input vccint26;
    input vccint27;
    input vccint28;
    input vccint29;
    input vccint3;
    input vccint30;
    input vccint31;
    input vccint32;
    input vccint33;
    input vccint34;
    input vccint35;
    input vccint36;
    input vccint37;
    input vccint38;
    input vccint39;
    input vccint4;
    input vccint40;
    input vccint41;
    input vccint42;
    input vccint43;
    input vccint44;
    input vccint45;
    input vccint46;
    input vccint47;
    input vccint48;
    input vccint49;
    input vccint5;
    input vccint50;
    input vccint51;
    input vccint52;
    input vccint53;
    input vccint54;
    input vccint6;
    input vccint7;
    input vccint8;
    input vccint9;
    input vcco_0_1;
    input vcco_0_2;
    input vcco_11_1;
    input vcco_11_2;
    input vcco_11_3;
    input vcco_12_1;
    input vcco_12_2;
    input vcco_12_3;
    input vcco_13_1;
    input vcco_13_2;
    input vcco_13_3;
    input vcco_15_1;
    input vcco_15_2;
    input vcco_15_3;
    input vcco_17_1;
    input vcco_17_2;
    input vcco_17_3;
    input vcco_18_1;
    input vcco_18_2;
    input vcco_18_3;
    input vcco_19_1;
    input vcco_19_2;
    input vcco_19_3;
    input vcco_1_1;
    input vcco_1_2;
    input vcco_20_1;
    input vcco_20_2;
    input vcco_20_3;
    input vcco_21_1;
    input vcco_21_2;
    input vcco_21_3;
    input vcco_22_1;
    input vcco_22_2;
    input vcco_22_3;
    input vcco_23_1;
    input vcco_23_2;
    input vcco_23_3;
    input vcco_25_1;
    input vcco_25_2;
    input vcco_25_3;
    input vcco_2_1;
    input vcco_2_2;
    input vcco_3_1;
    input vcco_3_2;
    input vcco_4_1;
    input vcco_4_2;
    input vcco_5_1;
    input vcco_5_2;
    input vcco_5_3;
    input vcco_6_1;
    input vcco_6_2;
    input vcco_6_3;
    inout vn_0;
    inout vp_0;
    inout vrefn_0;
    inout vrefp_0;


    initial
        begin
        end

endmodule
