-- generated by newgenasym Thu Feb 12 14:41:52 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sbb_4089 is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	RF_IN:     INOUT  STD_LOGIC;    
	RF_OUT:    INOUT  STD_LOGIC);
end sbb_4089;
