// generated by newgenasym  Thu Aug 27 16:31:26 2009


module vh12r48b (\case , cnt, gnd01, gnd02, gnd03, gnd04, \sense+ , \sense- , trim,
        \vin+ , \vin- , \vout+ , \vout- );
    inout \case ;
    inout cnt;
    input gnd01;
    input gnd02;
    input gnd03;
    input gnd04;
    inout \sense+ ;
    inout \sense- ;
    inout trim;
    inout \vin+ ;
    inout \vin- ;
    inout \vout+ ;
    inout \vout- ;


    initial
        begin
        end

endmodule
