-- generated by newgenasym Thu Aug 27 16:31:26 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity vh12r48b is
    port (    
	\case\:    INOUT  STD_LOGIC;    
	CNT:       INOUT  STD_LOGIC;    
	GND01:     IN     STD_LOGIC;    
	GND02:     IN     STD_LOGIC;    
	GND03:     IN     STD_LOGIC;    
	GND04:     IN     STD_LOGIC;    
	\sense+\:  INOUT  STD_LOGIC;    
	\sense-\:  INOUT  STD_LOGIC;    
	TRIM:      INOUT  STD_LOGIC;    
	\vin+\:    INOUT  STD_LOGIC;    
	\vin-\:    INOUT  STD_LOGIC;    
	\vout+\:   INOUT  STD_LOGIC;    
	\vout-\:   INOUT  STD_LOGIC);
end vh12r48b;
