-- generated by newgenasym Thu Apr 23 16:37:13 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fdv303n is
    port (    
	D:         INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC);
end fdv303n;
