-- generated by newgenasym Wed Sep 09 14:08:43 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity con_282841_3 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end con_282841_3;
