// generated by newgenasym  Thu Jun 30 11:04:43 2011


module maba_009484_etc31t (pri, pri_dot, sec, sec_ct, sec_dot);
    inout pri;
    inout pri_dot;
    inout sec;
    inout sec_ct;
    inout sec_dot;


    initial
        begin
        end

endmodule
