-- generated by newgenasym Fri Feb 10 16:44:18 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps63020dsj is
    port (    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	L1:        INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	L2:        INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	PAD:       INOUT  STD_LOGIC;    
	PG:        INOUT  STD_LOGIC;    
	\ps/sync\: INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	VINA:      INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1));
end tps63020dsj;
