// generated by newgenasym  Wed Sep 28 14:09:47 2011


module hmc470lp3e (acg1, acg2, acg3, acg4, acg5, acg6, \n/c , pad, rf1, rf2, v1, v2,
        v3, v4, v5, vdd);
    inout acg1;
    inout acg2;
    inout acg3;
    inout acg4;
    inout acg5;
    inout acg6;
    inout [2:1] \n/c ;
    inout pad;
    inout rf1;
    inout rf2;
    inout v1;
    inout v2;
    inout v3;
    inout v4;
    inout v5;
    inout vdd;


    initial
        begin
        end

endmodule
