// generated by newgenasym  Fri Jun 03 14:40:54 2011


module ad8302aruz (comm, inpa, inpb, mflt, mset, ofsa, ofsb, pflt, pset, vmag,
        vphs, vpos, vref);
    inout [2:1] comm;
    inout inpa;
    inout inpb;
    inout mflt;
    inout mset;
    inout ofsa;
    inout ofsb;
    inout pflt;
    inout pset;
    inout vmag;
    inout vphs;
    inout vpos;
    inout vref;


    initial
        begin
        end

endmodule
