-- generated by newgenasym Fri Jun 03 14:40:54 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8302aruz is
    port (    
	COMM:      INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	INPA:      INOUT  STD_LOGIC;    
	INPB:      INOUT  STD_LOGIC;    
	MFLT:      INOUT  STD_LOGIC;    
	MSET:      INOUT  STD_LOGIC;    
	OFSA:      INOUT  STD_LOGIC;    
	OFSB:      INOUT  STD_LOGIC;    
	PFLT:      INOUT  STD_LOGIC;    
	PSET:      INOUT  STD_LOGIC;    
	VMAG:      INOUT  STD_LOGIC;    
	VPHS:      INOUT  STD_LOGIC;    
	VPOS:      INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end ad8302aruz;
