-- generated by newgenasym Thu Jun 23 15:28:59 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74alvc164245dggr is
    port (    
	\1a1\:     INOUT  STD_LOGIC;    
	\1a2\:     INOUT  STD_LOGIC;    
	\1a3\:     INOUT  STD_LOGIC;    
	\1a4\:     INOUT  STD_LOGIC;    
	\1a5\:     INOUT  STD_LOGIC;    
	\1a6\:     INOUT  STD_LOGIC;    
	\1a7\:     INOUT  STD_LOGIC;    
	\1a8\:     INOUT  STD_LOGIC;    
	\1b1\:     INOUT  STD_LOGIC;    
	\1b2\:     INOUT  STD_LOGIC;    
	\1b3\:     INOUT  STD_LOGIC;    
	\1b4\:     INOUT  STD_LOGIC;    
	\1b5\:     INOUT  STD_LOGIC;    
	\1b6\:     INOUT  STD_LOGIC;    
	\1b7\:     INOUT  STD_LOGIC;    
	\1b8\:     INOUT  STD_LOGIC;    
	\1dir\:    INOUT  STD_LOGIC;    
	\1oe#\:    INOUT  STD_LOGIC;    
	\2a1\:     INOUT  STD_LOGIC;    
	\2a2\:     INOUT  STD_LOGIC;    
	\2a3\:     INOUT  STD_LOGIC;    
	\2a4\:     INOUT  STD_LOGIC;    
	\2a5\:     INOUT  STD_LOGIC;    
	\2a6\:     INOUT  STD_LOGIC;    
	\2a7\:     INOUT  STD_LOGIC;    
	\2a8\:     INOUT  STD_LOGIC;    
	\2b1\:     INOUT  STD_LOGIC;    
	\2b2\:     INOUT  STD_LOGIC;    
	\2b3\:     INOUT  STD_LOGIC;    
	\2b4\:     INOUT  STD_LOGIC;    
	\2b5\:     INOUT  STD_LOGIC;    
	\2b6\:     INOUT  STD_LOGIC;    
	\2b7\:     INOUT  STD_LOGIC;    
	\2b8\:     INOUT  STD_LOGIC;    
	\2dir\:    INOUT  STD_LOGIC;    
	\2oe#\:    INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC_VECTOR (8 DOWNTO 1);    
	VCCA:      INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	VCCB:      INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1));
end sn74alvc164245dggr;
