-- generated by newgenasym Tue Feb 24 17:15:28 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tcp_2_10 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end tcp_2_10;
