// generated by newgenasym  Wed Apr 29 14:34:53 2009


module sp3485en (a, b, de, di, gnd, \re# , ro, vcc);
    inout a;
    inout b;
    output de;
    input di;
    input gnd;
    output \re# ;
    output ro;
    input vcc;


    initial
        begin
        end

endmodule
