-- generated by newgenasym Wed Apr 29 14:34:53 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sp3485en is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	DE:        OUT    STD_LOGIC;    
	DI:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\re#\:     OUT    STD_LOGIC;    
	RO:        OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end sp3485en;
