// generated by newgenasym  Mon May 31 11:29:09 2010


module dac8311 (\avdd/vref , din, gnd, sclk, \sync# , vout);
    inout \avdd/vref ;
    inout din;
    inout gnd;
    inout sclk;
    inout \sync# ;
    inout vout;


    initial
        begin
        end

endmodule
