-- generated by newgenasym Thu Mar 15 17:26:24 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds12c887aa is
    port (    
	AD0:       INOUT  STD_LOGIC;    
	AD1:       INOUT  STD_LOGIC;    
	AD2:       INOUT  STD_LOGIC;    
	AD3:       INOUT  STD_LOGIC;    
	AD4:       INOUT  STD_LOGIC;    
	AD5:       INOUT  STD_LOGIC;    
	AD6:       INOUT  STD_LOGIC;    
	AD7:       INOUT  STD_LOGIC;    
	AS:        INOUT  STD_LOGIC;    
	\cs#\:     INOUT  STD_LOGIC;    
	DS:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\irq#\:    INOUT  STD_LOGIC;    
	MOT:       INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC_VECTOR (5 DOWNTO 1);    
	\nc/rclr#\: INOUT  STD_LOGIC;    
	\r/w#\:    INOUT  STD_LOGIC;    
	\reset#\:  INOUT  STD_LOGIC;    
	SQW:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end ds12c887aa;
