// generated by newgenasym  Wed Aug 12 14:41:25 2009


module lt5578 (gnd1, gnd10, gnd11, gnd12, gnd13, gnd14, gnd15, gnd16, gnd2,
        gnd3, gnd4, gnd5, gnd6, gnd7, gnd8, gnd9, \if+ , \if- , lo, pad, rf,
        vcc1, vcc2, vcc3, vcc4);
    inout gnd1;
    inout gnd10;
    inout gnd11;
    inout gnd12;
    inout gnd13;
    inout gnd14;
    inout gnd15;
    inout gnd16;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout gnd6;
    inout gnd7;
    inout gnd8;
    inout gnd9;
    inout \if+ ;
    inout \if- ;
    inout lo;
    inout pad;
    inout rf;
    inout vcc1;
    inout vcc2;
    inout vcc3;
    inout vcc4;


    initial
        begin
        end

endmodule
