// generated by newgenasym  Tue Mar 10 15:08:19 2009


module ads62c17irgc (agnd_1, agnd_2, agnd_3, agnd_5, agnd_6, agnd_7, agnd_8,
        agnd_9, avdd_1, avdd_2, avdd_3, clkm, clkoutm, clkoutp, clkp,
        cm, ctrl1, ctrl2, ctrl3, da0m, da0p, da10m, da10p, da2m, da2p,
        da4m, da4p, da6m, da6p, da8m, da8p, db0m, db0p, db10m, db10p,
        db2m, db2p, db4m, db4p, db6m, db6p, db8m, db8p, drgnd_1,
        drgnd_2, drgnd_4, drvdd_1, drvdd_2, drvdd_3, drvdd_4, inm_a,
        inm_b, inp_a, inp_b, nc_1, nc_2, nc_3, nc_4, nc_5, pad_drgnd,
        reset, sclk, sdata, sdout, sen);
    input agnd_1;
    input agnd_2;
    input agnd_3;
    input agnd_5;
    input agnd_6;
    input agnd_7;
    input agnd_8;
    input agnd_9;
    input avdd_1;
    input avdd_2;
    input avdd_3;
    input clkm;
    output clkoutm;
    output clkoutp;
    input clkp;
    output cm;
    input ctrl1;
    input ctrl2;
    input ctrl3;
    output da0m;
    output da0p;
    output da10m;
    output da10p;
    output da2m;
    output da2p;
    output da4m;
    output da4p;
    output da6m;
    output da6p;
    output da8m;
    output da8p;
    inout db0m;
    output db0p;
    output db10m;
    output db10p;
    output db2m;
    output db2p;
    output db4m;
    output db4p;
    output db6m;
    output db6p;
    output db8m;
    output db8p;
    input drgnd_1;
    input drgnd_2;
    input drgnd_4;
    input drvdd_1;
    input drvdd_2;
    input drvdd_3;
    input drvdd_4;
    input inm_a;
    input inm_b;
    input inp_a;
    input inp_b;
    input nc_1;
    inout nc_2;
    inout nc_3;
    inout nc_4;
    inout nc_5;
    input pad_drgnd;
    input reset;
    input sclk;
    input sdata;
    input sdout;
    input sen;


    initial
        begin
        end

endmodule
