// generated by newgenasym  Fri Feb 13 16:36:06 2009


module smb (\2 , \3 , \4 , \5 , in);
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout in;


    initial
        begin
        end

endmodule
