-- generated by newgenasym Fri Feb 13 16:36:06 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity smb is
    port (    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC);
end smb;
