-- generated by newgenasym Sat Apr 07 17:08:34 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps53353dqpt is
    port (    
	EN:        INOUT  STD_LOGIC;    
	LL:        INOUT  STD_LOGIC_VECTOR (6 DOWNTO 1);    
	MODE:      INOUT  STD_LOGIC;    
	\n/c\:     INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	PGOOD:     INOUT  STD_LOGIC;    
	RF:        INOUT  STD_LOGIC;    
	TRIP:      INOUT  STD_LOGIC;    
	VBST:      INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VFB:       INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC_VECTOR (6 DOWNTO 1);    
	VREG:      INOUT  STD_LOGIC);
end tps53353dqpt;
