// generated by newgenasym  Wed Nov 16 18:21:59 2011


module coup_dc0710j5020ahf (\1 , \2 , \3 , \4 , \5 , \6 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;


    initial
        begin
        end

endmodule
