-- generated by newgenasym Fri Sep 25 17:10:51 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CON_SIP25_8 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end CON_SIP25_8;
