// generated by newgenasym  Wed Jun 22 14:32:08 2011


module adl5357acpz (comm, ifgm, ifon, ifop, lext, lgm3, loi1, loi2, losw, \n/c , pad,
        pwdn, rfct, rfin, vgs0, vgs1, vlo2, vlo3, vpif, vpsw);
    inout [2:1] comm;
    inout ifgm;
    inout ifon;
    inout ifop;
    inout lext;
    inout lgm3;
    inout loi1;
    inout loi2;
    inout losw;
    inout \n/c ;
    inout pad;
    inout pwdn;
    inout rfct;
    inout rfin;
    inout vgs0;
    inout vgs1;
    inout vlo2;
    inout vlo3;
    inout vpif;
    inout vpsw;


    initial
        begin
        end

endmodule
