// generated by newgenasym  Fri Jul 09 10:51:03 2010


module con_1125_1202g2s115t1 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
