-- generated by newgenasym Tue Apr 24 14:45:25 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc574ms8e is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	RF:        INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end hmc574ms8e;
