// generated by newgenasym  Thu Mar 05 17:02:48 2009


module dfcl32g01lbjaa_tt1 (gnd1, gnd2, gnd3, gnd4, gnd5, gnd6, in, out);
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    inout in;
    inout out;


    initial
        begin
        end

endmodule
