// generated by newgenasym  Thu May 07 17:48:59 2009


module con_p50le_080p1_sml_da (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \19 , \2 , \20 , \21 , \22 , \23 , \24 , \25 ,
        \26 , \27 , \28 , \29 , \3 , \30 , \31 , \32 , \33 , \34 , \35 , \36 , \37 , \38 , \39 , \4 , \40 , \41 ,
        \42 , \43 , \44 , \45 , \46 , \47 , \48 , \49 , \5 , \50 , \51 , \52 , \53 , \54 , \55 , \56 , \57 , \58 ,
        \59 , \6 , \60 , \61 , \62 , \63 , \64 , \65 , \66 , \67 , \68 , \69 , \7 , \70 , \71 , \72 , \73 , \74 ,
        \75 , \76 , \77 , \78 , \79 , \8 , \80 , \81 , \82 , \9 );
    inout \1 ;
    inout \10 ;
    inout \11 ;
    inout \12 ;
    inout \13 ;
    inout \14 ;
    inout \15 ;
    inout \16 ;
    inout \17 ;
    inout \18 ;
    inout \19 ;
    inout \2 ;
    inout \20 ;
    inout \21 ;
    inout \22 ;
    inout \23 ;
    inout \24 ;
    inout \25 ;
    inout \26 ;
    inout \27 ;
    inout \28 ;
    inout \29 ;
    inout \3 ;
    inout \30 ;
    inout \31 ;
    inout \32 ;
    inout \33 ;
    inout \34 ;
    inout \35 ;
    inout \36 ;
    inout \37 ;
    inout \38 ;
    inout \39 ;
    inout \4 ;
    inout \40 ;
    inout \41 ;
    inout \42 ;
    inout \43 ;
    inout \44 ;
    inout \45 ;
    inout \46 ;
    inout \47 ;
    inout \48 ;
    inout \49 ;
    inout \5 ;
    inout \50 ;
    inout \51 ;
    inout \52 ;
    inout \53 ;
    inout \54 ;
    inout \55 ;
    inout \56 ;
    inout \57 ;
    inout \58 ;
    inout \59 ;
    inout \6 ;
    inout \60 ;
    inout \61 ;
    inout \62 ;
    inout \63 ;
    inout \64 ;
    inout \65 ;
    inout \66 ;
    inout \67 ;
    inout \68 ;
    inout \69 ;
    inout \7 ;
    inout \70 ;
    inout \71 ;
    inout \72 ;
    inout \73 ;
    inout \74 ;
    inout \75 ;
    inout \76 ;
    inout \77 ;
    inout \78 ;
    inout \79 ;
    inout \8 ;
    inout \80 ;
    inout \81 ;
    inout \82 ;
    inout \9 ;


    initial
        begin
        end

endmodule
