// generated by newgenasym  Fri Aug 21 15:54:10 2009


module epm240t100i5n (b1_io, \b1_io/dev_clrn , \b1_io/dev_oe , \b1_io/gclk0 ,
        \b1_io/gclk1 , b1_tck, b1_tdi, b1_tdo, b1_tms, b2_io,
        \b2_io/gclk2 , \b2_io/gclk3 , gndint, gndio, vccint, vccio1,
        vccio2);
    inout [34:1] b1_io;
    inout \b1_io/dev_clrn ;
    inout \b1_io/dev_oe ;
    inout \b1_io/gclk0 ;
    inout \b1_io/gclk1 ;
    inout b1_tck;
    inout b1_tdi;
    inout b1_tdo;
    inout b1_tms;
    inout [40:1] b2_io;
    inout \b2_io/gclk2 ;
    inout \b2_io/gclk3 ;
    input [2:1] gndint;
    input [6:1] gndio;
    input [2:1] vccint;
    input [3:1] vccio1;
    input [3:1] vccio2;


    initial
        begin
        end

endmodule
