-- generated by newgenasym Thu Mar 05 11:06:26 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8375acpz is
    port (    
	A0:        INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	COMM1:     INOUT  STD_LOGIC;    
	COMM2:     INOUT  STD_LOGIC;    
	COMM3:     INOUT  STD_LOGIC;    
	COMM4:     INOUT  STD_LOGIC;    
	COMM5:     INOUT  STD_LOGIC;    
	COMM6:     INOUT  STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	PWUP:      INOUT  STD_LOGIC;    
	VCOM:      INOUT  STD_LOGIC;    
	\vin+\:    IN     STD_LOGIC;    
	\vin-\:    IN     STD_LOGIC;    
	\vout1+\:  OUT    STD_LOGIC;    
	\vout1-\:  OUT    STD_LOGIC;    
	\vout2+\:  OUT    STD_LOGIC;    
	\vout2-\:  OUT    STD_LOGIC;    
	VPOS1:     INOUT  STD_LOGIC;    
	VPOS2:     INOUT  STD_LOGIC;    
	VPOS3:     INOUT  STD_LOGIC;    
	VPOS4:     INOUT  STD_LOGIC;    
	VPOS5:     INOUT  STD_LOGIC);
end ad8375acpz;
