// generated by newgenasym  Wed Sep 02 18:07:31 2009


module ad7814art (\cs# , din, dout, gnd, sclk, vdd);
    inout \cs# ;
    inout din;
    inout dout;
    inout gnd;
    inout sclk;
    inout vdd;


    initial
        begin
        end

endmodule
