-- generated by newgenasym Wed Sep 02 18:07:31 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad7814art is
    port (    
	\cs#\:     INOUT  STD_LOGIC;    
	DIN:       INOUT  STD_LOGIC;    
	DOUT:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	SCLK:      INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end ad7814art;
