// generated by newgenasym  Thu Feb 12 15:21:45 2009


module mt47h16m16bg (a0, a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9, ba0, ba1,
        \cas# , ck, \ck# , cke, \cs# , dq0, dq1, dq10, dq11, dq12, dq13, dq14,
        dq15, dq2, dq3, dq4, dq5, dq6, dq7, dq8, dq9, ldm, ldqs,
        \ldqs#/nu , nc1, nc2, odt, \ras# , rfu1, rfu2, rfu3, rfu4, udm,
        udqs, \udqs#/nu , vdd_1, vdd_2, vdd_3, vdd_4, vdd_5, vddl,
        vddq_1, vddq_10, vddq_2, vddq_3, vddq_4, vddq_5, vddq_6,
        vddq_7, vddq_8, vddq_9, vref, vss_1, vss_2, vss_3, vss_4,
        vss_5, vssdl, vssq_1, vssq_10, vssq_2, vssq_3, vssq_4,
        vssq_5, vssq_6, vssq_7, vssq_8, vssq_9, \we# );
    inout a0;
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout ba0;
    inout ba1;
    inout \cas# ;
    inout ck;
    inout \ck# ;
    inout cke;
    inout \cs# ;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout dq15;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dq8;
    inout dq9;
    inout ldm;
    inout ldqs;
    inout \ldqs#/nu ;
    inout nc1;
    inout nc2;
    inout odt;
    inout \ras# ;
    inout rfu1;
    inout rfu2;
    inout rfu3;
    inout rfu4;
    inout udm;
    inout udqs;
    inout \udqs#/nu ;
    input vdd_1;
    input vdd_2;
    input vdd_3;
    input vdd_4;
    input vdd_5;
    input vddl;
    input vddq_1;
    input vddq_10;
    input vddq_2;
    input vddq_3;
    input vddq_4;
    input vddq_5;
    input vddq_6;
    input vddq_7;
    input vddq_8;
    input vddq_9;
    input vref;
    input vss_1;
    input vss_2;
    input vss_3;
    input vss_4;
    input vss_5;
    input vssdl;
    input vssq_1;
    input vssq_10;
    input vssq_2;
    input vssq_3;
    input vssq_4;
    input vssq_5;
    input vssq_6;
    input vssq_7;
    input vssq_8;
    input vssq_9;
    inout \we# ;


    initial
        begin
        end

endmodule
