// generated by newgenasym  Fri Apr 17 15:31:41 2009


module \74lvc138apw  (a0, a1, a2, \e1# , \e2# , e3, gnd, vcc, \y0# , \y1# , \y2# , \y3# , \y4# , \y5# ,
        \y6# , \y7# );
    input a0;
    input a1;
    input a2;
    input \e1# ;
    input \e2# ;
    input e3;
    input gnd;
    input vcc;
    output \y0# ;
    output \y1# ;
    output \y2# ;
    output \y3# ;
    output \y4# ;
    output \y5# ;
    output \y6# ;
    output \y7# ;


    initial
        begin
        end

endmodule
