// generated by newgenasym  Thu Oct 21 14:00:34 2010


module adl5375_05acpz (comm1, comm10, comm2, comm3, comm4, comm5, comm6, comm7,
        comm8, comm9, dsop, ibbn, ibbp, loin, loip, nc1, nc2, nc3, nc4,
        pad, qbbn, qbbp, rfout, vps1, vps2);
    inout comm1;
    inout comm10;
    inout comm2;
    inout comm3;
    inout comm4;
    inout comm5;
    inout comm6;
    inout comm7;
    inout comm8;
    inout comm9;
    inout dsop;
    inout ibbn;
    inout ibbp;
    inout loin;
    inout loip;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout pad;
    inout qbbn;
    inout qbbp;
    inout rfout;
    inout vps1;
    inout vps2;


    initial
        begin
        end

endmodule
