-- generated by newgenasym Wed Oct 20 17:37:10 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8364acpz is
    port (    
	ACOM1:     INOUT  STD_LOGIC;    
	ACOM2:     INOUT  STD_LOGIC;    
	ADJA:      INOUT  STD_LOGIC;    
	ADJB:      INOUT  STD_LOGIC;    
	CHPA:      INOUT  STD_LOGIC;    
	CHPB:      INOUT  STD_LOGIC;    
	CLPA:      INOUT  STD_LOGIC;    
	CLPB:      INOUT  STD_LOGIC;    
	COMA:      INOUT  STD_LOGIC;    
	COMB:      INOUT  STD_LOGIC;    
	COMR:      INOUT  STD_LOGIC;    
	DECA:      INOUT  STD_LOGIC;    
	DECB:      INOUT  STD_LOGIC;    
	FBKA:      INOUT  STD_LOGIC;    
	FBKB:      INOUT  STD_LOGIC;    
	INHA:      INOUT  STD_LOGIC;    
	INHB:      INOUT  STD_LOGIC;    
	INLA:      INOUT  STD_LOGIC;    
	INLB:      INOUT  STD_LOGIC;    
	OUTA:      INOUT  STD_LOGIC;    
	OUTB:      INOUT  STD_LOGIC;    
	OUTN:      INOUT  STD_LOGIC;    
	OUTP:      INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	PWDN:      INOUT  STD_LOGIC;    
	TEMP:      INOUT  STD_LOGIC;    
	VLVL:      INOUT  STD_LOGIC;    
	VPSA:      INOUT  STD_LOGIC;    
	VPSB:      INOUT  STD_LOGIC;    
	VPSR:      INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC;    
	VSTA:      INOUT  STD_LOGIC;    
	VSTB:      INOUT  STD_LOGIC);
end ad8364acpz;
