-- generated by newgenasym Tue Jun 06 09:55:46 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity testpoint_rf is
    port (    
	GND:       IN     STD_LOGIC;    
	SIG:       INOUT  STD_LOGIC);
end testpoint_rf;
