// generated by newgenasym  Thu Feb 12 15:26:02 2009


module si7860adp (d1, d2, d3, d4, g, s1, s2, s3);
    inout d1;
    inout d2;
    inout d3;
    inout d4;
    inout g;
    inout s1;
    inout s2;
    inout s3;


    initial
        begin
        end

endmodule
