-- generated by newgenasym Thu Feb 12 15:26:02 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity si7860adp is
    port (    
	D1:        INOUT  STD_LOGIC;    
	D2:        INOUT  STD_LOGIC;    
	D3:        INOUT  STD_LOGIC;    
	D4:        INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	S1:        INOUT  STD_LOGIC;    
	S2:        INOUT  STD_LOGIC;    
	S3:        INOUT  STD_LOGIC);
end si7860adp;
