-- generated by newgenasym Wed Apr 29 15:45:37 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tvs_1sma is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end tvs_1sma;
