// generated by newgenasym  Tue Oct 25 14:59:31 2011


module glc7w2fbpsb51g2m (\1 , \2 , \3 , \4 , \5 , a1, a2);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout a1;
    inout a2;


    initial
        begin
        end

endmodule
