// generated by newgenasym  Sat Oct 09 11:06:41 2010


module cat811stbi (gnd, \mr# , \reset# , vcc);
    inout gnd;
    inout \mr# ;
    inout \reset# ;
    inout vcc;


    initial
        begin
        end

endmodule
