-- generated by newgenasym Fri Aug 05 17:12:10 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity W25X10BLSNIG is
    port (    
	CLK:       INOUT  STD_LOGIC;    
	\cs#\:     INOUT  STD_LOGIC;    
	DIO:       INOUT  STD_LOGIC;    
	DO:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\hold#\:   INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	\wp#\:     INOUT  STD_LOGIC);
end W25X10BLSNIG;
