// generated by newgenasym  Mon Mar 19 10:40:01 2012


module ovetgljtnf_50mhz (gnd, out, \tris/nc , vdd);
    input gnd;
    output out;
    inout \tris/nc ;
    input vdd;


    initial
        begin
        end

endmodule
