// generated by newgenasym  Tue Jul 12 17:31:06 2011


module ds26lv31tmnopb (\di#201 , \di#202 , \di#203 , \di#204 , \do#201+ , \do#201- , \do#202+ , \do#202- , \do#203+ ,
        \do#203- , \do#204+ , \do#204- , en, \en# , gnd, vcc);
    inout \di#201 ;
    inout \di#202 ;
    inout \di#203 ;
    inout \di#204 ;
    inout \do#201+ ;
    inout \do#201- ;
    inout \do#202+ ;
    inout \do#202- ;
    inout \do#203+ ;
    inout \do#203- ;
    inout \do#204+ ;
    inout \do#204- ;
    inout en;
    inout \en# ;
    inout gnd;
    inout vcc;


    initial
        begin
        end

endmodule
