-- generated by newgenasym Tue Jul 12 17:31:06 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds26lv31tmnopb is
    port (    
	\di 1\:    INOUT  STD_LOGIC;    
	\di 2\:    INOUT  STD_LOGIC;    
	\di 3\:    INOUT  STD_LOGIC;    
	\di 4\:    INOUT  STD_LOGIC;    
	\do 1+\:   INOUT  STD_LOGIC;    
	\do 1-\:   INOUT  STD_LOGIC;    
	\do 2+\:   INOUT  STD_LOGIC;    
	\do 2-\:   INOUT  STD_LOGIC;    
	\do 3+\:   INOUT  STD_LOGIC;    
	\do 3-\:   INOUT  STD_LOGIC;    
	\do 4+\:   INOUT  STD_LOGIC;    
	\do 4-\:   INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	\en#\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end ds26lv31tmnopb;
