// generated by newgenasym  Fri Sep 04 17:43:01 2009


module mcx (\2 , \3 , \4 , \5 , in);
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout in;


    initial
        begin
        end

endmodule
