// generated by newgenasym  Tue Apr 14 16:50:36 2009


module epm1270f256i5 (b1_io_1, b1_io_10, \b1_io_11/570nc43 , b1_io_12,
        \b1_io_13/570nc44 , b1_io_14, \b1_io_15/570nc45 , b1_io_16,
        b1_io_17, b1_io_18, \b1_io_19/570nc27 , b1_io_2, b1_io_20,
        \b1_io_21/570nc28 , b1_io_22, \b1_io_23/570nc29 , b1_io_24,
        b1_io_25, b1_io_26, \b1_io_27/gclk0 , \b1_io_28/gclk1 ,
        \b1_io_29/570nc31 , b1_io_3, b1_io_30, \b1_io_31/570nc18 ,
        b1_io_32, b1_io_33, b1_io_34, \b1_io_35/570nc23 , b1_io_36,
        \b1_io_37/570nc22 , b1_io_38, \b1_io_39/570nc21 , b1_io_4,
        b1_io_40, b1_io_41, b1_io_42, \b1_io_43/570nc10 , b1_io_44,
        b1_io_45, b1_io_46, b1_io_47, b1_io_48, b1_io_49, b1_io_5,
        b1_io_50, b1_io_51, b1_io_6, \b1_io_7/570nc35 , b1_io_8,
        b1_io_9, b2_io_1, b2_io_10, \b2_io_11/570nc33 , b2_io_12,
        b2_io_13, b2_io_14, \b2_io_15/570nc47 , b2_io_16,
        \b2_io_17/570nc32 , b2_io_18, \b2_io_19/570nc40 , b2_io_2,
        b2_io_20, b2_io_21, b2_io_22, \b2_io_23/570nc51 , b2_io_24,
        \b2_io_25/570nc39 , b2_io_26, b2_io_27, b2_io_28,
        \b2_io_29/570nc38 , b2_io_3, b2_io_30, \b2_io_31/570nc50 ,
        b2_io_32, b2_io_33, b2_io_34, \b2_io_35/570nc46 , b2_io_36,
        \b2_io_37/570nc37 , b2_io_38, \b2_io_39/570nc49 , b2_io_4,
        b2_io_40, b2_io_41, b2_io_42, \b2_io_43/570nc36 , b2_io_44,
        \b2_io_45/570nc48 , b2_io_46, b2_io_47, b2_io_48, b2_io_49,
        b2_io_5, b2_io_50, b2_io_51, b2_io_52, b2_io_53, b2_io_6,
        b2_io_7, b2_io_8, b2_io_9, b3_io_1, b3_io_10, b3_io_11,
        \b3_io_12/570nc9 , b3_io_13, \b3_io_14/570nc8 , b3_io_15,
        b3_io_16, b3_io_17, \b3_io_18/570nc20 , b3_io_19, b3_io_2,
        \b3_io_20/570nc19 , b3_io_21, \b3_io_22/570nc18 , b3_io_23,
        b3_io_24, b3_io_25, \b3_io_26/570nc17 , \b3_io_27/gclk2 ,
        \b3_io_28/gclk3 , b3_io_29, b3_io_3, \b3_io_30/570nc30 ,
        b3_io_31, b3_io_32, b3_io_33, \b3_io_34/570nc25 , b3_io_35,
        \b3_io_36/570nc24 , b3_io_37, \b3_io_38/570nc26 , b3_io_39,
        b3_io_4, b3_io_40, b3_io_41, \b3_io_42/570nc41 , b3_io_43,
        \b3_io_44/570nc42 , b3_io_45, b3_io_46, b3_io_47, b3_io_48,
        b3_io_49, b3_io_5, \b3_io_50/570nc34 , b3_io_51, b3_io_52,
        b3_io_53, b3_io_54, b3_io_55, b3_io_6, b3_io_7, b3_io_8,
        b3_io_9, b4_io_1, b4_io_10, \b4_io_11/570nc15 , b4_io_12,
        b4_io_13, b4_io_14, \b4_io_15/570nc4 , b4_io_16,
        \b4_io_17/570nc16 , b4_io_18, \b4_io_19/570nc11 , b4_io_2,
        b4_io_20, b4_io_21, b4_io_22, \b4_io_23/570nc5 , b4_io_24,
        \b4_io_25/570nc6 , b4_io_26, b4_io_27, b4_io_28, b4_io_29,
        b4_io_3, b4_io_30, \b4_io_31/dev_oe , \b4_io_32/dev_clrn ,
        \b4_io_33/570nc7 , b4_io_34, \b4_io_35/570nc12 , b4_io_36,
        \b4_io_37/570nc1 , b4_io_38, b4_io_39, b4_io_4, b4_io_40,
        \b4_io_41/570nc13 , b4_io_42, \b4_io_43/570nc2 , b4_io_44,
        b4_io_45, b4_io_46, \b4_io_47/570nc14 , b4_io_48, b4_io_49,
        b4_io_5, b4_io_50, b4_io_51, b4_io_52, b4_io_53, b4_io_6,
        b4_io_7, b4_io_8, \b4_io_9/570nc3 , gndint_1, gndint_2,
        gndint_3, gndint_4, gndio_1, gndio_10, gndio_11, gndio_12,
        gndio_13, gndio_14, gndio_15, gndio_16, gndio_2, gndio_3,
        gndio_4, gndio_5, gndio_6, gndio_7, gndio_8, gndio_9, tck,
        tdi, tdo, tms, vccint_1, vccint_2, vccint_3, vccint_4,
        vccio1_1, vccio1_2, vccio1_3, vccio1_4, vccio2_1, vccio2_2,
        vccio2_3, vccio2_4, vccio3_1, vccio3_2, vccio3_3, vccio3_4,
        vccio4_1, vccio4_2, vccio4_3, vccio4_4);
    inout b1_io_1;
    inout b1_io_10;
    inout \b1_io_11/570nc43 ;
    inout b1_io_12;
    inout \b1_io_13/570nc44 ;
    inout b1_io_14;
    inout \b1_io_15/570nc45 ;
    inout b1_io_16;
    inout b1_io_17;
    inout b1_io_18;
    inout \b1_io_19/570nc27 ;
    inout b1_io_2;
    inout b1_io_20;
    inout \b1_io_21/570nc28 ;
    inout b1_io_22;
    inout \b1_io_23/570nc29 ;
    inout b1_io_24;
    inout b1_io_25;
    inout b1_io_26;
    inout \b1_io_27/gclk0 ;
    inout \b1_io_28/gclk1 ;
    inout \b1_io_29/570nc31 ;
    inout b1_io_3;
    inout b1_io_30;
    inout \b1_io_31/570nc18 ;
    inout b1_io_32;
    inout b1_io_33;
    inout b1_io_34;
    inout \b1_io_35/570nc23 ;
    inout b1_io_36;
    inout \b1_io_37/570nc22 ;
    inout b1_io_38;
    inout \b1_io_39/570nc21 ;
    inout b1_io_4;
    inout b1_io_40;
    inout b1_io_41;
    inout b1_io_42;
    inout \b1_io_43/570nc10 ;
    inout b1_io_44;
    inout b1_io_45;
    inout b1_io_46;
    inout b1_io_47;
    inout b1_io_48;
    inout b1_io_49;
    inout b1_io_5;
    inout b1_io_50;
    inout b1_io_51;
    inout b1_io_6;
    inout \b1_io_7/570nc35 ;
    inout b1_io_8;
    inout b1_io_9;
    inout b2_io_1;
    inout b2_io_10;
    inout \b2_io_11/570nc33 ;
    inout b2_io_12;
    inout b2_io_13;
    inout b2_io_14;
    inout \b2_io_15/570nc47 ;
    inout b2_io_16;
    inout \b2_io_17/570nc32 ;
    inout b2_io_18;
    inout \b2_io_19/570nc40 ;
    inout b2_io_2;
    inout b2_io_20;
    inout b2_io_21;
    inout b2_io_22;
    inout \b2_io_23/570nc51 ;
    inout b2_io_24;
    inout \b2_io_25/570nc39 ;
    inout b2_io_26;
    inout b2_io_27;
    inout b2_io_28;
    inout \b2_io_29/570nc38 ;
    inout b2_io_3;
    inout b2_io_30;
    inout \b2_io_31/570nc50 ;
    inout b2_io_32;
    inout b2_io_33;
    inout b2_io_34;
    inout \b2_io_35/570nc46 ;
    inout b2_io_36;
    inout \b2_io_37/570nc37 ;
    inout b2_io_38;
    inout \b2_io_39/570nc49 ;
    inout b2_io_4;
    inout b2_io_40;
    inout b2_io_41;
    inout b2_io_42;
    inout \b2_io_43/570nc36 ;
    inout b2_io_44;
    inout \b2_io_45/570nc48 ;
    inout b2_io_46;
    inout b2_io_47;
    inout b2_io_48;
    inout b2_io_49;
    inout b2_io_5;
    inout b2_io_50;
    inout b2_io_51;
    inout b2_io_52;
    inout b2_io_53;
    inout b2_io_6;
    inout b2_io_7;
    inout b2_io_8;
    inout b2_io_9;
    inout b3_io_1;
    inout b3_io_10;
    inout b3_io_11;
    inout \b3_io_12/570nc9 ;
    inout b3_io_13;
    inout \b3_io_14/570nc8 ;
    inout b3_io_15;
    inout b3_io_16;
    inout b3_io_17;
    inout \b3_io_18/570nc20 ;
    inout b3_io_19;
    inout b3_io_2;
    inout \b3_io_20/570nc19 ;
    inout b3_io_21;
    inout \b3_io_22/570nc18 ;
    inout b3_io_23;
    inout b3_io_24;
    inout b3_io_25;
    inout \b3_io_26/570nc17 ;
    inout \b3_io_27/gclk2 ;
    inout \b3_io_28/gclk3 ;
    inout b3_io_29;
    inout b3_io_3;
    inout \b3_io_30/570nc30 ;
    inout b3_io_31;
    inout b3_io_32;
    inout b3_io_33;
    inout \b3_io_34/570nc25 ;
    inout b3_io_35;
    inout \b3_io_36/570nc24 ;
    inout b3_io_37;
    inout \b3_io_38/570nc26 ;
    inout b3_io_39;
    inout b3_io_4;
    inout b3_io_40;
    inout b3_io_41;
    inout \b3_io_42/570nc41 ;
    inout b3_io_43;
    inout \b3_io_44/570nc42 ;
    inout b3_io_45;
    inout b3_io_46;
    inout b3_io_47;
    inout b3_io_48;
    inout b3_io_49;
    inout b3_io_5;
    inout \b3_io_50/570nc34 ;
    inout b3_io_51;
    inout b3_io_52;
    inout b3_io_53;
    inout b3_io_54;
    inout b3_io_55;
    inout b3_io_6;
    inout b3_io_7;
    inout b3_io_8;
    inout b3_io_9;
    inout b4_io_1;
    inout b4_io_10;
    inout \b4_io_11/570nc15 ;
    inout b4_io_12;
    inout b4_io_13;
    inout b4_io_14;
    inout \b4_io_15/570nc4 ;
    inout b4_io_16;
    inout \b4_io_17/570nc16 ;
    inout b4_io_18;
    inout \b4_io_19/570nc11 ;
    inout b4_io_2;
    inout b4_io_20;
    inout b4_io_21;
    inout b4_io_22;
    inout \b4_io_23/570nc5 ;
    inout b4_io_24;
    inout \b4_io_25/570nc6 ;
    inout b4_io_26;
    inout b4_io_27;
    inout b4_io_28;
    inout b4_io_29;
    inout b4_io_3;
    inout b4_io_30;
    inout \b4_io_31/dev_oe ;
    inout \b4_io_32/dev_clrn ;
    inout \b4_io_33/570nc7 ;
    inout b4_io_34;
    inout \b4_io_35/570nc12 ;
    inout b4_io_36;
    inout \b4_io_37/570nc1 ;
    inout b4_io_38;
    inout b4_io_39;
    inout b4_io_4;
    inout b4_io_40;
    inout \b4_io_41/570nc13 ;
    inout b4_io_42;
    inout \b4_io_43/570nc2 ;
    inout b4_io_44;
    inout b4_io_45;
    inout b4_io_46;
    inout \b4_io_47/570nc14 ;
    inout b4_io_48;
    inout b4_io_49;
    inout b4_io_5;
    inout b4_io_50;
    inout b4_io_51;
    inout b4_io_52;
    inout b4_io_53;
    inout b4_io_6;
    inout b4_io_7;
    inout b4_io_8;
    inout \b4_io_9/570nc3 ;
    input gndint_1;
    input gndint_2;
    input gndint_3;
    input gndint_4;
    input gndio_1;
    input gndio_10;
    input gndio_11;
    input gndio_12;
    input gndio_13;
    input gndio_14;
    input gndio_15;
    input gndio_16;
    input gndio_2;
    input gndio_3;
    input gndio_4;
    input gndio_5;
    input gndio_6;
    input gndio_7;
    input gndio_8;
    input gndio_9;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    input vccint_1;
    input vccint_2;
    input vccint_3;
    input vccint_4;
    input vccio1_1;
    input vccio1_2;
    input vccio1_3;
    input vccio1_4;
    input vccio2_1;
    input vccio2_2;
    input vccio2_3;
    input vccio2_4;
    input vccio3_1;
    input vccio3_2;
    input vccio3_3;
    input vccio3_4;
    input vccio4_1;
    input vccio4_2;
    input vccio4_3;
    input vccio4_4;


    initial
        begin
        end

endmodule
