-- generated by newgenasym Wed May 27 14:12:02 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lp3878 is
    port (    
	ADJ:       INOUT  STD_LOGIC;    
	BYPASS:    INOUT  STD_LOGIC;    
	\down#\:   INOUT  STD_LOGIC;    
	GROUND:    INOUT  STD_LOGIC;    
	INPUT:     INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	OUTPUT:    INOUT  STD_LOGIC;    
	PAD_GND:   INOUT  STD_LOGIC);
end lp3878;
