// generated by newgenasym  Thu Oct 21 18:05:37 2010


module xc6slx150t_3fgg900i (cmpcs_b_2, done_2, gnd, io_l10n_0, io_l10n_2, io_l10n_3,
        io_l10n_m5a1_5, io_l10p_0, io_l10p_2, io_l10p_3,
        io_l10p_m5a0_5, io_l11n_0, io_l11n_2, io_l11n_3,
        io_l11n_m5clkn_5, io_l11p_0, io_l11p_2, io_l11p_3,
        io_l11p_m5clk_5, io_l12n_0, io_l12n_3,
        io_l12n_d2_miso3_2, io_l12n_m5odt_5, io_l12p_0,
        io_l12p_3, io_l12p_d1_miso2_2, io_l12p_m5a3_5, io_l13n_0,
        io_l13n_3, io_l13n_d10_2, io_l13n_m5a6_5, io_l13p_0,
        io_l13p_3, io_l13p_m1_2, io_l13p_m5a5_5, io_l14n_0,
        io_l14n_3, io_l14n_d12_2, io_l14n_m5casn_5, io_l14p_0,
        io_l14p_3, io_l14p_d11_2, io_l14p_m5rasn_5, io_l15n_0,
        io_l15n_2, io_l15n_3, io_l15n_m5ldm_5, io_l15p_0,
        io_l15p_2, io_l15p_3, io_l15p_m5udm_5, io_l16n_0,
        io_l16n_3, io_l16n_m5dq5_5, io_l16n_vref_2, io_l16p_0,
        io_l16p_2, io_l16p_3, io_l16p_m5dq4_5, io_l17n_0,
        io_l17n_2, io_l17n_m5dq7_5, io_l17n_vref_3, io_l17p_0,
        io_l17p_2, io_l17p_3, io_l17p_m5dq6_5, io_l18n_0,
        io_l18n_2, io_l18n_3, io_l18n_m5ldqsn_5, io_l18p_0,
        io_l18p_2, io_l18p_3, io_l18p_m5ldqs_5, io_l19n_0,
        io_l19n_2, io_l19n_3, io_l19n_m5dq3_5, io_l19p_0,
        io_l19p_2, io_l19p_3, io_l19p_m5dq2_5, io_l1n_a24_vref_5,
        io_l1n_m0_cmpmiso_2, io_l1n_vref_0, io_l1n_vref_3,
        io_l1p_3, io_l1p_a25_5, io_l1p_cclk_2, io_l1p_hswapen_0,
        io_l20n_0, io_l20n_2, io_l20n_3, io_l20n_m5dq1_5,
        io_l20p_0, io_l20p_2, io_l20p_3, io_l20p_m5dq0_5,
        io_l21n_0, io_l21n_2, io_l21n_3, io_l21n_m5dq9_5,
        io_l21p_0, io_l21p_2, io_l21p_3, io_l21p_m5dq8_5,
        io_l22n_0, io_l22n_2, io_l22n_3, io_l22n_m5dq11_5,
        io_l22p_0, io_l22p_2, io_l22p_3, io_l22p_m5dq10_5,
        io_l23n_0, io_l23n_2, io_l23n_3, io_l23n_m5udqsn_5,
        io_l23p_0, io_l23p_2, io_l23p_3, io_l23p_m5udqs_5,
        io_l24n_0, io_l24n_3, io_l24n_m5dq13_5, io_l24p_0,
        io_l24p_3, io_l24p_m5dq12_5, io_l25n_0, io_l25n_3,
        io_l25n_m5dq15_5, io_l25p_0, io_l25p_3, io_l25p_m5dq14_5,
        io_l26n_0, io_l26n_3, io_l26n_vref_5, io_l26p_0,
        io_l26p_3, io_l26p_5, io_l27n_3, io_l27n_5, io_l27p_3,
        io_l27p_5, io_l28n_2, io_l28n_3, io_l28n_vref_1,
        io_l28p_1, io_l28p_2, io_l28p_3, io_l29n_3,
        io_l29n_a22_m1a14_1, io_l29n_gclk2_2, io_l29p_3,
        io_l29p_a23_m1a13_1, io_l29p_gclk3_2, io_l2n_0, io_l2n_3,
        io_l2n_cmpmosi_2, io_l2n_m5a14_5, io_l2p_0, io_l2p_3,
        io_l2p_cmpclk_2, io_l2p_m5a13_5, io_l30n_3,
        io_l30n_a20_m1a11_1, io_l30n_gclk0_usercclk_2,
        io_l30p_3, io_l30p_a21_m1reset_1, io_l30p_gclk1_d13_2,
        io_l31n_a18_m1a12_1, io_l31n_gclk30_d15_2,
        io_l31n_vref_3, io_l31p_3, io_l31p_a19_m1cke_1,
        io_l31p_gclk31_d14_2, io_l32n_0, io_l32n_a16_m1a9_1,
        io_l32n_gclk28_2, io_l32n_m3dq15_3, io_l32p_0,
        io_l32p_a17_m1a8_1, io_l32p_gclk29_2, io_l32p_m3dq14_3,
        io_l33n_0, io_l33n_2, io_l33n_a14_m1a4_1,
        io_l33n_m3dq13_3, io_l33p_0, io_l33p_2,
        io_l33p_a15_m1a10_1, io_l33p_m3dq12_3, io_l34n_2,
        io_l34n_a12_m1ba2_1, io_l34n_gclk18_0,
        io_l34n_m3udqsn_3, io_l34p_2, io_l34p_a13_m1we_1,
        io_l34p_gclk19_0, io_l34p_m3udqs_3, io_l35n_a10_m1a2_1,
        io_l35n_gclk16_0, io_l35n_m3dq11_3, io_l35p_a11_m1a7_1,
        io_l35p_gclk17_0, io_l35p_m3dq10_3, io_l36n_a8_m1ba1_1,
        io_l36n_gclk14_0, io_l36n_m3dq9_3, io_l36p_a9_m1ba0_1,
        io_l36p_gclk15_0, io_l36p_m3dq8_3, io_l37n_a6_m1a1_1,
        io_l37n_gclk12_0, io_l37n_m3dq1_3, io_l37p_a7_m1a0_1,
        io_l37p_gclk13_0, io_l37p_m3dq0_3, io_l38n_a4_m1clkn_1,
        io_l38n_m3dq3_3, io_l38n_vref_0, io_l38p_0,
        io_l38p_a5_m1clk_1, io_l38p_m3dq2_3, io_l39n_m1odt_1,
        io_l39n_m3ldqsn_3, io_l39p_m1a3_1, io_l39p_m3ldqs_3,
        io_l3n_0, io_l3n_3, io_l3n_m5a11_5,
        io_l3n_mosi_csi_b_miso0_2, io_l3p_0, io_l3p_3,
        io_l3p_d0_din_miso_miso1_2, io_l3p_m5reset_5, io_l40n_2,
        io_l40n_gclk10_m1a6_1, io_l40n_m3dq7_3, io_l40p_2,
        io_l40p_gclk11_m1a5_1, io_l40p_m3dq6_3,
        io_l41n_gclk26_m3dq5_3, io_l41n_gclk8_m1casn_1,
        io_l41n_vref_2, io_l41p_2, io_l41p_gclk27_m3dq4_3,
        io_l41p_gclk9_irdy1_m1rasn_1, io_l42n_2,
        io_l42n_gclk24_m3ldm_3, io_l42n_gclk6_trdy1_m1ldm_1,
        io_l42p_2, io_l42p_gclk25_trdy2_m3udm_3,
        io_l42p_gclk7_m1udm_1, io_l43n_0, io_l43n_2,
        io_l43n_gclk22_irdy2_m3casn_3, io_l43n_gclk4_m1dq5_1,
        io_l43p_0, io_l43p_2, io_l43p_gclk23_m3rasn_3,
        io_l43p_gclk5_m1dq4_1, io_l44n_0, io_l44n_2,
        io_l44n_a2_m1dq7_1, io_l44n_gclk20_m3a6_3, io_l44p_0,
        io_l44p_2, io_l44p_a3_m1dq6_1, io_l44p_gclk21_m3a5_3,
        io_l45n_0, io_l45n_2, io_l45n_a0_m1ldqsn_1,
        io_l45n_m3odt_3, io_l45p_0, io_l45p_2,
        io_l45p_a1_m1ldqs_1, io_l45p_m3a3_3, io_l46n_0,
        io_l46n_2, io_l46n_foe_b_m1dq3_1, io_l46n_m3clkn_3,
        io_l46p_0, io_l46p_2, io_l46p_fcs_b_m1dq2_1,
        io_l46p_m3clk_3, io_l47n_0, io_l47n_2,
        io_l47n_ldc_m1dq1_1, io_l47n_m3a1_3, io_l47p_0,
        io_l47p_2, io_l47p_fwe_b_m1dq0_1, io_l47p_m3a0_3,
        io_l48n_0, io_l48n_m1dq9_1, io_l48n_m3ba1_3,
        io_l48n_rdwr_b_vref_2, io_l48p_0, io_l48p_d7_2,
        io_l48p_hdc_m1dq8_1, io_l48p_m3ba0_3, io_l49n_0,
        io_l49n_d4_2, io_l49n_m1dq11_1, io_l49n_m3a2_3,
        io_l49p_0, io_l49p_d3_2, io_l49p_m1dq10_1,
        io_l49p_m3a7_3, io_l4n_0, io_l4n_3, io_l4n_m5a12_5,
        io_l4n_vref_2, io_l4p_0, io_l4p_2, io_l4p_3,
        io_l4p_m5cke_5, io_l50n_0, io_l50n_2, io_l50n_m1udqsn_1,
        io_l50n_m3ba2_3, io_l50p_0, io_l50p_2, io_l50p_m1udqs_1,
        io_l50p_m3we_3, io_l51n_0, io_l51n_2, io_l51n_m1dq13_1,
        io_l51n_m3a4_3, io_l51p_0, io_l51p_2, io_l51p_m1dq12_1,
        io_l51p_m3a10_3, io_l52n_0, io_l52n_2, io_l52n_m1dq15_1,
        io_l52n_m3a9_3, io_l52p_0, io_l52p_2, io_l52p_m1dq14_1,
        io_l52p_m3a8_3, io_l53n_0, io_l53n_2, io_l53n_m3a12_3,
        io_l53n_vref_1, io_l53p_0, io_l53p_1, io_l53p_2,
        io_l53p_m3cke_3, io_l54n_0, io_l54n_1, io_l54n_2,
        io_l54n_m3a11_3, io_l54p_0, io_l54p_1, io_l54p_2,
        io_l54p_m3reset_3, io_l55n_0, io_l55n_1, io_l55n_2,
        io_l55n_m3a14_3, io_l55p_0, io_l55p_1, io_l55p_2,
        io_l55p_m3a13_3, io_l56n_0, io_l56n_1, io_l56n_2,
        io_l56n_3, io_l56p_0, io_l56p_1, io_l56p_2, io_l56p_3,
        io_l57n_0, io_l57n_1, io_l57n_2, io_l57n_vref_3,
        io_l57p_0, io_l57p_1, io_l57p_2, io_l57p_3, io_l58n_0,
        io_l58n_1, io_l58n_2, io_l58n_vref_4, io_l58p_0,
        io_l58p_1, io_l58p_2, io_l58p_4, io_l59n_0, io_l59n_1,
        io_l59n_2, io_l59n_m4dq15_4, io_l59p_0, io_l59p_1,
        io_l59p_2, io_l59p_m4dq14_4, io_l5n_0, io_l5n_2, io_l5n_3,
        io_l5n_m5a9_5, io_l5p_0, io_l5p_2, io_l5p_3,
        io_l5p_m5a8_5, io_l60n_0, io_l60n_1, io_l60n_2,
        io_l60n_m4dq13_4, io_l60p_0, io_l60p_1, io_l60p_2,
        io_l60p_m4dq12_4, io_l61n_0, io_l61n_1,
        io_l61n_m4udqsn_4, io_l61n_vref_2, io_l61p_0, io_l61p_1,
        io_l61p_2, io_l61p_m4udqs_4, io_l62n_1, io_l62n_d6_2,
        io_l62n_m4dq11_4, io_l62n_vref_0, io_l62p_0, io_l62p_1,
        io_l62p_d5_2, io_l62p_m4dq10_4, io_l63n_1, io_l63n_2,
        io_l63n_m4dq9_4, io_l63n_scp6_0, io_l63p_1, io_l63p_2,
        io_l63p_m4dq8_4, io_l63p_scp7_0, io_l64n_1, io_l64n_d9_2,
        io_l64n_m4dq1_4, io_l64n_scp4_0, io_l64p_1, io_l64p_d8_2,
        io_l64p_m4dq0_4, io_l64p_scp5_0, io_l65n_1,
        io_l65n_cso_b_2, io_l65n_m4dq3_4, io_l65n_scp2_0,
        io_l65p_1, io_l65p_init_b_2, io_l65p_m4dq2_4,
        io_l65p_scp3_0, io_l66n_1, io_l66n_m4ldqsn_4,
        io_l66n_scp0_0, io_l66p_1, io_l66p_m4ldqs_4,
        io_l66p_scp1_0, io_l67n_1, io_l67n_m4dq7_4, io_l67p_1,
        io_l67p_m4dq6_4, io_l68n_1, io_l68n_m4dq5_4, io_l68p_1,
        io_l68p_m4dq4_4, io_l69n_m4ldm_4, io_l69n_vref_1,
        io_l69p_1, io_l69p_m4udm_4, io_l6n_0, io_l6n_2, io_l6n_3,
        io_l6n_m5a4_5, io_l6p_0, io_l6p_2, io_l6p_3,
        io_l6p_m5a10_5, io_l70n_1, io_l70n_m4casn_4, io_l70p_1,
        io_l70p_m4rasn_4, io_l71n_1, io_l71n_m4a6_4, io_l71p_1,
        io_l71p_m4a5_4, io_l72n_1, io_l72n_m4odt_4, io_l72p_1,
        io_l72p_m4a3_4, io_l73n_1, io_l73n_m4clkn_4, io_l73p_1,
        io_l73p_m4clk_4, io_l74n_dout_busy_1, io_l74n_m4a1_4,
        io_l74p_awake_1, io_l74p_m4a0_4, io_l75n_m4ba1_4,
        io_l75p_m4ba0_4, io_l76n_m4a2_4, io_l76p_m4a7_4,
        io_l77n_m4ba2_4, io_l77p_m4we_4, io_l78n_m4a4_4,
        io_l78p_m4a10_4, io_l79n_m4a9_4, io_l79p_m4a8_4,
        io_l7n_0, io_l7n_2, io_l7n_3, io_l7n_m5ba2_5, io_l7p_0,
        io_l7p_2, io_l7p_3, io_l7p_m5we_5, io_l80n_m4a12_4,
        io_l80p_m4cke_4, io_l81n_m4a11_4, io_l81p_m4reset_4,
        io_l82n_m4a14_4, io_l82p_m4a13_4, io_l83n_vref_4,
        io_l83p_4, io_l8n_2, io_l8n_3, io_l8n_m5a2_5,
        io_l8n_vref_0, io_l8p_0, io_l8p_2, io_l8p_3,
        io_l8p_m5a7_5, io_l9n_0, io_l9n_2, io_l9n_3,
        io_l9n_m5ba1_5, io_l9p_0, io_l9p_2, io_l9p_3,
        io_l9p_m5ba0_5, mgtavcc_101, mgtavcc_123, mgtavcc_245,
        mgtavcc_267, mgtavccpll0_101, mgtavccpll0_123,
        mgtavccpll0_245, mgtavccpll0_267, mgtavccpll1_101,
        mgtavccpll1_123, mgtavccpll1_245, mgtavccpll1_267,
        mgtavttrcal_101, mgtavttrcal_245, mgtavttrx_101,
        mgtavttrx_123, mgtavttrx_245, mgtavttrx_267,
        mgtavtttx_101, mgtavtttx_123, mgtavtttx_245,
        mgtavtttx_267, mgtrefclk0n_101, mgtrefclk0n_123,
        mgtrefclk0n_245, mgtrefclk0n_267, mgtrefclk0p_101,
        mgtrefclk0p_123, mgtrefclk0p_245, mgtrefclk0p_267,
        mgtrefclk1n_101, mgtrefclk1n_123, mgtrefclk1n_245,
        mgtrefclk1n_267, mgtrefclk1p_101, mgtrefclk1p_123,
        mgtrefclk1p_245, mgtrefclk1p_267, mgtrref_101,
        mgtrref_245, mgtrxn0_101, mgtrxn0_123, mgtrxn0_245,
        mgtrxn0_267, mgtrxn1_101, mgtrxn1_123, mgtrxn1_245,
        mgtrxn1_267, mgtrxp0_101, mgtrxp0_123, mgtrxp0_245,
        mgtrxp0_267, mgtrxp1_101, mgtrxp1_123, mgtrxp1_245,
        mgtrxp1_267, mgttxn0_101, mgttxn0_123, mgttxn0_245,
        mgttxn0_267, mgttxn1_101, mgttxn1_123, mgttxn1_245,
        mgttxn1_267, mgttxp0_101, mgttxp0_123, mgttxp0_245,
        mgttxp0_267, mgttxp1_101, mgttxp1_123, mgttxp1_245,
        mgttxp1_267, program_b_2, rfuse, suspend, tck, tdi, tdo, tms,
        vbatt, vccaux, vccint, vcco_0, vcco_1, vcco_2, vcco_3,
        vcco_4, vcco_5, vfs);
    inout cmpcs_b_2;
    inout done_2;
    input [148:1] gnd;
    inout io_l10n_0;
    inout io_l10n_2;
    inout io_l10n_3;
    inout io_l10n_m5a1_5;
    inout io_l10p_0;
    inout io_l10p_2;
    inout io_l10p_3;
    inout io_l10p_m5a0_5;
    inout io_l11n_0;
    inout io_l11n_2;
    inout io_l11n_3;
    inout io_l11n_m5clkn_5;
    inout io_l11p_0;
    inout io_l11p_2;
    inout io_l11p_3;
    inout io_l11p_m5clk_5;
    inout io_l12n_0;
    inout io_l12n_3;
    inout io_l12n_d2_miso3_2;
    inout io_l12n_m5odt_5;
    inout io_l12p_0;
    inout io_l12p_3;
    inout io_l12p_d1_miso2_2;
    inout io_l12p_m5a3_5;
    inout io_l13n_0;
    inout io_l13n_3;
    inout io_l13n_d10_2;
    inout io_l13n_m5a6_5;
    inout io_l13p_0;
    inout io_l13p_3;
    inout io_l13p_m1_2;
    inout io_l13p_m5a5_5;
    inout io_l14n_0;
    inout io_l14n_3;
    inout io_l14n_d12_2;
    inout io_l14n_m5casn_5;
    inout io_l14p_0;
    inout io_l14p_3;
    inout io_l14p_d11_2;
    inout io_l14p_m5rasn_5;
    inout io_l15n_0;
    inout io_l15n_2;
    inout io_l15n_3;
    inout io_l15n_m5ldm_5;
    inout io_l15p_0;
    inout io_l15p_2;
    inout io_l15p_3;
    inout io_l15p_m5udm_5;
    inout io_l16n_0;
    inout io_l16n_3;
    inout io_l16n_m5dq5_5;
    inout io_l16n_vref_2;
    inout io_l16p_0;
    inout io_l16p_2;
    inout io_l16p_3;
    inout io_l16p_m5dq4_5;
    inout io_l17n_0;
    inout io_l17n_2;
    inout io_l17n_m5dq7_5;
    inout io_l17n_vref_3;
    inout io_l17p_0;
    inout io_l17p_2;
    inout io_l17p_3;
    inout io_l17p_m5dq6_5;
    inout io_l18n_0;
    inout io_l18n_2;
    inout io_l18n_3;
    inout io_l18n_m5ldqsn_5;
    inout io_l18p_0;
    inout io_l18p_2;
    inout io_l18p_3;
    inout io_l18p_m5ldqs_5;
    inout io_l19n_0;
    inout io_l19n_2;
    inout io_l19n_3;
    inout io_l19n_m5dq3_5;
    inout io_l19p_0;
    inout io_l19p_2;
    inout io_l19p_3;
    inout io_l19p_m5dq2_5;
    inout io_l1n_a24_vref_5;
    inout io_l1n_m0_cmpmiso_2;
    inout io_l1n_vref_0;
    inout io_l1n_vref_3;
    inout io_l1p_3;
    inout io_l1p_a25_5;
    inout io_l1p_cclk_2;
    inout io_l1p_hswapen_0;
    inout io_l20n_0;
    inout io_l20n_2;
    inout io_l20n_3;
    inout io_l20n_m5dq1_5;
    inout io_l20p_0;
    inout io_l20p_2;
    inout io_l20p_3;
    inout io_l20p_m5dq0_5;
    inout io_l21n_0;
    inout io_l21n_2;
    inout io_l21n_3;
    inout io_l21n_m5dq9_5;
    inout io_l21p_0;
    inout io_l21p_2;
    inout io_l21p_3;
    inout io_l21p_m5dq8_5;
    inout io_l22n_0;
    inout io_l22n_2;
    inout io_l22n_3;
    inout io_l22n_m5dq11_5;
    inout io_l22p_0;
    inout io_l22p_2;
    inout io_l22p_3;
    inout io_l22p_m5dq10_5;
    inout io_l23n_0;
    inout io_l23n_2;
    inout io_l23n_3;
    inout io_l23n_m5udqsn_5;
    inout io_l23p_0;
    inout io_l23p_2;
    inout io_l23p_3;
    inout io_l23p_m5udqs_5;
    inout io_l24n_0;
    inout io_l24n_3;
    inout io_l24n_m5dq13_5;
    inout io_l24p_0;
    inout io_l24p_3;
    inout io_l24p_m5dq12_5;
    inout io_l25n_0;
    inout io_l25n_3;
    inout io_l25n_m5dq15_5;
    inout io_l25p_0;
    inout io_l25p_3;
    inout io_l25p_m5dq14_5;
    inout io_l26n_0;
    inout io_l26n_3;
    inout io_l26n_vref_5;
    inout io_l26p_0;
    inout io_l26p_3;
    inout io_l26p_5;
    inout io_l27n_3;
    inout io_l27n_5;
    inout io_l27p_3;
    inout io_l27p_5;
    inout io_l28n_2;
    inout io_l28n_3;
    inout io_l28n_vref_1;
    inout io_l28p_1;
    inout io_l28p_2;
    inout io_l28p_3;
    inout io_l29n_3;
    inout io_l29n_a22_m1a14_1;
    inout io_l29n_gclk2_2;
    inout io_l29p_3;
    inout io_l29p_a23_m1a13_1;
    inout io_l29p_gclk3_2;
    inout io_l2n_0;
    inout io_l2n_3;
    inout io_l2n_cmpmosi_2;
    inout io_l2n_m5a14_5;
    inout io_l2p_0;
    inout io_l2p_3;
    inout io_l2p_cmpclk_2;
    inout io_l2p_m5a13_5;
    inout io_l30n_3;
    inout io_l30n_a20_m1a11_1;
    inout io_l30n_gclk0_usercclk_2;
    inout io_l30p_3;
    inout io_l30p_a21_m1reset_1;
    inout io_l30p_gclk1_d13_2;
    inout io_l31n_a18_m1a12_1;
    inout io_l31n_gclk30_d15_2;
    inout io_l31n_vref_3;
    inout io_l31p_3;
    inout io_l31p_a19_m1cke_1;
    inout io_l31p_gclk31_d14_2;
    inout io_l32n_0;
    inout io_l32n_a16_m1a9_1;
    inout io_l32n_gclk28_2;
    inout io_l32n_m3dq15_3;
    inout io_l32p_0;
    inout io_l32p_a17_m1a8_1;
    inout io_l32p_gclk29_2;
    inout io_l32p_m3dq14_3;
    inout io_l33n_0;
    inout io_l33n_2;
    inout io_l33n_a14_m1a4_1;
    inout io_l33n_m3dq13_3;
    inout io_l33p_0;
    inout io_l33p_2;
    inout io_l33p_a15_m1a10_1;
    inout io_l33p_m3dq12_3;
    inout io_l34n_2;
    inout io_l34n_a12_m1ba2_1;
    inout io_l34n_gclk18_0;
    inout io_l34n_m3udqsn_3;
    inout io_l34p_2;
    inout io_l34p_a13_m1we_1;
    inout io_l34p_gclk19_0;
    inout io_l34p_m3udqs_3;
    inout io_l35n_a10_m1a2_1;
    inout io_l35n_gclk16_0;
    inout io_l35n_m3dq11_3;
    inout io_l35p_a11_m1a7_1;
    inout io_l35p_gclk17_0;
    inout io_l35p_m3dq10_3;
    inout io_l36n_a8_m1ba1_1;
    inout io_l36n_gclk14_0;
    inout io_l36n_m3dq9_3;
    inout io_l36p_a9_m1ba0_1;
    inout io_l36p_gclk15_0;
    inout io_l36p_m3dq8_3;
    inout io_l37n_a6_m1a1_1;
    inout io_l37n_gclk12_0;
    inout io_l37n_m3dq1_3;
    inout io_l37p_a7_m1a0_1;
    inout io_l37p_gclk13_0;
    inout io_l37p_m3dq0_3;
    inout io_l38n_a4_m1clkn_1;
    inout io_l38n_m3dq3_3;
    inout io_l38n_vref_0;
    inout io_l38p_0;
    inout io_l38p_a5_m1clk_1;
    inout io_l38p_m3dq2_3;
    inout io_l39n_m1odt_1;
    inout io_l39n_m3ldqsn_3;
    inout io_l39p_m1a3_1;
    inout io_l39p_m3ldqs_3;
    inout io_l3n_0;
    inout io_l3n_3;
    inout io_l3n_m5a11_5;
    inout io_l3n_mosi_csi_b_miso0_2;
    inout io_l3p_0;
    inout io_l3p_3;
    inout io_l3p_d0_din_miso_miso1_2;
    inout io_l3p_m5reset_5;
    inout io_l40n_2;
    inout io_l40n_gclk10_m1a6_1;
    inout io_l40n_m3dq7_3;
    inout io_l40p_2;
    inout io_l40p_gclk11_m1a5_1;
    inout io_l40p_m3dq6_3;
    inout io_l41n_gclk26_m3dq5_3;
    inout io_l41n_gclk8_m1casn_1;
    inout io_l41n_vref_2;
    inout io_l41p_2;
    inout io_l41p_gclk27_m3dq4_3;
    inout io_l41p_gclk9_irdy1_m1rasn_1;
    inout io_l42n_2;
    inout io_l42n_gclk24_m3ldm_3;
    inout io_l42n_gclk6_trdy1_m1ldm_1;
    inout io_l42p_2;
    inout io_l42p_gclk25_trdy2_m3udm_3;
    inout io_l42p_gclk7_m1udm_1;
    inout io_l43n_0;
    inout io_l43n_2;
    inout io_l43n_gclk22_irdy2_m3casn_3;
    inout io_l43n_gclk4_m1dq5_1;
    inout io_l43p_0;
    inout io_l43p_2;
    inout io_l43p_gclk23_m3rasn_3;
    inout io_l43p_gclk5_m1dq4_1;
    inout io_l44n_0;
    inout io_l44n_2;
    inout io_l44n_a2_m1dq7_1;
    inout io_l44n_gclk20_m3a6_3;
    inout io_l44p_0;
    inout io_l44p_2;
    inout io_l44p_a3_m1dq6_1;
    inout io_l44p_gclk21_m3a5_3;
    inout io_l45n_0;
    inout io_l45n_2;
    inout io_l45n_a0_m1ldqsn_1;
    inout io_l45n_m3odt_3;
    inout io_l45p_0;
    inout io_l45p_2;
    inout io_l45p_a1_m1ldqs_1;
    inout io_l45p_m3a3_3;
    inout io_l46n_0;
    inout io_l46n_2;
    inout io_l46n_foe_b_m1dq3_1;
    inout io_l46n_m3clkn_3;
    inout io_l46p_0;
    inout io_l46p_2;
    inout io_l46p_fcs_b_m1dq2_1;
    inout io_l46p_m3clk_3;
    inout io_l47n_0;
    inout io_l47n_2;
    inout io_l47n_ldc_m1dq1_1;
    inout io_l47n_m3a1_3;
    inout io_l47p_0;
    inout io_l47p_2;
    inout io_l47p_fwe_b_m1dq0_1;
    inout io_l47p_m3a0_3;
    inout io_l48n_0;
    inout io_l48n_m1dq9_1;
    inout io_l48n_m3ba1_3;
    inout io_l48n_rdwr_b_vref_2;
    inout io_l48p_0;
    inout io_l48p_d7_2;
    inout io_l48p_hdc_m1dq8_1;
    inout io_l48p_m3ba0_3;
    inout io_l49n_0;
    inout io_l49n_d4_2;
    inout io_l49n_m1dq11_1;
    inout io_l49n_m3a2_3;
    inout io_l49p_0;
    inout io_l49p_d3_2;
    inout io_l49p_m1dq10_1;
    inout io_l49p_m3a7_3;
    inout io_l4n_0;
    inout io_l4n_3;
    inout io_l4n_m5a12_5;
    inout io_l4n_vref_2;
    inout io_l4p_0;
    inout io_l4p_2;
    inout io_l4p_3;
    inout io_l4p_m5cke_5;
    inout io_l50n_0;
    inout io_l50n_2;
    inout io_l50n_m1udqsn_1;
    inout io_l50n_m3ba2_3;
    inout io_l50p_0;
    inout io_l50p_2;
    inout io_l50p_m1udqs_1;
    inout io_l50p_m3we_3;
    inout io_l51n_0;
    inout io_l51n_2;
    inout io_l51n_m1dq13_1;
    inout io_l51n_m3a4_3;
    inout io_l51p_0;
    inout io_l51p_2;
    inout io_l51p_m1dq12_1;
    inout io_l51p_m3a10_3;
    inout io_l52n_0;
    inout io_l52n_2;
    inout io_l52n_m1dq15_1;
    inout io_l52n_m3a9_3;
    inout io_l52p_0;
    inout io_l52p_2;
    inout io_l52p_m1dq14_1;
    inout io_l52p_m3a8_3;
    inout io_l53n_0;
    inout io_l53n_2;
    inout io_l53n_m3a12_3;
    inout io_l53n_vref_1;
    inout io_l53p_0;
    inout io_l53p_1;
    inout io_l53p_2;
    inout io_l53p_m3cke_3;
    inout io_l54n_0;
    inout io_l54n_1;
    inout io_l54n_2;
    inout io_l54n_m3a11_3;
    inout io_l54p_0;
    inout io_l54p_1;
    inout io_l54p_2;
    inout io_l54p_m3reset_3;
    inout io_l55n_0;
    inout io_l55n_1;
    inout io_l55n_2;
    inout io_l55n_m3a14_3;
    inout io_l55p_0;
    inout io_l55p_1;
    inout io_l55p_2;
    inout io_l55p_m3a13_3;
    inout io_l56n_0;
    inout io_l56n_1;
    inout io_l56n_2;
    inout io_l56n_3;
    inout io_l56p_0;
    inout io_l56p_1;
    inout io_l56p_2;
    inout io_l56p_3;
    inout io_l57n_0;
    inout io_l57n_1;
    inout io_l57n_2;
    inout io_l57n_vref_3;
    inout io_l57p_0;
    inout io_l57p_1;
    inout io_l57p_2;
    inout io_l57p_3;
    inout io_l58n_0;
    inout io_l58n_1;
    inout io_l58n_2;
    inout io_l58n_vref_4;
    inout io_l58p_0;
    inout io_l58p_1;
    inout io_l58p_2;
    inout io_l58p_4;
    inout io_l59n_0;
    inout io_l59n_1;
    inout io_l59n_2;
    inout io_l59n_m4dq15_4;
    inout io_l59p_0;
    inout io_l59p_1;
    inout io_l59p_2;
    inout io_l59p_m4dq14_4;
    inout io_l5n_0;
    inout io_l5n_2;
    inout io_l5n_3;
    inout io_l5n_m5a9_5;
    inout io_l5p_0;
    inout io_l5p_2;
    inout io_l5p_3;
    inout io_l5p_m5a8_5;
    inout io_l60n_0;
    inout io_l60n_1;
    inout io_l60n_2;
    inout io_l60n_m4dq13_4;
    inout io_l60p_0;
    inout io_l60p_1;
    inout io_l60p_2;
    inout io_l60p_m4dq12_4;
    inout io_l61n_0;
    inout io_l61n_1;
    inout io_l61n_m4udqsn_4;
    inout io_l61n_vref_2;
    inout io_l61p_0;
    inout io_l61p_1;
    inout io_l61p_2;
    inout io_l61p_m4udqs_4;
    inout io_l62n_1;
    inout io_l62n_d6_2;
    inout io_l62n_m4dq11_4;
    inout io_l62n_vref_0;
    inout io_l62p_0;
    inout io_l62p_1;
    inout io_l62p_d5_2;
    inout io_l62p_m4dq10_4;
    inout io_l63n_1;
    inout io_l63n_2;
    inout io_l63n_m4dq9_4;
    inout io_l63n_scp6_0;
    inout io_l63p_1;
    inout io_l63p_2;
    inout io_l63p_m4dq8_4;
    inout io_l63p_scp7_0;
    inout io_l64n_1;
    inout io_l64n_d9_2;
    inout io_l64n_m4dq1_4;
    inout io_l64n_scp4_0;
    inout io_l64p_1;
    inout io_l64p_d8_2;
    inout io_l64p_m4dq0_4;
    inout io_l64p_scp5_0;
    inout io_l65n_1;
    inout io_l65n_cso_b_2;
    inout io_l65n_m4dq3_4;
    inout io_l65n_scp2_0;
    inout io_l65p_1;
    inout io_l65p_init_b_2;
    inout io_l65p_m4dq2_4;
    inout io_l65p_scp3_0;
    inout io_l66n_1;
    inout io_l66n_m4ldqsn_4;
    inout io_l66n_scp0_0;
    inout io_l66p_1;
    inout io_l66p_m4ldqs_4;
    inout io_l66p_scp1_0;
    inout io_l67n_1;
    inout io_l67n_m4dq7_4;
    inout io_l67p_1;
    inout io_l67p_m4dq6_4;
    inout io_l68n_1;
    inout io_l68n_m4dq5_4;
    inout io_l68p_1;
    inout io_l68p_m4dq4_4;
    inout io_l69n_m4ldm_4;
    inout io_l69n_vref_1;
    inout io_l69p_1;
    inout io_l69p_m4udm_4;
    inout io_l6n_0;
    inout io_l6n_2;
    inout io_l6n_3;
    inout io_l6n_m5a4_5;
    inout io_l6p_0;
    inout io_l6p_2;
    inout io_l6p_3;
    inout io_l6p_m5a10_5;
    inout io_l70n_1;
    inout io_l70n_m4casn_4;
    inout io_l70p_1;
    inout io_l70p_m4rasn_4;
    inout io_l71n_1;
    inout io_l71n_m4a6_4;
    inout io_l71p_1;
    inout io_l71p_m4a5_4;
    inout io_l72n_1;
    inout io_l72n_m4odt_4;
    inout io_l72p_1;
    inout io_l72p_m4a3_4;
    inout io_l73n_1;
    inout io_l73n_m4clkn_4;
    inout io_l73p_1;
    inout io_l73p_m4clk_4;
    inout io_l74n_dout_busy_1;
    inout io_l74n_m4a1_4;
    inout io_l74p_awake_1;
    inout io_l74p_m4a0_4;
    inout io_l75n_m4ba1_4;
    inout io_l75p_m4ba0_4;
    inout io_l76n_m4a2_4;
    inout io_l76p_m4a7_4;
    inout io_l77n_m4ba2_4;
    inout io_l77p_m4we_4;
    inout io_l78n_m4a4_4;
    inout io_l78p_m4a10_4;
    inout io_l79n_m4a9_4;
    inout io_l79p_m4a8_4;
    inout io_l7n_0;
    inout io_l7n_2;
    inout io_l7n_3;
    inout io_l7n_m5ba2_5;
    inout io_l7p_0;
    inout io_l7p_2;
    inout io_l7p_3;
    inout io_l7p_m5we_5;
    inout io_l80n_m4a12_4;
    inout io_l80p_m4cke_4;
    inout io_l81n_m4a11_4;
    inout io_l81p_m4reset_4;
    inout io_l82n_m4a14_4;
    inout io_l82p_m4a13_4;
    inout io_l83n_vref_4;
    inout io_l83p_4;
    inout io_l8n_2;
    inout io_l8n_3;
    inout io_l8n_m5a2_5;
    inout io_l8n_vref_0;
    inout io_l8p_0;
    inout io_l8p_2;
    inout io_l8p_3;
    inout io_l8p_m5a7_5;
    inout io_l9n_0;
    inout io_l9n_2;
    inout io_l9n_3;
    inout io_l9n_m5ba1_5;
    inout io_l9p_0;
    inout io_l9p_2;
    inout io_l9p_3;
    inout io_l9p_m5ba0_5;
    inout mgtavcc_101;
    inout mgtavcc_123;
    inout mgtavcc_245;
    inout mgtavcc_267;
    inout mgtavccpll0_101;
    inout mgtavccpll0_123;
    inout mgtavccpll0_245;
    inout mgtavccpll0_267;
    inout mgtavccpll1_101;
    inout mgtavccpll1_123;
    inout mgtavccpll1_245;
    inout mgtavccpll1_267;
    inout mgtavttrcal_101;
    inout mgtavttrcal_245;
    inout mgtavttrx_101;
    inout mgtavttrx_123;
    inout mgtavttrx_245;
    inout mgtavttrx_267;
    inout mgtavtttx_101;
    inout mgtavtttx_123;
    inout mgtavtttx_245;
    inout mgtavtttx_267;
    inout mgtrefclk0n_101;
    inout mgtrefclk0n_123;
    inout mgtrefclk0n_245;
    inout mgtrefclk0n_267;
    inout mgtrefclk0p_101;
    inout mgtrefclk0p_123;
    inout mgtrefclk0p_245;
    inout mgtrefclk0p_267;
    inout mgtrefclk1n_101;
    inout mgtrefclk1n_123;
    inout mgtrefclk1n_245;
    inout mgtrefclk1n_267;
    inout mgtrefclk1p_101;
    inout mgtrefclk1p_123;
    inout mgtrefclk1p_245;
    inout mgtrefclk1p_267;
    inout mgtrref_101;
    inout mgtrref_245;
    inout mgtrxn0_101;
    inout mgtrxn0_123;
    inout mgtrxn0_245;
    inout mgtrxn0_267;
    inout mgtrxn1_101;
    inout mgtrxn1_123;
    inout mgtrxn1_245;
    inout mgtrxn1_267;
    inout mgtrxp0_101;
    inout mgtrxp0_123;
    inout mgtrxp0_245;
    inout mgtrxp0_267;
    inout mgtrxp1_101;
    inout mgtrxp1_123;
    inout mgtrxp1_245;
    inout mgtrxp1_267;
    inout mgttxn0_101;
    inout mgttxn0_123;
    inout mgttxn0_245;
    inout mgttxn0_267;
    inout mgttxn1_101;
    inout mgttxn1_123;
    inout mgttxn1_245;
    inout mgttxn1_267;
    inout mgttxp0_101;
    inout mgttxp0_123;
    inout mgttxp0_245;
    inout mgttxp0_267;
    inout mgttxp1_101;
    inout mgttxp1_123;
    inout mgttxp1_245;
    inout mgttxp1_267;
    inout program_b_2;
    inout rfuse;
    inout suspend;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    inout vbatt;
    input [27:1] vccaux;
    input [31:1] vccint;
    input [15:1] vcco_0;
    input [14:1] vcco_1;
    input [13:1] vcco_2;
    input [14:1] vcco_3;
    input [7:1] vcco_4;
    input [8:1] vcco_5;
    inout vfs;


    initial
        begin
        end

endmodule
