// generated by newgenasym  Thu Feb 19 14:01:45 2009


module afct5760nlz (gnd10, gnd11, gnd12, gnd13, gnd14, gnd15, gnd16, gnd17,
        gnd18, gnd19, gnd20, gnd21, gnd22, gnd3, gnd4, gnd5, gnd6,
        gnd7, gnd8, gnd9, los, \mod-def0 , \mod-def1 , \mod-def2 , pad1,
        pad2, rate_select, \rd+ , \rd- , \td+ , \td- , tx_disable, tx_fault,
        vccr, vcct, veer1, veer2, veer3, veer4, veet1, veet2, veet3);
    inout gnd10;
    inout gnd11;
    inout gnd12;
    inout gnd13;
    inout gnd14;
    inout gnd15;
    inout gnd16;
    inout gnd17;
    inout gnd18;
    inout gnd19;
    inout gnd20;
    inout gnd21;
    inout gnd22;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout gnd6;
    inout gnd7;
    inout gnd8;
    inout gnd9;
    inout los;
    inout \mod-def0 ;
    inout \mod-def1 ;
    inout \mod-def2 ;
    inout pad1;
    inout pad2;
    inout rate_select;
    inout \rd+ ;
    inout \rd- ;
    inout \td+ ;
    inout \td- ;
    inout tx_disable;
    inout tx_fault;
    inout vccr;
    inout vcct;
    inout veer1;
    inout veer2;
    inout veer3;
    inout veer4;
    inout veet1;
    inout veet2;
    inout veet3;


    initial
        begin
        end

endmodule
