// generated by newgenasym  Fri Feb 03 17:41:10 2012


module tps54318 (agnd, boot, comp, en, gnd, pad, ph, pwrgd, \rt/clk , ss, vin,
        vsense);
    inout agnd;
    inout boot;
    inout comp;
    inout en;
    inout [2:1] gnd;
    inout pad;
    inout [3:1] ph;
    inout pwrgd;
    inout \rt/clk ;
    inout ss;
    inout [3:1] vin;
    inout vsense;


    initial
        begin
        end

endmodule
