// generated by newgenasym  Fri Jan 13 15:05:05 2012


module ad6641bcpzrl7_500 (avdd, \clk+ , \clk- , cml, csb, dnc, drgnd, drvdd, dump, empty,
        \fill+ , \fill- , full, pad, \pclk+ , \pclk- , \pd0+ , \pd0- , \pd1+ , \pd1- ,
        \pd2+ , \pd2- , \pd3+ , \pd3- , \pd4+ , \pd4- , \pd5+ , \pd5- , \pdor+ , \pdor- ,
        sclk, sdio, sp_sclk, sp_sdfs, sp_sdo, spi_vddio, \vin+ , \vin- ,
        vref);
    inout [11:1] avdd;
    inout \clk+ ;
    inout \clk- ;
    inout cml;
    inout csb;
    inout [5:1] dnc;
    inout [3:1] drgnd;
    inout [3:1] drvdd;
    inout dump;
    inout empty;
    inout \fill+ ;
    inout \fill- ;
    inout full;
    inout pad;
    inout \pclk+ ;
    inout \pclk- ;
    inout \pd0+ ;
    inout \pd0- ;
    inout \pd1+ ;
    inout \pd1- ;
    inout \pd2+ ;
    inout \pd2- ;
    inout \pd3+ ;
    inout \pd3- ;
    inout \pd4+ ;
    inout \pd4- ;
    inout \pd5+ ;
    inout \pd5- ;
    inout \pdor+ ;
    inout \pdor- ;
    inout sclk;
    inout sdio;
    inout sp_sclk;
    inout sp_sdfs;
    inout sp_sdo;
    inout spi_vddio;
    inout \vin+ ;
    inout \vin- ;
    inout vref;


    initial
        begin
        end

endmodule
