// generated by newgenasym  Fri Jun 24 11:46:46 2011


module ad8376acpz (a0, a1, a2, a3, a4, b0, b1, b2, b3, b4, enba, enbb, gnda, gndb,
        \ipa+ , \ipa- , \ipb+ , \ipb- , \opa+ , \opa- , \opb+ , \opb- , pad, vcca, vccb,
        vcma, vcmb);
    inout a0;
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout b0;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout enba;
    inout enbb;
    inout [2:1] gnda;
    inout [2:1] gndb;
    inout \ipa+ ;
    inout \ipa- ;
    inout \ipb+ ;
    inout \ipb- ;
    inout [2:1] \opa+ ;
    inout [2:1] \opa- ;
    inout [2:1] \opb+ ;
    inout [2:1] \opb- ;
    inout pad;
    inout vcca;
    inout vccb;
    inout vcma;
    inout vcmb;


    initial
        begin
        end

endmodule
