// generated by newgenasym  Mon Feb 23 15:34:55 2009


module \4a4305  (\1 , \2 , \3 , \4 , \5 , gnd1, gnd2, gnd3, gnd4, gnd5, gnd6);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;


    initial
        begin
        end

endmodule
