// generated by newgenasym  Fri Feb 10 17:02:43 2012


module bq24070rhlt (bat, ce, dppm, gnd, in, iset1, iset2, mode, out, pad, \pg# ,
        stat1, stat2, tmr, ts, vref, vss);
    inout [2:1] bat;
    inout ce;
    inout dppm;
    inout [2:1] gnd;
    inout in;
    inout iset1;
    inout iset2;
    inout mode;
    inout [3:1] out;
    inout pad;
    inout \pg# ;
    inout stat1;
    inout stat2;
    inout tmr;
    inout ts;
    inout vref;
    inout vss;


    initial
        begin
        end

endmodule
