-- generated by newgenasym Tue Apr 21 14:11:30 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tlp181gb is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end tlp181gb;
