// generated by newgenasym  Thu Feb 12 15:15:27 2009


module mic2774n (gnd, in, \mr# , \rst# , vdd);
    input gnd;
    input in;
    input \mr# ;
    output \rst# ;
    input vdd;


    initial
        begin
        end

endmodule
