-- generated by newgenasym Thu Feb 12 15:15:27 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mic2774n is
    port (    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\mr#\:     IN     STD_LOGIC;    
	\rst#\:    OUT    STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end mic2774n;
