// generated by newgenasym  Thu Jun 10 16:50:50 2010


module pm_ntgs4111pt1g (d1, d2, d3, d4, g, s);
    inout d1;
    inout d2;
    inout d3;
    inout d4;
    inout g;
    inout s;


    initial
        begin
        end

endmodule
