// generated by newgenasym  Tue Sep 21 14:44:44 2010


module vc936b_cead_122p88m (\e/d , gnd, out, \out# , vc, vcc);
    inout \e/d ;
    inout gnd;
    inout out;
    inout \out# ;
    inout vc;
    inout vcc;


    initial
        begin
        end

endmodule
