-- generated by newgenasym Tue Sep 21 14:44:44 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity VC936B_CEAD_122P88M is
    port (    
	\e/d\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\out#\:    INOUT  STD_LOGIC;    
	VC:        INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end VC936B_CEAD_122P88M;
