// generated by newgenasym  Tue Nov 09 17:10:55 2010


module hmc714lp5 (cinta, cintb, cofa, cofb, enx, fbka, fbkb, inna, innb, inpa,
        inpb, insa, insb, irefa, irefb, \n/c , outn, outp, pad, rmsa,
        rmsb, temp, vcca, vccb, vccbias, vlvl, vref2, vref3, vseta,
        vsetb, vtgt);
    inout cinta;
    inout cintb;
    inout cofa;
    inout cofb;
    inout enx;
    inout fbka;
    inout fbkb;
    inout inna;
    inout innb;
    inout inpa;
    inout inpb;
    inout insa;
    inout insb;
    inout irefa;
    inout irefb;
    inout [3:1] \n/c ;
    inout outn;
    inout outp;
    inout pad;
    inout rmsa;
    inout rmsb;
    inout temp;
    inout vcca;
    inout vccb;
    inout vccbias;
    inout vlvl;
    inout vref2;
    inout vref3;
    inout vseta;
    inout vsetb;
    inout vtgt;


    initial
        begin
        end

endmodule
