-- generated by newgenasym Tue Nov 09 17:10:55 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc714lp5 is
    port (    
	CINTA:     INOUT  STD_LOGIC;    
	CINTB:     INOUT  STD_LOGIC;    
	COFA:      INOUT  STD_LOGIC;    
	COFB:      INOUT  STD_LOGIC;    
	ENX:       INOUT  STD_LOGIC;    
	FBKA:      INOUT  STD_LOGIC;    
	FBKB:      INOUT  STD_LOGIC;    
	INNA:      INOUT  STD_LOGIC;    
	INNB:      INOUT  STD_LOGIC;    
	INPA:      INOUT  STD_LOGIC;    
	INPB:      INOUT  STD_LOGIC;    
	INSA:      INOUT  STD_LOGIC;    
	INSB:      INOUT  STD_LOGIC;    
	IREFA:     INOUT  STD_LOGIC;    
	IREFB:     INOUT  STD_LOGIC;    
	\n/c\:     INOUT  STD_LOGIC_VECTOR (3 DOWNTO 1);    
	OUTN:      INOUT  STD_LOGIC;    
	OUTP:      INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	RMSA:      INOUT  STD_LOGIC;    
	RMSB:      INOUT  STD_LOGIC;    
	TEMP:      INOUT  STD_LOGIC;    
	VCCA:      INOUT  STD_LOGIC;    
	VCCB:      INOUT  STD_LOGIC;    
	VCCBIAS:   INOUT  STD_LOGIC;    
	VLVL:      INOUT  STD_LOGIC;    
	VREF2:     INOUT  STD_LOGIC;    
	VREF3:     INOUT  STD_LOGIC;    
	VSETA:     INOUT  STD_LOGIC;    
	VSETB:     INOUT  STD_LOGIC;    
	VTGT:      INOUT  STD_LOGIC);
end hmc714lp5;
