// generated by newgenasym  Fri Apr 15 10:00:58 2011


module ad9548bcpz (avdd, avdd3, clkinn, clkinp, \cs#/sda , dacoutn, dacoutp,
        dvdd, dvdd3, irq, m0, m1, m2, m3, m4, m5, m6, m7, nc, out0n, out0p,
        out1n, out1p, out2n, out2p, out3n, out3p, out_rset, pad, refa,
        refaa, refb, refbb, refc, refcc, refd, refdd, reset, \sclk/scl ,
        sdio, sdo, sysclk_lf, sysclk_vreg, sysclkn, sysclkp, tclk,
        tdc_vrb, tdc_vrt, tdi, tdo, tms, vss);
    inout [11:1] avdd;
    inout [11:1] avdd3;
    inout clkinn;
    inout clkinp;
    inout \cs#/sda ;
    inout dacoutn;
    inout dacoutp;
    inout [8:1] dvdd;
    inout [2:1] dvdd3;
    inout irq;
    inout m0;
    inout m1;
    inout m2;
    inout m3;
    inout m4;
    inout m5;
    inout m6;
    inout m7;
    inout [5:1] nc;
    inout out0n;
    inout out0p;
    inout out1n;
    inout out1p;
    inout out2n;
    inout out2p;
    inout out3n;
    inout out3p;
    inout out_rset;
    inout pad;
    inout refa;
    inout refaa;
    inout refb;
    inout refbb;
    inout refc;
    inout refcc;
    inout refd;
    inout refdd;
    inout reset;
    inout \sclk/scl ;
    inout sdio;
    inout sdo;
    inout sysclk_lf;
    inout sysclk_vreg;
    inout sysclkn;
    inout sysclkp;
    inout tclk;
    inout tdc_vrb;
    inout tdc_vrt;
    inout tdi;
    inout tdo;
    inout tms;
    inout [6:1] vss;


    initial
        begin
        end

endmodule
