-- generated by newgenasym Thu May 07 14:12:58 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity esc_5r2017g03_t is
    port (    
	\50ohms\:  INOUT  STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	GND4:      IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end esc_5r2017g03_t;
