// generated by newgenasym  Thu Feb 12 17:26:12 2009


module dfc2017s15a3 (gnd1, gnd2, gnd3, gnd4, in, out);
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input in;
    output out;


    initial
        begin
        end

endmodule
