-- generated by newgenasym Thu Feb 12 17:26:12 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dfc2017s15a3 is
    port (    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	GND4:      IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end dfc2017s15a3;
