// generated by newgenasym  Fri Apr 13 14:31:36 2012


module lmk04808bisq (clkin0, \clkin0# , clkout0, \clkout0# , clkout1, \clkout1# ,
        clkout10, \clkout10# , clkout11, \clkout11# , clkout2,
        \clkout2# , clkout3, \clkout3# , clkout4, \clkout4# , clkout5,
        \clkout5# , clkout6, \clkout6# , clkout7, \clkout7# , clkout8,
        \clkout8# , clkout9, \clkout9# , clkuwire, cpout1, cpout2,
        datauwire, \fbclkin#/fin#/clkin1# , \fbclkin/fin/clkin1 ,
        gnd, ldobyp1, ldobyp2, leuwire, \n/c , oscin, \oscin# , oscout0,
        \oscout0# , oscout1, \oscout1# , pad, status_clkin0,
        status_clkin1, status_holdover, status_ld, sync, vcc1,
        vcc10, vcc11, vcc12, vcc13, vcc2, vcc3, vcc4, vcc5, vcc6, vcc7,
        vcc8, vcc9);
    inout clkin0;
    inout \clkin0# ;
    inout clkout0;
    inout \clkout0# ;
    inout clkout1;
    inout \clkout1# ;
    inout clkout10;
    inout \clkout10# ;
    inout clkout11;
    inout \clkout11# ;
    inout clkout2;
    inout \clkout2# ;
    inout clkout3;
    inout \clkout3# ;
    inout clkout4;
    inout \clkout4# ;
    inout clkout5;
    inout \clkout5# ;
    inout clkout6;
    inout \clkout6# ;
    inout clkout7;
    inout \clkout7# ;
    inout clkout8;
    inout \clkout8# ;
    inout clkout9;
    inout \clkout9# ;
    inout clkuwire;
    inout cpout1;
    inout cpout2;
    inout datauwire;
    inout \fbclkin#/fin#/clkin1# ;
    inout \fbclkin/fin/clkin1 ;
    inout gnd;
    inout ldobyp1;
    inout ldobyp2;
    inout leuwire;
    inout [4:1] \n/c ;
    inout oscin;
    inout \oscin# ;
    inout oscout0;
    inout \oscout0# ;
    inout oscout1;
    inout \oscout1# ;
    inout pad;
    inout status_clkin0;
    inout status_clkin1;
    inout status_holdover;
    inout status_ld;
    inout sync;
    inout vcc1;
    inout vcc10;
    inout vcc11;
    inout vcc12;
    inout vcc13;
    inout vcc2;
    inout vcc3;
    inout vcc4;
    inout vcc5;
    inout vcc6;
    inout vcc7;
    inout vcc8;
    inout vcc9;


    initial
        begin
        end

endmodule
