// generated by newgenasym  Wed Mar 09 11:20:08 2011


module tps7a80xx (en, \fb/sns , gnd, in, nr, out, pad);
    inout en;
    inout \fb/sns ;
    inout gnd;
    inout [2:1] in;
    inout nr;
    inout [2:1] out;
    inout [5:1] pad;


    initial
        begin
        end

endmodule
