// generated by newgenasym  Wed Sep 21 18:31:06 2011


module tnt4882_bqf66 (abus_oen, abusn, addr0, addr1, addr2, addr3, addr4, atnn,
        bbus_oen, bbusn, burst_rdn, cpuacc, csn, dackn, data0, data1,
        data10, data11, data12, data13, data14, data15, data2, data3,
        data4, data5, data6, data7, data8, data9, davn, dcas, dio1n,
        dio2n, dio3n, dio4n, dio5n, dio6n, dio7n, dio8n, drq, eoin,
        fifo_rdy, gnd1, gnd10, gnd11, gnd12, gnd13, gnd14, gnd15,
        gnd16, gnd17, gnd18, gnd19, gnd2, gnd20, gnd21, gnd22, gnd23,
        gnd24, gnd25, gnd3, gnd4, gnd5, gnd6, gnd7, gnd8, gnd9, ifcn,
        intr, keyclkn, keydq, keyrstn, ladcs, mode, \n/c , ndacn, nrfdn,
        paged, rdn, rdy1, rem, renn, resetn, srqn, swapn, tadcs, trig,
        vdd1, vdd2, vdd3, vdd4, vdd5, vdd6, vdd7, vdd8, vdd9, wrn,
        xtal0, xtal1);
    inout abus_oen;
    inout abusn;
    inout addr0;
    inout addr1;
    inout addr2;
    inout addr3;
    inout addr4;
    inout atnn;
    inout bbus_oen;
    inout bbusn;
    inout burst_rdn;
    inout cpuacc;
    inout csn;
    inout dackn;
    inout data0;
    inout data1;
    inout data10;
    inout data11;
    inout data12;
    inout data13;
    inout data14;
    inout data15;
    inout data2;
    inout data3;
    inout data4;
    inout data5;
    inout data6;
    inout data7;
    inout data8;
    inout data9;
    inout davn;
    inout dcas;
    inout dio1n;
    inout dio2n;
    inout dio3n;
    inout dio4n;
    inout dio5n;
    inout dio6n;
    inout dio7n;
    inout dio8n;
    inout drq;
    inout eoin;
    inout fifo_rdy;
    inout gnd1;
    inout gnd10;
    inout gnd11;
    inout gnd12;
    inout gnd13;
    inout gnd14;
    inout gnd15;
    inout gnd16;
    inout gnd17;
    inout gnd18;
    inout gnd19;
    inout gnd2;
    inout gnd20;
    inout gnd21;
    inout gnd22;
    inout gnd23;
    inout gnd24;
    inout gnd25;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout gnd6;
    inout gnd7;
    inout gnd8;
    inout gnd9;
    inout ifcn;
    inout intr;
    inout keyclkn;
    inout keydq;
    inout keyrstn;
    inout ladcs;
    inout mode;
    inout \n/c ;
    inout ndacn;
    inout nrfdn;
    inout paged;
    inout rdn;
    inout rdy1;
    inout rem;
    inout renn;
    inout resetn;
    inout srqn;
    inout swapn;
    inout tadcs;
    inout trig;
    inout vdd1;
    inout vdd2;
    inout vdd3;
    inout vdd4;
    inout vdd5;
    inout vdd6;
    inout vdd7;
    inout vdd8;
    inout vdd9;
    inout wrn;
    inout xtal0;
    inout xtal1;


    initial
        begin
        end

endmodule
