-- generated by newgenasym Thu Jun 10 18:21:36 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity con_2171_202mg2cunt3 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end con_2171_202mg2cunt3;
