// generated by newgenasym  Wed Apr 22 14:55:29 2009


module mmcx (\2 , \3 , \4 , \5 , in);
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout in;


    initial
        begin
        end

endmodule
