-- generated by newgenasym Mon Apr 20 17:13:03 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity resistor_vsr is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end resistor_vsr;
