-- generated by newgenasym Thu Feb 12 15:42:04 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ptvc75635 is
    port (    
	\e/d\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\rf-1\:    INOUT  STD_LOGIC;    
	\rf-2\:    INOUT  STD_LOGIC;    
	VC:        INOUT  STD_LOGIC;    
	VS:        INOUT  STD_LOGIC);
end ptvc75635;
