-- generated by newgenasym Mon Apr 16 17:48:04 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity con_19s101_40ml5 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC);
end con_19s101_40ml5;
