-- generated by newgenasym Fri Sep 11 13:55:05 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc349ms8ge is
    port (    
	BASE:      INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC;    
	RFC:       INOUT  STD_LOGIC;    
	VCTL:      INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end hmc349ms8ge;
