// generated by newgenasym  Thu Feb 12 15:22:22 2009


module mga_565p8_tr1 (gnd1, gnd2, gnd3, gnd4, gnd5, gnd6, gnd7, rf_in, rf_out, vd2,
        vd3);
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    input gnd7;
    input rf_in;
    output rf_out;
    inout vd2;
    inout vd3;


    initial
        begin
        end

endmodule
