// generated by newgenasym  Thu Apr 16 10:28:46 2009


module mt48lc8m16a2tg (a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9, ba0, ba1, \cas# ,
        cke, clk, \cs# , dq0, dq1, dq10, dq11, dq12, dq13, dq14, dq15, dq2,
        dq3, dq4, dq5, dq6, dq7, dq8, dq9, dqmh, dqml, nc, \nc/a12 , \ras# ,
        vdd_0, vdd_1, vdd_2, vddq_0, vddq_1, vddq_2, vddq_3, vss_0,
        vss_1, vss_2, vssq_0, vssq_1, vssq_2, vssq_3, \we# );
    input a0;
    input a1;
    input a10;
    input a11;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    input a9;
    inout ba0;
    inout ba1;
    input \cas# ;
    inout cke;
    inout clk;
    input \cs# ;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout dq15;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dq8;
    inout dq9;
    inout dqmh;
    inout dqml;
    inout nc;
    inout \nc/a12 ;
    inout \ras# ;
    input vdd_0;
    input vdd_1;
    input vdd_2;
    input vddq_0;
    input vddq_1;
    input vddq_2;
    input vddq_3;
    input vss_0;
    input vss_1;
    input vss_2;
    input vssq_0;
    input vssq_1;
    input vssq_2;
    input vssq_3;
    input \we# ;


    initial
        begin
        end

endmodule
