// generated by newgenasym  Thu Oct 14 09:37:32 2010


module hmc245qs16e (a, b, gnd1, gnd2, gnd3, gnd4, gnd5, gnd6, gnd7, gnd8, gnd9, rf1,
        rf2, rf3, rfc, vdd);
    inout a;
    inout b;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout gnd6;
    inout gnd7;
    inout gnd8;
    inout gnd9;
    inout rf1;
    inout rf2;
    inout rf3;
    inout rfc;
    inout vdd;


    initial
        begin
        end

endmodule
