-- generated by newgenasym Thu Oct 14 09:37:32 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc245qs16e is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	GND5:      INOUT  STD_LOGIC;    
	GND6:      INOUT  STD_LOGIC;    
	GND7:      INOUT  STD_LOGIC;    
	GND8:      INOUT  STD_LOGIC;    
	GND9:      INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC;    
	RF3:       INOUT  STD_LOGIC;    
	RFC:       INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end hmc245qs16e;
