-- generated by newgenasym Fri Apr 17 14:49:43 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ys05s10_dg is
    port (    
	GND:       IN     STD_LOGIC;    
	\on/off\:  INOUT  STD_LOGIC;    
	SENSE:     INOUT  STD_LOGIC;    
	TRIM:      INOUT  STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      IN     STD_LOGIC);
end ys05s10_dg;
