// generated by newgenasym  Wed Jun 17 09:31:21 2009


module mc100lvel11dg (d, \d# , q0, \q0# , q1, \q1# , vcc, vee);
    input d;
    input \d# ;
    output q0;
    output \q0# ;
    output q1;
    output \q1# ;
    input vcc;
    input vee;


    initial
        begin
        end

endmodule
