-- generated by newgenasym Wed Feb 11 14:04:57 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity resistor is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end resistor;
