-- generated by newgenasym Thu May 07 13:34:05 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity resistor_ntc is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end resistor_ntc;
