// generated by newgenasym  Fri Apr 17 10:52:23 2009


module ics854104agilft (clk, gnd, nclk, nq0, nq1, nq2, nq3, oe0, oe1, oe2, oe3, q0, q1,
        q2, q3, vdd);
    input clk;
    input gnd;
    input nclk;
    output nq0;
    output nq1;
    output nq2;
    output nq3;
    input oe0;
    input oe1;
    input oe2;
    input oe3;
    output q0;
    output q1;
    output q2;
    output q3;
    input vdd;


    initial
        begin
        end

endmodule
