-- generated by newgenasym Fri Apr 17 10:52:23 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ics854104agilft is
    port (    
	CLK:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	NCLK:      IN     STD_LOGIC;    
	NQ0:       OUT    STD_LOGIC;    
	NQ1:       OUT    STD_LOGIC;    
	NQ2:       OUT    STD_LOGIC;    
	NQ3:       OUT    STD_LOGIC;    
	OE0:       IN     STD_LOGIC;    
	OE1:       IN     STD_LOGIC;    
	OE2:       IN     STD_LOGIC;    
	OE3:       IN     STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end ics854104agilft;
