// generated by newgenasym  Wed Jun 02 14:26:13 2010


module xc6slx75_100_150t_3fgg484i (cmpcs_b_2, done_2, gnd_1, gnd_10, gnd_11, gnd_12, gnd_13,
        gnd_14, gnd_15, gnd_16, gnd_17, gnd_18, gnd_19, gnd_2,
        gnd_20, gnd_21, gnd_22, gnd_23, gnd_24, gnd_25, gnd_26,
        gnd_27, gnd_28, gnd_29, gnd_3, gnd_30, gnd_31, gnd_32,
        gnd_33, gnd_34, gnd_35, gnd_36, gnd_37, gnd_38, gnd_39,
        gnd_4, gnd_40, gnd_41, gnd_42, gnd_43, gnd_44, gnd_45,
        gnd_46, gnd_47, gnd_48, gnd_49, gnd_5, gnd_50, gnd_51,
        gnd_52, gnd_53, gnd_54, gnd_55, gnd_56, gnd_57, gnd_58,
        gnd_59, gnd_6, gnd_60, gnd_61, gnd_62, gnd_63, gnd_64,
        gnd_65, gnd_66, gnd_67, gnd_68, gnd_69, gnd_7, gnd_70,
        gnd_71, gnd_8, gnd_9, io_l10n_1, io_l10n_3, io_l10p_1,
        io_l10p_3, io_l12n_d2_miso3_2, io_l12p_d1_miso2_2,
        io_l13n_d10_2, io_l13p_m1_2, io_l14n_d12_2,
        io_l14p_d11_2, io_l15n_2, io_l15p_2, io_l16n_vref_2,
        io_l16p_2, io_l19n_1, io_l19n_2, io_l19p_1, io_l19p_2,
        io_l1n_a24_vref_1, io_l1n_m0_cmpmiso_2, io_l1n_vref_0,
        io_l1n_vref_3, io_l1p_3, io_l1p_a25_1, io_l1p_cclk_2,
        io_l1p_hswapen_0, io_l20n_1, io_l20p_1, io_l21n_1,
        io_l21n_2, io_l21p_1, io_l21p_2, io_l23n_3, io_l23p_3,
        io_l24n_3, io_l24p_3, io_l25n_3, io_l25p_3, io_l26n_3,
        io_l26p_3, io_l28n_vref_1, io_l28p_1,
        io_l29n_a22_m1a14_1, io_l29n_gclk2_2,
        io_l29p_a23_m1a13_1, io_l29p_gclk3_2, io_l2n_0, io_l2n_3,
        io_l2n_cmpmosi_2, io_l2p_0, io_l2p_3, io_l2p_cmpclk_2,
        io_l30n_a20_m1a11_1, io_l30n_gclk0_usercclk_2,
        io_l30p_a21_m1reset_1, io_l30p_gclk1_d13_2,
        io_l31n_a18_m1a12_1, io_l31n_gclk30_d15_2,
        io_l31n_vref_3, io_l31p_3, io_l31p_a19_m1cke_1,
        io_l31p_gclk31_d14_2, io_l32n_0, io_l32n_a16_m1a9_1,
        io_l32n_gclk28_2, io_l32n_m3dq15_3, io_l32p_0,
        io_l32p_a17_m1a8_1, io_l32p_gclk29_2, io_l32p_m3dq14_3,
        io_l33n_0, io_l33n_a14_m1a4_1, io_l33n_m3dq13_3,
        io_l33p_0, io_l33p_a15_m1a10_1, io_l33p_m3dq12_3,
        io_l34n_a12_m1ba2_1, io_l34n_gclk18_0,
        io_l34n_m3udqsn_3, io_l34p_a13_m1we_1, io_l34p_gclk19_0,
        io_l34p_m3udqs_3, io_l35n_a10_m1a2_1, io_l35n_gclk16_0,
        io_l35n_m3dq11_3, io_l35p_a11_m1a7_1, io_l35p_gclk17_0,
        io_l35p_m3dq10_3, io_l36n_a8_m1ba1_1, io_l36n_gclk14_0,
        io_l36n_m3dq9_3, io_l36p_a9_m1ba0_1, io_l36p_gclk15_0,
        io_l36p_m3dq8_3, io_l37n_a6_m1a1_1, io_l37n_gclk12_0,
        io_l37n_m3dq1_3, io_l37p_a7_m1a0_1, io_l37p_gclk13_0,
        io_l37p_m3dq0_3, io_l38n_a4_m1clkn_1, io_l38n_m3dq3_3,
        io_l38n_vref_0, io_l38p_0, io_l38p_a5_m1clk_1,
        io_l38p_m3dq2_3, io_l39n_m1odt_1, io_l39n_m3ldqsn_3,
        io_l39p_m1a3_1, io_l39p_m3ldqs_3, io_l3n_0,
        io_l3n_mosi_csi_b_miso0_2, io_l3p_0,
        io_l3p_d0_din_miso_miso1_2, io_l40n_2,
        io_l40n_gclk10_m1a6_1, io_l40n_m3dq7_3, io_l40p_2,
        io_l40p_gclk11_m1a5_1, io_l40p_m3dq6_3,
        io_l41n_gclk26_m3dq5_3, io_l41n_gclk8_m1casn_1,
        io_l41n_vref_2, io_l41p_2, io_l41p_gclk27_m3dq4_3,
        io_l41p_gclk9_irdy1_m1rasn_1, io_l42n_gclk24_m3ldm_3,
        io_l42n_gclk6_trdy1_m1ldm_1,
        io_l42p_gclk25_trdy2_m3udm_3, io_l42p_gclk7_m1udm_1,
        io_l43n_2, io_l43n_gclk22_irdy2_m3casn_3,
        io_l43n_gclk4_m1dq5_1, io_l43p_2,
        io_l43p_gclk23_m3rasn_3, io_l43p_gclk5_m1dq4_1,
        io_l44n_a2_m1dq7_1, io_l44n_gclk20_m3a6_3,
        io_l44p_a3_m1dq6_1, io_l44p_gclk21_m3a5_3, io_l45n_2,
        io_l45n_a0_m1ldqsn_1, io_l45n_m3odt_3, io_l45p_2,
        io_l45p_a1_m1ldqs_1, io_l45p_m3a3_3,
        io_l46n_foe_b_m1dq3_1, io_l46n_m3clkn_3,
        io_l46p_fcs_b_m1dq2_1, io_l46p_m3clk_3, io_l47n_2,
        io_l47n_ldc_m1dq1_1, io_l47n_m3a1_3, io_l47p_2,
        io_l47p_fwe_b_m1dq0_1, io_l47p_m3a0_3, io_l48n_m1dq9_1,
        io_l48n_m3ba1_3, io_l48n_rdwr_b_vref_2, io_l48p_d7_2,
        io_l48p_hdc_m1dq8_1, io_l48p_m3ba0_3, io_l49n_0,
        io_l49n_d4_2, io_l49n_m1dq11_1, io_l49n_m3a2_3,
        io_l49p_0, io_l49p_d3_2, io_l49p_m1dq10_1,
        io_l49p_m3a7_3, io_l4n_0, io_l4n_vref_2, io_l4p_0,
        io_l4p_2, io_l50n_0, io_l50n_m1udqsn_1, io_l50n_m3ba2_3,
        io_l50p_0, io_l50p_m1udqs_1, io_l50p_m3we_3, io_l51n_0,
        io_l51n_m1dq13_1, io_l51n_m3a4_3, io_l51p_0,
        io_l51p_m1dq12_1, io_l51p_m3a10_3, io_l52n_m1dq15_1,
        io_l52n_m3a9_3, io_l52p_m1dq14_1, io_l52p_m3a8_3,
        io_l53n_m3a12_3, io_l53n_vref_1, io_l53p_1,
        io_l53p_m3cke_3, io_l54n_m3a11_3, io_l54p_m3reset_3,
        io_l55n_m3a14_3, io_l55p_m3a13_3, io_l57n_vref_3,
        io_l57p_3, io_l58n_1, io_l58n_3, io_l58p_1, io_l58p_3,
        io_l59n_1, io_l59n_3, io_l59p_1, io_l59p_3, io_l5n_0,
        io_l5p_0, io_l60n_1, io_l60n_3, io_l60p_1, io_l60p_3,
        io_l61n_1, io_l61p_1, io_l62n_d6_2, io_l62n_vref_0,
        io_l62p_0, io_l62p_d5_2, io_l63n_2, io_l63n_scp6_0,
        io_l63p_2, io_l63p_scp7_0, io_l64n_d9_2, io_l64n_scp4_0,
        io_l64p_d8_2, io_l64p_scp5_0, io_l65n_cso_b_2,
        io_l65n_scp2_0, io_l65p_init_b_2, io_l65p_scp3_0,
        io_l66n_scp0_0, io_l66p_scp1_0, io_l6n_0, io_l6n_2,
        io_l6p_0, io_l6p_2, io_l70n_1, io_l70p_1, io_l71n_1,
        io_l71p_1, io_l72n_1, io_l72p_1, io_l73n_1, io_l73p_1,
        io_l74n_dout_busy_1, io_l74p_awake_1, io_l7n_0, io_l7n_3,
        io_l7p_0, io_l7p_3, io_l80n_3, io_l80p_3, io_l81n_3,
        io_l81p_3, io_l82n_3, io_l82p_3, io_l83n_vref_3,
        io_l83p_3, io_l8n_3, io_l8n_vref_0, io_l8p_0, io_l8p_3,
        io_l9n_1, io_l9n_3, io_l9p_1, io_l9p_3, mgtavcc_101,
        mgtavcc_123, mgtavccpll0_101, mgtavccpll0_123,
        mgtavccpll1_101, mgtavccpll1_123, mgtavttrcal_101,
        mgtavttrx_101, mgtavttrx_123, mgtavtttx_101,
        mgtavtttx_123, mgtrefclk0n_101, mgtrefclk0n_123,
        mgtrefclk0p_101, mgtrefclk0p_123, mgtrefclk1n_101,
        mgtrefclk1n_123, mgtrefclk1p_101, mgtrefclk1p_123,
        mgtrref_101, mgtrxn0_101, mgtrxn0_123, mgtrxn1_101,
        mgtrxn1_123, mgtrxp0_101, mgtrxp0_123, mgtrxp1_101,
        mgtrxp1_123, mgttxn0_101, mgttxn0_123, mgttxn1_101,
        mgttxn1_123, mgttxp0_101, mgttxp0_123, mgttxp1_101,
        mgttxp1_123, \nc/io_l17n_2 , \nc/io_l17p_2 , \nc/io_l18n_2 ,
        \nc/io_l18p_2 , \nc/io_l20n_2 , \nc/io_l20p_2 , \nc/io_l22n_2 ,
        \nc/io_l22p_2 , \nc/io_l23n_2 , \nc/io_l23p_2 , \nc/io_l42n_2 ,
        \nc/io_l42p_2 , \nc/io_l44n_2 , \nc/io_l44p_2 , \nc/io_l46n_2 ,
        \nc/io_l46p_2 , \nc/io_l50n_2 , \nc/io_l50p_2 , \nc/io_l57n_2 ,
        \nc/io_l57p_2 , \nc/io_l58n_2 , \nc/io_l58p_2 , \nc/io_l59n_2 ,
        \nc/io_l59p_2 , \nc/io_l5n_2 , \nc/io_l5p_2 , \nc/io_l60n_2 ,
        \nc/io_l60p_2 , program_b_2, rfuse, suspend, tck, tdi, tdo,
        tms, vbatt, vccaux_1, vccaux_10, vccaux_11, vccaux_12,
        vccaux_13, vccaux_2, vccaux_3, vccaux_4, vccaux_5,
        vccaux_6, vccaux_7, vccaux_8, vccaux_9, vccint_1,
        vccint_10, vccint_11, vccint_12, vccint_13, vccint_14,
        vccint_15, vccint_16, vccint_17, vccint_18, vccint_19,
        vccint_2, vccint_20, vccint_3, vccint_4, vccint_5,
        vccint_6, vccint_7, vccint_8, vccint_9, vcco_0_1, vcco_0_2,
        vcco_0_3, vcco_0_4, vcco_0_5, vcco_0_6, vcco_1_1,
        vcco_1_10, vcco_1_2, vcco_1_3, vcco_1_4, vcco_1_5,
        vcco_1_6, vcco_1_7, vcco_1_8, vcco_1_9, vcco_2_1,
        vcco_2_10, vcco_2_11, vcco_2_2, vcco_2_3, vcco_2_4,
        vcco_2_5, vcco_2_6, vcco_2_7, vcco_2_8, vcco_2_9, vcco_3_1,
        vcco_3_10, vcco_3_2, vcco_3_3, vcco_3_4, vcco_3_5,
        vcco_3_6, vcco_3_7, vcco_3_8, vcco_3_9, vfs);
    inout cmpcs_b_2;
    inout done_2;
    input gnd_1;
    input gnd_10;
    input gnd_11;
    input gnd_12;
    input gnd_13;
    input gnd_14;
    input gnd_15;
    input gnd_16;
    input gnd_17;
    input gnd_18;
    input gnd_19;
    input gnd_2;
    input gnd_20;
    input gnd_21;
    input gnd_22;
    input gnd_23;
    input gnd_24;
    input gnd_25;
    input gnd_26;
    input gnd_27;
    input gnd_28;
    input gnd_29;
    input gnd_3;
    input gnd_30;
    input gnd_31;
    input gnd_32;
    input gnd_33;
    input gnd_34;
    input gnd_35;
    input gnd_36;
    input gnd_37;
    input gnd_38;
    input gnd_39;
    input gnd_4;
    input gnd_40;
    input gnd_41;
    input gnd_42;
    input gnd_43;
    input gnd_44;
    input gnd_45;
    input gnd_46;
    input gnd_47;
    input gnd_48;
    input gnd_49;
    input gnd_5;
    input gnd_50;
    input gnd_51;
    input gnd_52;
    input gnd_53;
    input gnd_54;
    input gnd_55;
    input gnd_56;
    input gnd_57;
    input gnd_58;
    input gnd_59;
    input gnd_6;
    input gnd_60;
    input gnd_61;
    input gnd_62;
    input gnd_63;
    input gnd_64;
    input gnd_65;
    input gnd_66;
    input gnd_67;
    input gnd_68;
    input gnd_69;
    input gnd_7;
    input gnd_70;
    input gnd_71;
    input gnd_8;
    input gnd_9;
    inout io_l10n_1;
    inout io_l10n_3;
    inout io_l10p_1;
    inout io_l10p_3;
    inout io_l12n_d2_miso3_2;
    inout io_l12p_d1_miso2_2;
    inout io_l13n_d10_2;
    inout io_l13p_m1_2;
    inout io_l14n_d12_2;
    inout io_l14p_d11_2;
    inout io_l15n_2;
    inout io_l15p_2;
    inout io_l16n_vref_2;
    inout io_l16p_2;
    inout io_l19n_1;
    inout io_l19n_2;
    inout io_l19p_1;
    inout io_l19p_2;
    inout io_l1n_a24_vref_1;
    inout io_l1n_m0_cmpmiso_2;
    inout io_l1n_vref_0;
    inout io_l1n_vref_3;
    inout io_l1p_3;
    inout io_l1p_a25_1;
    inout io_l1p_cclk_2;
    inout io_l1p_hswapen_0;
    inout io_l20n_1;
    inout io_l20p_1;
    inout io_l21n_1;
    inout io_l21n_2;
    inout io_l21p_1;
    inout io_l21p_2;
    inout io_l23n_3;
    inout io_l23p_3;
    inout io_l24n_3;
    inout io_l24p_3;
    inout io_l25n_3;
    inout io_l25p_3;
    inout io_l26n_3;
    inout io_l26p_3;
    inout io_l28n_vref_1;
    inout io_l28p_1;
    inout io_l29n_a22_m1a14_1;
    inout io_l29n_gclk2_2;
    inout io_l29p_a23_m1a13_1;
    inout io_l29p_gclk3_2;
    inout io_l2n_0;
    inout io_l2n_3;
    inout io_l2n_cmpmosi_2;
    inout io_l2p_0;
    inout io_l2p_3;
    inout io_l2p_cmpclk_2;
    inout io_l30n_a20_m1a11_1;
    inout io_l30n_gclk0_usercclk_2;
    inout io_l30p_a21_m1reset_1;
    inout io_l30p_gclk1_d13_2;
    inout io_l31n_a18_m1a12_1;
    inout io_l31n_gclk30_d15_2;
    inout io_l31n_vref_3;
    inout io_l31p_3;
    inout io_l31p_a19_m1cke_1;
    inout io_l31p_gclk31_d14_2;
    inout io_l32n_0;
    inout io_l32n_a16_m1a9_1;
    inout io_l32n_gclk28_2;
    inout io_l32n_m3dq15_3;
    inout io_l32p_0;
    inout io_l32p_a17_m1a8_1;
    inout io_l32p_gclk29_2;
    inout io_l32p_m3dq14_3;
    inout io_l33n_0;
    inout io_l33n_a14_m1a4_1;
    inout io_l33n_m3dq13_3;
    inout io_l33p_0;
    inout io_l33p_a15_m1a10_1;
    inout io_l33p_m3dq12_3;
    inout io_l34n_a12_m1ba2_1;
    inout io_l34n_gclk18_0;
    inout io_l34n_m3udqsn_3;
    inout io_l34p_a13_m1we_1;
    inout io_l34p_gclk19_0;
    inout io_l34p_m3udqs_3;
    inout io_l35n_a10_m1a2_1;
    inout io_l35n_gclk16_0;
    inout io_l35n_m3dq11_3;
    inout io_l35p_a11_m1a7_1;
    inout io_l35p_gclk17_0;
    inout io_l35p_m3dq10_3;
    inout io_l36n_a8_m1ba1_1;
    inout io_l36n_gclk14_0;
    inout io_l36n_m3dq9_3;
    inout io_l36p_a9_m1ba0_1;
    inout io_l36p_gclk15_0;
    inout io_l36p_m3dq8_3;
    inout io_l37n_a6_m1a1_1;
    inout io_l37n_gclk12_0;
    inout io_l37n_m3dq1_3;
    inout io_l37p_a7_m1a0_1;
    inout io_l37p_gclk13_0;
    inout io_l37p_m3dq0_3;
    inout io_l38n_a4_m1clkn_1;
    inout io_l38n_m3dq3_3;
    inout io_l38n_vref_0;
    inout io_l38p_0;
    inout io_l38p_a5_m1clk_1;
    inout io_l38p_m3dq2_3;
    inout io_l39n_m1odt_1;
    inout io_l39n_m3ldqsn_3;
    inout io_l39p_m1a3_1;
    inout io_l39p_m3ldqs_3;
    inout io_l3n_0;
    inout io_l3n_mosi_csi_b_miso0_2;
    inout io_l3p_0;
    inout io_l3p_d0_din_miso_miso1_2;
    inout io_l40n_2;
    inout io_l40n_gclk10_m1a6_1;
    inout io_l40n_m3dq7_3;
    inout io_l40p_2;
    inout io_l40p_gclk11_m1a5_1;
    inout io_l40p_m3dq6_3;
    inout io_l41n_gclk26_m3dq5_3;
    inout io_l41n_gclk8_m1casn_1;
    inout io_l41n_vref_2;
    inout io_l41p_2;
    inout io_l41p_gclk27_m3dq4_3;
    inout io_l41p_gclk9_irdy1_m1rasn_1;
    inout io_l42n_gclk24_m3ldm_3;
    inout io_l42n_gclk6_trdy1_m1ldm_1;
    inout io_l42p_gclk25_trdy2_m3udm_3;
    inout io_l42p_gclk7_m1udm_1;
    inout io_l43n_2;
    inout io_l43n_gclk22_irdy2_m3casn_3;
    inout io_l43n_gclk4_m1dq5_1;
    inout io_l43p_2;
    inout io_l43p_gclk23_m3rasn_3;
    inout io_l43p_gclk5_m1dq4_1;
    inout io_l44n_a2_m1dq7_1;
    inout io_l44n_gclk20_m3a6_3;
    inout io_l44p_a3_m1dq6_1;
    inout io_l44p_gclk21_m3a5_3;
    inout io_l45n_2;
    inout io_l45n_a0_m1ldqsn_1;
    inout io_l45n_m3odt_3;
    inout io_l45p_2;
    inout io_l45p_a1_m1ldqs_1;
    inout io_l45p_m3a3_3;
    inout io_l46n_foe_b_m1dq3_1;
    inout io_l46n_m3clkn_3;
    inout io_l46p_fcs_b_m1dq2_1;
    inout io_l46p_m3clk_3;
    inout io_l47n_2;
    inout io_l47n_ldc_m1dq1_1;
    inout io_l47n_m3a1_3;
    inout io_l47p_2;
    inout io_l47p_fwe_b_m1dq0_1;
    inout io_l47p_m3a0_3;
    inout io_l48n_m1dq9_1;
    inout io_l48n_m3ba1_3;
    inout io_l48n_rdwr_b_vref_2;
    inout io_l48p_d7_2;
    inout io_l48p_hdc_m1dq8_1;
    inout io_l48p_m3ba0_3;
    inout io_l49n_0;
    inout io_l49n_d4_2;
    inout io_l49n_m1dq11_1;
    inout io_l49n_m3a2_3;
    inout io_l49p_0;
    inout io_l49p_d3_2;
    inout io_l49p_m1dq10_1;
    inout io_l49p_m3a7_3;
    inout io_l4n_0;
    inout io_l4n_vref_2;
    inout io_l4p_0;
    inout io_l4p_2;
    inout io_l50n_0;
    inout io_l50n_m1udqsn_1;
    inout io_l50n_m3ba2_3;
    inout io_l50p_0;
    inout io_l50p_m1udqs_1;
    inout io_l50p_m3we_3;
    inout io_l51n_0;
    inout io_l51n_m1dq13_1;
    inout io_l51n_m3a4_3;
    inout io_l51p_0;
    inout io_l51p_m1dq12_1;
    inout io_l51p_m3a10_3;
    inout io_l52n_m1dq15_1;
    inout io_l52n_m3a9_3;
    inout io_l52p_m1dq14_1;
    inout io_l52p_m3a8_3;
    inout io_l53n_m3a12_3;
    inout io_l53n_vref_1;
    inout io_l53p_1;
    inout io_l53p_m3cke_3;
    inout io_l54n_m3a11_3;
    inout io_l54p_m3reset_3;
    inout io_l55n_m3a14_3;
    inout io_l55p_m3a13_3;
    inout io_l57n_vref_3;
    inout io_l57p_3;
    inout io_l58n_1;
    inout io_l58n_3;
    inout io_l58p_1;
    inout io_l58p_3;
    inout io_l59n_1;
    inout io_l59n_3;
    inout io_l59p_1;
    inout io_l59p_3;
    inout io_l5n_0;
    inout io_l5p_0;
    inout io_l60n_1;
    inout io_l60n_3;
    inout io_l60p_1;
    inout io_l60p_3;
    inout io_l61n_1;
    inout io_l61p_1;
    inout io_l62n_d6_2;
    inout io_l62n_vref_0;
    inout io_l62p_0;
    inout io_l62p_d5_2;
    inout io_l63n_2;
    inout io_l63n_scp6_0;
    inout io_l63p_2;
    inout io_l63p_scp7_0;
    inout io_l64n_d9_2;
    inout io_l64n_scp4_0;
    inout io_l64p_d8_2;
    inout io_l64p_scp5_0;
    inout io_l65n_cso_b_2;
    inout io_l65n_scp2_0;
    inout io_l65p_init_b_2;
    inout io_l65p_scp3_0;
    inout io_l66n_scp0_0;
    inout io_l66p_scp1_0;
    inout io_l6n_0;
    inout io_l6n_2;
    inout io_l6p_0;
    inout io_l6p_2;
    inout io_l70n_1;
    inout io_l70p_1;
    inout io_l71n_1;
    inout io_l71p_1;
    inout io_l72n_1;
    inout io_l72p_1;
    inout io_l73n_1;
    inout io_l73p_1;
    inout io_l74n_dout_busy_1;
    inout io_l74p_awake_1;
    inout io_l7n_0;
    inout io_l7n_3;
    inout io_l7p_0;
    inout io_l7p_3;
    inout io_l80n_3;
    inout io_l80p_3;
    inout io_l81n_3;
    inout io_l81p_3;
    inout io_l82n_3;
    inout io_l82p_3;
    inout io_l83n_vref_3;
    inout io_l83p_3;
    inout io_l8n_3;
    inout io_l8n_vref_0;
    inout io_l8p_0;
    inout io_l8p_3;
    inout io_l9n_1;
    inout io_l9n_3;
    inout io_l9p_1;
    inout io_l9p_3;
    input mgtavcc_101;
    input mgtavcc_123;
    inout mgtavccpll0_101;
    inout mgtavccpll0_123;
    inout mgtavccpll1_101;
    inout mgtavccpll1_123;
    inout mgtavttrcal_101;
    input mgtavttrx_101;
    input mgtavttrx_123;
    input mgtavtttx_101;
    input mgtavtttx_123;
    inout mgtrefclk0n_101;
    inout mgtrefclk0n_123;
    inout mgtrefclk0p_101;
    inout mgtrefclk0p_123;
    inout mgtrefclk1n_101;
    inout mgtrefclk1n_123;
    inout mgtrefclk1p_101;
    inout mgtrefclk1p_123;
    inout mgtrref_101;
    inout mgtrxn0_101;
    inout mgtrxn0_123;
    inout mgtrxn1_101;
    inout mgtrxn1_123;
    inout mgtrxp0_101;
    inout mgtrxp0_123;
    inout mgtrxp1_101;
    inout mgtrxp1_123;
    inout mgttxn0_101;
    inout mgttxn0_123;
    inout mgttxn1_101;
    inout mgttxn1_123;
    inout mgttxp0_101;
    inout mgttxp0_123;
    inout mgttxp1_101;
    inout mgttxp1_123;
    inout \nc/io_l17n_2 ;
    inout \nc/io_l17p_2 ;
    inout \nc/io_l18n_2 ;
    inout \nc/io_l18p_2 ;
    inout \nc/io_l20n_2 ;
    inout \nc/io_l20p_2 ;
    inout \nc/io_l22n_2 ;
    inout \nc/io_l22p_2 ;
    inout \nc/io_l23n_2 ;
    inout \nc/io_l23p_2 ;
    inout \nc/io_l42n_2 ;
    inout \nc/io_l42p_2 ;
    inout \nc/io_l44n_2 ;
    inout \nc/io_l44p_2 ;
    inout \nc/io_l46n_2 ;
    inout \nc/io_l46p_2 ;
    inout \nc/io_l50n_2 ;
    inout \nc/io_l50p_2 ;
    inout \nc/io_l57n_2 ;
    inout \nc/io_l57p_2 ;
    inout \nc/io_l58n_2 ;
    inout \nc/io_l58p_2 ;
    inout \nc/io_l59n_2 ;
    inout \nc/io_l59p_2 ;
    inout \nc/io_l5n_2 ;
    inout \nc/io_l5p_2 ;
    inout \nc/io_l60n_2 ;
    inout \nc/io_l60p_2 ;
    inout program_b_2;
    inout rfuse;
    inout suspend;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    inout vbatt;
    input vccaux_1;
    input vccaux_10;
    input vccaux_11;
    input vccaux_12;
    input vccaux_13;
    input vccaux_2;
    input vccaux_3;
    input vccaux_4;
    input vccaux_5;
    input vccaux_6;
    input vccaux_7;
    input vccaux_8;
    input vccaux_9;
    input vccint_1;
    input vccint_10;
    input vccint_11;
    input vccint_12;
    input vccint_13;
    input vccint_14;
    input vccint_15;
    input vccint_16;
    input vccint_17;
    input vccint_18;
    input vccint_19;
    input vccint_2;
    input vccint_20;
    input vccint_3;
    input vccint_4;
    input vccint_5;
    input vccint_6;
    input vccint_7;
    input vccint_8;
    input vccint_9;
    input vcco_0_1;
    input vcco_0_2;
    input vcco_0_3;
    input vcco_0_4;
    input vcco_0_5;
    input vcco_0_6;
    input vcco_1_1;
    input vcco_1_10;
    input vcco_1_2;
    input vcco_1_3;
    input vcco_1_4;
    input vcco_1_5;
    input vcco_1_6;
    input vcco_1_7;
    input vcco_1_8;
    input vcco_1_9;
    input vcco_2_1;
    input vcco_2_10;
    input vcco_2_11;
    input vcco_2_2;
    input vcco_2_3;
    input vcco_2_4;
    input vcco_2_5;
    input vcco_2_6;
    input vcco_2_7;
    input vcco_2_8;
    input vcco_2_9;
    input vcco_3_1;
    input vcco_3_10;
    input vcco_3_2;
    input vcco_3_3;
    input vcco_3_4;
    input vcco_3_5;
    input vcco_3_6;
    input vcco_3_7;
    input vcco_3_8;
    input vcco_3_9;
    inout vfs;


    initial
        begin
        end

endmodule
