-- generated by newgenasym Tue Oct 25 15:47:26 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ct_750340744 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end ct_750340744;
