-- generated by newgenasym Thu Aug 27 16:34:12 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity jnw350r641_18 is
    port (    
	BASEPLATE: INOUT  STD_LOGIC;    
	GND01:     IN     STD_LOGIC;    
	GND02:     IN     STD_LOGIC;    
	GND03:     IN     STD_LOGIC;    
	GND04:     IN     STD_LOGIC;    
	\on/off\:  INOUT  STD_LOGIC;    
	\sense+\:  INOUT  STD_LOGIC;    
	\sense-\:  INOUT  STD_LOGIC;    
	TRIM:      INOUT  STD_LOGIC;    
	\vin+\:    INOUT  STD_LOGIC;    
	\vin-\:    INOUT  STD_LOGIC;    
	\vout+\:   INOUT  STD_LOGIC;    
	\vout-\:   INOUT  STD_LOGIC);
end jnw350r641_18;
