// generated by newgenasym  Mon May 23 16:04:54 2011


module cmf32c1575s10a (gnd1, gnd2, gnd3, in, out);
    input gnd1;
    input gnd2;
    input gnd3;
    input in;
    output out;


    initial
        begin
        end

endmodule
