// generated by newgenasym  Sat Jun 12 11:09:35 2010


module con_cf20201d0r0 (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \19 , \2 , \20 , \3 , \4 , \5 , \6 , \7 , \8 , \9 ,
        pad1, pad2);
    inout \1 ;
    inout \10 ;
    inout \11 ;
    inout \12 ;
    inout \13 ;
    inout \14 ;
    inout \15 ;
    inout \16 ;
    inout \17 ;
    inout \18 ;
    inout \19 ;
    inout \2 ;
    inout \20 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;
    inout pad1;
    inout pad2;


    initial
        begin
        end

endmodule
