-- generated by newgenasym Tue Apr 21 16:33:40 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PNP_pmbs3906 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end PNP_pmbs3906;
