// generated by newgenasym  Tue Jan 17 14:56:16 2012


module dc_sot6 (coupled, gnd, in, out);
    inout coupled;
    inout [3:1] gnd;
    inout in;
    inout out;


    initial
        begin
        end

endmodule
