-- generated by newgenasym Mon Apr 20 15:48:42 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tvs_ak10_076c is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end tvs_ak10_076c;
