-- generated by newgenasym Sat Apr 07 16:44:06 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity idtf1240nbgi8 is
    port (    
	GA0:       INOUT  STD_LOGIC;    
	GA1:       INOUT  STD_LOGIC;    
	\ga2/csb\: INOUT  STD_LOGIC;    
	\ga3/data\: INOUT  STD_LOGIC;    
	\ga4/clk\: INOUT  STD_LOGIC;    
	GA5:       INOUT  STD_LOGIC;    
	GB0:       INOUT  STD_LOGIC;    
	GB1:       INOUT  STD_LOGIC;    
	GB2:       INOUT  STD_LOGIC;    
	GB3:       INOUT  STD_LOGIC;    
	GB4:       INOUT  STD_LOGIC;    
	GB5:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC_VECTOR (4 DOWNTO 1);    
	\in_a+\:   INOUT  STD_LOGIC;    
	\in_a-\:   INOUT  STD_LOGIC;    
	\in_b+\:   INOUT  STD_LOGIC;    
	\in_b-\:   INOUT  STD_LOGIC;    
	ISET_A:    INOUT  STD_LOGIC;    
	ISET_B:    INOUT  STD_LOGIC;    
	\n/c\:     INOUT  STD_LOGIC;    
	\out_a+\:  INOUT  STD_LOGIC;    
	\out_a-\:  INOUT  STD_LOGIC;    
	\out_b+\:  INOUT  STD_LOGIC;    
	\out_b-\:  INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	STBY_A:    INOUT  STD_LOGIC;    
	STBY_B:    INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	VMODE:     INOUT  STD_LOGIC);
end idtf1240nbgi8;
