// generated by newgenasym  Tue Mar 01 18:32:52 2011


module tlk100php (clk25out, jtag_tck, jtag_tdi, jtag_tdo, jtag_tms,
        jtag_trstn, \led_act/an_en , \led_link/an_0 , \led_speed/an_1 ,
        mdc, mdio, \mii_col/phyad0 , \mii_crs/led_cfg , mii_rx_clk,
        mii_rx_dv, \mii_rx_err/mdix_en , \mii_rxd_0/phyad1 ,
        \mii_rxd_1/phyad2 , \mii_rxd_2/phyad3 , \mii_rxd_3/phyad4 ,
        mii_tx_clk, mii_tx_en, mii_txd_0, mii_txd_1, mii_txd_2,
        mii_txd_3, pad, \pwrdnn/int , rbias, \rd+ , \rd- , resetn, \td+ , \td- ,
        v18_pfbin1, v18_pfbin2, v18_pfbout, va11_pfbin1,
        va11_pfbin2, va11_pfbout, vdd11, vdd33_io, vdd33_v18,
        vdd33_va11, vdd33_vd11, vss, xi, xo);
    inout clk25out;
    inout jtag_tck;
    inout jtag_tdi;
    inout jtag_tdo;
    inout jtag_tms;
    inout jtag_trstn;
    inout \led_act/an_en ;
    inout \led_link/an_0 ;
    inout \led_speed/an_1 ;
    inout mdc;
    inout mdio;
    inout \mii_col/phyad0 ;
    inout \mii_crs/led_cfg ;
    inout mii_rx_clk;
    inout mii_rx_dv;
    inout \mii_rx_err/mdix_en ;
    inout \mii_rxd_0/phyad1 ;
    inout \mii_rxd_1/phyad2 ;
    inout \mii_rxd_2/phyad3 ;
    inout \mii_rxd_3/phyad4 ;
    inout mii_tx_clk;
    inout mii_tx_en;
    inout mii_txd_0;
    inout mii_txd_1;
    inout mii_txd_2;
    inout mii_txd_3;
    inout pad;
    inout \pwrdnn/int ;
    inout rbias;
    inout \rd+ ;
    inout \rd- ;
    inout resetn;
    inout \td+ ;
    inout \td- ;
    inout v18_pfbin1;
    inout v18_pfbin2;
    inout v18_pfbout;
    inout va11_pfbin1;
    inout va11_pfbin2;
    inout va11_pfbout;
    inout vdd11;
    inout [2:1] vdd33_io;
    inout vdd33_v18;
    inout vdd33_va11;
    inout vdd33_vd11;
    inout vss;
    inout xi;
    inout xo;


    initial
        begin
        end

endmodule
