-- generated by newgenasym Fri May 15 09:38:27 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity INDUCTOR_CM is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end INDUCTOR_CM;
