// generated by newgenasym  Fri Apr 10 16:14:49 2009


module is42s16800e (a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9, ba0, ba1, \cas# ,
        cke, clk, \cs# , dq0, dq1, dq10, dq11, dq12, dq13, dq14, dq15, dq2,
        dq3, dq4, dq5, dq6, dq7, dq8, dq9, dqmh, dqml, nc1, nc2, \ras# ,
        vdd1, vdd2, vdd3, vddq1, vddq2, vddq3, vddq4, vss1, vss2, vss3,
        vssq1, vssq2, vssq3, vssq4, \we# );
    input a0;
    input a1;
    input a10;
    input a11;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    input a9;
    input ba0;
    input ba1;
    input \cas# ;
    input cke;
    input clk;
    input \cs# ;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout dq15;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dq8;
    inout dq9;
    input dqmh;
    input dqml;
    inout nc1;
    inout nc2;
    input \ras# ;
    input vdd1;
    input vdd2;
    input vdd3;
    input vddq1;
    input vddq2;
    input vddq3;
    input vddq4;
    input vss1;
    input vss2;
    input vss3;
    input vssq1;
    input vssq2;
    input vssq3;
    input vssq4;
    input \we# ;


    initial
        begin
        end

endmodule
