// generated by newgenasym  Mon Mar 08 16:18:05 2004


module ring (ring1, ring2, ring3, ring4, ring5, ring6, ring7, ring8);
    inout ring1;
    inout ring2;
    inout ring3;
    inout ring4;
    inout ring5;
    inout ring6;
    inout ring7;
    inout ring8;


    initial
        begin
        end

endmodule
