// generated by newgenasym  Tue Nov 02 17:16:21 2010


module adc102s101cimmx (\cs# , din, dout, gnd1, in1, in2, sclk, va);
    inout \cs# ;
    inout din;
    inout dout;
    inout gnd1;
    inout in1;
    inout in2;
    inout sclk;
    inout va;


    initial
        begin
        end

endmodule
