// generated by newgenasym  Thu Feb 12 15:09:59 2009


module hmc194ms8e (a, b, gnd1, gnd2, nc, rf, rf1, rf2);
    inout a;
    inout b;
    inout gnd1;
    inout gnd2;
    inout nc;
    inout rf;
    inout rf1;
    inout rf2;


    initial
        begin
        end

endmodule
