-- generated by newgenasym Thu Feb 12 15:09:59 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hmc194ms8e is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	RF:        INOUT  STD_LOGIC;    
	RF1:       INOUT  STD_LOGIC;    
	RF2:       INOUT  STD_LOGIC);
end hmc194ms8e;
