// generated by newgenasym  Mon Apr 20 14:41:15 2009


module lt1640alcs8 (drain, gate, ov, \pwrgd# , sense, uv, vdd, vee);
    inout drain;
    inout gate;
    inout ov;
    inout \pwrgd# ;
    inout sense;
    inout uv;
    input vdd;
    inout vee;


    initial
        begin
        end

endmodule
