// generated by newgenasym  Tue Apr 10 11:27:59 2012


module ksz8873mmli (agnd, gnd, intrn, iset, \n/c , p1led0, p1led1, p2led0, p2led1,
        pwrdn, rstn, rxm2, rxp2, scl_mdc, scol1, scol3, scrs1, scrs3,
        sda_mdio, smrx_c1, smrxc3, smrxd10, smrxd11, smrxd12,
        smrxd13, smrxd30, smrxd31, smrxd32, smrxd33, smrxdv1,
        smrxdv3, smtxc1, smtxc3, smtxd10, smtxd11, smtxd12, smtxd13,
        smtxd30, smtxd31, smtxd32, smtxd33, smtxen1, smtxen3,
        \smtxer1/mii_link_1 , \smtxer3/mii_link_3 , spiq, spisn, txm2,
        txp2, \vdda_1.8 , \vdda_3.3 , vddc, vddco, vddio, x1, x2);
    inout [3:1] agnd;
    inout [3:1] gnd;
    inout intrn;
    inout iset;
    inout [3:1] \n/c ;
    inout p1led0;
    inout p1led1;
    inout p2led0;
    inout p2led1;
    inout pwrdn;
    inout rstn;
    inout rxm2;
    inout rxp2;
    inout scl_mdc;
    inout scol1;
    inout scol3;
    inout scrs1;
    inout scrs3;
    inout sda_mdio;
    inout smrx_c1;
    inout smrxc3;
    inout smrxd10;
    inout smrxd11;
    inout smrxd12;
    inout smrxd13;
    inout smrxd30;
    inout smrxd31;
    inout smrxd32;
    inout smrxd33;
    inout smrxdv1;
    inout smrxdv3;
    inout smtxc1;
    inout smtxc3;
    inout smtxd10;
    inout smtxd11;
    inout smtxd12;
    inout smtxd13;
    inout smtxd30;
    inout smtxd31;
    inout smtxd32;
    inout smtxd33;
    inout smtxen1;
    inout smtxen3;
    inout \smtxer1/mii_link_1 ;
    inout \smtxer3/mii_link_3 ;
    inout spiq;
    inout spisn;
    inout txm2;
    inout txp2;
    inout [2:1] \vdda_1.8 ;
    inout \vdda_3.3 ;
    inout vddc;
    inout vddco;
    inout [2:1] vddio;
    inout x1;
    inout x2;


    initial
        begin
        end

endmodule
