// generated by newgenasym  Tue May 19 15:34:25 2009


module is42s32800d_7tli (a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9, ba0, ba1, \cas# ,
        cke, clk, \cs# , dq0, dq1, dq10, dq11, dq12, dq13, dq14, dq15,
        dq16, dq17, dq18, dq19, dq2, dq20, dq21, dq22, dq23, dq24, dq25,
        dq26, dq27, dq28, dq29, dq3, dq30, dq31, dq4, dq5, dq6, dq7, dq8,
        dq9, dqm0, dqm1, dqm2, dqm3, nc1, nc2, nc3, nc4, nc5, nc6, \ras# ,
        vdd1, vdd2, vdd3, vdd4, vddq1, vddq2, vddq3, vddq4, vddq5,
        vddq6, vddq7, vddq8, vss1, vss2, vss3, vss4, vssq1, vssq2,
        vssq3, vssq4, vssq5, vssq6, vssq7, vssq8, \we# );
    input a0;
    input a1;
    input a10;
    input a11;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    input a9;
    input ba0;
    input ba1;
    input \cas# ;
    input cke;
    input clk;
    input \cs# ;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout dq15;
    inout dq16;
    inout dq17;
    inout dq18;
    inout dq19;
    inout dq2;
    inout dq20;
    inout dq21;
    inout dq22;
    inout dq23;
    inout dq24;
    inout dq25;
    inout dq26;
    inout dq27;
    inout dq28;
    inout dq29;
    inout dq3;
    inout dq30;
    inout dq31;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dq8;
    inout dq9;
    input dqm0;
    input dqm1;
    input dqm2;
    input dqm3;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    input \ras# ;
    input vdd1;
    input vdd2;
    input vdd3;
    input vdd4;
    input vddq1;
    input vddq2;
    input vddq3;
    input vddq4;
    input vddq5;
    input vddq6;
    input vddq7;
    input vddq8;
    inout vss1;
    input vss2;
    input vss3;
    input vss4;
    input vssq1;
    input vssq2;
    input vssq3;
    input vssq4;
    input vssq5;
    input vssq6;
    input vssq7;
    input vssq8;
    input \we# ;


    initial
        begin
        end

endmodule
