// generated by newgenasym  Thu Feb 12 16:51:08 2009


module scn_2_22 (gnd1, gnd2, gnd3, rfin, rfout1, rfout2);
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout rfin;
    inout rfout1;
    inout rfout2;


    initial
        begin
        end

endmodule
