-- generated by newgenasym Thu Feb 12 16:51:08 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity scn_2_22 is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	RFIN:      INOUT  STD_LOGIC;    
	RFOUT1:    INOUT  STD_LOGIC;    
	RFOUT2:    INOUT  STD_LOGIC);
end scn_2_22;
