// generated by newgenasym  Wed Dec 14 16:43:01 2011


module cdclvc1102pw (\1g , clkin, gnd, nc1, nc2, vdd, y0, y1);
    inout \1g ;
    inout clkin;
    inout gnd;
    inout nc1;
    inout nc2;
    inout vdd;
    inout y0;
    inout y1;


    initial
        begin
        end

endmodule
