// generated by newgenasym  Fri Apr 17 11:25:27 2009


module ics8538bg_31lft (clk, clk_en, clk_sel, nq0, nq1, nq2, nq3, nq4, nq5, nq6, nq7,
        q0, q1, q2, q3, q4, q5, q6, q7, vcc, vcco1, vcco2, vcco3, vee1,
        vee2, vee3, xtal_in, xtal_out);
    input clk;
    input clk_en;
    input clk_sel;
    output nq0;
    output nq1;
    output nq2;
    output nq3;
    output nq4;
    output nq5;
    output nq6;
    output nq7;
    output q0;
    output q1;
    output q2;
    output q3;
    output q4;
    output q5;
    output q6;
    output q7;
    input vcc;
    input vcco1;
    input vcco2;
    input vcco3;
    input vee1;
    input vee2;
    input vee3;
    input xtal_in;
    input xtal_out;


    initial
        begin
        end

endmodule
