// generated by newgenasym  Thu Apr 23 10:47:23 2009


module qrw025a0a41_h (\case , nc, \on/off , \sense+ , \sense- , trim, \vi+ , \vi- , \vo+ , \vo- );
    inout \case ;
    inout nc;
    inout \on/off ;
    inout \sense+ ;
    inout \sense- ;
    inout trim;
    inout \vi+ ;
    inout \vi- ;
    inout \vo+ ;
    inout \vo- ;


    initial
        begin
        end

endmodule
