// generated by newgenasym  Thu Feb 12 15:32:27 2009


module tlk3134zel (agnd_1, agnd_10, agnd_11, agnd_12, agnd_2, agnd_3, agnd_4,
        agnd_5, agnd_6, agnd_7, agnd_8, agnd_9, amux0, amux1, avdd_1,
        avdd_2, avdd_3, avdd_4, avdd_5, avdd_6, avdd_7, avdd_8,
        avdd_9, code, cp_out, dgnd_1, dgnd_10, dgnd_11, dgnd_12,
        dgnd_13, dgnd_14, dgnd_15, dgnd_16, dgnd_17, dgnd_18,
        dgnd_19, dgnd_2, dgnd_20, dgnd_21, dgnd_22, dgnd_23,
        dgnd_24, dgnd_25, dgnd_26, dgnd_27, dgnd_28, dgnd_29,
        dgnd_3, dgnd_30, dgnd_31, dgnd_32, dgnd_33, dgnd_34,
        dgnd_35, dgnd_36, dgnd_37, dgnd_38, dgnd_39, dgnd_4,
        dgnd_40, dgnd_41, dgnd_42, dgnd_43, dgnd_44, dgnd_45,
        dgnd_46, dgnd_47, dgnd_48, dgnd_49, dgnd_5, dgnd_50,
        dgnd_51, dgnd_6, dgnd_7, dgnd_8, dgnd_9, dvdd_1, dvdd_10,
        dvdd_11, dvdd_12, dvdd_13, dvdd_14, dvdd_15, dvdd_2, dvdd_3,
        dvdd_4, dvdd_5, dvdd_6, dvdd_7, dvdd_8, dvdd_9, enable, gpi1,
        gpo0, gpo1, gpo2, gpo3, gpo4, mdc, mdio, ploop, prbs_en,
        prtad0, prtad1, prtad2, prtad3, prtad4, rdn0, rdn1, rdn2,
        rdn3, rdp0, rdp1, rdp2, rdp3, refclk, refclkn, refclkp, res1,
        res2, res3, res4, \rst# , rxc_0, rxc_1, rxc_2, rxc_3, rxc_4,
        rxc_5, rxc_6, rxc_7, rxclk_0, rxclk_1, rxclk_2, rxclk_3,
        rxd_0, rxd_1, rxd_10, rxd_11, rxd_12, rxd_13, rxd_14, rxd_15,
        rxd_16, rxd_17, rxd_18, rxd_19, rxd_2, rxd_20, rxd_21,
        rxd_22, rxd_23, rxd_24, rxd_25, rxd_26, rxd_27, rxd_28,
        rxd_29, rxd_3, rxd_30, rxd_31, rxd_4, rxd_5, rxd_6, rxd_7,
        rxd_8, rxd_9, sloop, speed0, speed1, st, tck, tdi, tdn0, tdn1,
        tdn2, tdn3, tdo, tdp0, tdp1, tdp2, tdp3, testen, tms, \trst# ,
        tst_out, txc_0, txc_1, txc_2, txc_3, txc_4, txc_5, txc_6,
        txc_7, txclk_0, txclk_1, txclk_2, txclk_3, txd_0, txd_1,
        txd_10, txd_11, txd_12, txd_13, txd_14, txd_15, txd_16,
        txd_17, txd_18, txd_19, txd_2, txd_20, txd_21, txd_22,
        txd_23, txd_24, txd_25, txd_26, txd_27, txd_28, txd_29,
        txd_3, txd_30, txd_31, txd_4, txd_5, txd_6, txd_7, txd_8,
        txd_9, vco_tl_tst, vdd_cml, vdd_pll, vdda_cp, vdda_vco,
        vddd_1, vddd_2, vddd_3, vddd_4, vddd_5, vddm, vddo_1, vddo_2,
        vddo_3, vddo_4, vddo_5, vddo_6, vddq_1, vddq_10, vddq_11,
        vddq_12, vddq_13, vddq_14, vddq_15, vddq_16, vddq_17,
        vddq_18, vddq_19, vddq_2, vddq_20, vddq_21, vddq_22,
        vddq_23, vddq_24, vddq_25, vddq_26, vddq_27, vddq_28,
        vddq_3, vddq_4, vddq_5, vddq_6, vddq_7, vddq_8, vddq_9, vddr,
        vddt_1, vddt_2, vddt_3, vddt_4, vpp_1, vpp_2, vref1, vref2,
        vss_cml, vss_pll, vssa_cp, vssa_vco, vtune);
    input agnd_1;
    input agnd_10;
    input agnd_11;
    input agnd_12;
    input agnd_2;
    input agnd_3;
    input agnd_4;
    input agnd_5;
    input agnd_6;
    input agnd_7;
    input agnd_8;
    input agnd_9;
    inout amux0;
    inout amux1;
    input avdd_1;
    input avdd_2;
    input avdd_3;
    input avdd_4;
    input avdd_5;
    input avdd_6;
    input avdd_7;
    input avdd_8;
    input avdd_9;
    input code;
    inout cp_out;
    input dgnd_1;
    input dgnd_10;
    input dgnd_11;
    input dgnd_12;
    input dgnd_13;
    input dgnd_14;
    input dgnd_15;
    input dgnd_16;
    input dgnd_17;
    input dgnd_18;
    input dgnd_19;
    input dgnd_2;
    input dgnd_20;
    input dgnd_21;
    input dgnd_22;
    input dgnd_23;
    input dgnd_24;
    input dgnd_25;
    input dgnd_26;
    input dgnd_27;
    input dgnd_28;
    input dgnd_29;
    input dgnd_3;
    input dgnd_30;
    input dgnd_31;
    input dgnd_32;
    input dgnd_33;
    input dgnd_34;
    input dgnd_35;
    input dgnd_36;
    input dgnd_37;
    input dgnd_38;
    input dgnd_39;
    input dgnd_4;
    input dgnd_40;
    input dgnd_41;
    input dgnd_42;
    input dgnd_43;
    input dgnd_44;
    input dgnd_45;
    input dgnd_46;
    input dgnd_47;
    input dgnd_48;
    input dgnd_49;
    input dgnd_5;
    input dgnd_50;
    input dgnd_51;
    input dgnd_6;
    input dgnd_7;
    input dgnd_8;
    input dgnd_9;
    input dvdd_1;
    input dvdd_10;
    input dvdd_11;
    input dvdd_12;
    input dvdd_13;
    input dvdd_14;
    input dvdd_15;
    input dvdd_2;
    input dvdd_3;
    input dvdd_4;
    input dvdd_5;
    input dvdd_6;
    input dvdd_7;
    input dvdd_8;
    input dvdd_9;
    input enable;
    input gpi1;
    output gpo0;
    output gpo1;
    output gpo2;
    output gpo3;
    output gpo4;
    input mdc;
    inout mdio;
    input ploop;
    input prbs_en;
    input prtad0;
    input prtad1;
    input prtad2;
    input prtad3;
    input prtad4;
    input rdn0;
    input rdn1;
    input rdn2;
    input rdn3;
    input rdp0;
    input rdp1;
    input rdp2;
    input rdp3;
    input refclk;
    input refclkn;
    input refclkp;
    inout res1;
    inout res2;
    inout res3;
    inout res4;
    input \rst# ;
    output rxc_0;
    output rxc_1;
    output rxc_2;
    output rxc_3;
    output rxc_4;
    output rxc_5;
    output rxc_6;
    output rxc_7;
    output rxclk_0;
    output rxclk_1;
    output rxclk_2;
    output rxclk_3;
    output rxd_0;
    output rxd_1;
    output rxd_10;
    output rxd_11;
    output rxd_12;
    output rxd_13;
    output rxd_14;
    output rxd_15;
    output rxd_16;
    output rxd_17;
    output rxd_18;
    output rxd_19;
    output rxd_2;
    output rxd_20;
    output rxd_21;
    output rxd_22;
    output rxd_23;
    output rxd_24;
    output rxd_25;
    output rxd_26;
    output rxd_27;
    output rxd_28;
    output rxd_29;
    output rxd_3;
    output rxd_30;
    output rxd_31;
    output rxd_4;
    output rxd_5;
    output rxd_6;
    output rxd_7;
    output rxd_8;
    output rxd_9;
    input sloop;
    input speed0;
    input speed1;
    input st;
    input tck;
    input tdi;
    output tdn0;
    output tdn1;
    output tdn2;
    output tdn3;
    output tdo;
    output tdp0;
    output tdp1;
    output tdp2;
    output tdp3;
    input testen;
    input tms;
    input \trst# ;
    inout tst_out;
    input txc_0;
    input txc_1;
    input txc_2;
    input txc_3;
    input txc_4;
    input txc_5;
    input txc_6;
    input txc_7;
    input txclk_0;
    input txclk_1;
    input txclk_2;
    input txclk_3;
    input txd_0;
    input txd_1;
    input txd_10;
    input txd_11;
    input txd_12;
    input txd_13;
    input txd_14;
    input txd_15;
    input txd_16;
    input txd_17;
    input txd_18;
    input txd_19;
    input txd_2;
    input txd_20;
    input txd_21;
    input txd_22;
    input txd_23;
    input txd_24;
    input txd_25;
    input txd_26;
    input txd_27;
    input txd_28;
    input txd_29;
    input txd_3;
    input txd_30;
    input txd_31;
    input txd_4;
    input txd_5;
    input txd_6;
    input txd_7;
    input txd_8;
    input txd_9;
    inout vco_tl_tst;
    input vdd_cml;
    input vdd_pll;
    input vdda_cp;
    input vdda_vco;
    input vddd_1;
    input vddd_2;
    input vddd_3;
    input vddd_4;
    input vddd_5;
    input vddm;
    input vddo_1;
    input vddo_2;
    input vddo_3;
    input vddo_4;
    input vddo_5;
    input vddo_6;
    input vddq_1;
    input vddq_10;
    input vddq_11;
    input vddq_12;
    input vddq_13;
    input vddq_14;
    input vddq_15;
    input vddq_16;
    input vddq_17;
    input vddq_18;
    input vddq_19;
    input vddq_2;
    input vddq_20;
    input vddq_21;
    input vddq_22;
    input vddq_23;
    input vddq_24;
    input vddq_25;
    input vddq_26;
    input vddq_27;
    input vddq_28;
    input vddq_3;
    input vddq_4;
    input vddq_5;
    input vddq_6;
    input vddq_7;
    input vddq_8;
    input vddq_9;
    input vddr;
    input vddt_1;
    input vddt_2;
    input vddt_3;
    input vddt_4;
    input vpp_1;
    input vpp_2;
    input vref1;
    input vref2;
    input vss_cml;
    input vss_pll;
    input vssa_cp;
    input vssa_vco;
    inout vtune;


    initial
        begin
        end

endmodule
