-- generated by newgenasym Fri Aug 05 14:59:17 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SMP1330_005LF is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end SMP1330_005LF;
