// generated by newgenasym  Fri May 13 17:42:44 2011


module sn74hc04pw (\1a , \1y , \2a , \2y , \3a , \3y , \4a , \4y , \5a , \5y , \6a , \6y , gnd, vcc);
    inout \1a ;
    inout \1y ;
    inout \2a ;
    inout \2y ;
    inout \3a ;
    inout \3y ;
    inout \4a ;
    inout \4y ;
    inout \5a ;
    inout \5y ;
    inout \6a ;
    inout \6y ;
    inout gnd;
    inout vcc;


    initial
        begin
        end

endmodule
