-- generated by newgenasym Fri May 13 17:42:44 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74hc04pw is
    port (    
	\1a\:      INOUT  STD_LOGIC;    
	\1y\:      INOUT  STD_LOGIC;    
	\2a\:      INOUT  STD_LOGIC;    
	\2y\:      INOUT  STD_LOGIC;    
	\3a\:      INOUT  STD_LOGIC;    
	\3y\:      INOUT  STD_LOGIC;    
	\4a\:      INOUT  STD_LOGIC;    
	\4y\:      INOUT  STD_LOGIC;    
	\5a\:      INOUT  STD_LOGIC;    
	\5y\:      INOUT  STD_LOGIC;    
	\6a\:      INOUT  STD_LOGIC;    
	\6y\:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end sn74hc04pw;
