-- generated by newgenasym Fri Aug 05 16:52:57 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity STCA is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC);
end STCA;
