// generated by newgenasym  Wed Sep 02 18:06:45 2009


module w25x20avssi (clk, \cs# , dio, do, gnd, \hold# , vcc, \wp# );
    inout clk;
    inout \cs# ;
    inout dio;
    inout do;
    inout gnd;
    inout \hold# ;
    inout vcc;
    inout \wp# ;


    initial
        begin
        end

endmodule
