// generated by newgenasym  Mon May 31 14:51:03 2010


module o23b_ecbd_10mhz (gnd, \output , vc, vcc, vref);
    inout gnd;
    inout \output ;
    inout vc;
    inout vcc;
    inout vref;


    initial
        begin
        end

endmodule
