-- generated by newgenasym Mon May 31 14:51:03 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity O23B_ECBD_10MHZ is
    port (    
	GND:       INOUT  STD_LOGIC;    
	OUTPUT:    INOUT  STD_LOGIC;    
	VC:        INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end O23B_ECBD_10MHZ;
