// generated by newgenasym  Wed Jun 22 14:41:06 2011


module adl5382acpz (bias, cml, cmrf, com, ihi, ilo, loin, loip, pad, qhi, qlo, rfin,
        rfip, vpa, vpb, vpl, vpx);
    inout bias;
    inout [3:1] cml;
    inout [3:1] cmrf;
    inout [2:1] com;
    inout ihi;
    inout ilo;
    inout loin;
    inout loip;
    inout pad;
    inout qhi;
    inout qlo;
    inout rfin;
    inout rfip;
    inout vpa;
    inout [2:1] vpb;
    inout [3:1] vpl;
    inout vpx;


    initial
        begin
        end

endmodule
