-- generated by newgenasym Wed Jun 22 14:41:06 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adl5382acpz is
    port (    
	BIAS:      INOUT  STD_LOGIC;    
	CML:       INOUT  STD_LOGIC_VECTOR (3 DOWNTO 1);    
	CMRF:      INOUT  STD_LOGIC_VECTOR (3 DOWNTO 1);    
	COM:       INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	IHI:       INOUT  STD_LOGIC;    
	ILO:       INOUT  STD_LOGIC;    
	LOIN:      INOUT  STD_LOGIC;    
	LOIP:      INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	QHI:       INOUT  STD_LOGIC;    
	QLO:       INOUT  STD_LOGIC;    
	RFIN:      INOUT  STD_LOGIC;    
	RFIP:      INOUT  STD_LOGIC;    
	VPA:       INOUT  STD_LOGIC;    
	VPB:       INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	VPL:       INOUT  STD_LOGIC_VECTOR (3 DOWNTO 1);    
	VPX:       INOUT  STD_LOGIC);
end adl5382acpz;
