-- generated by newgenasym Thu Mar 05 10:20:36 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lt5527 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	\if+\:     INOUT  STD_LOGIC;    
	\if-\:     INOUT  STD_LOGIC;    
	LO:        INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NC5:       INOUT  STD_LOGIC;    
	NC6:       INOUT  STD_LOGIC;    
	NC7:       INOUT  STD_LOGIC;    
	RF:        INOUT  STD_LOGIC;    
	VCC1:      IN     STD_LOGIC;    
	VCC2:      IN     STD_LOGIC);
end lt5527;
