// generated by newgenasym  Thu Apr 14 16:09:16 2011


module lea_6t (\aadet* , extint0, gnd, \n/c , reserved1, reserved2, reserved3,
        reserved4, \reset* , rf_in, rxd1, scl2, sda2, timepulse,
        timepulse2, txd1, usb_dm, usb_dp, v_ant, v_bckp, vcc,
        vcc_out, vcc_rf, vddusb);
    inout \aadet* ;
    inout extint0;
    inout [5:1] gnd;
    inout \n/c ;
    inout reserved1;
    inout reserved2;
    inout reserved3;
    inout reserved4;
    inout \reset* ;
    inout rf_in;
    inout rxd1;
    inout scl2;
    inout sda2;
    inout timepulse;
    inout timepulse2;
    inout txd1;
    inout usb_dm;
    inout usb_dp;
    inout v_ant;
    inout v_bckp;
    inout vcc;
    inout vcc_out;
    inout vcc_rf;
    inout vddusb;


    initial
        begin
        end

endmodule
