-- generated by newgenasym Thu Apr 30 14:25:04 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ics8302amilft is
    port (    
	CLK:       INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	Q0:        INOUT  STD_LOGIC;    
	Q1:        INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VDDO1:     INOUT  STD_LOGIC;    
	VDDO2:     INOUT  STD_LOGIC);
end ics8302amilft;
