-- generated by newgenasym Sat Jun 12 10:58:44 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity RJ45_V_8 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	PIN_B1:    INOUT  STD_LOGIC;    
	PIN_B2:    INOUT  STD_LOGIC;    
	PIN_T1:    INOUT  STD_LOGIC;    
	PIN_T2:    INOUT  STD_LOGIC);
end RJ45_V_8;
