-- generated by newgenasym Thu Feb 12 14:39:48 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ics85408bgilft is
    port (    
	CLK:       IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	NCLK:      IN     STD_LOGIC;    
	NQ0:       OUT    STD_LOGIC;    
	NQ1:       OUT    STD_LOGIC;    
	NQ2:       OUT    STD_LOGIC;    
	NQ3:       OUT    STD_LOGIC;    
	NQ4:       OUT    STD_LOGIC;    
	NQ5:       OUT    STD_LOGIC;    
	NQ6:       OUT    STD_LOGIC;    
	NQ7:       OUT    STD_LOGIC;    
	OE:        IN     STD_LOGIC;    
	Q0:        OUT    STD_LOGIC;    
	Q1:        OUT    STD_LOGIC;    
	Q2:        OUT    STD_LOGIC;    
	Q3:        OUT    STD_LOGIC;    
	Q4:        OUT    STD_LOGIC;    
	Q5:        OUT    STD_LOGIC;    
	Q6:        OUT    STD_LOGIC;    
	Q7:        OUT    STD_LOGIC;    
	VDD1:      IN     STD_LOGIC;    
	VDD2:      IN     STD_LOGIC;    
	VDD3:      IN     STD_LOGIC);
end ics85408bgilft;
