// generated by newgenasym  Thu Feb 12 13:48:52 2009


module isl12022ibz (gnd, \irq#/fout , scl, sda, vbat, vdd, x1, x2);
    inout gnd;
    inout \irq#/fout ;
    inout scl;
    inout sda;
    inout vbat;
    inout vdd;
    inout x1;
    inout x2;


    initial
        begin
        end

endmodule
