// generated by newgenasym  Wed Jun 22 17:04:01 2011


module coupler_rcp200b03 (\-90#20deg , \0#20deg , in, iso, pad1, pad2, pad3, pad4, pad5, pad6,
        pad7, pad8);
    inout \-90#20deg ;
    inout \0#20deg ;
    inout in;
    inout iso;
    input pad1;
    input pad2;
    input pad3;
    input pad4;
    input pad5;
    input pad6;
    input pad7;
    input pad8;


    initial
        begin
        end

endmodule
