-- generated by newgenasym Wed Jun 22 17:04:01 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity COUPLER_RCP200B03 is
    port (    
	\-90 deg\: INOUT  STD_LOGIC;    
	\0 deg\:   INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	ISO:       INOUT  STD_LOGIC;    
	PAD1:      IN     STD_LOGIC;    
	PAD2:      IN     STD_LOGIC;    
	PAD3:      IN     STD_LOGIC;    
	PAD4:      IN     STD_LOGIC;    
	PAD5:      IN     STD_LOGIC;    
	PAD6:      IN     STD_LOGIC;    
	PAD7:      IN     STD_LOGIC;    
	PAD8:      IN     STD_LOGIC);
end COUPLER_RCP200B03;
