// generated by newgenasym  Fri Apr 13 17:03:51 2012


module ics85314agi_11lf (clk0, clk1, clk_sel, nclk0, nclk1, nclk_en, nq0, nq1, nq2,
        nq3, nq4, q0, q1, q2, q3, q4, reserved, vcc, vee);
    inout clk0;
    inout clk1;
    inout clk_sel;
    inout nclk0;
    inout nclk1;
    inout nclk_en;
    inout nq0;
    inout nq1;
    inout nq2;
    inout nq3;
    inout nq4;
    inout q0;
    inout q1;
    inout q2;
    inout q3;
    inout q4;
    inout reserved;
    inout [2:1] vcc;
    inout vee;


    initial
        begin
        end

endmodule
