// generated by newgenasym  Mon Jun 29 15:49:06 2009


module lt5557 (en, gnd1, gnd2, \if+ , \if- , lo, nc1, nc2, nc3, nc4, nc5, nc6, nc7,
        pad, rf, vcc1, vcc2);
    inout en;
    inout gnd1;
    inout gnd2;
    inout \if+ ;
    inout \if- ;
    inout lo;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout nc7;
    inout pad;
    inout rf;
    inout vcc1;
    inout vcc2;


    initial
        begin
        end

endmodule
