-- generated by newgenasym Mon Jun 29 15:49:06 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lt5557 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	\if+\:     INOUT  STD_LOGIC;    
	\if-\:     INOUT  STD_LOGIC;    
	LO:        INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NC5:       INOUT  STD_LOGIC;    
	NC6:       INOUT  STD_LOGIC;    
	NC7:       INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	RF:        INOUT  STD_LOGIC;    
	VCC1:      INOUT  STD_LOGIC;    
	VCC2:      INOUT  STD_LOGIC);
end lt5557;
